### ISSUE TITLE
Change related to Criminal events?

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source-X#1001]
Hello guys,

Will the change regarding Criminal events stay like this? I tried to find a solution to this problem with my own means. Both from source codes and scripts, but because criminal events spread to too many places in the emulator, when you change one place, the other place is corrupted and the business becomes inextricable. Is it possible to at least do this optionally retroactively? In the country we play, these criminal events are perceived as a problem.

The problem is, for example, while players a and b are fighting among themselves, player a, that is, the player who makes the first attack, gets the general criminal (criminal 1) flag. It wasn't like this before. When players a and b were fighting among themselves, only each other would be marked as guilty. Does the comunity offer their support on this issue or should we come up with our own solutions on this issue?

Happy new year everyone.

**Comment by AtillaG1** [comment]
Hello,

isnt it because of this? 
// Attacking is considered a crime (even without hit)
AttackingIsaCrime=1

**Comment by canerksk** [comment]
NOTE: You are also guilty if you kill the pk characters before they write "guards".

**Comment by falanlar** [comment]
başkan bunu sen scriptle fixlesene neden bekliyorsun ? normal fix gelincede değişirsin

**Comment by canerksk** [comment]
Scripti fixi olması gerektiği gibi olmuyor, sonuçta bu bir sorun ve bu sorunu daha önce bildiren olmamış. Konu fixlemek değil kendi emülatör sürümümde fixli zaten ama asıl konu bu sorunun master brachte kayıtlı olması.

**Comment by falanlar** [comment]
Başkan bende bu emülatörü kullanıyorum senin yukarda bahsettiğin olay bende olmuyor. Benim anlatmak istediğim yukarda script olarak da bir çözüm bulamadığını belirttiğin için yazma gereği duydum eğer durum senin için önemliyse script olarak buraya kodlamaya çalışayım ama zaten sende fixliyse zaten emülatörde şu an için bir sorun göremiyorum bu konuyla alakalı olarak

**Comment by canerksk** [comment]
Adım adım anlatayım tekrar bu şekilde bi denip buraya yazar mısın?

1 ve 2. Oyunduğu düşünelim.

1. Oyuncu wara geçip 2. Oyuncuya çift tıklıyor (eğer criminal sorgusu açıksa ok seçip atak alınır)

Daha sonra 1. Oyuncu 2. Oyuncuya vurduğu an hem 2. Oyuncuya hem de herkese crim (.xcriminal 1 yapılmış gibi) olur bunu daha iyi anlamak için kenarda bir 3. Oyuncu bekletmekte fayda var.

**Comment by falanlar** [comment]
Başkan kusura bakma işlerden güçlerden yeni deneyebildim ve herşey normal bende bir sıkıntı yok sadece vuran vurduğuna crim oluyor

**Comment by xMirroRx** [comment]
- Added: In @Criminal trigger, RETURN 0 doesn't flag the char as criminal but does remove SRC's MEMORY_SAWCRIME.
RETURN 1 still blocks the whole trigger behaviour, so it will not flag as criminal and won't remove the MEMORY_SAWCRIME.

// i saw them commit a crime or i was attacked criminally. i can call the guards on them.

```
on=@criminal
return 0
```

Senin @Criminal tetikleyicisine return 0 vermen sorunu çözmüyor memory_sawcrime siliyor bu şekilde oyuncu guard çağıramaz.

**Comment by falanlar** [comment]
"i saw them commit a crime or i was attacked criminally. i can call the guards on them." iyi de başkan bu zaten yazıyor altına iki satır kodla çözülebilecek bir şey eğer işlem çokluğundan dolayı komplike bir durum söz konusuysa bunun için birşey diyememe ama böyle ivedilik gerektiren bir konu değil he tek satırla olsa daha mı kolay evet ama olmasada sorun yok demek istediğim bu

**Comment by xMirroRx** [comment]
Müsait olduğunda şu çalışmayı bitirip koysana bro şuraya görelim.

**Comment by falanlar** [comment]
`ON=@CRIMINAL
IF (<ARGN2> == 1)
	IF !(<SRC.CTAG0.GUARD>)
		SRC.CTAG0.GUARD 1
	ELSE
		CRIMINAL 1
	ENDIF
ENDIF
IF (<SRC.DTAG.GENELCRIM> < <SERV.TIME>)
	RETURN 1 // 1=SADECE KİŞİYE CRİM OLUR 0= HERKESE CRIM OLUR
ENDIF

ON=@SPELLEFFECT
IF !(<SRC.ISGM>) && (<UID> != <SRC>)
	IF (<SERV.SPELL.<ARGN1>.FLAGS> &SPELLFLAG_GOOD)
		IF ((<KILLS> > <SERV.MURDERMINCOUNT>) || (<FLAGS>&STATF_CRIMINAL)) && (<SRC.KILLS> < <SERV.MURDERMINCOUNT>)
			SRC.TAG0.GENELCRIM <EVAL <SERV.TIME> + 100> // TIMER
			SRC.CRIMINAL 1	
		ENDIF
	ELSE
		IF (<KILLS> < <SERV.MURDERMINCOUNT>) && !(<FLAGS>&STATF_CRIMINAL) && !(<SRC.F_BANACRIM <UID>>)
			CRIMINAL 1
		ENDIF

	ENDIF	
ENDIF

ON=@DEATH
REF1=<UID.<ATTACKER.LAST>>
IF ((<REF1.ISCHAR>) && (<REF1.OWNER>)) && ((<SRC.KILLS> < <SERV.MURDERMINCOUNT>) && !(<SRC.FLAGS>&STATF_CRIMINAL)) && (<SRC.F_BANACRIM <REF1.OWNER>>)
	REF2=<REF1.OWNER>
	REF2.KILLS +=1
	IF (<REF2.KILLS> <= <SERV.MURDERMINCOUNT>)
		REF2.TAG0.GENELCRIM <EVAL <SERV.TIME> + 100>
		REF2.CRIMINAL 1
	ENDIF
	IF (<REF2.KILLS> == <EVAL <SERV.MURDERMINCOUNT> + 1>)
		REF2.SAY Artık katilsiniz.
	ENDIF
ENDIF
IF (<SRC.FLAGS>&STATF_CRIMINAL)
	SRC.CRIMINAL 0
ENDIF`
@ATTACK altına da SpellEffect gibi düzenleme yapıp en son memory @destroy kısmından ctag.guard 0 yaparsan olur diye düşünüyorum yine olmazsa bir düzenleme daha yaparız yani fixlenebilir

**Comment by xMirroRx** [comment]
İyide buradaki çalışmada oyuncunun crim süresi ne zaman bitiyor ve suçlunun genel suçlu ilan edilmesi durumu var. 
Olay bu değil a oyuncusu b oyuncusuna vurduğu zaman zaten genel crim oluyor sorun bu. A, b oyncusuna vurduğu zaman a oyuncusu sadece b oyuncusuna crim olmalı. b oyuncusu ölmediği veya a oyuncusuna guard çekmediği sürece a oyuncusu genel crim olamaz.

**Comment by xMirroRx** [comment]
Ya başkan her şeyi geçtim tamam bu bi şekilde çözülür @Criminal triggerine bir return 1 koyar sıfırdan criminal sistemi de yazılır. Ama olay bu değil!
Bu şu an ki criminal sistemi bozuk mu, yoksa bilerek mi böyle yapıldı ve yapıldıysa da niye yapıldı neydi bunun değişmesini gerektiren şey ?

Senin kendince bulduğun çözüme gelecek olursak
IsSamePartyOF <uid> // bu çalışmıyor şimdi bu çalışmıyor diye bende fonksiyon mu yazayım.

```
[function f_issameparty]
ref1 = <args>
if ( <isinparty> ) 
    for 0 <eval <party.members>-1>
	ref2 = <party.member.<dlocal._for>>
	if ( <ref1> == <ref2> ) 
	    return 1
	endif
    endfor
endif
```

**Comment by falanlar** [comment]
İyi de bozuk diye hiçbir şey yapmadan bekleyecek miyim bu şekilde kullanırım düzelene kadar, düzeldikten sonra zaten kaldırırım. Zaten attığım ilk yorumdada bunu belirtiyorum yoksa bende buraya sorunları yazıyorum ama diğer taraftan alternatif yol üretip onları kullanıyorum diğer türlü fix gelene kadar beklesem soğurum iyice birşey yapmam. Eğer aktif sunucu için yazıyorsanız bu size geçici olarak ilaç olur demek istediğim o

**Comment by canerksk** [comment]
Criminal veya kills sorgulamalarının yanısıra <src.notogetflag <uid>> == noto_criminal gibi sorgulamalar da eklemeni öneririm. Çünkü bu yazdığın scriptler dost / düşman guild ve party içindeki criminallik olaylarında sapıtması muhtemel. Mesela ben burada ceset kestiğin zaman da genel crim oluyorsun bununla ilgili bir kontrol göremedim. Bu iş uzar da gider. Notoflag olaylar emülatörün içine çok fazla yaygın halde ve bunu script ile çözmek için de çok fazla kontrol yapmak gerek. Şahsen şu senin yazdığın kodların yüzlerce farklı varyasyonunu yaptım ama script olarak fix edilmesi çok sağlıklı olmuyor. Çok fazla sorgu çok fazla kontrol yapmak gerekiyor ki bir sorunu en kısa yoldan çözmek her zaman daha iyidir ki bu işin en uzun yolu. Tabi ki şu an ortada bir sorun var ve kendince bir fix oluşturmuşsun. Şahsen benim kullanacağım bir yöntem değil kullanacak arkadaşlar burdan faydalanabilir.

**Comment by falanlar** [comment]
> Ya başkan her şeyi geçtim tamam bu bi şekilde çözülür @criminal triggerine bir return 1 koyar sıfırdan criminal sistemi de yazılır. Ama olay bu değil! Bu şu an ki criminal sistemi bozuk mu, yoksa bilerek mi böyle yapıldı ve yapıldıysa da niye yapıldı neydi bunun değişmesini gerektiren şey ?
> 
> Senin kendince bulduğun çözüme gelecek olursak IsSamePartyOF // bu çalışmıyor şimdi bu çalışmıyor diye bende fonksiyon mu yazayım.
> 
> ```
> [function f_issameparty]
> ref1 = <args>
> if ( <isinparty> ) 
>     for 0 <eval <party.members>-1>
> 	ref2 = <party.member.<dlocal._for>>
> 	if ( <ref1> == <ref2> ) 
> 	    return 1
> 	endif
>     endfor
> endif
> ```

Fonksiyona gerek yok <X.party.master.uid> == <Y.party.master.uid> yeterlidir



> Criminal veya kills sorgulamalarının yanısıra `<src.notogetflag <uid>> == noto_criminal` gibi sorgulamalar da eklemeni öneririm. Çünkü bu yazdığın scriptler dost / düşman guild ve party içindeki criminallik olaylarında sapıtması muhtemel. Örneğin bir kişi ile dost guilddesin veya aynı guilddesin ama o kişi genel crim yani criminal 1. Normalde o kişiyi guardlayamazsın çünkü dost. Ama burada criminallik sorguları baz alındığı için sanıyorum ki dost guilddeki kişiler de criminal 1 olacak ve guardlanacak. Mesela ben burada ceset kestiğin zaman da genel crim oluyorsun bununla ilgili bir kontrol göremedim. Bu iş uzar da gider. Notoflag olaylar emülatörün içine çok fazla yaygın halde ve bunu script ile çözmek için de çok fazla kontrol yapmak gerek. Şahsen şu senin yazdığın kodların yüzlerce farklı varyasyonunu yaptım ama script olarak fix edilmesi çok sağlıklı olmuyor. Çok fazla sorgu çok fazla kontrol yapmak gerekiyor ki bir sorunu en kısa yoldan çözmek her zaman daha iyidir ki bu işin en uzun yolu. Tabi ki şu an ortada bir sorun var ve kendince bir fix oluşturmuşsun. Şahsen benim kullanacağım bir yöntem değil kullanacak arkadaşlar burdan faydalanabilir.

notoupdate olaylarınında farkındayım ama eğer bu olayı sorun olarak görüyorsanız alternatif üretmediğiniz sürece sadece sorun olarak kalır benim açımdan öyle ivedilikle çözülmesi gereken bir sorun değil. Kaldı ki bizim sunucularımız ne scriptler ne fixler gördü bu kod onların yanında en kısa ve uğraşsız olayı çokta bir yük oluşturduğunuda düşünmüyorum geçerli süreliğine yapılır. tabi gerisi size kalmış ben alternatifleri sundum. iyi günler
