### ISSUE TITLE
refx doesn't work on region.uid.

### ISSUE THREAD

**Issue by xMirroRx** [Sphereserver/Source-X#1005]
[FUNCTION test]
REF1 = <SRC.REGION.UID>
SERV.B <REF1.NAME> // 0

**Comment by falanlar** [comment]
yazmış olduğun komut sadece multilerin içinde çalışır diğer alanlar için region.name kullanmam yeterlidir

**Comment by xMirroRx** [comment]
```
I am already using the processes you mentioned where they should be used, I am aware of them. My request to request the domain name by reference was just a simple example to show.

Can you show me how I can do this in another way?

[FUNCTION f_ForExample]
LOCA.X = 1111 // is just an example.
LOCAL.Y = 1111 // is just an example.
REF1 = <SERV.MAP(<LOCAL.X>,<LOCAL.Y>,0).REGION.UID>
REF1.TAG.ForExample = 1
IF ( <REF1.dTAG.ForExample> ) 
    SERV.B <REF1.Name>, Region is ready for dTAG.ForExample.
ELSE
    SERV.B Oop's a problem occured.
ENDIF




```

**Comment by falanlar** [comment]
```
[FUNCTION f_ForExample]
LOCAL.X <P.X> 		// <ARGV[0]>
LOCAL.Y <P.Y>		// <ARGV[1]>
IF (<P.Z> != 0)
	LOCAL.Z <P.Z> 	// <ARGV[2]>
ELSE
	LOCAL.Z 0
ENDIF
IF (<P.M> != 0)
	LOCAL.M <P.M>	 // <ARGV[3]>
ELSE
	LOCAL.M 0
ENDIF
LOCAL.KOORDINAT <DLOCAL.X>,<DLOCAL.Y>,<DLOCAL.Z>,<DLOCAL.M>
UID.<SERV.MAP(<LOCAL.KOORDINAT>).REGION>.TAG0.FOREXAMPLE 1
IF (<SERV.MAP(<LOCAL.KOORDINAT>).REGION.TAG.FOREXAMPLE>)
    	SERV.B <SERV.MAP(<LOCAL.KOORDINAT>).REGION.NAME>, Region is ready for dTAG.ForExample.
ELSE
    	 SERV.B Oop's a problem occured.
ENDIF
```
dene bakalım bi

**Comment by falanlar** [comment]
hmm I guess there doesn't seem to be a mechanism to remotely control other areas except multi areas

**Comment by canerksk** [comment]
`
[FUNCTION f_ForExample]
LOCAl.X = <P.X>
LOCAL.Y = <P.Y>
LOCAL.Z = <P.Z>
LOCAL.M = <P.M>

SERV.NEWITEM I_GOLD
NEW.ATTR=ATTR_DECAY|ATTR_INVIS
NEW.P=<LOCAL.X>,<LOCAL.Y>,<LOCAL.Z>,<LOCAL.M>
NEW.TIMER=1
NEW.FIX
NEW.REGION.TAG0.ForExample=1

IF (<NEW.REGION.dTAG.ForExample>) 
    SRC.SYSMESSAGE <NEW.REGION.NAME> Region is ready for dTAG.ForExample.
ELSE
    SRC.SYSMESSAGE Oops a problem occured.
ENDIF
`

**Comment by xMirroRx** [comment]
The problem I gave above was an example, which is not the main issue.
You should focus on the title.

**Comment by canerksk** [comment]
Such a parser did not exist. The reference can only be used for objects that exist on the server. It can be an asset, item, house, ship. I don't think you can reference it as Region is not an object. You should be able to do this with another method for now.

**Comment by xMirroRx** [comment]
I waited for a while and I guess this situation was not welcomed.

**Comment by cbnolok** [comment]
REFx can work only with classes derived from CObjBase: items, chars, multis, etc. It would require a big internal change and in my opinion it's not justified because it's a niche scenario.
