### ISSUE TITLE
COMBAT_ANIM_HIT_SMOOTH problem

### ISSUE THREAD

**Issue by wagneruo** [Sphereserver/Source-X#1011]
when it enabled it ini 
the hit occurs belatedly after the animation is completed

**Comment by Jhobean** [comment]
Same than #788 ?

**Comment by wagneruo** [comment]
> Same than #788 ?

yeah

**Comment by wagneruo** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/122651417/212476257-b99b6d31-01d2-4aba-94a8-76343919eaef.png)
looks like shit happen here :)

**Comment by drk84** [comment]
Fix Sent

**Comment by drk84** [comment]
I consider this closed
