### ISSUE TITLE
melee attacks and just ATTACK LAST not interrupt spell casting

### ISSUE THREAD

**Issue by wagneruo** [Sphereserver/Source-X#1012]
melee attacks and just ATTACK LAST not interrupt spell casting like was in 56b
its a feature or bug?

**Comment by drk84** [comment]
In the other Issue you says melee attacks interrupts spellcasting ?

**Comment by wagneruo** [comment]
> In the other Issue you says melee attacks interrupts spellcasting ?

no! melee attack and just attack by dclick in warmode must interrupt spellcasting (it was always in sphere)
and spellcasting atm just interrupt and looks like remove war target

**Comment by drk84** [comment]
Impossible that you were able to fight back and casting the spell at the same time

**Comment by Tolokio** [comment]
> Impossible that you were able to fight back and casting the spell at the same time

He means that in the past when u attack a target it interrupts ur spell casting. Just as if u tab (war/peace). 
It is a diferent thing than the other post.

Example:
1-Start casting spell
2-Dclick on new target to attack it (in war mode)
3-Spell is canceled.

This was like this in the past he is right, but I dont know if it is desired now.

**Comment by cbnolok** [comment]
I can't get it, could you explain it more thoroughly? Is the involved mechanic the spellcasting interruption when trying to attack a char (the same or another)? What's happening exactly now and what was happening before?

**Comment by xwerswoodx** [comment]
If I understand correctly, he means if you casting a spell to player, then you dclick to target another player it stop casting the spell and remove attack target directly.

For example, there are players that named A and B

You start casting flame strike to A
And double click to B to get target
Your spell failed and A removed from your attack target

I understand that from their posts but I am not sure if they meant that.

**Comment by xwerswoodx** [comment]
After seeing another issue, I guess he means same as https://github.com/Sphereserver/Source-X/issues/684

**Comment by wagneruo** [comment]
> I can't get it, could you explain it more thoroughly? Is the involved mechanic the spellcasting interruption when trying to attack a char (the same or another)? What's happening exactly now and what was happening before?

in the sphere, it always worked like this: if a player tried to attack during a spell cast, then the cast process was interrupted. This is not happening now

**Comment by wagneruo** [comment]
> After seeing another issue, I guess he means same as #684

no, it's a different problem :)

**Comment by Soulless-1** [comment]
This is not really an issue, but re-implementing this as you suggested would actually be a restriction on admins who may want it to behave like this. its much simpler to add this for your particular requirement:

on=@attack
action=-1
return 0

also being allowed does not cause an issue, if you dclick during a spell cast your action does not change to combat, it stays in magery, and you go into combat afterwards. 

i'm going to go ahead and close this out since its a year old
