### ISSUE TITLE
Wall of stone on dead characters

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source-X#1015]
If the wall of stone spell falls on the dead characters, the wall of stone does not form in the frame where the dead character is located. Is this a problem or was it done on purpose? For example, let's say we have 5 dead characters next to each other, if we apply the wall of stone magic right under them, the wall of stone will not be formed at all.

**Comment by Jhobean** [comment]
If there only 1 body, it will create with 1 Hole?

**Comment by drk84** [comment]
Hmmm can't reproduce
