### ISSUE TITLE
Cannot get MULTI tiledata info

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#1023]
I am unable to get any info for tiledata in multis to find out what statics there are. for instance this stone wall. This is important for being able to properly check to see if a location inside a house is a valid area for locking down / securing items.

![image](https://user-images.githubusercontent.com/17236327/217587494-adadd1d0-0542-4f0b-ba2b-5bf90e97e30c.png)

**Comment by drk84** [comment]
This can be closed or not yet?

**Comment by Jhobean** [comment]
Maybe post the solution here before close it
