### ISSUE TITLE
Custom ships Z component problem when turning west

### ISSUE THREAD

**Issue by DavideRei** [Sphereserver/Source-X#1026]
When you turn the ship on the west side, sphere don't use the component DZ correctly, set wrong planks height and from that moment the planks are fucked up. It seems that the DZ is inverted between left side and right side.

Same problem in 56d, no problem in 56c.

west side custom ship
COMPONENT=03e8a,2,-3,2
COMPONENT=03e8a,-2,-3,2
COMPONENT=03e85,2,3
COMPONENT=03e85,-2,3
![image](https://user-images.githubusercontent.com/118212274/217826312-a8330f07-3ea1-40ae-a9b0-2d361f55d907.png)

sud side
COMPONENT=03eb2,3,-3
COMPONENT=03eb2,3,2
COMPONENT=03eb1,-3,-3,2
COMPONENT=03eb1,-3,2,2
![image](https://user-images.githubusercontent.com/118212274/217826846-d547f8b9-8f52-4310-9796-4e1fc2330679.png)

from sud side to west side (turn right)
![image](https://user-images.githubusercontent.com/118212274/217827184-6f5d9c17-e7c0-4461-be68-297359650d4b.png)

**Comment by AtillaG1** [comment]
dunno if thats a bug, but to fix it you have to use same height for the components in all sides.
so if you set height 2, you have to have 2 for N,E,S,W.

**Comment by DavideRei** [comment]
It works on 56c 2014 (Sphere Version 0.56c [WIN32] by www.sphereserver.com, compiled at Jan  6 2014 (00:05:24), internal build #1759).
So imho something has changed and removed the possibility to have different heights for the ship components.

I confirm that, if i set the same height (2 or no height) for all components, works.

**Comment by Jhobean** [comment]
Ship and multi have been reworked hard since 56c. I think they work better now. 

Thw height mistake was on your script pack or on official scriptpack?

**Comment by AtillaG1** [comment]
> My script, i had made two custom ships for my shard.
> 
> Nord: COMPONENT=03e4e,0,0 // tiller. COMPONENT=i_ship_hatch_n,0,-11 COMPONENT=03eb2,3,-2 // right COMPONENT=03eb2,3,3 // right COMPONENT=03eb1,-3,-2,2 // left COMPONENT=03eb1,-3,3,2 // left
> 
> East: COMPONENT=03e55,0,0 COMPONENT=i_ship_hatch_e,11,0 COMPONENT=03e85,-3,3 //right COMPONENT=03e85,2,3 COMPONENT=03e8a,-3,-3,2 //left COMPONENT=03e8a,2,-3,2
> 
> Sud: COMPONENT=03e4b,0,0 COMPONENT=i_ship_hatch_s,0, 11 COMPONENT=03eb2,3,-3 //left COMPONENT=03eb2,3,2 COMPONENT=03eb1,-3,-3,2 //right COMPONENT=03eb1,-3,2,2
> 
> West: COMPONENT=03e50,0,0 COMPONENT=i_ship_hatch_w,-11,0 COMPONENT=03e8a,2,-3,2 //right COMPONENT=03e8a,-2,-3,2 COMPONENT=03e85,2,3 //left COMPONENT=03e85,-2,3
> 
> However, there is something wrong, because if i turn the ship between Nord, East and Sud there's no problem at all, only if i turn to West side

you have still different height in each side

**Comment by DavideRei** [comment]
yes, i know, but if different height is forbidden, why it's working between Nord, East and Sud?

same height: https://www.youtube.com/watch?v=kLuQF8SlBCY

original height: https://www.youtube.com/watch?v=OwdBxbok2O4

**Comment by AtillaG1** [comment]
I have no idea. If you have correct IDs for each side and with correct same height, and you create new boat everytime you do changes, it should work fine.

**Comment by cbnolok** [comment]
Is this still an issue?

**Comment by DavideRei** [comment]
yes, just tried again, same issue when turning west

**Comment by xwerswoodx** [comment]
> yes, just tried again, same issue when turning west

Can you send the custom code you wrote to me to test to see if I can see the reason, because I don't use any custom ship, if you don't wish to share it on here, you can contact me on Discord @xwerswoodx.

**Comment by DavideRei** [comment]
The Issue is still present
