### ISSUE TITLE
Using function in if statement call the function twice

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#1032]
To reproduce, call function in if statement. at the moment there more than one function, the last element is called twice.

```
[function fuck]
if (<one> || <two>)
    serv.log yeah
endif

[FUNCTion one]
serv.log Function one
return 0

[FUNCTion two]
serv.log Function two
return 0
```

![image](https://user-images.githubusercontent.com/51728381/218542886-4bb00b46-9cf6-46c1-bef0-ce24ac432fe0.png)

**Comment by Jhobean** [comment]
Could check these issue in same time
https://github.com/Sphereserver/Source-X/issues/796
https://github.com/Sphereserver/Source-X/issues/766

**Comment by AtillaG1** [comment]
> To reproduce, call function in if statement. at the moment there more than one function, the last element is called twice.
> 
> ```
> [function fuck]
> if (<one> || <two>)
>     serv.log yeah
> endif
> 
> [FUNCTion one]
> serv.log Function one
> return 0
> 
> [FUNCTion two]
> serv.log Function two
> return 0
> ```
> 
> ![image](https://user-images.githubusercontent.com/51728381/218542886-4bb00b46-9cf6-46c1-bef0-ce24ac432fe0.png)

tested your function and now its OK.
not sure about the two other issues. 
https://github.com/Sphereserver/Source-X/issues/796
https://github.com/Sphereserver/Source-X/issues/766

**Comment by Jhobean** [comment]
fix here: https://github.com/Sphereserver/Source-X/commit/1ec0790b415d6772c036898cbb2efac1b5a61d79
