### ISSUE TITLE
at.0.xx err

### ISSUE THREAD

**Issue by Leodinas** [Sphereserver/Source-X#1033]
[typedef t_spawn_char]
on=@timer
ref1=<at.0.uid>
serv.log <ref1.name>

09:51:ERROR:(type_spawn_char.scp,4)Can't resolve <at.0.uid>.
09:51:ERROR:(type_spawn_char.scp,5)Can't resolve <ref1.name>.

Is it a error or has it been modified?
old version it working

after this modification
how to find that NPC?

**Comment by canerksk** [comment]
```
[typedef t_spawn_char]
ON=@SPAWN
IF (<ARGO.ISVALID>) && (<ARGO.ISCHAR>)
	TAG0.UID=<ARGO>
ENDIF
```

**Comment by Leodinas** [comment]
for 0 <eval <amount>-1>
at.<dlocal._for>.xxx     //can directly call serial in addobj
endfor

**Comment by drk84** [comment]
Remember that the keyword AT is used for accessing **existing**  objects in the world

**Comment by canerksk** [comment]
at.* is currently deprecated, not working.

**Comment by drk84** [comment]
(Cheap) Fix Sent.

**Comment by canerksk** [comment]
It does not work as at.*, but as a direct horse.

work;
`xshow at`

doesnt work:
`.xshow at.0 or at.0.name`

but I think it's not needed since it's a spawn trigger.

**Comment by drk84** [comment]
After the fix it works here
![image](https://user-images.githubusercontent.com/13728442/220357246-b3baaac0-5ef0-4f66-abdd-40d06c168d9f.png)

**Comment by AtillaG1** [comment]
works for me too

**Comment by drk84** [comment]
I close this
