### ISSUE TITLE
ISSAMEPARTYOF

### ISSUE THREAD

**Issue by xMirroRx** [Sphereserver/Source-X#1034]
ISSAMEPARTYOF character_uid // I guess it's not working.
Sphere Build 3576

**Comment by falanlar** [comment]
Kanka bak yine geçici çözüm öneriyorum sana 
IF (<PARTY.MASTER.UID> == <SRC.PARTY.MASTER.UID>) al sana ISSAMEPARTYOF

**Comment by drk84** [comment]
It works fine, correct usage is:
PARTY.ISSAMEPARTYOF uid

`[FUNCTION sameParty]
targetf ft_sameParty

[FUNCTION ft_sameParty]
if <isinparty>
	if <party.ISSAMEPARTYOF <argo>>
		argo.say yes!
	else
		argo.say no !
	endif 
else
	say I am not into a party!
endif`

**Comment by xMirroRx** [comment]
> Bro i propose a solution again :) IF (<X.PARTY.MASTER.UID> == <Y.PARTY.MASTER.UID>) same thing with "ISSAMEPARTYOF"

look no need :)

thank you drk
