### ISSUE TITLE
NPCs & Players(rarely) falling through the terrain

### ISSUE THREAD

**Issue by GladieUO** [Sphereserver/Source-X#1035]
I just found an issue with the monsters and players(rarely) falling through the terrain. Im afraid this "bug" has been part of sphere forever. At this location in Buccaneers den 2722,2025,22, i remember falling to the caves forever.

For some reason, NPCs are constantly falling through the roof into the cave, even tho the tiles are in flat line of same height.

**So first we have lets say mine cave in height = 0 | you can see its in static**
![image](https://user-images.githubusercontent.com/25097484/219103264-d140db9c-87ae-4f8e-b788-c0d08a348611.png)

Above this, we have graveyard, which is part of map terrain, height = 40 / 50
![image](https://user-images.githubusercontent.com/25097484/219103628-5d2c3355-94cb-4db6-9a23-45f59993b99c.png)

**Comment by Jhobean** [comment]
Could be link to that: https://github.com/Sphereserver/Source-X/issues/983

**Comment by Tolokio** [comment]
Can be related, but I dont think so. It could be related if the tile that make u fall is not flat or if it is surrounded by not flat tiles. Anyway I dont know xD

IT would be so usefull (at least for me that im god programing), to be able to recreate this issue using centred. We need to know the exactly circunstances this bug show up.

Movement system is a nightmare for me. MAybe a senior should take care about this.

**Comment by AtillaG1** [comment]
you dont need to recreate it, in buccaneers den in original files, there are caves systems around the village, and there are NPCs falling through immediately.

**Comment by Tolokio** [comment]
Atila, have u info about which directions makes u fall down? or happens with all directions? any info u can gather will speed things up.

**Comment by AtillaG1** [comment]
dir 4, fromZ 41,  toZ 0
dir 0, fromZ 41,  toZ 0
dir 5, fromZ 41,  toZ 0
dir 7, fromZ 41,  toZ 0
dir 6, fromZ 41,  toZ 0
dir 0, fromZ 40,  toZ 0
dir 1, fromZ 40,  toZ 0
dir 6, fromZ 41,  toZ 0

**Comment by Tolokio** [comment]
u sure it is a normal grass terrain and not a fake terrain like tha one used for hidden places?

**Comment by AtillaG1** [comment]
> u sure it is a normal grass terrain and not a fake terrain like tha one used for hidden places?

not sure how do i know the fake one, but this is standard grass terrain 03 04 05 06 which is user everywhere, same with dirt terrain  078 071 074 073

**Comment by Tolokio** [comment]
There is a fail with alttitude at sphere. Some terrain's Z are bad calculated. 
In certain terrain tiles, sphere put the Char at  lower z than it should. It can happen that when sphere applys gravity it select as new tile the static floor of the cave as lower point. Should be related to this but maybe there could be more.

**Comment by AtillaG1** [comment]
There is something seriously wrong with the Z calculations and overall monsters or objects calculating it.
Like lots of the statics are just weird. Monsters claiming half walls, even the roofs sometimes, then failing to get down from there.
Other time they fall through.
Idk whats going on

![image](https://user-images.githubusercontent.com/25097484/228890003-96ef5152-5119-418c-8334-0cc289356af0.png)

**Comment by xwerswoodx** [comment]
@AtillaG1 can you test it on 

https://github.com/Sphereserver/Source-X/actions/runs/6511357815

to see if it's fixed.

**Comment by AtillaG1** [comment]
Still keeps happening, sadly.
![image](https://github.com/Sphereserver/Source-X/assets/25097484/25588309-719a-41ed-96ee-48e19b12e08d)
![image](https://github.com/Sphereserver/Source-X/assets/25097484/35387f2f-0afb-4fb1-bff5-e04fd61b0a8d)

**Comment by AtillaG1** [comment]
Interesting is, that on the right side, they dont fall down. on the left side they do.
![image](https://github.com/Sphereserver/Source-X/assets/25097484/f4e73b04-23bf-4b79-bec2-df0ce00dc553)

**Comment by xwerswoodx** [comment]
What's the location of these sections? And how do you drop down while walking or after used .update etc?

**Comment by AtillaG1** [comment]
Its custom location, but on original map its here, 2736,2061,31.
Players can fell down just by running over it, but not happens everytime. Monsters fall constantly.

**Comment by xwerswoodx** [comment]
Should have been fixed with last update. I remember there was some spots in Buccaneer's Den that you can drop down, but we changed the Z calculation system so now it should calculate it correctly.

**Comment by Jhobean** [comment]
https://github.com/Sphereserver/Source-X/pull/1128

**Comment by AtillaG1** [comment]
I just briefly tested from work and its still same problem.
It almost feels like the NPCs can walk through the little gaps in terrain which they should not. I have noticed it in dungeon too, I will try to explain best I can.

CASE 1:
you have dungeon floor Z=0, on this floor, you have stalagmites or rock on Z=2, all in static/map. The NPC it feels like its height is ignored, and squueks through the gap between 0-2, which should be impossible.

CASE 2:
you have terrain like shown on example, and bellow this you have cave, same as in case 1, it seems like the NPC can squeek through the little gaps in terrain.
  2  2   2  2
  0  0   0  0
-2 -2 -2 -2
this represent the terrain going up like in buccaneers den, so whenever the terrain isnt exactly Z=0 at all tiles, they NPC can squeeks through, more rarely players too.

**Comment by drk84** [comment]
About Buccaneer's Den: 
![image](https://github.com/Sphereserver/Source-X/assets/13728442/0044e681-dd4c-40a8-9515-6583fbf2d025)

That post is taken from the OSI's forum, and I can confirm that even in Sphere that spot where you fall down to the tunnel does indeed exist. So I think it's a client/map glitch more than a sphere problem.

**Comment by AtillaG1** [comment]
> About Buccaneer's Den: ![image](https://user-images.githubusercontent.com/13728442/276868506-0044e681-dd4c-40a8-9515-6583fbf2d025.png)
> 
> That post is taken from the OSI's forum, and I can confirm that even in Sphere that spot where you fall down to the tunnel does indeed exist. So I think it's a client/map glitch more than a sphere problem. Coordinates around 2693,2057,23. Just run around between the ferns and tress while on the crest of the hill

Know about this one, but im testing it like 2 screens away.
2732,2060,25

Btw. can this be linked to low height of NPC?

**Comment by xwerswoodx** [comment]
I wonder, when you drop down, does .update moved you back on the terrain? Because if update fixes it, it probably causes from client-side. Because if update calculates height correctly means Client couldn't and drop you down. But silly because I run the place you said for 10 mins and never dropped down, I will give a try with npcs tonight to see if I can reproduce the issue, because as I can't reproduce, I can't manage to find issue at all, I can only guess why it happens.

**Comment by AtillaG1** [comment]
> Silly because I run the place you said for 10 mins and never dropped down, I will give a try with npcs tonight to see if I can reproduce the issue, because as I can't reproduce, I can't manage to find issue at all, I can only guess why it happens.

I will try more stuff on how to reproduce, but with players falling its very rarely, with npcs its immediate.

**Comment by AtillaG1** [comment]
> 13:28:(e_npc_generic_event.scp,105)DIR 6, NPC: Llama 03149e with Height: 10 Falling from: 2726,2065,27 - TO: X:2725 Y:2064 Z:-20 | REGION: Buccaneer's Den Uzemi

will try to find more spots

**Comment by cbnolok** [comment]
Is this still happening? There was a commit some time ago which introduced z map tile averaging

**Comment by GladieUO** [comment]
The location above tunels in buccaners den was always weird, and there is atleast 1 fall through intended from OSI.

In regards to other spots, it was in custom locations, I looked through the similar locations from other server, and they are bulding it so that above the mining caves, on the grass where you can run, they build like extra layer of special invisible black tiles 0x0490, so maybe thats the correct way how to prevent falling through in such locations.

However, since no one really reported same issue, I would close it for now.

![image](https://github.com/user-attachments/assets/438b2211-b8d5-4f01-9932-b1084da3a14c)
![image](https://github.com/user-attachments/assets/34d37b06-6dad-44e3-8dd1-ac11b7743ead)
![image](https://github.com/user-attachments/assets/5b093e36-978b-4fc2-a955-3198eeab8f0e)

**Comment by Tolokio** [comment]
![image](https://github.com/user-attachments/assets/76cc5ec5-5b26-4b30-a4fb-aa57bc059552)
 This can happen if custom npcs have no height and there is a gap betwen terrain and the static. (i think)

**Comment by Tolokio** [comment]
> There is something seriously wrong with the Z calculations and overall monsters or objects calculating it. Like lots of the statics are just weird. Monsters claiming half walls, even the roofs sometimes, then failing to get down from there. Other time they fall through. Idk whats going on
> 
> ![image](https://user-images.githubusercontent.com/25097484/228890003-96ef5152-5119-418c-8334-0cc289356af0.png)

Thoose are stairs ("bridge" on tiledata) I think npcs can climb them even if players can't. But not sure. I think client denys it but sphere allow it, so players can't.

**Comment by GladieUO** [comment]
Yea I fixed this one long time ago. My dumbass activated in all regions noblockheight flag.

**Comment by Tolokio** [comment]
So, all issues of this post can be closed? Are fixed?
