### ISSUE TITLE
FOR loop doesn't work on Linux when over 10k iterations

### ISSUE THREAD

**Issue by DavideRei** [Sphereserver/Source-X#1037]
15:43:ERROR:(d_add_sqlite.scp,45)Terminating loop cycle since it seems being dead-locked (10000 iterations already passed)

crashed Sphere.

no problem on Windows

**Comment by drk84** [comment]
Have you tried setting MaxLoop times in sphere.ini to ?
// Limit the number of cycles the while/for loop can proceed. Setting this to
// zero disables the limitation
MaxLoopTimes=10000

**Comment by DavideRei** [comment]
Sorry, my fault. I didn't notice that on Windows i have MaxLoopTimes=100.000.
Now it works.
