### ISSUE TITLE
CChar::CallGuards() function

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source-X#1040]
Hello,

I guess because of a query under the CallGuards() function, it's not working as it should.

For example;

In the past, this command was working outside the guard zone, and when "guards" is written next to someone who is guilty, that person becomes a general criminal (criminal 1, Noto_Criminal() ). But right now, I saw that this function is stopped working except for city protection under the function.

```
	ADDTOCALLSTACK("CChar::CallGuards");
	if (!m_pArea || 
	!m_pArea->IsGuarded() || <-- its use other than gz is turned off here.
	IsStatFlag(STATF_DEAD|STATF_STONE))
		return;
```
In the current situation when I type the "guards" command outside of gz, someone who criminal me does not become a general criminal.

Do you think this is a bug?

**Comment by drk84** [comment]
If the are is not guarded no guards should be called

**Comment by canerksk** [comment]
No just calling guards under the CChar::CallGuards() function,

```
if (m_pPlayer && Memory_FindObjTypes(pCriminal, MEMORY_SAWCRIME))
  pCriminal->Noto_Criminal(this, true);
```
query is also available. which should make that person "criminal 1" outside of city guard.
