### ISSUE TITLE
Spell 24 - s_wall_of_stone

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#1042]
The Duration in spelldef doesnt work, you can set 10000 or 0, the wall will always last for around 10s.
Other field spells seems to work well.

probably bugged?

**Comment by drk84** [comment]
I set it to 1 and it lasted one second

**Comment by AtillaG1** [comment]
With X-PACK? even tho there is this?
`[ITEMDEF 080]
//This is the hardcoded ITEMDEF used by Wall of Stone spell
//It has been excluded from the i_wall_hugebrick DUPELIST on purpose
on @create
if <serv.spell.<morex>.flags>&SPELLFLAG_FIELD
timerf 1,timer = <R10,15>
endif`

**Comment by drk84** [comment]
Oh looks like setting one second in the duration field of the SPELLDEF makes the stone wall disappears before the timerf sets the 10,15 seconds timer. Anyway you should comment it

**Comment by drk84** [comment]
It's a scriptack x bug btw

**Comment by AtillaG1** [comment]
> Oh looks like setting one second in the duration field of the SPELLDEF makes the stone wall disappears before the timerf sets the 10,15 seconds timer. Anyway you should comment it

of course i did comment it, but still the timer is always 10s 😁

**Comment by drk84** [comment]
Change the timer on spelldef duration
