### ISSUE TITLE
Wrong spells duration?

### ISSUE THREAD

**Issue by DavideRei** [Sphereserver/Source-X#1043]
It's seems that spells duration is wrong.
For example s_gate_travel
DURATION=60.0

The gate lasts 600 seconds, shouldn't be 60 seconds?

![image](https://user-images.githubusercontent.com/118212274/221402065-fb6e17a5-f995-4b6c-adb4-8ed0b714d065.png)

Tested on last Windows version with clean save and script pack.

**Comment by drk84** [comment]
60  seconds is 6.0

**Comment by DavideRei** [comment]
Should't duration be in tenth of seconds? 

http://wiki.spherecommunity.net/index.php?title=SPELL

![image](https://user-images.githubusercontent.com/118212274/221505444-133d4c4d-1e7c-49d4-a12a-0f53ea9a9953.png)

**Comment by drk84** [comment]
Fix Sent

**Comment by DavideRei** [comment]
It works
