### ISSUE TITLE
t_ship_hold_locked message

### ISSUE THREAD

**Issue by DavideRei** [Sphereserver/Source-X#1044]
If i dclick a t_ship_hold_locked item i get "You can't think of a way to use that item" instead of "The items is locked" or "That is locked".

Also i get this errors on sphere loading

Loading scripts/core/messages.scp
ERROR:(messages.scp,481)Setting not used message override named 'msg_gmpage_canceled'
ERROR:(messages.scp,482)Setting not used message override named 'msg_gmpage_notified'
ERROR:(messages.scp,483)Setting not used message override named 'msg_gmpage_qnum'
ERROR:(messages.scp,485)Setting not used message override named 'msg_gmpage_rec'
ERROR:(messages.scp,486)Setting not used message override named 'msg_gmpage_update'

This messages are on the script X pack.

Tested on last Windows version with clean save and script pack.

**Comment by drk84** [comment]
Fix Sent, i can't reproduce the other error from messages.scp as i don't get them.
