### ISSUE TITLE
Dropping items into wall tiles in multis. (Issue #1024)

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source-X#1045]
After this change, it is not possible to enter the stairs in front of the customizable houses.

However, if we add the stairs in front of the house to +2 height with 

`ADDITEM 1873,<LOCAL._FOR>,<ARGV3>,2 <-- pz`

it can pass inside the house.

**Comment by drk84** [comment]
for customizable houses you mean the house foundation multi?

**Comment by drk84** [comment]
I placed a stair with the customizable menu and i entered

**Comment by canerksk** [comment]
Have you tried with a player character?

**Comment by drk84** [comment]
Uh i'll try

**Comment by drk84** [comment]
Yes i can enter
![image](https://user-images.githubusercontent.com/13728442/221645737-f8c71522-b002-4698-a32d-8c2388d4467c.png)

**Comment by canerksk** [comment]
This is interesting, I'll give it some more experimentation and provide feedback.
