### ISSUE TITLE
Clilocs in journal while using DeadCannotSeeLiving=2 | errors in console

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#1049]
Hi,

If im trying to use DeadCannotSeeLiving=2 and player that i cannot see is casting spells which has its mantras by using clilocs, the sphere will fire errors and show nothing in journal for the dead guy.

![image](https://user-images.githubusercontent.com/25097484/223205007-451d38b3-4fef-46bb-b097-fb07f6a4b117.png)
![image](https://user-images.githubusercontent.com/25097484/223204949-05c786c3-8367-44b8-a65b-a7587de2ba2d.png)

**Comment by drk84** [comment]
How do you use the cliloc in the spell?

**Comment by AtillaG1** [comment]
> How do you use the cliloc in the spell?

RUNES=.@,,2 1060720

**Comment by drk84** [comment]
Partial fix sent, the errors are not displayed anymore but I noticed that the name of the speaker is not sent a dead player get a localized message and DeadCannotSeeLiving is set to 2

**Comment by AtillaG1** [comment]
no erros in console.
The spell manthra is possible to see by dead player now.
![image](https://user-images.githubusercontent.com/25097484/226392092-9f74ebe0-6fab-4c29-a136-345fc9171fc5.png)
