### ISSUE TITLE
ON=@Cancel works on skillmenu but add undefined/no draw item

### ISSUE THREAD

**Issue by DavideRei** [Sphereserver/Source-X#1056]
Tested on last version with clean sphere.
Client 7.0.97.25 or 7.0.7.1

Info about this trigger on wiki http://wiki.spherecommunity.net/index.php?title=SKILLMENU

sm_legacy_cartography.scp
![image](https://user-images.githubusercontent.com/118212274/226168017-5c636d93-9179-420e-8d14-56960a5c1548.png)

.add i_mapmakers_pen

without blank map dclick open this menu, is it correct?

![image](https://user-images.githubusercontent.com/118212274/226168342-49c1cb07-b6bb-49b8-b6ec-0cbe94470eb3.png)

.add i_map_blank
dlick the pen

![image](https://user-images.githubusercontent.com/118212274/226168581-05eda982-b18e-4047-ba56-9fb963035be6.png)

if i dclick unused i get "Unexpected menu info."

The trigger is fired

![image](https://user-images.githubusercontent.com/118212274/226168645-810e2cf3-e146-4c35-8bbe-6d28cb6cbc3a.png)

In my scripts i have redefined t_cartography (various checks and tag management, in the end return 0) and ON=@Cancel in the skillmenu make the client crash. Client 7.0.7.1
No crash with client 7.0.97.25

Worked on 56d and 56c

**Comment by Tolokio** [comment]
![image](https://user-images.githubusercontent.com/20745578/226184213-60de49b2-f42f-4753-8859-62dd2f3e39ae.png)

The part marked with red is suppossed to stop it?

**Comment by drk84** [comment]
fix sent

**Comment by DavideRei** [comment]
it works! thank you!
