### ISSUE TITLE
MODMAXWEIGHT on npcs doesn't work due to the main backpack weight limit

### ISSUE THREAD

**Issue by DavideRei** [Sphereserver/Source-X#1061]
.add c_llama_pack
.set modmaxweight 99999
transfer the lama to yourself
gm off

.add i_corpse_wolf (100.0 weight) and try to put 5 of those in lama backpack
you can't put in the backpack more than five or you get "That container cannot hold more weight".

So you can't exceed 500.0 weight.
The only way is to use the BackpackOverload ini option, but i don't want to unlock the limit also for players.
In fact the description of BackpackOverload ini option refers to players, not npcs
![image](https://user-images.githubusercontent.com/118212274/230008174-f6e86b3a-c1fa-41ee-98d0-0561c898d27e.png)

Tested on clean sphere, last version

**Comment by Tolokio** [comment]
Is modmaxweight supposed to work on chars? Should it not be applied to llama's backpack?

**Comment by DavideRei** [comment]
![image](https://user-images.githubusercontent.com/118212274/230567286-4a54f9c4-4a23-4d9c-92cc-16ee41d6caea.png)
In the beginning i think it was meant for chars.
In the wiki is on chars page and it worked on 56c.
![image](https://user-images.githubusercontent.com/118212274/230567479-318b7b4a-ff8f-4e20-9574-cab1a723cc17.png)

But it seems to work also on items.
![image](https://user-images.githubusercontent.com/118212274/230567868-3b576f5e-fe6e-4e74-b5cd-d06b1db3e398.png)

.set findlayer(21).modmaxweight on lama pack works.
But i can't do it under @create trigger 
![image](https://user-images.githubusercontent.com/118212274/230568198-8a97c5ca-51c4-43d6-a301-f632ad829dde.png)

**Comment by drk84** [comment]
I confirm the bug

**Comment by drk84** [comment]
Fix sent

**Comment by DavideRei** [comment]
it works! thanks!
