### ISSUE TITLE
Monsters getting constantly stuck in static

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#1063]
Hi,

so i have started spawning dungeons, and i dont understand if its just original UO static that bad, or there is problem on sphere side, since there are problems with the Z calculations etc....
Monster constantly WALK into the static where they should not, because even players/GM cant get there, and then they get stuck and cannot go back. 
In my case, where the spells are not allowed to drop out of LOS, you cannot get to these monsters. :(
![image](https://user-images.githubusercontent.com/25097484/230733920-3d34cd7f-097a-47bc-9877-fd11f3add919.png)
![image](https://user-images.githubusercontent.com/25097484/230733923-ad479145-bef0-433e-9c9e-d461aa7c2bfd.png)
![image](https://user-images.githubusercontent.com/25097484/230734219-5c71ef89-1a41-4319-a3bc-5bf5000af446.png)

**Comment by Tolokio** [comment]
are new mounts? do it happens with normals npcs? maybe u need to set height or something

**Comment by AtillaG1** [comment]
New monsters, i guess i could be able to use them as mounts too.
It happenes with all npcs, no matter height.

**Comment by Tolokio** [comment]
try advanced pathfiding if u didnt. Maybe npcs are crossing through diagonals.
Only happens with statics or with ingame items as well?
 Would be nice to be able to reproduce it.

Anyway, this can also happen if sphere`s muls are not = than client. Be sure of that.

**Comment by AtillaG1** [comment]
> try advanced pathfiding if u didnt. Maybe npcs are crossing through diagonals. Only happens with statics or with ingame items as well? Would be nice to be able to reproduce it.
> 
> Anyway, this can also happen if sphere`s muls are not = than client. Be sure of that.

I have ad. pthf. activated.

Only happens with statics, im usually fixing it by items placed there so its not possible to step there.
I think you can reproduce it easily, these are original spots in original map. Just spawn some NPC there and let them walk around these spots, they will eventually get stuck in there.
These are just few i can remember now, but there is shit ton of these.
1) 5779,1346,-3
2) 5858,1303,-1
3) 5815,1347,-21
4) 6278,885,-6,1

These should point to the Fire Dungeon spots and one in Painted Caves.

With the muls files, unless there is problem with using one folder with UO for both Sphere & Client in same time this shouldnt be the problem, also its NPCs that get stuck, it should not have anything to do with client (user). :(

**Comment by AtillaG1** [comment]
They are able to casually walk through the walls, they spawn on the spawn and walk through.......
![image](https://user-images.githubusercontent.com/25097484/236630611-53324f63-8ca4-44fa-ba13-8ea054afc7a9.png)

**Comment by AtillaG1** [comment]
> They are able to casually walk through the walls, they spawn on the spawn and walk through....... ![image](https://user-images.githubusercontent.com/25097484/236630611-53324f63-8ca4-44fa-ba13-8ea054afc7a9.png)

ok this one i managed to fix, its these small foundations that are set to "BRIDGE" and not "IMPASSABLE"........

**Comment by Tolokio** [comment]
Does it happen just with new custom npcs? 
U need to give a proper Height for thoose npcs. If not, they will have a base height of 0 or 1, allowing them to fit betwen the floor and the wall. COuld be this what is happening to you?

**Comment by AtillaG1** [comment]
> Does it happen just with new custom npcs? U need to give a proper Height for thoose npcs. If not, they will have a base height of 0 or 1, allowing them to fit betwen the floor and the wall. COuld be this what is happening to you?

sadly no, the height is fine, 10, 16 etc...

**Comment by Tolokio** [comment]
are u sure? does it happen with vanilla mobs?

I think it got to be set here:
![image](https://github.com/Sphereserver/Source-X/assets/20745578/675196b2-e45e-4ab0-9db7-08a73b410b9a)

**Comment by AtillaG1** [comment]
Yes its happening with vanila TOL or so mobs, and they have height set, i dont think you can use height only via this def file. If u set it in Chardef it works too.
However the TOL and latest mobs i cant find in this def file.

**Comment by AtillaG1** [comment]
![image](https://github.com/Sphereserver/Source-X/assets/25097484/2baa17a4-7b23-4302-bad2-db4563477796)
😁😲
