### ISSUE TITLE
Npc double hit

### ISSUE THREAD

**Issue by DavideRei** [Sphereserver/Source-X#1065]
Npc randomly strike 2 times in a row.
@hittry is fired 2 times in a row without speed change (ARGN1) between the 2 hits.

This is a zombie hitting me with serv.rticks, actdiff, argn1 in @hittry. the delay between the hits sometimes changes randomly and serv.rticks is the same or changes by 1. Like the last two hits. 

![image](https://user-images.githubusercontent.com/118212274/231374265-2551b415-6209-47e9-b784-d89217f7bc7f.png)

And the problem get worse as dex increases. A dragon with 100 dex kills a player in 5 sec if it always hits.

Tested on clean sphere, last version.

Issue confirmed by others on discord. Seems to happen on all combat settings.

**Comment by drk84** [comment]
If you set ARGN1 manually in the @HitTry trigger does this still happen?

**Comment by drk84** [comment]
Yes it happens also by manualyl setting argn1

**Comment by drk84** [comment]
Possible fix sent.

**Comment by DavideRei** [comment]
It works!!!! awesome!!
