### ISSUE TITLE
Summon Creature Spell set owner after placing the npc in game

### ISSUE THREAD

**Issue by DavideRei** [Sphereserver/Source-X#1067]
If a player summons a npc onto a fire field, when the npc takes damage it doesn't have an owner set yet and attacks the player.

```
[EVENTS e_npc_generic_event]
//Generic event to all npc

ON=@GetHIt
serv.log owner <owner>
```

Use a plevel 1 account char and give him a spellbook with fire field and summon creature.
Cast fire field, go on it and cast summon creature.

![image](https://user-images.githubusercontent.com/118212274/233565849-2a98050a-b0c3-49eb-8841-25dbc301b463.png)

Tested on last version with clean sphere

**Comment by canerksk** [comment]
`serv.log owner: <owner>`

works as

**Comment by DavideRei** [comment]
i updated the message, the code was not visible.

@canerksk  i don't understand your reply. Is not <src.owner> in my code. When you summon a creature on a fire field the owner is empty.

**Comment by canerksk** [comment]
Is the attacker the owner of the summon entity or another player?

**Comment by DavideRei** [comment]
In my test src is the owner of the summoned creature (the player who cast the fire field)

**Comment by canerksk** [comment]
If an asset owner takes the hit of the asset, that person is no longer the owner of that asset. The @gethit trigger returns zero because it fires after the owner of the asset is deleted. Instead, find a trigger that fires before @gethit and use it.

For example;
```
on=@PETDESERT
serv.log PETDESERT: <src>,<src.name>, <owner>, <owner.name>
```

This trigger will partially work because it is triggered before the @gethit trigger.

**Comment by DavideRei** [comment]
just tried, @PETDESERT doesn't fire when summon a creature on a fire field

**Comment by canerksk** [comment]
The summon entity is deleted as soon as players attack the summon entities they have. The idle summon entity event has been removed. I don't understand exactly why you want this.

**Comment by DavideRei** [comment]
The problem is that i can't control what happens. I changed s_summon_creature @effect to use my custom followers system but if a player summon a creature on a fire field or others step damage spell, it seems that the creature was never owned by the player.
I had to force the ownership of the summoned creature to the player under @EffectAdd and in my custom combat system i had to block the damage done by players to their pets.
So i opened the ticket, because i think that the owner of the summoned creature is set after placing the creature in game, otherwise i don't understand why is not possible to manage this scenario (summoned creature on fire field).

**Comment by Tolokio** [comment]
Pet gets released before trigger @gethit takes place, so will never see the owner's uid at @gethit unless u set specific config on sphere.ini

![image](https://user-images.githubusercontent.com/20745578/235011340-c9a1280e-7474-4c46-ae3a-3c4584ee06df.png)


As u can see in the image u can set COMBAT_NOPETDESERT=1 on sphere.ini to deny pets desserting. Then u can create ur own system using @gethit

**Comment by DavideRei** [comment]
ok, then the problem is on @petdesert, because is not firing when you summon a creature on a fire field.

`[EVENTS e_npc_generic_event]
//Generic event to all npc

//ON=@CombatStart
//say combat start
//
//ON=@CombatEnd
//say combat end
//
//ON=@CombatAdd
//say combat add <src.name>
//
//ON=@CombatDelete
//say combat delete <src.name>
//
//ON=@hittry
//actdiff=1000
//say <serv.rticks>, <actdiff>, <ARGN1>

ON=@GetHIt
serv.log owner <owner>

ON=@PetDesert
serv.log PETDESERT: <src>,<src.name>, <owner>, <owner.name>, <flags>, <name>`

![image](https://user-images.githubusercontent.com/118212274/235081783-a61f5b0c-3a6d-48ff-9fc1-cb1304d864f2.png)

**Comment by drk84** [comment]
fix sent

**Comment by DavideRei** [comment]
It works, thank you!
