### ISSUE TITLE
Summon Creature create c_man if casted after target an enemy

### ISSUE THREAD

**Issue by DavideRei** [Sphereserver/Source-X#1070]
.add c_zombie
set the war status in the paperdoll
dclick on zombie
.cast s_summon_creature

![image](https://user-images.githubusercontent.com/118212274/236665181-d623537a-7ae8-44a4-9568-1ac29f8f88f4.png)

.cast s_summon_creature now work

if you dclick again the zombie and .cast s_summon_creature another c_man is summoned

**Comment by canerksk** [comment]
Yes, this is a problem, most likely actarg2 is involved. If you want to temporarily solve this problem with a script, you can add the code below. After this problem is fixed, you can remove the script.

```
ON=@SKILLMENU
IF (<ARGS> == SM_SUMMON)
	SRC.FLAGS &= ~STATF_WAR
ENDIF
```

**Comment by drk84** [comment]
Fix sent

**Comment by DavideRei** [comment]
it works, thank you
