### ISSUE TITLE
Decay timer not set on ammo at @hitmiss

### ISSUE THREAD

**Issue by DavideRei** [Sphereserver/Source-X#1072]
When you miss a ranged attack and an ammo is created on the ground, the timer on the ammo is -1

On Garbage Collection you get errors

![image](https://github.com/Sphereserver/Source-X/assets/118212274/f5764ff7-c244-49b7-99f2-24a18a9e7372)

**Comment by Jhobean** [comment]
Nice, I had this error but did not know why. Good find

**Comment by canerksk** [comment]
In CCharFight.cpp, close 1912 lines and replace it.

```
pAmmo->UnStackSplit(1);
//pAmmo->MoveToDecay(pCharTarg->GetTopPoint(), g_Cfg.m_iDecay_Item);
pAmmo->MoveNear(pCharTarg->GetTopPoint(), 0);
pAmmo->Update();
pAmmo->SetDecayTimeS(g_Cfg.m_iDecay_Item);
```

I added it and the problem was solved.

**Comment by drk84** [comment]
Fix sent

**Comment by DavideRei** [comment]
it works, thank you
