### ISSUE TITLE
Skill Value on SkillGump

### ISSUE THREAD

**Issue by LuxionUO** [Sphereserver/Source-X#1076]
Hi there,
I think would be very helpful to have a setting in Sphere.ini where we can decide to show a fixed value for the skillgump. For example, I would like to always show the real value (When you select "Show Real").

Something like:
ShowAlwaysRealSkillValue=1 // 1 = show real - 0 = not enabled

```cpp
writeInt16((word)(i + 1));
			writeInt16(character->Skill_GetAdjusted((SKILL_TYPE)i));
			writeInt16(character->Skill_GetBase((SKILL_TYPE)i));
			writeByte((byte)(character->Skill_GetLock((SKILL_TYPE)i)));
			if (includeCaps)
				writeInt16((word)(character->Skill_GetMax((SKILL_TYPE)I)));
```

I hope this helps.

Best.

**Comment by drk84** [comment]
I don't think it's necessary, as you wrote the show real button already does that, it looks more like an "eye-candy" feature.

**Comment by Jhobean** [comment]
If this option exist, i'll delete the show real button.

This button is so useless and some player complain about it

**Comment by LuxionUO** [comment]
So, I have got the issue (not really an issue).

To get this fixed it's simply needed to remove all bonuses from each skill, and it will returns always the base value.

```
[SKILL 1]
DEFNAME=Skill_Anatomy
KEY=Anatomy
TITLE=Biologist
PROMPT_MSG=Whom shall I examine?
DELAY=3.0,1.0
STAT_STR=15
STAT_DEX=15
STAT_INT=70
BONUS_STR=0 // set this to 0
BONUS_DEX=0 // set this to 0
BONUS_INT=0 // set this to 0
BONUS_STATS=0 // set this to 0
ADV_RATE=10.0,20.0,800.0

ON=@Fail
	SRC.SYSMESSAGE You can't think of anything about this creature

ON=@Abort
	SRC.SYSMESSAGE You fail to examine the creature fully.
```

I hope this helps.
