### ISSUE TITLE
Combat Adjustment

### ISSUE THREAD

**Issue by Turbo-swag** [Sphereserver/Source-X#1077]
Damage formula (tactics/str/anatomy/lumberjacking probly evaint/inscription) can be individual Like Tactics = %50 meaning %50 of tactic skill level effect on your damage instead of Sphere/Uo default values or, Tactics = 1 Making it Able to modify damage as default uo ruleset.

For example :
//Combat Settings 
Tactics = 1
Anatomy = 1
Lumberjacking = 0
Inscription = 0
Evalint = 1
Str = 1

Hit chance : 
We can change this as 
Value 1 %100 success
Value 2 Act like base uo rules without Hit chance increase/decrease 
Value 3 Base uo rules with Hit chance inc/dec

Swingspeed formula can stay but AOS SE ML is kinda not flexible to do things custom.
For example if i set sphere custom with combatspeed because i want dex effects on swingspeed not stam and want also swingspeed stat effects on as well. With default sphere.ini settings you cant do it.

**Comment by Soulless-1** [comment]
Check out these triggers on the wiki, you can accomplish this custom behavior in a script

@hitcheck 
@GetHit | Fires when the character receives damage.
@Hit | Fires when the character hits another in combat.
@HitMiss | Fires when the character fails to hit another in combat.
@HitParry | X branch only. Fires when the character is attempting to parry a hit. 
@HitTry | Fires when the character tries to hit another in combat.

I'm going to go ahead and close this out, please reach out to us on discord if you need help with these triggers
