### ISSUE TITLE
Broken T_MULTI_CUSTOM custom houses | foundations 8x8 10x10 etc...

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#1079]
Just found out that custom foudnation houses are now broken.
Edit: I tried older releases and its not helping, I mean in some cases for example for 8x8 foundation, suddenly it fixed itself, but then 7x7, 7x8, 8x7 appeared broken. Im not able to find link to specific release that could cause this. :(
![image](https://github.com/Sphereserver/Source-X/assets/25097484/71e7750f-acad-4e33-8661-b636fd5328ab)
![image](https://github.com/Sphereserver/Source-X/assets/25097484/3ab50111-d157-452e-86f6-9becbbe5d674)

**Comment by AtillaG1** [comment]
Tried like 20 older releases of X sphere, even from last year.
tried vanilla multi, vanilla X pack, vanilla client, still same problem.

**Comment by AtillaG1** [comment]
Compiled at Dec  7 2022 (15:58:47) [build 3553 / GIT hash ba966c81e78d8c2df21e2c6fa3bab4997cd73f44]
seems like so far its OK there.

![image](https://github.com/Sphereserver/Source-X/assets/25097484/bfdca8d1-e84c-4e58-bd88-7b4031bea6aa)

**Comment by AtillaG1** [comment]
First time the problem appears in this build, but only once, after repacking and building again it works, but watch the GIF, it gets builded wrong, but then changes itself to correct state....
Compiled at Jan 11 2023 (21:16:59) [build 3569 / GIT hash 7de9bb49594f0a8274469012e625e687317c1cc6]
https://i.gyazo.com/27fd8036039640fba60c21b3b1d172f1.mp4

**Comment by canerksk** [comment]
> First time the problem appears in this build, but only once, after repacking and building again it works, but watch the GIF, it gets builded wrong, but then changes itself to correct state.... Compiled at Jan 11 2023 (21:16:59) [build 3569 / GIT hash [7de9bb4](https://github.com/Sphereserver/Source-X/commit/7de9bb49594f0a8274469012e625e687317c1cc6)]
> 
> https://i.gyazo.com/27fd8036039640fba60c21b3b1d172f1.mp4

This is an plevel account and does not perform a bump check on home/ship creation in their plevel account. For example, you can also land a ship. When you try this with a player account, it will not be able to build a house or foundation in the area in the video at all. This seems to be a height issue caused by the roughness. Some parts of the foundation remain under the roughness.

**Comment by AtillaG1** [comment]
> > First time the problem appears in this build, but only once, after repacking and building again it works, but watch the GIF, it gets builded wrong, but then changes itself to correct state.... Compiled at Jan 11 2023 (21:16:59) [build 3569 / GIT hash [7de9bb4](https://github.com/Sphereserver/Source-X/commit/7de9bb49594f0a8274469012e625e687317c1cc6)]
> > https://i.gyazo.com/27fd8036039640fba60c21b3b1d172f1.mp4
> 
> This is staff account and does not perform a bump check on home/ship creation in their staff account. For example, you can even land a ship. When you try this with a player account, it will not be able to build a house or foundation in the area in the video at all. This seems to be a height issue caused by the roughness. Some parts of the foundation remain under the roughness.

Thats what I eventually thought too, but then with normal account.

https://i.gyazo.com/e7545b2132ff667c0f64e88f8713a7b0.mp4

**Comment by AtillaG1** [comment]
If I change type of the multi from t_multi_custom to t_multi, its being built fine.

**Comment by AtillaG1** [comment]
I think there is something broken in CItemMulti.cpp, line 3342

`pItemNew->MoveToUpdate(pt);`

> bool CItem::MoveToUpdate(const CPointMap& pt, bool fForceFix)
> {
> 	bool fReturn = MoveTo(pt, fForceFix);
> 	Update();
> 	return fReturn;
> }

`bool MoveToUpdate(const CPointMap& pt, bool fForceFix = false);`

**Comment by AtillaG1** [comment]
With debug version, I think now its nicely to see whats going on?

https://i.gyazo.com/40c0392a5eb4a5808c6be4b1c77786a8.mp4

**Comment by AtillaG1** [comment]
Another update.
with @Rastero we pinpointed the problematic sphere version, it is May of 2023. Totaly broken its in version from 25th of May. In version of 15th of May, its mostly OK.
@Rastero thinks its these two commits doing that.
https://github.com/Sphereserver/Source-X/commit/a3416ab2bc5c7b1a4491d916d91f69b03202c760#diff-f09e4f987f8434bd60c5572ce63d150396c860196ebae48f99973edba3d13bdd

https://github.com/Sphereserver/Source-X/commit/a3416ab2bc5c7b1a4491d916d91f69b03202c760

**Comment by cbnolok** [comment]
So, to recap. Is the foundation placement bug fixed? Is there another, different multi bug?

**Comment by AtillaG1** [comment]
Placement is fixed, but I think same commit that broke it before, now broke also the commiting in builder mode.
On this build it was working all fine. Compiled at Apr 7 2023 (11:48:53) [build 3590 / GIT hash https://github.com/Sphereserver/Source-X/commit/744da2360303357a3f66ec71797a04fa90a113d0]
