### ISSUE TITLE
Houses vs Maxhouses | removing houses, but not allowing build more

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#1080]
Since playing with the multis again, i find out that while building house and then repacking it, it will correctly remove house from .houses.
I have correctly houses 0 and maxhouses=5. But since i builded and repacked 5 houses already, while testing, now I cannot build anymore.

I assume somehow even I have 0 actual houses, i fall into FALSE in this code. 
This state get fixed with restarting Sphere.

```
    uint8 iMaxHouses = pChar->m_pPlayer->_iMaxHouses;
    if (iMaxHouses == 0)
    {
        if (pChar->GetClientActive())
        {
            iMaxHouses = pChar->GetClientActive()->GetAccount()->_iMaxHouses;
        }
    }
    if (iMaxHouses == 0)
    {
        return true;
    }
    if (GetHouseCountTotal() + iHouseCount <= iMaxHouses)
    {
        return true;
    }
    pChar->SysMessageDefault(DEFMSG_HOUSE_ADD_LIMIT);
    return false;
```

![image](https://github.com/Sphereserver/Source-X/assets/25097484/4ac9df82-82d4-418b-aeda-230fb74d6203)
![image](https://github.com/Sphereserver/Source-X/assets/25097484/11c191db-cdc0-4613-8acf-71715dc23249)

**Comment by Tolokio** [comment]
I think there was a fix for this issue, or at least I tried xD
