### ISSUE TITLE
CAN=can_o_nosleep

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#1082]
I have items with this CAN Flag, that should change location when the timer reaches 0.
It seems like sometimes they got stuck at 0 in sleeping sector, even tho they should continue.

If i set them by script to timer 1, then for some time they work as intended, even in sleeping sector.

How is this possible? Might this stucking at 0 be because of sphere rr?

![image](https://github.com/Sphereserver/Source-X/assets/25097484/3749c483-c31e-45a5-bcdc-ac1a6d398393)

**Comment by AtillaG1** [comment]
So i created a new item just for this testing, and it works, but then i leave the PC, come back next day, and the original items that I need to work are stuck on 0.
What can be a situation that it gets stuck on 0? 😫

**Comment by Jhobean** [comment]
Good observation.  The sector awake and fall in sleep mode again.

**Comment by AtillaG1** [comment]
Looks like it, but also the items with can_o_nosleep somehow. 
![image](https://github.com/Sphereserver/Source-X/assets/25097484/779778e7-2e8c-4b8d-95ae-9bb66f7d69d5)

**Comment by AtillaG1** [comment]
More info:
After the sphere restart, all the items even with flag are set as sleeping and thus the timer will stuck at 0.

**Comment by Jhobean** [comment]
Interesting... That mean boot process set item to sleep!?

**Comment by AtillaG1** [comment]
> Interesting... That mean boot process set item to sleep!?

It seems like it set all the sectors to sleep immediately, this way all the items too.
Maybe using different method
