### ISSUE TITLE
Npcs with spawn item inside buildings created outside buildings

### ISSUE THREAD

**Issue by DavideRei** [Sphereserver/Source-X#1084]
If you put a char spawn inside a building the npc can be created outside the building.
Even in a dungeon, if you put a spawn in a corridor next to other rooms/caverns, the npc can be created in other rooms/caverns.

![image](https://github.com/Sphereserver/Source-X/assets/118212274/9236ab4b-e43c-44b7-a5b5-a83c3c61486a)

You have to keep low the spawn range if you want the char to spawn where you want to.
On 0.56d (and 0.56c) is not like that, the creature spawns only inside the building/room/corridor where is the spawn item.

**Comment by drk84** [comment]
HMm i doubt the spawn gems ever checked the room  shape

**Comment by DavideRei** [comment]
You can try on 56d. If you are in a room the npc is created outside only if near the door and with the door open. I remember it like this since 2013.

![Screenshot_2023-07-19-00-22-10-760_com android chrome](https://github.com/Sphereserver/Source-X/assets/118212274/052ff79b-c0e9-4750-8667-95c7f9237c50)

It's not a big deal, it's just that it was convenient.

**Comment by Jhobean** [comment]
X fork was in 2016. So the changelog you show is implemented on X.
When spawning, server choose a random position and verify if char is stuck.

**Comment by AtillaG1** [comment]
I can confirm this is happening, thats why I had to add the check if its dungeons, you spawn NPC on spawnpoint, otherwise it can be placed over the locked door, which you can unlock by killing this monster (impossible).
Back then Ive been told the spawn checks for not spawning outside of room, or in dead ends, but it never did.

**Comment by AtillaG1** [comment]
If anyone need im using alternative solution for the dungeons (r_dungeon) event needs to be on the region, until fixed. 😇

> IF (<SPAWNITEM>) && (<SPAWNITEM.REGION.ISEVENT.R_DUNGEON>) 
> 	P=<HOME>
> ENDIF

**Comment by AtillaG1** [comment]
for me it seems like it works, if the NPC should be spawned outside the room you cant access, then its spawned directly on the spawn, correct?

**Comment by DavideRei** [comment]
It works! Thank you!
