### ISSUE TITLE
Locked ships gang plank problem

### ISSUE THREAD

**Issue by DavideRei** [Sphereserver/Source-X#1089]
.add i_deed_small_ship_n
place the ship on water

The ship side items have type t_ship_side_locked
If you dclick a side the type become t_ship_plank

First "problem": t_ship_plank doesn't have a timer anymore. I remember that once, after a while, the plank close itself automatically. Now it remains open indefinitely.

Second problem: dclick both sides and leave the planks open. Now turn right or left the ship (turn right or turn left). The planks are now closed, but the type is not t_ship_side_locked anymore, as it should be. It's t_ship_plank, as if the planks were open.
Now a player without the key and outside the ship, can dclick a ship side and he's teleported on the boat.
So a player can go in the ship, even if the ship is closed, and he's trapped, because inside the ship the sides are locked.

**Comment by drk84** [comment]
Fix sent

**Comment by DavideRei** [comment]
thank you, the problem is solved but now if you open the plank and close it with dclick, the timer is not stopped and the plank is removed :P

**Comment by drk84** [comment]
Fix sent

**Comment by DavideRei** [comment]
thanks
