### ISSUE TITLE
Sphere.ini ManaLossPercent don't work

### ISSUE THREAD

**Issue by Nefrelius** [Sphereserver/Source-X#1096]
in sphere.ini 
ManaLossPercent=100    // Percent of mana lost if cast fail/abort (0-100) 
setting doesn't working unless the setting is 100. 

```
// Mana lost if magic fail/Abort
ManaLossAbort=1        // When spell is abort during casting
ManaLossFail=1        // When spell fizzle because of lacking skill
ManaLossPercent=100    // Percent of mana lost if cast fail/abort (0-100)
```
 
when i set manalosspercent=50 no mana lost.

**Comment by drk84** [comment]
Fix sent

**Comment by xwerswoodx** [comment]
As we haven't heard from you for a while, I am closing that issue, if it still occurs you can open the issue back.
