### ISSUE TITLE
CAN_O_NOSLEEP and sphere reboot bug 

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#1097]
hi there,

this one seems like its working now. #1082
Now there is a problem, if you reboot sphere, all the items and sectors are set to sleeping.
This means the items with flag can_o_nosleep sleeps immediately and never tick.

**Comment by xwerswoodx** [comment]
I can confirm that items with CAN_O_NOSLEEP go sleep after server reboot.

**Comment by AtillaG1** [comment]
Heyo, any chance anyone had time to look at this thingy? 🦕
