### ISSUE TITLE
attacker.target work only if the NPC is casting spells

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#1098]
![image](https://github.com/Sphereserver/Source-X/assets/25097484/ecee5779-66b3-4d14-8464-de3aac662dc0)
attacker.target should return the best target that the NPC is fighting with. But right now, if the NPC isnt casting magic, the target will always be -1. It used to work on older X versions.

**Comment by drk84** [comment]
oh for NPC not for player

**Comment by AtillaG1** [comment]
> oh for NPC not for player

Yup, NPCs

**Comment by drk84** [comment]
fix sent

**Comment by AtillaG1** [comment]
Good, thanks!
