### ISSUE TITLE
Lumberjacking doesn't work with non file static trees

### ISSUE THREAD

**Issue by DavideRei** [Sphereserver/Source-X#1112]
.add i_tree_5

Equip an hatchet and try to chop the tree: "you cannot chop so close to yourself".
If i add SKF_NOMINDIST to the skill flags i get "try chopping elsewhere".
No worldgem bit is created

It's the same with trees with static flag saved in spherestatics.scp

**Comment by drk84** [comment]
Woah i have noticed even normal trees doesn't produce any wood

**Comment by Jhobean** [comment]
Some repport on my shard about this too. Player try different tree far from city and sometime it work. Weird.

**Comment by xwerswoodx** [comment]
Was a really simple issue but hard to notice 👎

**Comment by Jhobean** [comment]
Ho god!!!  Nice fix it was a weird intermittent bug

**Comment by DavideRei** [comment]
It works! Thank you
