### ISSUE TITLE
npc <attacker> ignore

### ISSUE THREAD

**Issue by Cele35** [Sphereserver/Source-X#1114]
When player takes aggro of 1 creature and moves behind the wall
When player 2 kills the creature, they both see <attacker> as uid 0
06:55:ERROR:(sphere_item_char_icons.scp,55)Can't resolve <uid.0.name>.
both players can't open the corpse

[@death.txt](https://github.com/Sphereserver/Source-X/files/12729107/%40death.txt)

when i check with serv.log it doesn't see the person who killed the creature. it sees the person who took the agros

18:10:(e_pet.scp,76)tag0.olum0=01edc
18:10:(e_pet.scp,77)tag0.dam0=0
18:10:(e_pet.scp,76)tag0.olum0=01edc
18:10:(e_pet.scp,77)tag0.dam0=0

**Comment by drk84** [comment]
You can't use this for script problems

**Comment by Cele35** [comment]
I am progressing by checking with serv.log I think I need to query the damage given with @gethit
