### ISSUE TITLE
f_onchar_create_init dosnt work

### ISSUE THREAD

**Issue by Tolokio** [Sphereserver/Source-X#1117]
as title said. It dosnt work.

![image](https://github.com/Sphereserver/Source-X/assets/20745578/5f27de2d-1214-4bf2-99d4-999c4916c2b3)

f_onchar_create does work

![image](https://github.com/Sphereserver/Source-X/assets/20745578/14b9b38f-c8b2-4801-a98c-4a6b63c5bb46)

I think it dosnt work cos it is called from Client and client is always 0 on any serv_trigger

**Comment by Tolokio** [comment]
![image](https://github.com/Sphereserver/Source-X/assets/20745578/088d9aff-681c-42ac-bcb0-401940702888)

This check never get fired, we could remove it cos it is not needed anyway.
This is what happening if u try to create a new character 
![image](https://github.com/Sphereserver/Source-X/assets/20745578/ecbab897-7b87-432a-a5fe-685484abc2ad)

And it denys character's creation.

![image](https://github.com/Sphereserver/Source-X/assets/20745578/e10ebf5e-4818-41cf-9893-4628af5216e3)

**Comment by drk84** [comment]
f_onchar_create_init doesn't work because the 2nd parameter is null, it should be pChar or &gServ. 
When you do serv.log it tries to call the command on the 2nd parameter, but because there are no object nothing is displayed (it actually trhrows a warning)

**Comment by xwerswoodx** [comment]
&g_Serv is probably better choice here, while pChar is initialized after this function triggered.
