### ISSUE TITLE
Issue with Pet Attacking (going criminal)

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#1123]
if you have AttackingIsaCrime=0 in the INI and you make your pet attack someone, you will go criminal upon targeting them. This should match the behavior that happens when a player attacks someone. so when its disabled only go criminal when actual damage is done.

**Comment by AtillaG1** [comment]
now even after the hit from pet, Im not criminal. Anyone can confirm?

**Comment by xwerswoodx** [comment]
I tested it many times but I can check it when I am on pc

**Comment by Soulless-1** [comment]
working fine for me here. tested with a variety of alignments. when attacking an innocent char with my pet it only goes criminal after they get hit. @AtillaG1 can you confirm or give more info about your specific scenario?

**Comment by AtillaG1** [comment]
Tested it again more carefully and it works fine, sorry. I need to stop testing these things as a GM 😁

**Comment by Soulless-1** [comment]
okay perfect. thank you! closing out
