### ISSUE TITLE
Paralyze Spell behaviour (possible enchancement request?)

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#1124]
Applies to both NPCs/PLAYERS

**Old Behaviour:**
Cant move, cant use items, but can cast spells and fight

**New Behaviour:**
Cant do anything, nor unparalyze youself

**Proposal:**
If the new behaviour is intended, make an switch in sphere.ini, to change between old and new behaviour.

**Comment by Jhobean** [comment]
I remember there a flag added on item you can check. "Can use when paralyse"
What paralyse suppose to do? Able tonattack yourself?

**Comment by drk84** [comment]
yea there is a can flag

**Comment by AtillaG1** [comment]
OK correction, I have tested it wrongly. Only difference between old and new behaviour is that now, If players / NPC paralyzed, cant attack anyone, even someone standing right next to him.

I Found the flag for the cast while paralyzed.

**Comment by xwerswoodx** [comment]
I added Combat flag for it, you can check ACTIONS tab if you wish to update. 080000 is the new flag that I added, and if it set, character can continue to attack while paralyzed.

**Comment by AtillaG1** [comment]
works, thank you.
