### ISSUE TITLE
Hardcoded in-game CHAT, DEBUG

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#1140]
Tested with OrionUO
Cant see any messages, and the DEBUG spam will appear

ChatFlags=01|02
https://pastebin.com/4uhySFeV

**Comment by Jhobean** [comment]
About Orion, there a bug with client itself. I was able to fix it. I can share.
Does the chat was working for you with orion before this commit?

The debug you get need to be fix on sphere.

**Comment by AtillaG1** [comment]
> About Orion, there a bug with client itself. I was able to fix it. I can share. Does the chat was working for you with orion before this commit?
> 
> The debug you get need to be fix on sphere.

I honestly never tested it before as I though that it was never implemented/working and I have full custom global chat and other chats.
What is the bug in Orion? Yes if you could share it that would be great, since I assume Hotride isnt coming back anytime soon. 🤔

**Comment by AtillaG1** [comment]
looks like fixed
thanks
