### ISSUE TITLE
[Feature Request] Visual Range diff set sphere.ini settings

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source-X#1144]
`m_iVisualRange = UO_MAP_VIEW_SIZE_DEFAULT;`

The fixed setting may be different for each server or separate for authorized accounts, or it may be desired to increase it with an additional item. Here, instead of this being a constant, it can be added so that the maximum VisualRange value can be adjusted in Sphere.ini. Unless this setting is present, sphere will not allow this even if we enter the .visualrange 40 command.

eg;
`m_iVisualRange = g_Cfg.m_iVisualRange;`

_The codes here are purely examples. Although many have been tested, some may need to be rewritten._

**Comment by cbnolok** [comment]
That's just a default value, you can change it using VISUALRANGE via scripts.
Is it worth it, in your opinion, to add a ini setting to change the default value? 16 or 18 is the maximum value supported by the official clients, do custom ones support higher visual range?
