### ISSUE TITLE
[Bug (Maybe)] Kill Increase When a Criminal Kills

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source-X#1160]
In the past, +kill was not earned when a criminal was killed.

eg fix;

old:
```
	else if ( NotoThem != NOTO_GUILD_SAME )
	{
		// I'm a murderer !
```

new:
```
	else if ( NotoThem < NOTO_NEUTRAL && NotoThem != NOTO_GUILD_SAME )
	{
		// I'm a murderer !
```

_The codes here are purely examples. Although many have been tested, some may need to be rewritten._

**Comment by cbnolok** [comment]
Maybe a ini setting would be good here to edit default behavior, and an override in a trigger could be useful

**Comment by Soulless-1** [comment]
is the request to add a kill to a player who kills a criminal? that's not typically how UO works, since a kill is a murder, and you cannot 'murder' someone who is committing criminal actions. this sort of custom behavior could be achieved in the scripts as well.

**Comment by Raylde** [comment]
Here i think we have a "little problem"
In the original UO content. Kills are only earned if the killed mark the murder count

https://uo.com/wiki/ultima-online-wiki/player/the-murder-system/

but in the website say
```If the victim dies before the criminal flag timer ends, the attacker is guilty of murder, regardless of whether he actually administered the killing blow. This includes damage inflicted by pets or summons.```

so criminal kills dont earn kills

**Comment by Raylde** [comment]
Closed, this work fine. Maybe implement the feature of Report murder system
