### ISSUE TITLE
[Feature Request] New trigger: @Drink

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source-X#1162]
There may be a need for a trigger that will fire when a character drinks potion. It may be necessary to replace the empty bottle returned by a potion, or you may want to adjust the time of drinking the next potion here, or you may want to turn off the loss of potion when the potion is drunk.

under void CChar::Use_Drink( CItem * pItem )

```
	const CItemBase *pItemDef = pItem->Item_GetDef();
	ITEMID_TYPE idbottle = (ITEMID_TYPE)pItemDef->m_ttDrink.m_ridEmpty.GetResIndex();

	int64 pDelay = 150;
	word pConsume = 1;

	TRIGRET_TYPE iRet = TRIGRET_RET_DEFAULT;
	if (IsTrigUsed(TRIGGER_DRINK))
	{
		CScriptTriggerArgs args;
		args.m_pO1 = pItem;
		args.m_VarsLocal.SetNumNew("IdBottle", idbottle);
		args.m_iN1 = pDelay;
		args.m_iN2 = pConsume;
		iRet = OnTrigger(CTRIG_Drink, this, &args);
		idbottle = (ITEMID_TYPE)args.m_VarsLocal.GetKeyNum("IdBottle");
		pDelay = args.m_iN1 ? args.m_iN1 : 150;
		pConsume = args.m_iN2 ? (word)(args.m_iN2) : 1;

		if (iRet == TRIGRET_RET_TRUE)
			idbottle = (ITEMID_TYPE)ITEMID_NOTHING;
	}
```
ON=@ drink
// return 1 = does not give empty potions
// argo =the potion she drank
// local.IdBottle = empty potion id
// src = drinking char
// argn1 = cooldown time
// argn2 = potion reduce amount

_The codes here are purely examples. Although many have been tested, some may need to be rewritten._

**Comment by drk84** [comment]
SpellEffect do that with argo being the item used, but it will be nice to add the coooldown time for potions as currently is hardcoded

**Comment by canerksk** [comment]
> SpellEffect bunu argo kullanılan öğeyle yapıyor, ancak şu anda sabit kodlanmış olduğundan iksirlere bekleme süresi eklemek güzel olacak

It would also be nice if it gives an empty potion after using the potion or if it gives an empty potion with a different id.

**Comment by Jhobean** [comment]
I like this new trigger.  Could be use on alcool bottle too.

**Comment by Tolokio** [comment]
> > SpellEffect bunu argo kullanılan öğeyle yapıyor, ancak şu anda sabit kodlanmış olduğundan iksirlere bekleme süresi eklemek güzel olacak
> 
> It would also be nice if it gives an empty potion after using the potion or if it gives an empty potion with a different id.

![image](https://github.com/Sphereserver/Source-X/assets/20745578/a789d33c-618f-465e-95ff-665b095beaf5)

U can modify data1 to retrieve a diferent empty bottle or whatever.

and LAYER_FLAG_PotionUsed should be able to be modified so u can set there the CoolDown by many ways.

**Comment by Tolokio** [comment]
> SpellEffect do that with argo being the item used, but it will be nice to add the coooldown time for potions as currently is hardcoded

Should be nice to use tdata2 for it. so if tdata2 is defined it would be used to override potion's cd.

**Comment by canerksk** [comment]
When the potion is made with the tdata value, this will be valid for all items. It seems like it would be nice to set the empty potion refund in a customized settings menu so that it can be turned on and off. I don't think it's shockingly effective to include too many triggers instead of controlling many things about the pot you drink with a single trigger.
