### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by Nefrelius** [Sphereserver/Source-X#1165]
When I delete a guildstone or any multi with the latest build, sphere.exe closes directly. I tried it with a clean pack to see if I broke it and the same thing happened there. Can someone test this or is it a known issue? (agust 28 build work fine and not close) 

SphereServer Version X1-Nightly [Windows-x86_64] by www.spherecommunity.net.
Compiled at Oct 24 2023 (13:34:57) [build 3693 / GIT hash bc500502500a5aa70b36114140b6b6264939eb9c]

**Comment by AtillaG1** [comment]
seems like fixed
