### ISSUE TITLE
@hitCheck trigger too slow

### ISSUE THREAD

**Issue by Nmls021** [Sphereserver/Source-X#1166]
Hi,

I have found that @hitCheck on X is much more slower than on older spheres. Here is 1 second timer. Due to slower hitCheck its nearly impossible to do a swing while running around your target. 
Probably best way would be adjustable timer on it

**Comment by AtillaG1** [comment]
I tested it yesterday evening with latest build and I can hit the target everytime Im passing around him while running with each next swing as it comes....
Maybe you are trying to achieve something else, that Im not aware of. Just wanted to share my testing.

**Comment by AtillaG1** [comment]
Ideally you should test it with latest sphere + X script pack, try different sphere.ini settings, and if the problem persist, then its an sphere issue, if not, its your custom combat.
