### ISSUE TITLE
[Bug (Maybe)] Should the cursor return to normal after death?

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source-X#1172]
If the cursor does not close after death, we may invite many things, otherwise we may need to ask whether the cursor is dead or not under each targeting query. This can also be optionally added as a death trigger argument or INCLUDED IN DEATHFLAGS.

for example;

`DEATH_CLOSECURSOR 0x020`

```
if ((m_TagDefs.GetKeyNum("DEATHFLAGS") & DEATH_CLOSECURSOR ))
pClient->addTargetCancel();
```

**Comment by Raylde** [comment]
Not need to have DEATH_CLOSECURSOR  because is normal behaviour that cancel target when character death

**Comment by DavideRei** [comment]
In ClassicUO they did a commit to not close the target on character death because it's OSI default behavior, they say

**Comment by cbnolok** [comment]
So, are there clients where the target is not cancelled on death?

**Comment by DavideRei** [comment]
Yes
https://github.com/ClassicUO/ClassicUO/commit/fd7bede01e6fd3959aa422bf6870b179b8e7e5c6

**Comment by canerksk** [comment]
Maybe some servers may want to take action after death in order to use additional systems, so I thought it would be better to connect it to a deathflag.
