### ISSUE TITLE
Slayer property works on NPCs with faction 00 or different

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#1179]
If I add slayer property, for example faction_wolf to the spellbook or weapon, and hit monster that doesnt have any faction or different one, it will still count the extra damage.

Seems like the different types of slayer / faction are ignored, as far as weapon or book have slayer, it will always calculated extra damage bonus.

**Comment by xwerswoodx** [comment]
I remember that I did some changes on FACTION system before, should be fixed already, but is it still an issue?

**Comment by AtillaG1** [comment]
Yes, this issue is different, and was created probably by the fix you made for me before.
Now the problem is that if you have weapon slayer *040* and NPC faction *020* or *00*, the NPC still get extra damage from the slayer, which shouldnt.

**Comment by AtillaG1** [comment]
solved on dev branch, thank you!
