### ISSUE TITLE
New Flag: Can_I_Timer (Feature Request)

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#1180]
For the items that are create with "can_i_timer"

1. Item created in the world or placed in the container/layer with set timer, will be allowed to decrease the timer and trigger @timer
2. If the item is moved from the ground or layer to the container, the timer will be kept and not anulled to -1
3. If the item is on the ground and timer triggers, proceed with the trigger and then kept default behaviour (decay)

I assume this flag would have to be connected to the can_o_nosleep, since there can be situation when the item is left somewhere and once the sector falls to sleep, the trigger would not fire? Or maybe once the sector is awake?

**Comment by jexnico** [comment]
I really need this
