### ISSUE TITLE
SQL Error: 21

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#1203]
I just wanted to start doing some LDB stuff, and probably find out that it might be broken?
I have tried the dynamictemplates from X scriptpack to confirm the issue, and the result is spam of same errors I got from my script.

Function used: f_DTL_ldb_rebuild
Problematic line: 		

> ldb.query` INSERT OR REPLACE INTO '<def.DTL_DB_Table>' ('defname','class','race','sex','expansion','flags') VALUES `("<local.defname>","<local.c>","<local.r>",<dlocal.sid>,<dlocal.e>,<dlocal.f>)

![image](https://github.com/Sphereserver/Source-X/assets/25097484/ed67b5a0-79b0-465c-b487-7b7d38b4a98e)

**Comment by cbnolok** [comment]
That's indeed weird, it worked at the time, might have been broken by a sqlite update? I'll look into it

**Comment by AtillaG1** [comment]
> That's indeed weird, it worked at the time, might have been broken by a sqlite update? I'll look into it

Is there any recent commit for sqlite with older artifact that I could test to confirm?

**Comment by AtillaG1** [comment]
It kind of works If u use the function from console, but this way, im not able to run it from players or from ingame to change their progres or so. Dont know if its intended or not, or im doing something wrong.

**Comment by canerksk** [comment]
![image](https://github.com/Sphereserver/Source-X/assets/10347131/2b10cb6a-6ec0-4f0c-9ce6-bf96ca287763)

**Comment by AtillaG1** [comment]
Is it possible that somehow using it from game, not from server console, there are some permissions missing?
