### ISSUE TITLE
Criminal & Guard Problem.

### ISSUE THREAD

**Issue by Nefrelius** [Sphereserver/Source-X#1213]
First of all, I apologize for writing a message with translation. My English is not very good.

SphereX penalty system is different from old version emulators (like 56b).
For example; there are two blue players. One of them orders his followers to kill and attack the other blue player. At this point, the attacking player becomes a criminal and when the injured player calls GUARDS, a guard comes to the attacking player. BUT! If the followers ordered to attack are BLUE/GREY and they harm the player, they are not guilty. Their name is now GRAY and I have memory_sawcrime on me, but when I call a guard, the guard doesn't come or the guards around don't attack. Because they are only GRAY but not GUILTY. For example, if a player attacks a vendor (banker etc) where city guards are active, he dies, but the followers (attacker) do not die. The guard comes for the follower and does not attack the follower :) It only attacks if the follower is in PK state. The setting in Sphere.ini says that if the owner is guilty, the follower is also guilty. There is a logic error here. Each character should be guilty with their own memory. Can't a PK player ride a BLUE mount?
If this is not seen as a bug, a setting should be introduced in sphere.ini.

Translated with [DeepL.com]

**Comment by canerksk** [comment]
see also #1040

**Comment by Nefrelius** [comment]
I wanted to make a video on this topic, but the size is too big to embed it here directly. Video link : [HERE](https://www.youtube.com/watch?v=krl4hQ37-2g)
