### ISSUE TITLE
Follower Commands Don't Work.

### ISSUE THREAD

**Issue by Nefrelius** [Sphereserver/Source-X#1215]
There is no need to elaborate on the problem here.
We know that there are commands for followers such as kill, come, stay and these are heard by the follower closest to us. But when the player types ALL <command>, all the followers around him should obey the command. But there is no such thing :) Even if you type Kill or All Kill, only the follower closest to you hears the command.  BUT! The player once typed ALL KILL and the closest follower attacked. Then if the player types ALL KILL again, all followers attack. I think there is a small query error.

[translate DeepL]

**Comment by xwerswoodx** [comment]
It looks like working for me , I spawn 5-6 horses around and when I type ALL KILL all of them start attacking, are you sure it's not a script-side bug? Could you reproduce it with an clean sphere?

**Comment by Soulless-1** [comment]
i tried it also myself. as non gm, surrounded by many untamed animals and my tamed animals. they did attack the target
![image](https://github.com/Sphereserver/Source-X/assets/17236327/c161bb60-d124-45cf-8e60-3b9228ad0e5c)

in the past though i did report some issues, and i believe they were resolved, at least it appears that way as of current.

**Comment by DavideRei** [comment]
There is a bug in CChar::NPC_Act_Follow, it the pet follow his master, it uses m_Act_UID else it uses m_Fight_Targ_UID even if the pet is not in combat!
I can fix this

**Comment by xwerswoodx** [comment]
I tried again with the info you gave, I used all kill, attacked all npcs to the one target, then used all come and they start following me, used that way many times even tried to change all kill target, they always listen what I told and changed their target, even stop and following me etc, but all command range looks a bit small maybe this makes player to think it doesn't working, I will check the range

**Comment by AtillaG1** [comment]
Thats is great to hear!!! I will comment my custom commands and try it again!
Also "All guard me" should work too right? automatically attacking what im attacking.

**Comment by xwerswoodx** [comment]
Yes, I tested all guard me and it works fine too, as soon as I tried to attack, every npcs around me start attacking it
