### ISSUE TITLE
t_crops

### ISSUE THREAD

**Issue by falanlar** [Sphereserver/Source-X#1216]
![aaaa](https://github.com/Sphereserver/Source-X/assets/77461792/066de84c-29a0-40a4-aabf-314807bb0db2)

The " More" values ​​of this do not work properly, you can try it on corn plants.

**Comment by falanlar** [comment]
sorry, the working value is not more1 but tdata2 and tdata3

**Comment by xwerswoodx** [comment]
I am checking it right now and it seems like working exactly as it explained in picture, no issue over here, could you check if you still have any issue, maybe it's already fixed.

**Comment by cbnolok** [comment]
Closing since it appears to be working correctly, unless proved otherwise.
