### ISSUE TITLE
Pets with property "Bonded" not following after death

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#1225]
This was introduced by Coruja in 2015, since then it wasnt touched. It looks like its working fine, the only thing is, the pet after death is wandering, and when calling him to follow me, he stops and just dont move anymore. Even tho action is set.
![image](https://github.com/Sphereserver/Source-X/assets/25097484/2f6afae7-8fc0-49e8-8de9-3358526d9a92)
TBH no idea if it should be able to follow, I think it should.
https://github.com/Sphereserver/Source-X/commit/16e8c1a9b4a86f0ff7956356216889ab90617e07

https://i.gyazo.com/2821f576fc73d4606573e86be5c0ccda.mp4

**Comment by xwerswoodx** [comment]
I guess it's because you are GM on. I test it now, and yes if you are GM it listens you and start following you, if you go a little far it starts walking towards you, but if you are not gm, it directly ignores your commands. And I tested and following seems working fine with default script pack. But normally players cannot command them so they are just need to wander around.

**Comment by AtillaG1** [comment]
I tried to add some script solution to this so pet will follow me, but its seems like there is not way to do it.
If its intended or not, maybe some switch for that would be good, but is nothing major and up to you guys if its worth.

**Comment by xwerswoodx** [comment]
I haven't tried but it seems like working same as wild animals, so if you want let someone to command him, you just need to give him an ownership.

**Comment by AtillaG1** [comment]
it has Owner, its just that the bonded status is blocking all other than wandering
![image](https://github.com/Sphereserver/Source-X/assets/25097484/d3970cc2-49a9-4a88-86f0-5a991de5a350)

**Comment by Jhobean** [comment]
We are able to know how it work on osi?

**Comment by AtillaG1** [comment]
A bonded pet, when killed, turns into a ghost that will accept non-combat based commands. It cannot target or be targetted while in this form, nor can it be [stabled] . A player with [Veterinary]skill is capable of resurrecting the creature. However, as a result the pet will lose 0.1 from any skills it had prior to death.

https://www.uoguide.com/Pet_Bonding

**Comment by xwerswoodx** [comment]
I created a c_llama, tamed it with a player character, then set it's bonded value to 1, killed him, and I used come command with a player character, and seems like working fine.

**Comment by AtillaG1** [comment]
I cant seem to make it work like you said, even with player char.
Do you set bonded as player char or gm?

**Comment by xwerswoodx** [comment]
I used .xbonded command on llama with my gm char of course, as players can't use commands but the llama is owned by a player character, and after I killed it (with .kill command), when I say all come it start following the player character without any issue.

**Comment by AtillaG1** [comment]
Ok I might try to play with some sphere.ini settings like DeadCannotHear or pet speech, because I'm doing the same and Llama is just standing like dummy 🤣

**Comment by AtillaG1** [comment]
Ok, I figured that out, its not listening to me, because im using // Ghosts are not able to see and hear living players and creatures (0=disabled, 1=only npcs, 2=both npcs and players)
DeadCannotSeeLiving=0

Shouldnt this flag works only for players?

**Comment by AtillaG1** [comment]
solved on dev branch, thanks!
