### ISSUE TITLE
Not able use events on item. Bug?

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#1226]
```
[EVENTS e_potato]
on=@DropOn_Ground
serv.log DropOn_Ground work!

on=@DClick
serv.log dclick work!

on=@DropOn_Char
serv.log  DropOn_Char work!

[TYPEDEF T_potato] //(EDITED)
on=@DropOn_Ground
serv.log TEVENTS DropOn_Ground work!

on=@DClick
serv.log TEVENTS dclick work!

on=@DropOn_Char
serv.log TEVENTS DropOn_Char work!

[ITEMDEF 0f06]
DEFNAME=i_bottle_black
TYPE=t_potion
TDATA1=i_bottle_empty
WEIGHT=1.0
RESOURCES=1 i_bottle_empty
tevents=T_potato
CATEGORY=Magic
SUBSECTION=Potions (basic)
DESCRIPTION=Potion (Black)(Nightsite)
ON=@Create
   MORE1=s_night_sight
   MORE2={30.0 90.0}
   events= e_potato
```

It's normal I can't use events on an item?

**Comment by xwerswoodx** [comment]
tevents=T_potato

tevents should be type events means you need to defined in [TYPEDEF] not [EVENTS]

**Comment by Jhobean** [comment]
Ok work for tevent.

But If I have an existing item and want add an event on it, it work?

**Comment by xwerswoodx** [comment]
Seems like events also works on TYPEDEF I am not sure if it's a default behaviour, as I have never used event on items. But if it's a default behaviour why TEVENTS added, probably it's an issue.

**Comment by Jhobean** [comment]
Ok made some test with Gladie.

Apparently Item can have event on them but it make nothing. You can add event on them but they must be define as a TYPEDEF.
Example 

```
[TYPEDEF ei_potato]
on=@DropOn_Ground
serv.log DropOn_Ground work!
```

after that you can do
`.xevents +ei_potato`
