### ISSUE TITLE
region.tag (t_multi)

### ISSUE THREAD

**Issue by Steinny** [Sphereserver/Source-X#1228]
im use command ".xregion.tag.forsale = 1" on t_multi of house
.xshow region.tag.forsale return 0

im use command ".region.tag.forsale = 1" in house area
.show region.tag.forsale return 1

.xshow region.uid and .show region.uid return equal

.xshow region.name return "name" of t_multi
.show region.name return "name of region (name of t_multi)" like Mainland (Wizard Tower)
i dont know why this work like that

in sphere ini
AreaFlags=02

and i checked if i do .region.tag.forsale = 1
in taglist on t_multi tag.forsale does not appear

and another wish
when command .region.tag.forsale
sphere server should send a reply message

**Comment by Steinny** [comment]
in my defense, I will say that I study the scripts that come with the sphere X.
and I asked this question in discord

**Comment by xwerswoodx** [comment]
Honestly I don't remember how was it in older version of sphere but as I remember it was always like this, maybe I misremember but it can be script-side issue, or we may set region of the multi as a main region, so region could be used on multi.

**Comment by Steinny** [comment]
I agree with this logic in scripts, but not when I do it manually in the game.

**Comment by xwerswoodx** [comment]
I've already sent a fix for it, it seems like REGION reference missed for multis so with a pr build it should work fine.
