### ISSUE TITLE
t_multi_custom remove

### ISSUE THREAD

**Issue by Steinny** [Sphereserver/Source-X#1232]
After remove t_multi_custom 
I can't build new a house
.xshow houses return 0
but i have msg "House redeeded. You already own..." - its hardcoded msg.
after save and restart server. all work correct.

**Comment by AtillaG1** [comment]
I reported this long time ago, and it was fixed. Maybe the problem is back?
History:
https://github.com/Sphereserver/Source-X/issues/895
https://github.com/Sphereserver/Source-X/commit/ba966c81e78d8c2df21e2c6fa3bab4997cd73f44

**Comment by Steinny** [comment]
I downloaded the new version now and the problem remained

**Comment by xwerswoodx** [comment]
I see, so many collisions inside CItemMulti, need to check it deeper, firstly _iHouseTotal not load after server restart so this is why it looks like solved for you. Secondly, someone adds a multicount for each multi. Although it's writeable, it doesn't saved anywhere at all, so while remove same multi it can remove less/more slots. This issue looks like a pain in ass, I will take a look.
