### ISSUE TITLE
TEVENTS not being saved on the item

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#1235]
1. build house (multi)
2. on the brass sign, it will add (ei_house_sign), which is dialog for housing. (added to the sign via itemdef)
3. save sphere
4. reboot sphere
5. check brass sign
6. TEVENT is no longer there

Changing TEVENT to EVENT, it will save it fine.

**Comment by xwerswoodx** [comment]
It's working fine for me, are you sure you are using correct command to check? You need to use .xshow TEVENTS to check TEVENTS?

**Comment by xwerswoodx** [comment]
It still looking fine for me, I created house, turned it to customizable house,

Before Restart:
![image](https://github.com/Sphereserver/Source-X/assets/6155640/596ed54e-9ba2-4dd7-9ab6-d6238cacb20f)
After Restart:
![image](https://github.com/Sphereserver/Source-X/assets/6155640/2b800f7f-dcc4-447f-b306-a3e38b5ac950)

**Comment by xwerswoodx** [comment]
Could you try it with this build;

https://github.com/Sphereserver/Source-X/actions/runs/8680991381

maybe it was fixed, while I am fixing another things.

**Comment by AtillaG1** [comment]
Hmm didnt help. I wonder what can cause this on script side. Doesnt make sense to me.

**Comment by AtillaG1** [comment]
Ok, got it. For some reason I had defname=i_sign_brass for 3 different signs. Even tho they are custom itemdefs with ID of original.
Thanks for help!

**Comment by cbnolok** [comment]
> Ok, got it. For some reason I had defname=i_sign_brass for 3 different signs. Even tho they are custom itemdefs with ID of original.
> Thanks for help!

Didn't you get a console error for that?

**Comment by AtillaG1** [comment]
Nope, I think its because the items are scripted fine, only has same defnames, which for custom items work like alternative name or something, not sure 100%.

**Comment by AtillaG1** [comment]
![image](https://github.com/Sphereserver/Source-X/assets/25097484/4dc4cf2f-469e-42db-867e-387999779192)

**Comment by Jhobean** [comment]
Normaly on boot you should have a warning like "redefining i_sign_brass"

**Comment by cbnolok** [comment]
I think you get that error message only when setting a defname as an argument to the itemdef section header, i feel we should add a warning also when overwriting with a duplicate defname inside the section itself
