### ISSUE TITLE
PLEVEL commands not working on GM account

### ISSUE THREAD

**Issue by DavideRei** [Sphereserver/Source-X#1243]
I have GMs with PLEVEL account 4 that can't use commands even if the commands are in spheretables.
For example .set tag.test=1

I added SET and TAG command under [PLEVEL 4] in spheretables.
Also XSET and XTAG because in the past i found that some commands works only on yourself and not on others if you don't add the same command with X. For example MOVE and XMOVE. In oldest version of Sphere you didn't have to do that.

.set tag.test=1 works on the GM char itself but you can't use it on other chars.
You can select the target but Sphere tells you "You lack privilege to do this".

With other commands the target it doesn't even open.
For example .set mana=10

It seems like adding SET or TAG in spheretables it's not enough, like if you have to add also all the commands that the GM could use after .set

In addition, .tag on yourself (without .set) doesn't work "You are not privileged to do that".

**Comment by DavideRei** [comment]
Jhobean made me notice that there is a .ini option to use commands

// Set from 0 - 7 to set what the default plevel is to use commands.
DefaultCommandLevel=7

- Added #1916: sphere.ini now contains "DefaultCommandLevel". It takes a level
  of 0 - 7 (# corresponds to plevel). Default is 7. Whatever you set the value
  to will be the min plevel for a char to use all commands not in a [plevel xxx].

If i set 4 seems to work, but is it safe? In this way he could use any function like a command, right?

**Comment by Soulless-1** [comment]
it's safe. this is typical of it to work this way. you can test to make sure that commands above it are not usable.
