### ISSUE TITLE
can_i_damageable and ItemHitpointsUpdate, do not update status

### ISSUE THREAD

**Issue by GladieUO** [Sphereserver/Source-X#1248]
Hi,

so i find out that if u have item with can_i_damageable, and you set as GM .xhits 10, it will update the status instantly.

But if you do it via script like hits -=10 it will take hits, but not update the status bar.
If you try use damage <amount>, it will trigger the @damage trig, but not give any dmg.
Is it fixable or client issue?

![image](https://github.com/Sphereserver/Source-X/assets/25097484/3d620f75-0a25-415c-b7bd-df6bc8c98584)

edit: if you change dispid or for example target that item with something, it will update the status, but update doesnt work
edit2: chaging something on the item works too, for example immediately add +1 to more2

**Comment by Jhobean** [comment]
What if you do Update on damage trigger?

**Comment by AtillaG1** [comment]
> What if you do Update on damage trigger?

Seems like its not possible to pass damage to the item with this flag to fire @damage trigger on it.
If I tried to bypass it and then fire update in there it didnt help.

By using damage XY,dmg type,source to trigger @damage it doesnt do damage

Its all weird 😁
