### ISSUE TITLE
ON=@FollowersUpdate not working as intended?

### ISSUE THREAD

**Issue by GladieUO** [Sphereserver/Source-X#1251]
> Added @FollowersUpdate trigger called in any update of followers related to OF_PetSlots:
> 	argn1 (R/W): 0 = Adding followers (taming, unshrinking, summoning, buying ...), 1 = sustracting followers (release, transfer ...)
> 	argn2 (R/W): FollowerSlots used.
> 	SRC: Pet causing the trigger to run, when buying in vendors there's no PET yet, so SRC will point to the vendor.
> 	Return 1 will not allow following actions to occur: Transfer, Summon, UnShrinks from t_figurine, Buy from vendors. Any other actions (like release, set owner...) will not take in count returns.

Im using EF_FollowerList and OF_PetSlots. Im trying to use my own followerslots, since the default behaviour is not using more than 1.
Somehow, even tho i set ARGN2 to whatever amount, there is always only 1 slot used.

Is this suppose to be still linked to the maxfollowers and curfollowers, and slots? I feel like its working like half a way 😥

**Comment by AtillaG1** [comment]
https://github.com/Sphereserver/Source-X/blob/8e444840f7e916126f5f4c1a56b4049e34b20fbd/src/game/chars/CCharUse.cpp#L1172

It will add correct follower slots only if EF_FollowerList is disabled.

**Comment by xwerswoodx** [comment]
Ah okay I totally forgot that there is FollowerSlots for pets honestly, it's totally my mistake, I am currently waiting nolok to finish his work, then I will take a look for this issue.

**Comment by GladieUO** [comment]
PRs and commits in regards to this issue should be ignored. This one is waiting for followerslots rework to vector.

**Summary:**
EF_FollowerList and OF_PetSlots activated together dont check followerslots on CHAR, and add always +1.
