### ISSUE TITLE
SkillClass on NPCS

### ISSUE THREAD

**Issue by Tolokio** [Sphereserver/Source-X#1253]
This is a suggestion.

Right now, Skillclass is not RW on npcs.

U can force skillclass to store value even on npcs, but U can't read it.

Trick: Give npc an account, set/read skillclass, remove npc from account. (Value will remain, but u need to make the npc player to RW it)

The idea is to activate SKILLCLASS on npcs.  No other change, just that. Activate skillclass to let it be used.

No skillgain changes or any other. 

I asked developers and no one told me a reason to deny skillclass on npc.

If people agree, I can do a pull.

pd: I dont mind if people dont agree, but I think this is an improvement.

**Comment by cbnolok** [comment]
I think this is too far from how UO ever worked and managed it, it's not the case to add support for that in the core, also because it's not as simple as "enable to write that property on npcs". It can be easily managed in scripts though.
