### ISSUE TITLE
(opinion) Retrocompatibility is a lie

### ISSUE THREAD

**Issue by Tolokio** [Sphereserver/Source-X#1262]
Well, I want to share my opinion about one thing. I just want to talk straight without offending anyone or dramas. Plz dont get offended. And be polite. I dont force anyone to read this or agree with me.  

I think keeping "stuff" for retrocompatibility is causing problems and denys improvements. We could have better systems, better performance if we cut that fear to make admins adapt their scripts. I think there are stuff that we should keep but not if it blocks good improvements, we should aim for the improvement with the best design as possible.

**Why should we respect retrocompatibility?**

Sphere 56b/d/c scriptpacks are not compatible with sphere-x. It needs toons of changes. There is no real retrocompatibility. U can say there is but it is a lie, it is partial. If anyone wants to use their old scripts on new sphere-x they will need to work many hours on it.

If admins wants the best updates for their server/project/busyness it is normal that they have to work on it. Most of them have personal interests to adapt their script to have a better shard. sphere´s colaborateurs dosnt have that motivation. And if admins dont want adapt script, they dosnt deserve the update. **What we cannot do is to move all that work to colabotareur's and dev's side**. **There got to be a balance**. I know it can be a headache for admins to update their scripts. But it is even more headache what we have to renounce to preserve outdated features. (and the work it gives)

Sphere should aim for best integral solutions always, not for best patchs. Retrocompatibility are the parents, and we should not be scare of make admins work on their project for a good cause. If the update worth they will update and if not they will not. Sphere until I know sells nothing, we dont have to be afraid of customers. I think this is about learning how do things as best as posible, help each other for no profit, and being proud of ur own work. It is hard to be proud if work is crippled.

(remember I got no personal or special interest on sphere-x source and I am not talking about me)

**Comment by cbnolok** [comment]
I beg your pardon, who does get benefits? Can you explain that better?
To me it's obvious that it's impossible to achieve full retrocompatibility, but this doesn't mean that we should push breaking changes constantly. We must have respect for people's time, everyone here is doing this for fun (except some shard getting donations perhaps?) and on spare time, breaking changes should be kept at a bare minimum and done only if it's really worth it.
That said, simply and honestly put, i don't think that the changes you suggested were useful for more people than yourself, for two reasons.
First, you are asking to change a behavior that has always been untouched and had always been working for everyone, only to match your desirable expected behavior. As i can read from others in the issues, really, this behavior is bothering only you and it is seen as a necessary change by no one. Not saying also that this can be changed via scripts. Not saying also that sphere is open source and you can keep a fork with your custom changes.
Second, just because you want a thing to work like you feel it should, you can't ignore the desires and expectations of other people on that and for sure you can't force for that reason every other sphere user to change their scripts.

**Comment by Tolokio** [comment]
Hope u did not get this as an attack, cbnolok. All my respects... I know it is hard to get me. 
Nobody in sphereserver gets profits until I know. Not from shards not from users.

I agree with u at all points cbnolok.But I think We need to study deeply certain features before reject it cos retrocompatibility. Sphere-x is complex and deep, it is not about black or white I think. It is a whole thing moved by many pieces connected to each others. You change one and change many of them. I dont want to force anyone, but the "isvalid" change did and I see it wonderfull. What's the rule?  Changes on source-x dosnt affect my project so I dont have any personal interest but bringing best improvements as possible and learn in the process.

I dont want to talk about profits but go look on any Uo shard and look for donation systems. None would pass a deep tax officer inspection. But the thing is, admins got interests, profits, ambitions to make their shards be the best. Could be emotional , economical or whatever. The interest of any shard dont have to bother anyone here.
There are tons of servers opened, that get 2-5k money thx to fake donations system and then close as they sux keeping all money and selling server's files for more even more profits.
REceantly and old server from Xun was opened giving profits for months by selling virtual things. Couple month after opening, server closed and the owner sold files to a player that already spent a lot of money on the server. He even sold all other scripts and arts that people donate to his server to help him. 

I just took that economic argument to tell a point. **Admins have interest to make their server be the best** and get most players as possible, not us. Not not only emotional interest but economical.** If update is worth they will work on it, if not they will not work on it**.  Our updates are not pulled into their live shards messing everything. They decide. there are nightlys and releases, they can update or not, they can eval if it is worth or not. They can work with stable or unstable version.
 I dont talk about ignoring feedback and deny any retrocompatibility by system. No way. I just point it is not worth that mentality and it makes sphere+x to be worst than it should be.
 
This is for many cases, no only maxhits. But for example in maxhits case, @statchange is very powerfull, u could center all stats managment there, but trigger cant be used as pretended cos we want to preverve a "smart fix" from 55 that is no longer needed! Where is the point? that fix was very smart then, but now it is not. Who are we supporting preserving it? what are we really supporting with that mentallity? It is not worth. We should be here for the science. What's the goal of the proyecT? Support people's live's shards and interests or do best work as possible? Sphere-x is no longer 56b or 55! Lets be brave and lets unchain sphere-x. Dont let it be dragged by old outdated features that no longer have sense to preserve personal interests of certain admins we dont even know.

**Comment by cbnolok** [comment]
I get your point and i respect that, but to me the line is "how much of an improvement will it be, and how much of an hassle for others will it be". For isvalid? Big hassle, but enormous gain, and just this is a proof that no one here is contrary on breaking compatibility just because. For your @statchange idea? Some hassle, but what's the upside? I honestly feel there is no one, since it works perfectly fine for 99% of the people, and for that 1% it can be extended via scripts.
People getting profits on their shards might be a reality, but i'd be very cautious to say that it's the majority of them. And changes are not something can be set on and off: if someone stops updating the core won't miss only that new enhancements but several others, plus bug fixes, so it's not really "well, i don't like that so i will just plain stop updating, whatever".

**Comment by Tolokio** [comment]
Ty for the words and the time.

First, I want to clarify that the @statchange idea is not mine. It was developed and improved by Nazghul, Xun, Matex, and you. I’m just trying to ensure it works as designed, without unnecessary limitations. I believe you don’t see its full potential, which is currently hindered by an outdated feature from 55i that isn't useful today. It's just a convenience for those who don’t want to spend five minutes updating scripts. Im not defending my idea or work at all.

**This is  about our decision-making process**. Is there a rule or protocol? How do we evaluate these things? When is a common opinion properly formed? 

You mentioned, "Some hassle, but what's the upside? I honestly feel there is no one since it works perfectly fine for 99% of people, and for that 1%, it can be extended via scripts."

What you said isn’t accurate, Nolok. It’s your perception, not reality. If it were true, I’d be extremely happy to be in the 1%, but that’s not the case. If that's the rule I'm advocating for, let's use it. Bring in more people until I’m the 1%, and establish a protocol for that rule. That’s my point. Please, look at how we make decisions and form opinions.

Nolok, only three people have commented on it, and they don’t even understand my point. They haven’t evaluated or tested the improvement, and they dont know the source. One of them is upset with me. With that, you tell me your opinion is formed. You claim 99% of people have spoken, and you decide it's not worth it break retro, so let’s make another easy patch instead. Come on, man. Is this how you operate? Is it serious? Do you think it’s respectable?

Why don’t we ask the people who developed that trigger for their opinion? Nazghul, Xun, Matex... maybe they agree with you, or maybe they don’t. Do you really think you have enough feedbackto discard anything? Has the improvement been thoroughly evaluated? By whom? How did you form your opinion? You talk about your feelings and a supposed majority of 99% to explain why it’s not worth breack BC. Are you serious? Do you think anyone with common sense would put up with this? They won’t stick around, or maybe they’ve already left.

 **Please community, think about this for a moment** What kind of motivation will anyone have to invest their time in seeking the best, if something as trivial as 'maxhits' causes literally the best option to be rejected due to retrofoolishness? **It's like putting all your talent into making perfect and unique chairs for a community only to see how they wobbly them for selfish reasons**. Are you telling me you think it was worth to do this to the guys who made the @statchange trigger? The community should understand how important it is to motivate talent instead of frustrating it with arguments like that. They will leave. **If community cannot give up something as useless as 'maxhits' in exchange for the best, you are selfish and do not deserve the skilled people helping.** By the way, where are them? Burnt maybe? I think community should regret about BC. It is a big mistake. Who doubts that maxhits is hindering the best possible solution? do you really thinks it is worth what u do? for what? for whom?

"People getting profits on their shards might be a reality, but I'd be very cautious to say that it's the majority of them."

Really? "99% (of 4) have spoken" is right but "majority" or "most of them" is a drama... Are u serious?... Who doubts that the majority profit? Especially with Sphere, which is simple to set up. Maybe you don’t count short-lived servers, those that open, get 2-5k in a couple of months, then close and sell the server’s files to the highest bidder and foolish player. But even without counting those, they are still the majority. However, I don’t want to discuss about economic or emotional profits. We need to understand we dont know who are we supporting, which is why shards interests should be the lowest priority. If they can’t invest five minutes in improvements, why should collaborators invest 40 minutes juggling mental gymnastics to preserve nothing by making lazy patches everywhere? Why is community forcing that just for selfish? Who has the real interest here? Why should we sacrifice the best systems and proud, for what exactly? Retrocompatibility is already broken, so what’s the problem? **As long as Sphere-X shards exist, should we stop striving for the best development?** Why was Sphere-X created? There were other goals beyond fleeing from Brazil. Why have these been missed? 

 I don't want to change how community decides or how anyone evaluates anything,I think it would be not needed if some simple rules like these were applied. I think this proposal is well balanced.

1-Always aim for the best (with head)

2-If the best solution is found, implementation can be postponed but never denied due to backward compatibility reasons. This ensures that we only evaluate the technical prowess without further delay, thereby avoiding wasting anyone's time.

3-Priorize Script tools/control over harcoded settings. Many times it is more interesting to "developt" script modules and tools in the scriptpack than having patches everywhere and less powerful tools. U already started to do it on scriptpack, so I just say we could follow and improve that philosofy. It is also good for new user to have more scripts and examples on scriptpack.


Dudes, I know I'm hard to understand and a very chaotic person. Thanks for your patience.

Best regards,
