### ISSUE TITLE
FLAGS & too long numbers (bug is back)

### ISSUE THREAD

**Issue by GladieUO** [Sphereserver/Source-X#1268]
Hi,

this bug was fixed some time ago #1078 , but now for some reason its back.
Basically try to set .xfaction 0200000000 on monster or NPC. It does nothing.

I think its again problem with too long def numbers?

Also might be connected to this -> #1255 #1256 thats the reason I looked for the free slots, since the long ones we're not recognized.

**Comment by cbnolok** [comment]
That commit should have fixed handling flags between 0xFFFF and 0xFFFF FFFF, but flags greater than 0xFFFF FFFF never worked (and if they  did, they *appeared* to do so but it should have been situational and not reproducible).
