### ISSUE TITLE
Calling custom trigger on timerf

### ISSUE THREAD

**Issue by GladieUO** [Sphereserver/Source-X#1273]
With the latest master with the housing system, im trying to call custom trigger with timerf 1, but seems like its not being call at all.

```
[TYPEDEF ei_house_sign]
On=@Create
	timerf 1, serv.log halo <uid> ------> this part works, and UID is house sign
	timerf 1, trigger @HouseSysInit -------> this is not being called at all.
```

**Comment by cbnolok** [comment]
Did it happen with the previous master?

**Comment by GladieUO** [comment]
> Did it happen with the previous master?

It was good before

**Comment by GladieUO** [comment]
One more addition to this, I think problem is with custom triggers, they are not being fired at all. I think its the custom triggers, and not timerf.

**Comment by GladieUO** [comment]
fixed. https://github.com/Sphereserver/Source-X/commit/7a9a90c47c5c5d7aaade18778ce7232962ef3b9e
