### ISSUE TITLE
Move the server binary of the workflow

### ISSUE THREAD

**Issue by raydienull** [Sphereserver/Source-X#1277]
When workflow generate the binary of server, create a folder like `build/<arch>` 

Idea is move from that build, to the root of the folder. For have the files in folders in the right order

```
- accounts/    
- logs/
- save/
- scripts
- sphere.ini
- sphereCrypt.ini
- SphereSvr // executable in root
```

**Comment by cbnolok** [comment]
Couldn't we change the archiviation command in the workflow to add the exec in the root folder? Or just mv-ing it to the root folder

**Comment by Otacon** [comment]
I think it's just a misalignment of the 7z command between the two platforms.
Yes, I think we could just add a `mv` command and that's it.
