### ISSUE TITLE
Broken Profiler

### ISSUE THREAD

**Issue by GladieUO** [Sphereserver/Source-X#1278]
I dont think its working correctly?
![image](https://github.com/user-attachments/assets/8e70540b-1361-4705-9e68-11f3a6ed7cd8)
![image](https://github.com/user-attachments/assets/2cdd31e8-46fd-4029-986e-73879585047a)

**Comment by Jhobean** [comment]
I confirm. Missing some info

**Comment by cbnolok** [comment]
Is your ini FreezeRestartTime > 0?

**Comment by Jhobean** [comment]
Profiler without TMain (not working)
![image](https://github.com/user-attachments/assets/93eb07fa-04d9-43df-9850-6f6056278772)


Profiler with T-MAIN working
![image](https://github.com/user-attachments/assets/6393b5c7-0c6c-4371-b737-559a4ad52c19)



Bug Begin maybe on this one:
https://github.com/Sphereserver/Source-X/commit/89e27bfd3e578e67b5c8973890e9c5d952edc977
(I'm not able compile it on my PC)

Or this one https://github.com/Sphereserver/Source-X/commit/75a07b4498bd62837c6f51afa968fb5c8789df64

**Comment by GladieUO** [comment]
> Profiler without TMain (not working) ![image](https://private-user-images.githubusercontent.com/51728381/362030432-93eb07fa-04d9-43df-9850-6f6056278772.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4Njk0ODUsIm5iZiI6MTcyNDg2OTE4NSwicGF0aCI6Ii81MTcyODM4MS8zNjIwMzA0MzItOTNlYjA3ZmEtMDRkOS00M2RmLTk4NTAtNmY2MDU2Mjc4NzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE4MTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZTliMmVkYzE5NmZmNTU1ZTg4MDg4NzFkNmQxNTA3YTJkZmY4ZjEzYjZkM2U1NWM3MjJmY2ZkZjc3ZWYxMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wOCoJWH3kfsKuuA95lmxGTYI4npxZZseo8UENHpG43k)
> 
> Profiler with T-MAIN working ![image](https://private-user-images.githubusercontent.com/51728381/362029458-6393b5c7-0c6c-4371-b737-559a4ad52c19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4Njk0ODUsIm5iZiI6MTcyNDg2OTE4NSwicGF0aCI6Ii81MTcyODM4MS8zNjIwMjk0NTgtNjM5M2I1YzctMGM2Yy00MzcxLWI3MzctNTU5YTRhZDUyYzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE4MTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YjRiYmQ1YzU2ZjllNjUzYTVlNDRmMzM0NDgyYjNhNDA1MTUzZjZhNjQ5ZjE0MTFlZWFiNDA0NmIzZWRkNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UfJ5QQCGRQbGqs72iRJrUtuWn7SLXhkReunzHvQ0QFA)
> 
> Bug Begin maybe on this one: [89e27bf](https://github.com/Sphereserver/Source-X/commit/89e27bfd3e578e67b5c8973890e9c5d952edc977) (I'm not able compile it on my PC)
> 
> Or this one [75a07b4](https://github.com/Sphereserver/Source-X/commit/75a07b4498bd62837c6f51afa968fb5c8789df64)

how do you activate Tmain?

**Comment by Jhobean** [comment]
> how do you activate Tmain?

you can't, I compiled an old build

**Comment by Jhobean** [comment]
Confirm Fix on dev branch

**Comment by Jhobean** [comment]
We now Have this on boot
![image](https://github.com/user-attachments/assets/73be4b9f-1520-4c9b-ad7f-1102a24a2100)

Usefull?

**Comment by cbnolok** [comment]
Guess so, i added it lol
