### ISSUE TITLE
Running a second sphere instance make sphere crash

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#1281]
Normally if you start a second sphere instance you get an error -9 because it's impossible to bind IP.

Now the new sphere just crash.

Bug Begin maybe on this one:
https://github.com/Sphereserver/Source-X/commit/89e27bfd3e578e67b5c8973890e9c5d952edc977
(I'm not able compile it on my PC)

Or this one https://github.com/Sphereserver/Source-X/commit/75a07b4498bd62837c6f51afa968fb5c8789df64

**Comment by Jhobean** [comment]
Yes happen on last dev Windows. Linux I can't test.

**Comment by xwerswoodx** [comment]
I have no issue about it, I just tried to start second instance but gives me -9 error but it didn't crash, can you check if it's still exists.

**Comment by Jhobean** [comment]
Fixed on last dev
