### ISSUE TITLE
Server do not take correct light number on lightsource

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#1284]
If I add a lampost on the map with centred, The light source is good
![image](https://github.com/user-attachments/assets/0d52c924-8c47-4755-81ac-968e2fb57a99)
![image](https://github.com/user-attachments/assets/445b3d20-733a-4ce3-a3a2-4dfb8b2b5e63)
![image](https://github.com/user-attachments/assets/55d673fb-ec33-45dc-8806-13417646f254)

If I add the same lampost on game, I get a weird light source 
![image](https://github.com/user-attachments/assets/fdf40035-7e31-465a-b745-6c65e4b99cf1)
![image](https://github.com/user-attachments/assets/e6a4b014-d8c8-42ef-be90-324616b8761b)

```
[ITEMDEF 0b20]
DEFNAME=i_lamppost1_lit
TYPE=t_light_lit
TDATA3=i_lamppost1
WEIGHT=22.1
CATEGORY=Decoration - Lightsources
SUBSECTION=Lamp Posts
DESCRIPTION=Lamp Post
ON=@Create
   MOREZ=29
```

I try to change the moreZ on script and yes the light source change but make no sens with the value I set.
The only correct number working is 0 to 7  After that, we get weird random light choose (Dono find the patern of random)

**Comment by DavideRei** [comment]
It works for me with ClassicUO, are you sure is not a problem with your client?
I can change morez in game and with .fix i have the updated light and it's correct, event after 7, 29 is working fine for me

**Comment by Jhobean** [comment]
> It works for me with ClassicUO, are you sure is not a problem with your client? I can change morez in game and with .fix i have the updated light and it's correct, event after 7, 29 is working fine for me

Interesting it's client bug. I'll make some test.

**Comment by Jhobean** [comment]
I confirm sphere send the good data 
![image](https://github.com/user-attachments/assets/cf60638b-067a-4e82-ac47-46afdc7804c9)
 Client bug
