### ISSUE TITLE
Attacker.List Add Issue

### ISSUE THREAD

**Issue by xMirroRx** [Sphereserver/Source-X#1350]
If the list is empty, it adds the first person it fights with to the list, but when it attacks someone new, it doesn't add them to the list. I tried adding this manually as ATTACKER.ADD=<x> but it still didn't add it.

**Comment by canerksk** [comment]
![image](https://github.com/user-attachments/assets/f2140365-0755-4e4e-8836-b1f3a33e465d)
It adds the char I attacked to the attacker list.

**Comment by xMirroRx** [comment]
![image](https://github.com/user-attachments/assets/a2b368bb-1dc1-49c9-b23d-1c4c0939dd0f)

**Comment by xMirroRx** [comment]
<ATTACKER> // 4 returns the correct number, but the list content contains only 1 uid.
