### ISSUE TITLE
Picking up partial stacks makes the client duplicate the item.

### ISSUE THREAD

**Issue by shiryux** [Sphereserver/Source-X#205]
Easy way to reproduce this, I was mining with a new character (plevel 1) account.
- Get some iron ore in a single pile.
- Try to separate 1 by 1 (or by 2 if you prefer).
You will see your pile with the same amount you started, and the single ore in the corner of the bag.
Or grab a pile of 100 of any item. Try to pick only 50, you will end with 150.

**Comment by AtillaG1** [comment]
not able to reproduce it, so it looks like fixed ?

**Comment by Seokotov** [comment]
fixed or some experemental flags enabled )))
