### ISSUE TITLE
Showing real armorclass for each part of armor

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-X#268]
Would be nice to make it for tooltips (maybe sphere.ini option)
just calculating it in sphere and showing real armor instead a full set AR

**Comment by cbnolok** [comment]
Tooltips are showing the protection given by the armor piece, can you be
more precise about your request?

>

**Comment by Seokotov** [comment]
![x2](https://user-images.githubusercontent.com/28328535/57264842-09412d00-707d-11e9-9721-8f3e705e9a7a.jpg)

**Comment by drk84** [comment]
You can send a custom tooltip by script with the value for each  armor part, 
see here http://wiki.spherecommunity.net/index.php?title=Armor_Calculation

**Comment by Seokotov** [comment]
yes i can, but it looks totally wrong if using it by default...do you know any other game with same system?
also this calculation have mistakes, cause it's have differences depends by armor type

**Comment by drk84** [comment]
What it  counts is the AR  displayed in the in tooltip, the AR in the status bar is not used when calculating damage.

**Comment by Seokotov** [comment]
yes, it's just useless digits.
therefore, I would like to see real ar that each part can give...sphere calculating this value for equip, so i think it's easy to make it for showing

**Comment by soulless320** [comment]
use this for your tooltips

`
[function real_armor]
local.armorrating=<eval <avgvalue <armor>>+<modar>>
return <eval ((<def0.layer<dlayer>_percentage>*<local.armorrating>)/100)>		//this is in the scripts/custom/defs_templates.scp file

[function avgvalue]
for <argv>
  local.n += <eval <argv[<eval <local._for>-1>]>/<argv>>
endfor
return <dlocal.n>

[defname armor_layer_percentages]	//defines the % of armor that actually counts towards a layer
layer6_percentage		15	//head
layer10_percentage		7	//neck
layer20_percentage		0	//back
layer13_percentage		35	//chest
layer19_percentage		14	//arms
layer7_percentage		7	//hands
layer4_percentage		22	//legs
layer3_percentage		0	//feet
layer2_percentage		100	//shield

`

**Comment by Seokotov** [comment]
looks like almost fine
have some issues. for example:
i see ar=1 on bone arms and ar=17 on my myth legs
if i equip only arms i have 1 ar
if i equip only legs i have 17
but if i equip both i have 19 ar
Why?

**Comment by cbnolok** [comment]
Is this still an issue?

**Comment by Soulless-1** [comment]
I would close it out. he was incorrect in assuming it was a bug, the armor value in UO shows the total provided by all pieces not an individual one. what he wanted was easily achievable in the scripts.
