### ISSUE TITLE
DEFs not working in @Create trigger

### ISSUE THREAD

**Issue by rodBiase** [Sphereserver/Source-X#284]
Sometimes when you put a def inside the trigger On=@Create (probably inside any trigger also) it doesn't work.

On=@Create
ITEMNEWBIE=i_hair_short
COLOR=<def.colors_hair>
ITEMNEWBIE=i_bow
COLOR=<def.match_hair>

It only works if I put:
On=@Create
ITEMNEWBIE=i_hair_short
COLOR=colors_hair
ITEMNEWBIE=i_bow
COLOR=match_hair

**Comment by cbnolok** [comment]
Even with latest commit?

Il lun 8 lug 2019, 21:35 rodrigobiase <notifications@github.com> ha scritto:

**Comment by cbnolok** [comment]
Did it ever work or is it a recent bug?

Il lun 8 lug 2019, 21:36 Claudio Bongiorno <cbnolok@gmail.com> ha scritto:

**Comment by rodrigobiase** [comment]
Compiled at Jul  8 2019 (18:39:28) [build 3130] here.

I remember it was not working 2 months ago, but I completely forgot to report this.

**Comment by cbnolok** [comment]
I forgot about this, it never worked as far as i can remember. The reason is that under @Create trigger, Sphere does only a quick and partial parsing, for speed's sake

**Comment by cbnolok** [comment]
To leave a note for me or anyone willing to help here: an idea could be to restore the old functioning of FULLINTERP.
If that's on in the current context/trigger, switch to full parsing instead of the fast one.

**Comment by xwerswoodx** [comment]
I don't know if it's changed or not but it's working fine for me with latest build.

**Comment by Jhobean** [comment]
There a workaroud proposed by Xun and I tested it and work well:

```
[EVENTS e_damndam]
ON=@Create
ITEMNEWBIE=i_hair_short
COLOR=<def.colors_hair>


[CHARDEF c_npcToSpawn]
...
...
tevents=e_damndam
```

**Comment by Soulless-1** [comment]
tested and working fine for me with the latest build. closing this issue out.
