### ISSUE TITLE
Negative skillgains when under the infuelce of stats altering spells

### ISSUE THREAD

**Issue by Iron-Wolf-UO** [Sphereserver/Source-X#325]
If a player is influenced by a negative stats altering spell (Mindrot, curse, weaken, whatever)
He/She will gain negative skill-gains instead of positive should any skillgain occur during the spell is active.

**Comment by cbnolok** [comment]
Can you give a precise way to replicate this? I did SPELLEFFECT s_curse, 100.0 on myself and i started attacking an npc, from 10.0 tactics and wrestling are increasing, not decreasing. Does this happen really with every skill or also for ones? In the latter case, do you have any negative or unordered values for ADV_RATE, BONUS_*, STAT_* etc in the SKILL block?
