### ISSUE TITLE
The stairs its still not working in custom multi (check old issue)

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#329]
with X latest and X scripts it is working. With our scripts NOT.
with coruja latest build and his scps = working. With our scripts working.

_Originally posted by @AtillaG1 in https://github.com/Sphereserver/Source-experimental/issues/320#issuecomment-541930689_

**Comment by cbnolok** [comment]
Could you try to add piece by piece your housing code to vanilla x scripts so that we can narrow down the searching field in the source?

**Comment by Swiftik023** [comment]
I find in scripts this:

https://pastebin.com/qZUssvn0

I change .additem to addmulti, but stairs disappear after resync with warning:
`WARNING:(housing.scp,1511)Unscripted multi 01db0 being added to building 0422d57bf by 00.`

https://gyazo.com/4abab092a35896eda2470e1bb38576f5


but I have scripted multi: https://pastebin.com/u2jHU6YN

where is problem?

**Comment by Swiftik023** [comment]
I comment in scp part after : 'if <local.subcmd>==013' and I have stair without filling: https://gyazo.com/0aa55b60f925acab782a89dbe1485f0d, but it's maybe ok...
