### ISSUE TITLE
Spell Paralyze disturb player's attack target

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-X#342]
when NPC cast Paralyze to players, they lost attack target. Sometime can't just push attacklast, need dismount|mount or peace|war changing
Have no idea why it happen...

**Comment by Seokotov** [comment]
ahh it's happen after all paralyze spell...by player too...

**Comment by alexdan2** [comment]
I make some test too for this issue whit new release (3285) and problem solved.

**Comment by meaowR** [comment]
looks like fixed for me too. Thnx
