### ISSUE TITLE
RegenStat

### ISSUE THREAD

**Issue by alexrmrm** [Sphereserver/Source-X#353]
on a horse, if you are riding on it it was not executed (on any animal).
once it is dismount it is not executed again.

**Comment by alexrmrm** [comment]
not work, if u are mount pet dont regentstat

**Comment by alexrmrm** [comment]
Not fixed.

First problem was fixed with commit of https://github.com/Sphereserver/Source-X/commit/41a8b163f07e912c023ffe4da20ab031e8af1b10. That problem was: when dismount npc not regen again anymore.

But second problem: If u mount, npc not exec @RegenStat

**Comment by alexrmrm** [comment]
`13-03-2021, Nolok
- Added: LASTDISCONNECTED player keyword, holding the SERV.TIMEHIRES at the time of the last client disconnection.
- Fixed: LASTUSED player attribute was not saved.
- Fixed: Object not being removed from client view when its CONT was changed.
- Fixed: If Timer elapsed on an object in a disconnected or sleeping state, the trigger wouldn't fire when the object got active again (Issues #535, #596).
- Fixed: Timer and REGENs not firing on a ridden characters (Issue #353). Now it fires even if the original character (which gets detatched from its physical REGION) is in a sleeping sector,
    given that the riding character is in an active (not sleeping nor disconnected) state.`

trying with last build, but not work.

`[events e_test_Regenstat]
ON=@RegenStat
serv.log exec regenstat on <name>
if (<local.StatID> == 3)
 serv.log <name> ! food exec..
endif`
Dismount work when mount stop of work that event.

**Comment by cbnolok** [comment]
Is this still an issue?

**Comment by Soulless-1** [comment]
looks to be working
![image](https://github.com/Sphereserver/Source-X/assets/17236327/82ee335b-fc0d-4588-bd80-fb7da442c74d)

closing issue out
