### ISSUE TITLE
Backward compatibility script don't work

### ISSUE THREAD

**Issue by FiLoUs64** [Sphereserver/Source-X#357]
DEFNAME used for backward compatibility don't work. If you do for example .add i_multi_ship_small_n , it's not detected. If you use it as <DEF. it work.

> [DEFNAME backward_compatibility_defs]
// Ships (multis)
i_multi_ship_small_n				m_small_ship_n
i_multi_ship_small_e				m_small_ship_e
i_multi_ship_small_s				m_small_ship_s

**Comment by canerksk** [comment]
I am having the same problem.

```
[DEFNAME backward_compatibility_defs]
c_daemon					c_demon
```

`Invalid WORLDCHAR block, index 'c_daemon'`

**Comment by canerksk** [comment]
There is one more workaround. It works if defined as DEFANAME2.

for ex;
```
[ITEMDEF 02136]
DEFNAME=i_pet_ostard_frenzied_2
DEFNAME2=i_pet_ostard_zostrich

```

**Comment by xwerswoodx** [comment]
For the information about latest update of nolok;

Using [RESDEFNAME backward_compatibility_defs] instead of DEFNAME solve your issue from now on.

I tested in my server, and confirm that it is working fine.
