### ISSUE TITLE
Tooltips not showing

### ISSUE THREAD

**Issue by orishi** [Sphereserver/Source-X#359]
Confirmed on Discord discussion by drk84, X is not showing tooltips for client <6.0.50. I'm currently using 5.0.9.0. On 56 version the tooltips work without any troubles.

> drk84 today at 13:37
> no no
> confirmed
> version before 6.0.50
> does not show up
> the tooltip

**Comment by meaowR** [comment]
check your ini or scripts...all fine for vanilla X

**Comment by orishi** [comment]
> check your ini or scripts...all fine for vanilla X

We already did a lot of testing, it's not the scripts or ini. Confirmed with drk84 on discord, as I already stated above, that this is a bug and that the tooltips are only showing for clients >6.0.50

**Comment by orishi** [comment]
Any progress on this? Sorry to bump that, but we kinda need it :(

**Comment by meaowR** [comment]
> Any progress on this? Sorry to bump that, but we kinda need it :(

no
anyway i decided to not using tooltips anymore )))

**Comment by orishi** [comment]
I'm still stuck on 56 on this "project", too bad. Unfortunately I cannot use higher client version without making huge changes to it :(

**Comment by Nirad** [comment]
@orishi is it posible to ask you where i can find your mul file?

**Comment by orishi** [comment]
@Nirad you don't need muls to replicate this, just download basic ML client with 5.0.9.0 patch

**Comment by Nirad** [comment]
@orishi you can test the core with this fix here : https://ci.appveyor.com/project/Nirad/source-experimental-c49x7/build/job/n4lhisy36m0ny0i6/artifacts

**Comment by orishi** [comment]
@Nirad For character it works fine. It doesn't work for items, they don't show any tooltip at all.

**Comment by Jhobean** [comment]
??? 
![image](https://user-images.githubusercontent.com/51728381/102224029-7355c100-3eb3-11eb-891c-18ed749229e6.png)

**Comment by orishi** [comment]
It's probably something in my scripts then. Lets wait if there is more feedback from other users. I'll check it later again.

**Comment by Jhobean** [comment]
> There something strange. At your first connexion it's do not work because you dont have the Version configured. Log out log in and it's work.

Ok "Bug" found. First login your tooltip is not activate because your account dont have clientversion on the save. Just reboot the client and it will be fine. After the next save your tooltip will work for ever.  I confirm this Fix work on my side

**Comment by orishi** [comment]
It was script error on my side, it's working correctly.

**Comment by Jhobean** [comment]
Its not merge yet
