### ISSUE TITLE
Adding REQDEX and REQINT to items properties like REQSTR for same using

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-X#360]
It's not a problem just Feature request. 
Adding REQDEX and REQINT to items properties like REQSTR for same using

**Comment by cbnolok** [comment]
It isn't an OSI property as far as i know, you can easily achieve this custom feature by scripts, using a TAG and @ItemEquipTest trigger

**Comment by Seokotov** [comment]
yeah, i know it but would be great to have this properties

**Comment by cbnolok** [comment]
Looks too niche to me to add official support to that
