### ISSUE TITLE
How about add overrideTAG.NAME.HUE for items?

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-X#362]
How about add override TAG.NAME.HUE for items?

**Comment by JulianUO** [comment]
Hi,
You can change the color in @AfterClick using local.ClickMsgHue
Also you can modify the message displayed in there.

**Comment by meaowR** [comment]
hey, i think about this option too. But i wanna easy change name's color in tooltips. 
and for click of course

**Comment by JulianUO** [comment]
I'm sorry but name's color can't be changed on tooltips, that's client side.

**Comment by meaowR** [comment]
> I'm sorry but name's color can't be changed on tooltips, that's client side.

im changing it by tags, but it work for custom tooltips only
```
on=@clienttooltip
IF (<TAG0.NAMECOLOR>==1)
ADDCLILOC 1063491,<DEF.HTML_BLUETEXT>,<NAME>
```

if you overridename for player it will showing in tooltip too, so...it's possible

**Comment by meaowR** [comment]
wait a minute
tag.name.hue coloring clicked name only? if so, why it needed?
![p1](https://user-images.githubusercontent.com/61579076/77838751-50e21300-717f-11ea-8798-de5e4ebf1159.jpg)

**Comment by cbnolok** [comment]
Same as #390. Will continue there.
