### ISSUE TITLE
parrying gain

### ISSUE THREAD

**Issue by alexrmrm** [Sphereserver/Source-X#365]
you gain skill in combat without a shield

**Comment by cbnolok** [comment]
Which parrying flags are you using in the ini?

**Comment by alexrmrm** [comment]
// Parrying behaviour
// 01 = pre-SE parrying chance formula (not using the Bushido skill). Mutually exclusive with 02 flag.
// 02 = SE parrying chance formula (using also the Bushido skill). Mutually exclusive with 01 flag.
// 010 = can parry with a shield
// 020 = can parry with a one-handed weapon without a shield
// 040 = can parry with two handed weapons
// 080 =  Shield Armour value will scale according to the character's skill, otherwise only a 7% of the ARMOUR value is used. Not compatible with Combat Elemental Engine Flag
CombatParryingEra=01|010

**Comment by drk84** [comment]
Hmm i probably introduced it when i changed the <= to < in the following check:
`
Had to replace <= with < otherwise we will never be able to increase the parrying  skill if the Parrying skill is too low.
	For example, without a shield and using the legacy formula we will not be able to get a gain in the skill if the character
	Parrying skill is less than 8.0.
	*/
   
 if (iParryChance < 0)
        return false;`

**Comment by drk84** [comment]
I think that setting iParryChance to -1 at the beginning instead of 0  would fix the problem, but maybe there is a more elegant solution?

**Comment by cbnolok** [comment]
I think it's a clever solution tbh!
