### ISSUE TITLE
pk creatures on region guarded

### ISSUE THREAD

**Issue by alexrmrm** [Sphereserver/Source-X#366]
if region.guarded 1, pks monster not attack onseeplayer

**Comment by cbnolok** [comment]
What do you mean as pk monsters?

**Comment by alexrmrm** [comment]
![image](https://user-images.githubusercontent.com/20444397/74742619-30a96500-525f-11ea-875c-25a12a4daec4.png)

**Comment by drk84** [comment]
I think it's intended for monsters not attacking first on guarded zone
