### ISSUE TITLE
Multiple errors and loss of a lot of items on startup since build 1.1.0.594

### ISSUE THREAD

**Issue by FiLoUs64** [Sphereserver/Source-X#367]
Got multiples errors on startup after build release 1.1.0.594. I've found that all of the shrink animal are corrupt. When you dclick on the shrink, it become as a c_man and died. Impossible to have newer build on live server, too much error and loss for players.

I have these errors still again but with previous build no.

Problem seems to be with shrink mount and a lot of other items

> 10:04:ERROR:GC: Deleted UID=046a11, Defname='c_drazos', Name='Drazos'. Invalid code=0x1204 (Ridden NPC without a valid mount item).
10:04:ERROR:Mount (UID=046a11, id=061dc 'Drazos'): Can't auto-fix invalid mount item (ACTARG1=04016569e)'
10:04:ERROR: Reason: Mount item in owner's LAYER_HORSE has a MORE2 which doesn't match this mount UID (owner's riding another mount?).
10:04:ERROR:GC: Deleted UID=04006347c, Defname='i_tambourine', Name='Tambourine'. Invalid code=0x1104 (Ridden NPC without a valid mount item).

With build 1.1.0.591 everything working good.

Thanks

**Comment by Jhobean** [comment]
https://github.com/Sphereserver/Source-X/commit/0d3c068ddf479ea1d537fd2a963160139a8d5981
