### ISSUE TITLE
PacketDeath

### ISSUE THREAD

**Issue by alexrmrm** [Sphereserver/Source-X#369]
PacketDeath make anim of "you are death" but not activate black screen

**Comment by xwerswoodx** [comment]
Have you tried to turn on sphere.ini, PacketDeathAnimation setting?

// Enable death screen animation on classic clients (on enhanced clients this is always enabled)
PacketDeathAnimation=1

**Comment by alexrmrm** [comment]
yes i try make anim and show msg of you are death but not black screen.

**Comment by xwerswoodx** [comment]
Hmm, I don't know why that happened, I am trying and packet is sending for me, which version of uo are you using? If you are using Razor or Orion they can block packets or render packets different.

**Comment by alexrmrm** [comment]
client 203 without any.

**Comment by criminalx** [comment]
https://puu.sh/FFnp2/24e52470ce.mp4
that account was gm, but it happen same with player account.

sphere.ini:
// Enable death screen animation on classic clients (on enhanced clients this is always enabled)
PacketDeathAnimation=1

**Comment by criminalx** [comment]
Also you can't pass through a door while dead

**Comment by GitMadKing** [comment]
i can confirm, client 3.0.6j
even if logout and login back, dead, still see in color

**Comment by criminalx** [comment]
It is not fixed yet

**Comment by alexrmrm** [comment]
Not work that fix. continue same problem.

**Comment by xwerswoodx** [comment]
Hmm, I tried with my latest build and I got you are dead animation when I died (tested on 2.0.3 client)

**Comment by xwerswoodx** [comment]
Just for make sure, do you have any @Death trigger? Maybe you can use @Death to send player some safe area when he is dead. If you return 1, he is technically don't die so animation doesn't work. Even nothing done about this from all these time but as I said before I had no issue from the beginning, and after 5 fixes, if the issue haven't solved, I personally think it's some script side issue. Maybe you need to check all of your @Death @Kill @DeathCorpse triggers.

**Comment by cbnolok** [comment]
Is this still an issue?
