### ISSUE TITLE
Cannot add same event to INI for both players and Pets

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-X#370]
If you add it to EventsPet= and then to EventsPlayer= you will get an error about duplicate events. But sometimes you need the same event on an NPC as you do a Player.  Sphere used to function this way in the past as well.

**Comment by fjgo86** [comment]
Right now this would require a big update to CResourceRefArray which stores all events into the same container for other purposes. My best suggestion for the moment is to move all the code inside the triggers of these events to functions, then replicate the events with other name and the same triggers, but just calling the functions instead.

**Comment by soulless320** [comment]
I have it sorted out with the same method you mention, using functions inside the triggers. I just wanted to make sure I reported this, it's not critical, but it was one of those things I constantly forgot to report. Thank you.

**Comment by soulless320** [comment]
confirmed this is working, thank you!
