### ISSUE TITLE
polymorth

### ISSUE THREAD

**Issue by alexrmrm** [Sphereserver/Source-X#375]
not update auto when finish cast spell, need make .update for refresh skin

**Comment by alexrmrm** [comment]
its only for client 203

**Comment by GitMadKing** [comment]
maybe because on sphere_spells animation is an item for higher client.
try use old item for animation.
or maybe just wrong reslevel

**Comment by alexrmrm** [comment]
spell make poly but need make .update for update client and show new skin

**Comment by fjgo86** [comment]
Confirmed, but before sending a fix I would need a range of clients having this problem.

**Comment by GitMadKing** [comment]
i can confirm 2.0.4c

**Comment by xwerswoodx** [comment]
so as developer asked noone cared to help even the one who opened the issue 👎 Maybe you can send a fix directly so we can improve it in time @fjgo86

**Comment by Soulless-1** [comment]
is this still an issue?

**Comment by Jhobean** [comment]
Same than #803 updatex ?

**Comment by Soulless-1** [comment]
> Confirmed, but before sending a fix I would need a range of clients having this problem.

this issue is three years old, please open a new issue with a client range if it still persists.
