### ISSUE TITLE
NPCs sometimes will remain in war mode for long term 

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-X#377]
NPCs sometimes will remain in warmode (statf_war flag) even though combat has ended, they have an empty attack list and they have no memory items for combat.

seems to happen sporadically and i cannot recreate it

**Comment by Jhobean** [comment]
I think this issues may be a part of our bug of "core saturation".

**Comment by fjgo86** [comment]
Set a possible fix to this, tho @Jhobean I do not think this can cause the problem you have because it's just a flag on the character which does not alter it's behaviour.

**Comment by Jhobean** [comment]
Work for me!  NPC do not stay in war mode

**Comment by soulless320** [comment]
This appears to be fixed for me as well, i'll close it out since Jhobean also was able to confirm it.

**Comment by Jhobean** [comment]
I think this issue Is back...
