### ISSUE TITLE
cure poison

### ISSUE THREAD

**Issue by alexrmrm** [Sphereserver/Source-X#381]
cure always cure not check any.

**Comment by xwerswoodx** [comment]
I don't understand what you mean, but if you mean double clicking on cure potion always consume it without checking you have poison or not, it's always like this (if I remember correct) but if you don't want to consume it if he is not poisoned, just add On=@Dclick trigger and check statf_poisoned flag under trigger.

**Comment by xwerswoodx** [comment]
Mate, maybe you forgot the issue you open, could you check this issue? We need more information about that.

**Comment by criminalx** [comment]
he says the poison level is not checked by spell/potion, so with lesser cure, you can cure deadly poison

**Comment by xwerswoodx** [comment]
Oh, got it now, but I guess it's all about cure spell. I can check cure spell for poison levels.

**Comment by cbnolok** [comment]
How does it work on OSI?

**Comment by drk84** [comment]
fix sent

**Comment by drk84** [comment]
I close
