### ISSUE TITLE
Not able to train from NPC

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#383]
They always say the same message and i'm not able to give them gold

![image](https://user-images.githubusercontent.com/51728381/77196700-3ee6dd00-6aba-11ea-8683-4b36de1bf8f3.png)

**Comment by fjgo86** [comment]
I need a little more information, i've tried to train Anatomy and and Animal Taming without any problem both with and without context menus.

**Comment by Jhobean** [comment]
Your are right.

When I use X Script Pack, all work well. When Use D pack no..  Any idea where to look at first?

**Comment by meaowR** [comment]
> Your are right.
> 
> When I use X Script Pack, all work well. When Use D pack no.. Any idea where to look at first?
> 
> The core send this message:
> 
> https://github.com/Sphereserver/Source-X/blob/cd5a196ba71f37d2c526958decb137a9056a6bc9/src/tables/defmessages.tbl#L695

check e_trainer
I remember on 56d there were some problems and bugs related to training skills and dupe money

**Comment by fjgo86** [comment]
The only code from scripts that I see it can alter this behaviour is this:
-TAG.OVERRIDE.TRAINSKILLMAX
-TAG.OVERRIDE.TRAINSKILLMAXPERCENT
-Their relative ini settings.
-@PayGold (argn1 <= 0 aborts the payment, called on the vendor with src = player).
-@DropON_Char (called on the item(gold) with src = player)
-@ContextMenuSelect (if clicking on the context menu to pay)
-@ReceiveItem (called on the vendor, src = player)

**Comment by Jhobean** [comment]
Thx i'll test this WE.

**Comment by Jhobean** [comment]
You was right!  Was missing [EVENTS e_trainer]
THis event is not usefull on 56d but is necessery on X.

Thx!
