### ISSUE TITLE
t_dyes only works with tubs, not with t_dye_vat

### ISSUE THREAD

**Issue by Tolokio** [Sphereserver/Source-X#388]
If u change the type of any ítem to t_dye_vat, u Will be not able to dye it with dyes, the only thing u can dye with dyes are tubs.

gms can dye any t_dye_vat item, players can´t

https://youtu.be/QsbLHCVPs4Y

https://youtu.be/6zIrs_Y6yW4

**Comment by Tolokio** [comment]
https://youtu.be/QsbLHCVPs4Y

**Comment by xwerswoodx** [comment]
This is because you haven't set OF_DyeType flag in sphere.ini to OptionFlags;

Here is the information in sphere ini;
`// OF_DyeType					00008000 // Allow use i_dye on all items with t_dye_vat typedef instead only on i_dye_tub itemdef`
You just need to add 08000 to OptionFlags to active it.

**Comment by Tolokio** [comment]
right

**Comment by xwerswoodx** [comment]
If this solve your issue, please close the topic, so developers knows there is no issue left to check.
