### ISSUE TITLE
TAG.NAME.HUE not changing name's color in tooltip

### ISSUE THREAD

**Issue by meaowR** [Sphereserver/Source-X#390]
![p1](https://user-images.githubusercontent.com/61579076/77848383-f1125900-71cc-11ea-8e2f-4b590d6f8b51.jpg)
i set tag.name.hue=020 but in tooltip it showing same as without tag

**Comment by cbnolok** [comment]
This TAG is supposed to work only with overhead text, not with clilocs, so i'd consider this issue as a feature request

**Comment by meaowR** [comment]
> This TAG is supposed to work only with overhead text, not with clilocs, so i'd consider this issue as a feature request

yes, it is a feature request. now this options just useless, cause we can change overhead text without tags. 
sure, we can change character's color using NOTO. Would be a great to add this tag to noto code.

**Comment by meaowR** [comment]
not the same, but would be nice to have both features ;)

**Comment by xwerswoodx** [comment]
Uhm, i was just checking it, but the problem is TAG.NAME.HUE is depends on hues mul, and clilocs use html color codes, so both are different style. Adding another tag maybe be a solution but I am not sure if it's really needed or not, even it can be easily done by script.

Anyway I am leaving the possible cliloc code here for later usage to not forget it, 1116481

**Comment by Jhobean** [comment]
Yes its a really cool feature if we can change colir name in tooltip. But It's client side I think

**Comment by alexdan2** [comment]
> Yes its a really cool feature if we can change colir name in tooltip. But It's client side I think

Yep is client side.
According information on packet BF.10 - Display Equipment Info 
All data are readed from Cliloc for string and other extra value, Not exist any data for HUE.

**Comment by alexdan2** [comment]
I make better test and is possible.....

Tooltio color can be chaged.. i try this:

.set name <basefont color="#00ff00">ColoredName
And work in tooltip.

![image](https://user-images.githubusercontent.com/6176986/106516275-18b20c00-64d7-11eb-864b-fe2a979418dc.png)

**Comment by xwerswoodx** [comment]
Seems like Julian added a tag for it, so I am going to close it, if needed you can open a new issue or ask us in discord to open the issue back.
