### ISSUE TITLE
Problem with Account Tagging

### ISSUE THREAD

**Issue by xwerswoodx** [Sphereserver/Source-X#391]
There is a problem while you trying to set value on Account with TAG. When I try to use .xaccount.tag.premium 1 in game, it set it to "1" but when I try to set it under script, it doesn't set.

Here is an example code;
```
[FUNCTION hasPremium]
SERV.LOG Check - <NAME>
IF !(<ACCOUNT.dTAG.PREMIUM>)
  SERV.LOG !!!!
  ACCOUNT.TAG.PREMIUM=1
  SERV.LOG PREMIUM: <ACCOUNT.TAG.PREMIUM>
ENDIF
//RETURN <QVAL <ACCOUNT.TAG.PREMIUM>&<ARGS>?1:0>
```
When I use hasPremium on Resci the output is;
```
Check - Resci
!!!!
PREMIUM: 
```
When I change ACCOUNT.TAG to TAG it doesn't have any problem while set the value but when I want to set value on account, it's still empty. And if I try to get <ACCOUNT.TAG.PREMIUM>&01 like <ATTR>&attr_newbie, it gives an error because ACCOUNT.TAG.PREMIUM value is empty. I don't understand why sphere only let me to set account.tag with a command.

**Comment by drk84** [comment]
![immagine](https://user-images.githubusercontent.com/13728442/77910053-bec93000-728e-11ea-916f-f02100190cb9.png)
Works fine here

**Comment by xwerswoodx** [comment]
I download today's release and tried it when you said it's working, working for me too now. Thanks for information.

**Comment by xwerswoodx** [comment]
If you use it as a command it works, for example if you use .hasPremium in game it works, but if you use it under @Hit trigger like, <hasPremium pflag_experience> it does return;

```
VERSION=X1

[DEFNAME dn_premium]
pflag_nothing		01
pflag_damage		02
pflag_experience	04
pflag_drop			08

[EVENTS e_level]
On=@Hit
LOCAL.BONUS=<QVAL (<hasPremium pflag_damage>)?25:0> //25% more damage if the player has damage premium.
ARGN1 += <eVal (<dARGN1> * (<dTAG0.LEVEL> + <dLOCAL.BONUS>) / 100> //1% damage increase per level

[FUNCTION addPremium]
ACCOUNT.TAG.PREMIUM |= <ARGS>

[FUNCTION delPremium]
ACCOUNT.TAG.PREMIUM ~&= <ARGS>

[FUNCTION addPremiumAll]
ACCOUNT.TAG.PREMIUM = pflag_damage|pflag_experience|pflag_drop

[FUNCTION hasPremium]
SERV.LOG Check!
SERV.LOG <NAME> - <ACCOUNT.NAME> - <ACCOUNT.dTAG.PREMIUM>
IF !(<ACCOUNT.dTAG.PREMIUM>)
  SERV.LOG !!!!
  ACCOUNT.TAG.PREMIUM=01
  SERV.LOG PREMIUM: <ACCOUNT.dTAG.PREMIUM>
ENDIF
RETURN <QVAL <ACCOUNT.TAG.PREMIUM>&<ARGS>?1:0>

[EOF]
```

```
15:34:(sphere_system_premium.scp,19)Check!
15:34:(sphere_system_premium.scp,20)Hamit - xwerswoodx - 0
15:34:(sphere_system_premium.scp,22)!!!!
15:34:(sphere_system_premium.scp,24)PREMIUM: 0
15:34:ERROR:(sphere_system_level.scp,251)Undefined symbol ''
```

**Comment by drk84** [comment]
Yup, in  the debug build this warning is thrown:
![immagine](https://user-images.githubusercontent.com/13728442/77969329-c5d15c00-72e9-11ea-8f9c-ee9b8b1b3196.png)

**Comment by xwerswoodx** [comment]
Yeah seems like you can't set value on ACCOUNT under any @Trigger.

**Comment by GitMadKing** [comment]
MAYBE... and i say MAYBE (if i remember right)

there is a plevel for script inside sphere.ini 
so if plevel set for scripts is not enough to set it, cannot do it.

also same for account with higher plevel

**Comment by xwerswoodx** [comment]
But the problem is the command using by the Server itself, so there is no plevel possible to give server, so server can't use account command under triggers at all.

**Comment by GitMadKing** [comment]
under what thing you ar trying to change it?

```
[MENU M_TAT]
<ACCOUNT> SELECT ACCOUNT TAG SETTING <ACCOUNT.TAG0.PREMIUM>

ON=0 3
SERV.LOG @OLD TAG FOR ACCOUNT <ACCOUNT> IS <ACCOUNT.TAG0.PREMIUM>
ACCOUNT.TAG.PREMIUM=3
SERV.LOG @NEW TAG FOR ACCOUNT <ACCOUNT> IS <ACCOUNT.TAG0.PREMIUM>

ON=0 6
SERV.LOG @OLD TAG FOR ACCOUNT <ACCOUNT> IS <ACCOUNT.TAG0.PREMIUM>
ACCOUNT.TAG.PREMIUM=6
SERV.LOG @NEW TAG FOR ACCOUNT <ACCOUNT> IS <ACCOUNT.TAG0.PREMIUM>

ON=0 9
SERV.LOG @OLD TAG FOR ACCOUNT <ACCOUNT> IS <ACCOUNT.TAG0.PREMIUM>
ACCOUNT.TAG.PREMIUM=9
SERV.LOG @NEW TAG FOR ACCOUNT <ACCOUNT> IS <ACCOUNT.TAG0.PREMIUM>

```
23:43:1:'m' commands 'menu m_tat'=1
23:43:OLD TAG FOR ACCOUNT m IS 0
23:43:NEW TAG FOR ACCOUNT m IS 3
23:43:1:'m' commands 'menu m_tat'=1
23:44:OLD TAG FOR ACCOUNT m IS 3
23:44:NEW TAG FOR ACCOUNT m IS 9
23:44:1:'m' commands 'menu m_tat'=1
23:44:OLD TAG FOR ACCOUNT m IS 9
23:44:NEW TAG FOR ACCOUNT m IS 6

**Comment by GitMadKing** [comment]
looks like 
account.tag.premium += 1 //DOESN'T WORK under @hit
serv.account.<account>.tag.premium += 1  // this WORK under @hit

**Comment by xwerswoodx** [comment]
Hmm, thank you for information that you gave. I haven't tested it that much, you found a good solution. I just left that issue open for the developers fix the ACCOUNT issue under @Hit trigger, I thought every trigger call same function (because most of it does that) and because of this, I haven't test other triggers. But your informations is very valuable for the developer who will fix that. Or maybe I can check the hit trigger to find out what the issue, if I can.

**Comment by GitMadKing** [comment]
the problem is actually present, so if someone will fixit is good for others that may face it in the future.
it looks kinda account* is readonly.



Marius

---- On mer, 01 apr 2020 00:14:50 +0200 notifications@github.com wrote ----



Hmm, thank you for information that you gave. I haven't tested it that much, you found a good solution. I just left that issue open for the developers fix the ACCOUNT issue under @hit trigger, I thought every trigger call same function (because most of it does that) and because of this, I haven't test other triggers. But your informations is very valuable for the developer who will fix that. Or maybe I can check the hit trigger to find out what the issue, if I can.

**Comment by GitMadKing** [comment]
CONFIRM WORKING

**Comment by xwerswoodx** [comment]
Yeah I also confirm it working, thank you.
