### ISSUE TITLE
unhide Character when snooping

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#393]
Same Issue than 56d https://github.com/Sphereserver/Source/issues/251

If my character is hide and snoop a back, my hide flag switch to off...

On the skill, I putted these line.

ON=@prestart
if (<src.flags>&statf_hidden)
	serv.log hide
ELSE
	serv.log unhide
endif
On the prestart, my hide flag is already off
That show the unhiding action appear before the skill... It seem that the dclic action unhide.

**Comment by Jhobean** [comment]
Work Very well for snooping on last build! THX!

But the steal dont seem to work well
```
// REVEALF_STEALING_SUCCESS		0100	// Reveal hidden players when stealing successfully finished.
// REVEALF_STEALING_FAIL		0200	// Reveal hidden players when stealing failed.
```

I put these 2 flags and when I am hide and stealing, i'l always stay hide.

**Comment by Jhobean** [comment]
Second Bug, I don't know if it's just me but every player ha a HIDDEN flag on connexion...   So I cant see nobody with my GM...  The only way to see them is with .allshow

This seem to be fix when someone hide and dehide themself

**Comment by xwerswoodx** [comment]
I tested when I coded it and they works fine but I can check the latest build in a minute. For the hidden flag, nothing has changed, but for seeing the hidden characters with gm, you have you use .privset 07 command in game to set yourself as an owner.

**Comment by xwerswoodx** [comment]
I tested it with the latest release and working everything fine. If you wish I can get a video, but maybe it can be the reason if you have changed something under stealing/snooping skill or maybe you can add some hidden flag for testing something.

**Comment by Jhobean** [comment]
Work a+!!  I think I made mistake in my .ini  I forgot the 0 before the number  |100 instead of |0100

Thx for all your help and this cool feature!
