### ISSUE TITLE
Sphere freezes every midnight

### ISSUE THREAD

**Issue by orishi** [Sphereserver/Source-X#398]
SphereServer Version X1-Nightly [WIN64] by www.spherecommunity.net.
Compiled at Apr  1 2020 (18:39:06) [build 3254 / GIT hash 1e2d2f5d07e3134b1e676db5fa35017a3eb32e25]

![image](https://user-images.githubusercontent.com/2725562/78431268-62428800-7675-11ea-98db-5f3ab05b495e.png)

After every midnight, sphere freezes. It doesn't respond to any commands, player cannot login. You must kill the process in order to restart it.

**Comment by GitMadKing** [comment]
maybe happens for some reason when saving satics
1) try changing the hour when savestatics ocurrs (serv_triggers.scp line 168)
2) try saving manually STATICS and see if it still hungs

**Comment by orishi** [comment]
`[FUNCTION f_onserver_save]
// This function is called before server worldsave start.
// Variables:
//	ARGN1 --> Save is forced (writable)
//	ARGN2 --> Save stage (for backgroud save goes 1 to 6146 [sector count + 2])
// Return:
//	0 --> Allow save (default action)
//	1 --> Deny save

SERV.SaveStatics	//Uncomment this line if you are building your server, so static items are saved also with normal saves, or comment it again in live servers to speed up the save proccess (if commented, you MUST type manually .serv.savestatics to save static items)`

There is no hour settings. Statics are saved with every save (20 minutes).
![image](https://user-images.githubusercontent.com/2725562/78452073-7d1ef780-7689-11ea-9814-c97f41cb2056.png)

**Comment by GitMadKing** [comment]
so is not connected with statics, because during the day work,
mult be something connected to new day and first statics save
maybe something connected to other day than when started.

**Comment by alexdan2** [comment]
I can confirm this issue, me and other my friend have same. 

Additional info:
- When happen server process use 0% 
- If close (X) the server window he not really shutdown, have to terminate from taskmgr.

**Comment by cbnolok** [comment]
I think to have found the cause, i'll add the fix to the commit i'm working
on

Il sab 4 apr 2020, 19:34 Alessandro <notifications@github.com> ha scritto:

**Comment by xwerswoodx** [comment]
I don't know if they are connected but when I use .resurrect command, sphere freezes. It doesn't give any error, it doesn't crash the sphere, or it doesn't try to get response, it's just freeze and when you close the application you have to stop it from process in task manager to close. This error occurs when I kill myself with kill command and try to resurrect.

**Comment by orishi** [comment]
Sphere no longer freezes after midnight. Thanks for the fix.
