### ISSUE TITLE
Maxhits vs STR

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#399]
I explain the situation.

On our shard, we have item that only modify MAXHITS.
EX:
```
[ITEMDEF i_chainmail_coif_biro]
defname=i_chainmail_coif_biro
NAME=Coiffe de maille de Biro
ID=i_chainmail_coif
REQSTR=20
WEIGHT=7.0
ON=@EQUIP
SRC.MAXHITS=<SRC.MAXHITS>+2
```
It's fine. But now my STR and MAXHITS are unlink. If I equip a second item boosting my STR, my hits do not move.

Important add to this. When str and maxhits are unlink, the spell do not affect anymore. Maxhits, maxstam and maxmana.....

We have MODSTR item too (Work well if we do not equipe the other item FIRST)
```
[ITEMDEF i_fou_chest]
ID=i_platemail_chest
TYPE=T_ARMOR
WEIGHT=23.0
ARMOR=115
REQSTR=60
NAME=Plastron du berseker

ON=@EQUIP
SRC.HITS=<SRC.HITS>+50
SRC.MODSTR=<SRC.MODSTR>+50
ON=@UNEQUIP
SRC.HITS=<SRC.HITS>-50
SRC.MODSTR=<SRC.MODSTR>-50
```

Any hint how to fix that?

ISSUE ON 56d TOO: https://github.com/Sphereserver/Source/issues/249

**Comment by GitMadKing** [comment]
create a player tag.bonushits
on equip
maxhits=0 //link to str
tag.bonushits += 5
maxhits=<ostr>+<modstr>+<tag0.bonushits>


kinda?

**Comment by Jhobean** [comment]
Don't think it work because you  modify maxhits...

**Comment by GitMadKing** [comment]
then use this: https://wiki.spherecommunity.net/index.php?title=@StatChange
when changing str or modstr recalculate including tag.bonushits

**Comment by GitMadKing** [comment]
oh, wait. there is no need to do so..

**just use MODMAXHITS**

**Comment by Jhobean** [comment]
Working THX!!!
