### ISSUE TITLE
Server crash when cast Magic Reflection

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#400]
Hello, when cast this spell server crash.

Spell definition:
[SPELL 36]
DEFNAME=s_magic_reflection
NAME=Magic Reflection
SOUND=snd_spell_magic_reflection
RUNES=IJS
CAST_TIME=3.0
RESOURCES=i_reag_garlic,i_reag_mandrake_root,i_reag_spider_silk
RUNE_ITEM=i_rune_magic_reflection
SCROLL_ITEM=i_scroll_magic_reflection
FLAGS=spellflag_dir_anim|spellflag_targ_char|spellflag_fx_targ|spellflag_good|spellflag_bless
EFFECT_ID=i_fx_bless_effect
EFFECT=0
LAYER=layer_spell_magic_reflect
DURATION=60.0,2*60.0
MANAUSE=14
SKILLREQ=MAGERY 50.0
INTERRUPT=100.0,100.0
PROMPT_MSG=Who shall you protect?

Additional info:
- How try use simple .cast s_magic_reflection in game
- Server simple close no trace of any error in logs file
- Try on different version build (X64) 3257 (last) and old one same issue
Thx

**Comment by GitMadKing** [comment]
did not happen to me
Compiled at Apr  3 2020 (17:48:03) [build 3255 / GIT hash f008c5c2fbb86ee1365f1c9cb6874a4cc754f37b]

**Comment by alexdan2** [comment]
I'm using https://forum.spherecommunity.net/sshare.php?srt=4 clear script pack for test and happen also.

Possible some different in INI ?

**Comment by GitMadKing** [comment]
also me 
magicflags=0
clean scripts
try clean sphere.ini

**Comment by pentanorl** [comment]
it seems that both "s_magic_reflection" and "s_curse" cause crash only when casted on players on @spelleffect. On npcs they work as supposed to (at lease magic reflection, curse seems to do nothing).

**Comment by alexdan2** [comment]
Is is a ini flag. Coming details...

**Comment by pentanorl** [comment]
Looks like the OptionFlag "OF_Buffs" conflicts with the CombatFlag "COMBAT_ELEMENTAL_ENGINE". Disabling one or the other solves it.

**Comment by alexdan2** [comment]
yes @pentanorl. I can confirm if enable OF_Buffs and COMBAT_ELEMENTAL_ENGINE server crash when cast.

**Comment by alexdan2** [comment]
Just tested on Build 3262. Fix working good. No longer crash when cast s_magic_reflection and s_curse on Playerm whit both flags enabled
