### ISSUE TITLE
Server Crash on Save (GC Issue i think) - Build 3257 

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#401]
Hello,
Server crash when save and someone have deleted a char 'Mounted'. if no mount seems not happen.

Extra info:
- Log error (https://pastebin.com/eqe7AvXF)
- Happen only on build (3257) Last 
- Use clear script pack

**Comment by Jhobean** [comment]
Same

**Comment by alexdan2** [comment]
Hello, i just try new release ... and ... 
"Server crash when save and someone have deleted a char 'Mounted'. if no mount seems not happen."

NO longer happen ... seems all OK !

Waiting @Jhobean feedback for closing issue.

**Comment by Jhobean** [comment]
Fine for Mee too!  Thx for fast Fix Nolok

**Comment by alexdan2** [comment]
yes thx too Nolok. 
All is OK!

**Comment by alexdan2** [comment]
Found a new bug.. is possible cause by this fix:

Script Example for reproduce:

`[ITEMDEF 0b95]
//library
DEFNAME=i_sign_library
RESOURCES=3 i_board,1 i_ingot_iron
CATEGORY=Decoration - Signs
SUBSECTION=Trade
DESCRIPTION=Library
DUPELIST=0b96

ON=@DClick
	REF1 = <SRC>
	SRC.SYSMESSAGE REF1 <REF1>
	args = #some data
	SRC.SYSMESSAGE REF1 <REF1>`


When set a ARGS in a funcion he destry all REF pointer

**Comment by alexdan2** [comment]
Found a new bug.. is possible caused by this fix:

Script Example for reproduce:


[ITEMDEF 0b95]
//library
DEFNAME=i_sign_library
RESOURCES=3 i_board,1 i_ingot_iron
CATEGORY=Decoration - Signs
SUBSECTION=Trade
DESCRIPTION=Library
DUPELIST=0b96

ON=@DClick
	REF1 = <SRC>
	SRC.SYSMESSAGE REF1 <REF1>
	args = #some data
	SRC.SYSMESSAGE REF1 <REF1>

When set a ARGS in a funcion, dialog ecc he destroy all REF pointer.
Last buid work is 3243, after this is broken

**Comment by xwerswoodx** [comment]
Confirmed, Setting an ARGS removes REF values.

**Comment by alexdan2** [comment]
@xwerswoodx  I think other also pointer is broken, if use bandage crash server... After 3243 not happen.

**Comment by xwerswoodx** [comment]
Yeah seems like most codes broken which uses ARGS, I tried my working dialog creator script and ARGS broke the script, I don't know why that happened but seems like ARGS has some issue.

**Comment by cbnolok** [comment]
Fixing it right now, btw guys for the future please use a single github issue for a single bug.

**Comment by GitMadKing** [comment]
maybe that is why also archery stop working, #402 for args being used  (if like in sphere combat)  to see if weapon is ranged



Marius

---- On mar, 07 apr 2020 19:30:23 +0200 notifications@github.com wrote ----



Yeah seems like most codes broken which uses ARGS, I tried my working dialog creator script and ARGS broke the script, I don't know why that happened but seems like ARGS has some issue.

**Comment by pentanorl** [comment]
@GitMadKing the archery issue was definitely antecedent to the ARGS one.
