### ISSUE TITLE
Archery not attack. swing stuck on 0

### ISSUE THREAD

**Issue by GitMadKing** [Sphereserver/Source-X#402]
archery does not attack.
swillstart
hitcheck loop argn1 0
no hittry, never

**Comment by pentanorl** [comment]
same problem here, I think that the problem is rooted into the new variable "CombatArcheryMovementDelay" in the *ini* that mess with the timer.
Try this:
- place a target near you and attack him -> archery won't work
- logout, login and DO NOT MOVE, just attack the target -> archery will work until you move

If you take even one single step after login, archery won't work, unless you enable the combatflag "COMBAT_ARCHERYCANMOVE" in the "*ini". Then skill works fine. A temporary workaround, as I did, is to enable the archerycanmove flag and at the same time add the "SKF_IMMOBILE" to the skill Archery. That makes the skill at least usable, with no "spring-effect" when an archer moves away from his target without need to TAB. Anyway the attack will not restart by itself, you'll need a macro to retarget and restart the attack when you stop moving.

**Comment by xwerswoodx** [comment]
I am currently tested archery with a i_bow and it working fine with sphere custom combat system. What is your option, combat flags and which combat system are you using? I just running around and attacking the target without any issue.

Using: Latest Sphere Nightly X1 and Custom Sphere Base Script pack which is updated version of @cbnolok version of pack.

**Comment by pentanorl** [comment]
Well, that's nice, my latest test about this was a a few days ago. Tested right now the latest build and the issue seems solved. Archery works again as supposed to.

**Comment by pentanorl** [comment]
Anyway I'm going to make a few more tests with ini settings hoping to get to the bottom of the matter.

**Comment by pentanorl** [comment]
Tried so far on three different machines with same build, scripts, ini settings (all synced by the same git repo)... two of them work fine, one does not. There is definitely something strange happening here.

**Comment by GitMadKing** [comment]
> same problem here, I think that the problem is rooted into the new variable "CombatArcheryMovementDelay" in the _ini_ that mess with the timer.
> Try this:
> 
> * place a target near you and attack him -> archery won't work
> * logout, login and DO NOT MOVE, just attack the target -> archery will work until you move
> 
> If you take even one single step after login, archery won't work, unless you enable the combatflag "COMBAT_ARCHERYCANMOVE" in the "*ini". Then skill works fine. A temporary workaround, as I did, is to enable the archerycanmove flag and at the same time add the "SKF_IMMOBILE" to the skill Archery. That makes the skill at least usable, with no "spring-effect" when an archer moves away from his target without need to TAB. Anyway the attack will not restart by itself, you'll need a macro to retarget and restart the attack when you stop moving.

I CONFIRM,
still build 5 april, 6 april
sphere combat sys (no scp)
default sphere.ini
first login without move, archery shoot
after moved, no more archery

**Comment by xwerswoodx** [comment]
Could you send your archer skill scripts, I can compare my one, and try to find why is this strange issue happening.

**Comment by GitMadKing** [comment]
I' not working on any shard.
just playing around with sphere.
however here you are my full server.
account to use: m
pass to use: k
the pack is:
Sphere-X, win 64, 6 april
clean classic sphere scripts
sphere.ini addedd agree, changed mul path, and enabled nocrypt client (wich i use)
created empty [eof] saves, create account m
that is all
to reproduce
i use i_bow, i_arrow 50, c_ogre
login (using m as user, k as password) char Mad King
remove .invul
create c_ogre (far enough), attack.
it will attack.
try move, wait again, il wont attack anymore.

[clsph.zip](https://github.com/Sphereserver/Source-X/files/4445031/clsph.zip)

**Comment by GitMadKing** [comment]
just enabled sphere_combat
added some checkpoints in vairous point of the scirpt
it looks like <IsSkillRanged <action>> is always 0
even if for archeryr should be 1

**Comment by GitMadKing** [comment]
```
[function IsSkillRanged]
if !(<def0.<args>>)
	return 0
endif
return <qval <args>==archery ? 1 : <qval <args>==throwing ? 1 : 0>>
```
edited to

```
[function IsSkillRanged]
serv.b isr <args>
if !(<def0.<args>>)
	return 2
endif
return <qval <args>==archery ? 3 : <qval <args>==throwing ? 4 : 5>>
```

it returnes 2
so
def0.archery returns always 0

**Comment by alexdan2** [comment]
@GitMadKing yes i confirm (Tested on my local file)

Step:
- Login 
- NO make any step
- Summon NPC and attack (ok Working)
- Move around (walk, running ecc)
- No more shot arrow.

This also happen in 3243 before pointer broken

**Comment by alexdan2** [comment]
I make a short clip for explain better achery bug. (Release 3262 still affected)

https://www.youtube.com/watch?v=eaVyo2mr3iw&feature=youtu.be

**Comment by xwerswoodx** [comment]
It's silly but when I copy my save and account files in your save/account files, everything works fine :) Seems like somethings broken after I created the account or my character.

**Comment by alexdan2** [comment]
i notice another strange flag, possible is connected to this issue:

Fresh Login and no move:
![image](https://user-images.githubusercontent.com/6176986/79006978-84974280-7b5a-11ea-861d-694401154259.png)

Make some step:
![image](https://user-images.githubusercontent.com/6176986/79007003-8e20aa80-7b5a-11ea-80a5-1541ac110166.png)

I not enabled this flag he automatic enabled when make a step in game and if i stop move not disable. i'm a normal c_man no garg features enabled.

**Comment by GitMadKing** [comment]
fly should reset after some seconds,
is used if running
if only walking no flying


if does not reset may be the problem



Marius

---- On ven, 10 apr 2020 18:40:05 +0200 notifications@github.com wrote ----



i notice another strange flag, possible is connected to this issue:

Fresh Login and no move:


Make some step:y


I not enabled this flag he automatic enabled when make a step in game and if i stop move not disable. i'm a normal c_man no garg features enabled.

**Comment by alexdan2** [comment]
Yes i confirm, i remove flag but archery still bugged.. Flag issue i think is other one

**Comment by GitMadKing** [comment]
i'm curious about @xwerswoodx saves and accounts if he done some more testing to understand what.

a test i've done is that "archery can move" ini flag is enabled, then archery is ok

**Comment by alexdan2** [comment]
Yes, whit "archery can move" flags work.
I think is some related CombatArcheryMovementDelay this delay is broken not reset when time end

**Comment by xwerswoodx** [comment]
I copied my own server (which is working) with all scripts, sphere.ini and sphere but it's not working, when I create new account in your file, it's not working, but if I put my own account and save files to your sphere file it's working, I don't understand the situation, it's really silly, but I can send you my own account file if you needed, so you can check flags etc, I am still working on it currently to understand the issue.

**Comment by GitMadKing** [comment]
try putting just account file
to understand if is the account or the save.

**Comment by xwerswoodx** [comment]
After so many stupid tests, I found out the issue, for fixing the issue, just close your server, open save/sphere_multis.scp and Set TIMEHIRES=3837381162

If you do that, your archery starts working. I don't know why that happened, but I am guessing it's caused after multi update, I will start to check multi update for solution. I don't really understand why multis block archery or how could it, I know it's totally silly but believe me same as you I can't understand at all. But changing TIMEHIRES fixing the issue.

**Comment by pentanorl** [comment]
confirmed on multiple machines... the TIMEHIRES workaround works like a charm XD

**Comment by cbnolok** [comment]
Is it working now?

**Comment by alexdan2** [comment]
I Just stested on build 3272 whit normal TIMEHIRES and work perfect if use OLD build 3268 have issue.

New Build is OK !

**Comment by GitMadKing** [comment]
build 3272 confirm working
