### ISSUE TITLE
WeightReduction 

### ISSUE THREAD

**Issue by Tolokio** [Sphereserver/Source-X#407]
I am having problems with weightreduction. It´s related to stackable ítems.

-First stack of an item u get into a bag Will get weightreduction but it Will do no effect.
-If u get the stack back, part of the weight Will remain in the bag, so puting it in and getting it back Will increase the weight of the bag.
-If u add a stack of an ítem that is already inside the bag it Will work and Will stack with the ítem that is already in the bag. But this Will not fix the first stack u put inside.
-Ítems with diffrent weightreduction can stack together.
-There is a random factor on this issue. Sometimes it Works like i Said, other times Works as it should work, and other it never work.

tested with:
[ITEMDEF i_xbag]
ID=i_bag
NAME=xbag
TYPE=t_container

on=@DropOn_Self
argo.weightreduction=50

on=@PickUp_Self
argo.weightreduction -=50

**Comment by xwerswoodx** [comment]
Seems like spliting item is triggering pickup_self trigger to all stack but when you split the stack, the items left in the container doesn't trigger dropon_self trigger. So game directly see them as picked up from container and remove the bonus.

**Comment by Swiftik023** [comment]
weightreduction is percentage

this working:
```
on=@DropOn_Self
	argo.weightreduction=50
on=@PickUp_Self
	argo.weightreduction=0
```

**Comment by xwerswoodx** [comment]
The problem is stacks not working well under @DropOn_Self and @PickUp_Self triggers, so here is a simple fix you can use;

```[ITEMDEF i_xbag]
ID=i_bag
NAME=xbag
TYPE=t_container
TEVENTS=e_itemt

On=@Create
Timer=1

On=@DropOn_Self
ARGO.WEIGHTREDUCTION += 50
IF !(<ARGO.isEvent.t_e>)
  ARGO.EVENTS +t_e
ENDIF

[TYPEDEF t_e]
On=@PickUp_Stack
IF !(<ARGO.isEvent.t_e>)
  ARGO.EVENTS +t_e
ENDIF
WEIGHTREDUCTION -= 50
EVENTS -t_e

On=@PickUp_Pack
IF (<dARGN1> == <dAMOUNT>)
  WEIGHTREDUCTION -= 50
  EVENTS -t_e
ENDIF

On=@DropOn_Self
ARGO.WEIGHTREDUCTION += 50
IF !(<ARGO.isEvent.t_e>)
  ARGO.EVENTS +t_e
ENDIF
```

**Comment by Tolokio** [comment]
[function f_Reags_Al_Libro]
ref1=<ARGV[1]> 
ref2=<ARGV[0]> 
ref3=<ARGV[2]> 
FORCONT <ref3>
	if <type> == t_reagent
		ref2.sysmessage @,,1 You add <amount> of <name> in reagent book.
		cont = <ref1> 
		WeightReduction = <ref1.tag0.reduce>
	endif
endfor

Well, I tried many ways. I use to do it by this function as well and it dosnt work. it is not about the trigger.
I have a fix by script for the issue, but the fix does not worth for normal containers.
 The problem is when u get the items into de bag, not when u take them off.
 If u have already a Stack inside, it Will work often, if the bag is empty it use to fail. I am not the only one having problems with this. 
Did you check it? Test it deeper cos it is broken.
Btw I am rastrero.
