### ISSUE TITLE
Lost target after hiding/invisibility and cannot attack him anymore

### ISSUE THREAD

**Issue by pentanorl** [Sphereserver/Source-X#409]
When a player under attack become hidden or invisible, the attacker lose the target and cannot attack him anymore until he targets someone else, only then he can attack his previous target again.
I checked the attacker list and the "non-selectable" player remains into the list.
Any idea what's causing this?

Here's a video I found on Discord about this same issue.
https://www.dropbox.com/s/4kgfr4xu6xpv2qk/Hid.mp4?dl=0

**Comment by xwerswoodx** [comment]
Seems like you are not using default client, have you tried it on default client?

**Comment by xwerswoodx** [comment]
I confirm this issue.

**Comment by alexdan2** [comment]
Me too, make some test and happen same. 
Tested on different build (new, and old one 10d ago) same.

**Comment by Massi17** [comment]
same issue with paralyze

 https://github.com/Sphereserver/Source-X/issues/342

**Comment by pentanorl** [comment]
any news about a possible cause?

**Comment by FiLoUs64** [comment]
We have this problem too. Can be very OP in PVP

**Comment by pentanorl** [comment]
OP and annoying, ‘cause if you are 1vs1 there is no way to overcome this bug, and when you lose the possibility to target your opponent, be sure that you are going to die badly. ^^

**Comment by fjgo86** [comment]
Sent a commit for this, this will affect NPCs too, so any feedback covering the hiding issue against both players and npcs would be appretiated.

**Comment by GitMadKing** [comment]
@fjgo86 build failing.

**Comment by xwerswoodx** [comment]
I tried it with latest build and issue still continue, when I tried to attack with X char to Y it starts and when Y goes invis X stop and when Y continue attack to X after reveal, X doesn't attack the char at all while it should call an attack when get hit, but the attack totally stops for X until peace/war.

**Comment by Jhobean** [comment]
I confirm fix do not work.

**Comment by alexdan2** [comment]
I make some test and i can also confirm still bugged

**Comment by xwerswoodx** [comment]
I fixed the issue and send a pull request but it can take time to accept, so I put here the fixed version, so you can try and tell me if there is still issue.

https://www.mediafire.com/file/1uls29llqyri55b/SphereSvrX64_nightly.rar/file

**Comment by alexdan2** [comment]
@xwerswoodx hello, i tested your file and work good :) thx

**Comment by Jhobean** [comment]
It's not work for me in the last build

**Comment by alexdan2** [comment]
@Jhobean 
i tested whit this: https://www.mediafire.com/file/1uls29llqyri55b/SphereSvrX64_nightly.rar/file

**Comment by Jhobean** [comment]
I tested the one on media fire.. Dont seem to work too..  Look What I do.
1- Player X attack Y
2- Player Y move away and hide
3- After unhide, player X do not attack anymore until they Dclick again

**Comment by alexdan2** [comment]
@Jhobean yes correct. this is not my bug.

OLD bug is: 
1- Player X attack Y
2- Player Y move away and hide
3- After unhide, player X do not attack anymore until they Dclick again **(Old bug is if dclick again no longer attack have to dclick other target and back)**

**Comment by Jhobean** [comment]
HAAA  Cool We had this bug too!  Some player was saying this issue but did not know it is fix in this commit.

**Comment by xwerswoodx** [comment]
If I remember correct, the default behavior is when the target hidden, the attack cancelled, and you need to dclick back to attack, This is why I just clear attacker to fix the issue cannot attack same target again. But maybe we can do something for continuous attack.

**Comment by Jhobean** [comment]
Yes it's cool. But don't waste time to find it, I pretty Sure julian's PR fix it

**Comment by alexdan2** [comment]
"This is why I just clear attacker to fix the issue cannot attack same target again" 
Exactly, this work very good

**Comment by Massi17** [comment]
it would be cool if we can have the possibility to choose with 2 flags in sphere.ini to remember the attack and  remember the swing.. so each of us can choose the dynamic to use.

**Comment by GitMadKing** [comment]
the correct behaviour should be
A attack B
B got hidden
B unhide
A should NOT autoattack B
A should NOT lose target
if A use attacklast it attacks B without having to target again

**Comment by Jhobean** [comment]
On 55i, A autoattack B.  For me, I want it like this. If you don't, yes will be cool to have a setting.

**Comment by xwerswoodx** [comment]
Honestly I already know how to make it continuous so it's not wasting time, we discuss it with Julian yesterday, and we thought to add some COMBATF flag to let owner choose between continue attack or not. So I can make a quick fix for after nolok's build passed and can send a enchanted version for test.

**Comment by xwerswoodx** [comment]
Anyway I will wait the Julian's PR accepted, because if I pull the request, pull request collude each others, so after julian's pr accepted we can make some flags for it.

**Comment by Rizzzolo** [comment]
> it would be cool if we can have the possibility to choose with 2 flags in sphere.ini to remember the attack and remember the swing.. so each of us can choose the dynamic to use.

The correct behavior has to be:
“A” attacks “B”
“B” hides
During the time “B” is hidden, “A” can’t hit “B” 
“A” never loses the target
When “B” is revealed or visible again, “A” can immediately attack again by using “attack last” 

I don’t really understand why we are proposing to change an intrinsic behavior which was never changed since Sphere51a (and probably TUS); especially when it really takes 2 lines of code to clear out attacker list.
But if you implement this new change and Sphere will clear the attacker by default, how am I supposed to keep the current behavior?
Please consider at least to have a .ini flag.

**Comment by Massi17** [comment]
remember than the problem occur even when we cast a spell.
a attack b
a cast on b
a can't attack b

**Comment by xwerswoodx** [comment]
As I said before, I only fixed the issue which causes the player cannot attack target after unhide (with or without dclicking) I haven't changed default behaviour at all. After Julian's PR accepted, the auto attacking to target will be fixed, I can fix but that can cause the collusion and also I can't get his credit, as he has already fixed it. So "I haven't changed default behaviour, I just fixed the targetting issue."

**Comment by xwerswoodx** [comment]
Here is the extended version of the fix;

https://www.mediafire.com/file/1uls29llqyri55b/SphereSvrX64_nightly.rar/file

In this build attack should continue after the character unhide. I won't gonna pull the request for this right now, because I used some changes from Julian's PR and fixed some more lines, so I wait to accepted his pr first. So I just giving that here for you to test, or if maybe you want to use fixed version.

**Comment by Jhobean** [comment]
I like your "extended version of the fix"! Don't seem to work on the last build. Please add it it's almost like 55i

Thx

**Comment by JulianUO** [comment]
I see that both fixes conflict with each other. The attacker clean after IsAttackable is fixing the War/Peace issue but you still have to doble click. I would say you send the PR hehe.

**Comment by Jhobean** [comment]
@xwerswoodx  I don't know how it work the original FIX but it don't seem to work when a NPC is INVUL.  When he came back normal, impossible attack him until change weapon or change target.  (We have some boss with INVUL mecanic)

**Comment by xwerswoodx** [comment]
I am currently working on, archery, dagger, invul, freeze issues, I already fixed some of them, but I am working for fix others before pulling the request.

**Comment by Jhobean** [comment]
a++ on my side! TYVM

**Comment by alexdan2** [comment]
I make some test, and work perfect! Thx a lot!

**Comment by meaowR** [comment]
Fixed, thnx

**Comment by pentanorl** [comment]
targeting after hiding looks restored, thank you guys.
