### ISSUE TITLE
@SkillGain doesn't work well

### ISSUE THREAD

**Issue by xwerswoodx** [Sphereserver/Source-X#411]
Under @SkillGain, when I set 

```
On=@SkillGain
IF (<SKILLLOCK[<dARGN1>]> == 1)
  RETURN 1
ENDIF
```

That should block to gaining/losing when skill in decrease mode on skill menu. Generally it's working but when you continue to attack, sometimes it decreases.

The issue only happening if another skill gaining same time. For example if I lock Tactics skill, it never decreases, but when I set Tactics skill up (increasing) mode some times (not always) it decreases Swordsmanship. But tactics does not always increase.

I am thinking the issue is while checking to tactics increase, if other melee skills in decrease mode, it decreases without checking @SkillGain trigger. But I am totally not sure about why this bug happening.

**Note:** I know that we have lock ability to lock skills, but this example is just for example for test, I tried to do something else.

**Edit:** Magery also drops skills which is decrease mode without checking @skillgain trigger, seems like decreasing skills doesn't check @SkillGain trigger at all.

**Comment by xwerswoodx** [comment]
I also know that we have lock ability to lock skills, but this example is just for example for test, I tried to do something else.

**Comment by Jhobean** [comment]
Fixed with the commit of the other issue?

**Comment by xwerswoodx** [comment]
Probably, but I can check later on if still an issue and take a look if needed. I wrote this here to not forget but I forget why I was trying that :D
