### ISSUE TITLE
Items not getting removed from server

### ISSUE THREAD

**Issue by JulianUO** [Sphereserver/Source-X#412]
We were making some tests in the discord channel. It happens with nuke, with remove and with mass dispel, so it must be linked to the internal delete item. When you play any of those actions, only half of the items targetted get removed.

I tested this: https://cdn.discordapp.com/attachments/476635430821953567/698909136477224980/4RjqS1qOl5.gif
Criminal posted this: https://puu.sh/FwxZ1/8b23b7e22f.mp4

**Comment by xwerswoodx** [comment]
```
FORITEMS 18
  REMOVE
ENDFOR

```
also not working, I think both of the same issue.

**Comment by GitMadKing** [comment]
i've done some tests
i't is very strange the behaviour
```
//this get all item around colored, and works
[function remar]
foritems <argn1>
	color=021
endfor
```

```
//this remove like 1 yes and 1 no, but does not color the other, if problem was the remove
[function remar]
foritems <argn1>
	color=021
	remove
endfor
```

**Comment by JulianUO** [comment]
This is the starting point of this bug:
https://github.com/Sphereserver/Source-X/commit/01a081bcfdc41a85b243d51aae6d396c4e0f8ffc

**Comment by GitMadKing** [comment]
confirm working

**Comment by alexdan2** [comment]
I make some test and .nuke work good on rectangle, also mass dispel get all field tile, foritem now count all item.

For me is OK!
