### ISSUE TITLE
[Spell] Summon Creature (not read char location)

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#413]
When cast a summon creature NPC not placed corrected under char feet but save every last spell location.

How reproduce:
- Cast a poison wall (s_poison_field)
- Cast summon creature (s_summon_creature)
- Summoned npc is placed on location targetted by field not under char feet
- If not previus cast make when login get a server error (on save) because summoned NPC not have any location:
- Other spell like s_summon_elem_air work correct
```
12:58:ERROR:GC: Deleted UID=01fee, Defname='c_rabbit', Name='rabbit'. Invalid code=0x3202 (Object not placed in the world).
```

Extra info:
- Tested on clear save and clear comunity script pack
- Tested on 3262 Build

**Comment by JulianUO** [comment]
Can you confirm this has been fixed on the latest commit?

**Comment by alexdan2** [comment]
Just tested on Build 3273, and work perfect. Thx !
