### ISSUE TITLE
Running flag (statf_fly) do not apperar when running

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#414]
For testing:
Add a function and make a macro to say .test when you run
```
[FUNCTIOn test]
say <qval (<flags>&STATF_FLY)? 1 : 0 >
```

When walking and running <flags> is suppose to be different.

Thx for help.

**Comment by Jhobean** [comment]
I want to use this flag for unhide character that are stealt..  domt understand the core program but there something about fly flag and stealstep

https://github.com/Sphereserver/Source-X/blob/0b31e986a5c68368bcb3edb5a6dcb6b785b454f7/src/game/chars/CCharAct.cpp#L3448

**Comment by Jhobean** [comment]
It's seem that the flag change intermittent...

For testing I made this function I lauch it before running and during running

```
[FUNCTIOn test]
say <FLAGS>
```

It seem that in X, the flag dont change each time

56 D
![image](https://user-images.githubusercontent.com/51728381/79604439-14d60a00-80bc-11ea-8051-664abf55aa36.png)

Sphere X:
![image](https://user-images.githubusercontent.com/51728381/79604495-2fa87e80-80bc-11ea-8d48-c80c80d853d4.png)

**Comment by alexdan2** [comment]
Yes i confirm this flag totally broken, Check Issue #404 also post a screen about flag change

**Comment by GitMadKing** [comment]
build 3272 working very nice, better than ever

**Comment by alexdan2** [comment]
Yes i confirm too 3272 is working well!

**Comment by Jhobean** [comment]
Perfect!!  THX!!!
