### ISSUE TITLE
Long function make server crash

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#418]
I know it's not the best way to script but we experiment a BUG when the server take the same function lot of time.  I'm about to script it differently but because  of this error,  our server always crash.  If you want to recreate it, here you go:

Work on 56d
Crash server on X with no debug

Just lauche the test function

```
[function test]
ctag.skilla1=0
ctag.skilla2=1600 //Try with 1500 it's work!
test2

[FUNCTION test2]
if (<eval <ctag.skilla2>> >=10)
	serv.log <ctag.skilla2>
  ctag.skilla2=<eval <ctag.skilla2>-10>
  ctag.skilla1=<eval <ctag.skilla1>+10>
  test2
endif
```

**Comment by GitMadKing** [comment]
made some tests

problem is not ctag

problem is recursive function.

```
//351 WORKS
//352 CRASH WITHOUT ERROR
[function test]
if <argn1> < 351
	test <eval <argn1>+1>
endif
```

**Comment by cbnolok** [comment]
56d probably crashes after a bigger amount of recursions, it's expected
behavior and a bad script design, you shouldn't make functions that recurse
this much, i'd stay away from them as much as possible

Il lun 20 apr 2020, 21:20 Mario Iacchetti <notifications@github.com> ha
scritto:

**Comment by GitMadKing** [comment]
@Jhobean 
here you are how to achieve the the same stuff, without recursive

```
[function test]
ctag.skilla1=0
ctag.skilla2=50000 //still no problem
test2

[FUNCTION test2]
WHILE (<eval <ctag0.skilla2>> >=10)   // continue to loop whilst an i_memory item is found inside the object
	ctag.skilla2=<eval <ctag.skilla2>-10>
	ctag.skilla1=<eval <ctag.skilla1>+10>
ENDWHILE
```

@cbnolok you're welcome

**Comment by Jhobean** [comment]
Ok thx for test. It was an old script we made in 55i. So I assume its not a bug. It's a poor scripting.
For information, when the server crash, its possible to print an error message before? Just to help other encounter this?

**Comment by cbnolok** [comment]
Is this still an issue?

**Comment by Jhobean** [comment]
![image](https://github.com/Sphereserver/Source-X/assets/51728381/ec2e76ec-01e6-4a3a-9fc2-245988a43969)
 Fixed THX!
