### ISSUE TITLE
Spawning ITEM with DISPID

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#419]
I have this custom item:

```
[ITEMDEF i_cocoon_mephitis_quest_escort]
DEFNAME=i_cocoon_mephitis_quest_escort
ID=010da
NAME=Cocon

ON=@CREATE
ATTR=ATTR_MOVE_NEVER

```

The ID 010da do reference to this:
010da is a dupe item of 010d8
```
[ITEMDEF 010d8]
DEFNAME=i_web_cocooon
WEIGHT=100.0
RESOURCES=100 i_spiderweb
CATEGORY=Decoration - Dungeons and The Dead
SUBSECTION=Spiderwebs
DESCRIPTION=Egg Case Web
DUPELIST=010d9,010da,010db,010dc,010dd

[ITEMDEF 010da]
//web_cocooon_3
DUPEITEM=010d8
```

When I do .add i_cocoon_mephitis_quest_escort , my Item take the apparence of 010d8 instead of 010da.

I know it's easy to Fix By adding  DISPID=010da on the @create  But it's a bug??  On 56d, no problem without adding info on the @create.

**Comment by xwerswoodx** [comment]
I confirm that, when you set id to item from the dupelist, it replaced to the value DUPEITEM shows.

**Comment by fjgo86** [comment]
It makes sense to me, the 'real' item is 010d8 and the others are 'shadowed copies' so when you set the ID to your items they get redirected to the 'real' one. Can't you change your code to 010da and make 010d8 part of the dupelist of it?

**Comment by GitMadKing** [comment]
putting under @create
dispid=010da

maybe?

**Comment by Jhobean** [comment]
i don't understand what you propose xwerswoodx. Its a cocoon, si i need 010da.  You propose make o10d8 original and 010da the original??:unamused:

**Comment by Jhobean** [comment]
Thx Fix is to Put the DISPID you need on the @create too.  LIKE THIS:
```
[ITEMDEF i_cocoon_mephitis_quest_escort]
DEFNAME=i_cocoon_mephitis_quest_escort
ID=010da
NAME=Cocon

ON=@CREATE
ATTR=ATTR_MOVE_NEVER
DISPID=010da
```
If dev can make a core FIX tag the issue else, close it.    Thx for Help
