### ISSUE TITLE
Console Resync

### ISSUE THREAD

**Issue by GitMadKing** [Sphereserver/Source-X#421]
Is still (if were any) a sense for console resync stop and waint until resync again. (right mouse action or R in console)

as in game "serv.resync" or "resync" in console

maybe can be changed to "resync" directly ans also, the bold message of server stopped for resync in game.

does has a real use?

**Comment by cbnolok** [comment]
You can use that to upload the scripts to your remote server or, who knows if will ever be implemented, update the mul files while the server is running, i wouldn't change it

**Comment by GitMadKing** [comment]
i, and all of us i think, that always have been used like:
copy files, r once, r twice  to get them working
i think no one ever use otherwise.
what actually happens on the backs when 
`Server is being PAUSED for Resync`
??
just ways for another R?

is there any other kind of actions going on during this time?

is there a "problem" maybe if overwrite files or even delete them if not in "PAUSE"?

scripts are loaded in memory, there is no need for them once the server is up. no?

**Comment by cbnolok** [comment]
Once the server is up, before accessing an in-memory script, if certain conditions are met sphere looks if there's an updated version of the script to load in memory. Using the resync/serv.resync doesn't cause any pause. Most of the time there isn't any issue when overwriting the scripts on a live server, tho the right thing to do would be to do that during a resync pause.

**Comment by xwerswoodx** [comment]
Honestly I am using R-stop to check latest messages or logs for quick look, so I think it's very important for console. Maybe a sphere.ini setting can add for enable/disable resync pause, but you can just add any macro for .SERV.RESYNC if you don't want to pause server, so I don't think it's really important to add if statement for this.

**Comment by Jhobean** [comment]
Stop the script and load new script on the go is the big advantage of Sphere. I think it should stay like this. If you don't want the server "stop" use the command resync.

**Comment by GitMadKing** [comment]
sometimes i wonder if is me not explaining myself well OR are the others not understanding the question.

so, i try again:

RESYNC IS IMPORTANT, DON'T REMOVE IT

just asking what is difference FROM " R in console" and "resync" in console (or .serv.resync in game)

HAS "R" a difference with the other?

SHOULD "resync" replace "R" so definitivelly eliminate the "server paused for resync" and game stoP?

**Comment by Jhobean** [comment]
.serv.resync is same than resync in console.  R is juste a resync in 2 step permetting you to stop the shard.  On old shard like 55i resync was not available. So resync fonction seem to be an evolution.

**Comment by cbnolok** [comment]
The resync pause is useful to have a server "pause" time to upload new scripts. In the past, it was used also to detach handles to mul files and to update them server-side without closing sphere, so maybe that may be coded again for X2.
