### ISSUE TITLE
Issues with logging in on old chars

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-X#422]
Receiving these errors when trying to login with my old GM Char. I'm able to login with regular new chars though. 
![unknown](https://user-images.githubusercontent.com/17236327/79830485-7d024580-8373-11ea-949e-74f2985662a8.png)
![unknown (1)](https://user-images.githubusercontent.com/17236327/79830486-7d9adc00-8373-11ea-8d76-ebd03e13e14b.png)

**Comment by pentanorl** [comment]
happened to me something similar a while ago, I had to login with another char, then go to the position of the "bugged char" and just move it in a different spot.

**Comment by cbnolok** [comment]
Can you paste the P of the char?

**Comment by soulless320** [comment]
`SERIAL=01
NAME=Soulless
COLOR=083ea
MODAR=130
TAG.damage_attacker=38
TAG.damage_reduction=19
TAG.faction=2
TAG.faction_kills=2
TAG.faction_loyalties=1
TAG.faction_loyalty=1
TAG.faction_silver=10
TAG.faction_title="King"
TAG.flags_autoloot=254
TAG.flags_player=168
TAG.hit_recovery=28
TAG.level=58
TAG.level_exp=33019
TAG.level_nextat=206100
TAG.level_statpoints=308
TAG.level_traitpoints=83
TAG.magic_damage_reduction=6
TAG.murder_lastat=86273127
TAG.override.skillsum=15500
TAG.profile_community_rating=1
TAG.racial_lastat=86384309
TAG.toolbar_off=1
TAG.toolbar_slot1="i_halberd"
EVENTS=e_bandaging
EVENTS=e_squad
EVENTS=e_factions
EVENTS=e_house_priv
EVENTS=Class_undeclared
ACCOUNT=soulless
DEATHS=48
SPEECHCOLOR=173
DSPEECH=spk_guildspeech
SkillLock[0]=1
SkillLock[2]=1
SkillLock[3]=1
SkillLock[4]=1
SkillLock[6]=1
SkillLock[7]=1
SkillLock[8]=1
SkillLock[9]=1
SkillLock[11]=1
SkillLock[12]=1
SkillLock[13]=1
SkillLock[14]=1
SkillLock[15]=1
SkillLock[18]=1
SkillLock[19]=1
SkillLock[20]=1
SkillLock[22]=1
SkillLock[23]=1
SkillLock[24]=1
SkillLock[28]=1
SkillLock[29]=1
SkillLock[30]=1
SkillLock[32]=1
SkillLock[33]=1
SkillLock[34]=1
SkillLock[35]=1
SkillLock[36]=1
SkillLock[37]=1
SkillLock[38]=1
SkillLock[39]=1
SkillLock[43]=1
SkillLock[44]=1
SkillLock[45]=1
SkillLock[48]=1
SkillLock[49]=1
SkillLock[50]=1
SkillLock[51]=1
SkillLock[52]=1
SkillLock[53]=1
SkillLock[54]=1
SkillLock[55]=1
SkillLock[56]=1
SkillLock[57]=1
P=1395,1512,10
TITLE=Grandmaster Healer
OSKIN=083ea
FLAGS=0a0012101
DAM=1,1
ARMOR=186
ACT=0f4a1
ACTP=514,1570
HOME=1313,1074,6
OKARMA=9700
OFAME=4001
OFOOD=5
FOOD=5
OSTR=100
OINT=100
ODEX=134
MAXHITS=220
HITS=220
MAXSTAM=16
STAM=16
MANA=100
Anatomy=1000
Parrying=1000
Healing=1000
Magery=15
MagicResistance=95
Tactics=1016
Swordsmanship=280
Macefighting=1006
Meditation=124
FASTERCASTING=50
NIGHTSIGHT=1
RESPOISON=34`

**Comment by xwerswoodx** [comment]
```
SERIAL=01
NAME=Soulless
COLOR=083ea
MODAR=130
TAG.damage_attacker=38
TAG.damage_reduction=19
TAG.faction=2
TAG.faction_kills=2
TAG.faction_loyalties=1
TAG.faction_loyalty=1
TAG.faction_silver=10
TAG.faction_title="King"
TAG.flags_autoloot=254
TAG.flags_player=168
TAG.hit_recovery=28
TAG.level=58
TAG.level_exp=33019
TAG.level_nextat=206100
TAG.level_statpoints=308
TAG.level_traitpoints=83
TAG.magic_damage_reduction=6
TAG.murder_lastat=86273127
TAG.override.skillsum=15500
TAG.profile_community_rating=1
TAG.racial_lastat=86384309
TAG.toolbar_off=1
TAG.toolbar_slot1="i_halberd"
EVENTS=e_bandaging
EVENTS=e_squad
EVENTS=e_factions
EVENTS=e_house_priv
EVENTS=Class_undeclared
ACCOUNT=soulless
DEATHS=48
SPEECHCOLOR=173
DSPEECH=spk_guildspeech
**P=1395,1512,10**
TITLE=Grandmaster Healer
OSKIN=083ea
**FLAGS=0a0012101**
DAM=1,1
ARMOR=186
ACT=0f4a1
ACTP=514,1570
HOME=1313,1074,6
OKARMA=9700
OFAME=4001
OFOOD=5
FOOD=5
OSTR=100
OINT=100
ODEX=134
MAXHITS=220
HITS=220
MAXSTAM=16
STAM=16
MANA=100
Anatomy=1000
Parrying=1000
Healing=1000
Magery=15
MagicResistance=95
Tactics=1016
Swordsmanship=280
Macefighting=1006
Meditation=124
FASTERCASTING=50
NIGHTSIGHT=1
RESPOISON=34
```

**Comment by soulless320** [comment]
Fixed, thank you!
