### ISSUE TITLE
TDATA3 and TDATA4 on t_container not working

### ISSUE THREAD

**Issue by pentanorl** [Sphereserver/Source-X#423]
According to changelog:
```
24-09-2017, Nolok
- Fixed: TDATA3 and TDATA4 for t_container were not working.
	TDATA3 stores the minimum X of an object placed inside a container as the first 16 bits, while the last 16 bits store the minimum Y.
	TDATA4 stores the maximum X and maximum Y in the same way. Example:
	TDATA3=((45 << 16) | 65)	// MinXY = ((X << 16) | Y)
	TDATA4=((100 << 16) | 100)	// MaxXY
```
I'm using the format suggested in that changelog but nothing happens.
The container I'm trying to fix is the "i_chest_gargish" from the communitypack ( ITEMDEF 04025), with "TDATA2=058e". The open gump has maxX/Y 400x322.

**Comment by cbnolok** [comment]
Can you paste here the script you are trying?

Il mar 21 apr 2020, 11:40 Stefano <notifications@github.com> ha scritto:

**Comment by pentanorl** [comment]
```
[ITEMDEF I_SAFEBOX]
DEFNAME=I_SAFEBOX
ID=04025 //i_chest_gargish
NAME=Safebox
TYPE=t_container
TDATA2 = 058e
TDATA3=((0 << 16) | 0)
TDATA4=((400 << 16) | 322)
```
The item itself is nothing more than a standard container, but the area for placing objects doesn't change no matter what I put as TDATA3/4. It remains limited to a very small rectangle on the left of the gump.

**Comment by GitMadKing** [comment]
do you create a new item after changing the properties?it is not set for old, already in world, itemsMarius ---- On mar, 21 apr 2020 13:55:27 +0200  notifications@github.com  wrote ----
[ITEMDEF I_SAFEBOX]
DEFNAME=I_SAFEBOX
ID=04025 //i_chest_gargish
NAME=Safebox
TYPE=t_container
TDATA2 = 058e
TDATA3=((0 << 16) | 0)
TDATA4=((400 << 16) | 322)

The item itself is nothing more than a standard container, but the area for placing objects doesn't change no matter what I put as TDATA3/4. It remains limited to a very small rectangle on the left of the gump.

**Comment by alexdan2** [comment]
I test the code of @pentanorl 

and get this result:
![image](https://user-images.githubusercontent.com/6176986/79871701-07cf5880-83e5-11ea-910f-178e587f6e47.png)

Drag and drop area is rectagle from coin, try also to increase TDATA4 400 and 322 value but not change nothing

**Comment by pentanorl** [comment]
> do you create a new item after changing the properties?it is not set for old, already in world, items

yes of course, I tried even to restart sphere and then create the new object.

**Comment by GitMadKing** [comment]
i'm trying also to change them.
here i take exact points
![image](https://user-images.githubusercontent.com/16067766/79875351-d311d000-83e9-11ea-8e61-462d11d50db6.png)

and here the result
![image](https://user-images.githubusercontent.com/16067766/79875436-f3da2580-83e9-11ea-841e-c3fbbfda4e54.png)

editing the  pouch script
```
[ITEMDEF 09b0]
DEFNAME=i_pouch
TYPE=t_container
//TDATA2=047
TDATA2=040
// TDATA3=010001
// TDATA4=0900090
TDATA3=((20 << 16) | 49)
TDATA4=((152 << 16) | 127)
DYE=1
FLIP=1
VALUE=13
WEIGHT=0.1
RESOURCES=1 i_hides_cut,1 i_thread
SKILLMAKE=Tailoring 10.0,t_sewing_kit
CATEGORY=Provisions - Miscellaneous
SUBSECTION=Containers
DESCRIPTION=Pouch
DUPELIST=0e79
```

**Comment by alexdan2** [comment]
I make some test whit last commit and sems not work:

- Upper left corner 30,121
- Down right corner 320, 220

**Code:** 
```
[ITEMDEF I_SAFEBOX2]
DEFNAME=I_SAFEBOX2
ID=04025 //i_chest_gargish
NAME=Safebox
TYPE=t_container
TDATA2 = 058e
TDATA3=((30 << 16) | 121)
TDATA4=((320 << 16) | 220)
```

Red dot point in script
Green dot drag item position
Result:
![image](https://user-images.githubusercontent.com/6176986/80797298-c89dc600-8ba1-11ea-8d5d-7e98d4c6c974.png)

**Comment by xwerswoodx** [comment]
I don't know why it doesn't work for you, but when I just copied your code and tried to put gold;

[IMAGE](http://resimag.com/p1/1de9f2695c1.png)

**Comment by xwerswoodx** [comment]
I can send you a debug version for that issue, so if you tell me the output of the debug I can check it for you.

**Comment by alexdan2** [comment]
Sure sure send 
--
Inviato da Libero Mail per Android Venerdì, 01 Maggio 2020, 00:58PM +02:00 da xwerswoodx  notifications@github.com :

**Comment by xwerswoodx** [comment]
It's now working, but the problem is Client itself set the default values of the gumps inside it's code, so sphere can't override it because you use the client to put item, so sphere get the information after client fixed the corners itself. The tdata3 and tdata4 work fine for make squares smaller but it's impossible to override Client default corners. So I suppose you to use some enchantment program like orion to use that containers.

I checked the packets but haven't seen any packet that let us to override default client settings so there is no way to change it on default clients.

**Comment by alexdan2** [comment]
I confirm @xwerswoodx words!
