### ISSUE TITLE
Moving item in backpack reveal Character

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#426]
BUG: When we are hide, if we move item in OUR backpack, we are revealed.

HOW to test:
- Hide yourself
- Move item

**Comment by xwerswoodx** [comment]
It causes REVEALF_LOOTINGOTHERS, I don't know why it sees you as looting but if you remove 04 flags from the revealf until it fixed.

It will be fixed with next nolok's commit.

**Comment by Jhobean** [comment]
Work a1  THX  c97a6bf0f912acd9ad78eabff2e974ecfbad9fa6
