### ISSUE TITLE
Possible cheating on packet BF.2C

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#427]
Hello when sending packet BF.2C (Use item on target).
Fires only @target trigger not @Dclick or some other way to detect use.
Is normale ?

This is packet info:
![image](https://user-images.githubusercontent.com/6176986/80101394-a12b7580-8571-11ea-8e62-759ef434c214.png)

**Comment by JulianUO** [comment]
That packet is supposed to be for Use Bandage macro.
It is triggered with another internal macro?

**Comment by alexdan2** [comment]
Yes bandage:
For example if have custom bandage system and someone send this packet avoid al check on @dclick.
Also i think avoid al check on vet also.

**Comment by pentanorl** [comment]
confirmed what @alexdan2 says, the @Dclick doesn’t trigger at all... a temporary fix would be to place the delay check under TargOn_Char.

**Comment by xwerswoodx** [comment]
If I understand you correctly, this packed doesn't trigger @DClick trigger, but it triggers @TargOn_Char trigger? Am I correct? If true, maybe we can add some trigger between @DClick and @TargOn_* triggers some trigger like @Use, @AfterDclick or @Target_Start to make you to use this trigger instead of @DClick, but if it directly trigger the @TargOn_Char trigger, you can do checks under @Targon_Char too.

**Comment by alexdan2** [comment]
Yes i set check on @Targon_Char and work good. tomorrow i test, @use, @AfterDclick for see if fire, if fire i put check here for prevent ppl pull out target and after target execute tell delay message

**Comment by alexdan2** [comment]
I make some test on Packet BF.2C 

Trigger Fire:
- @target*

Trigger not fire:
- @use 
- @AfterDclick 
- @Target_Start

I think is not correct put all check for delay ecc on a targer action. Have different opinion ?

**Comment by xwerswoodx** [comment]
Seems like Xun fixed it, could you test and close the issue if it's fixed please?

**Comment by alexdan2** [comment]
Hello, 
I make a test whit simple check

```
[ITEMDEF 0e21]
DEFNAME=i_bandage
NAME=Clean Bandage%s
TYPE=t_bandage
VALUE=1
ON=@Dclick
	SRC.SYSMESSAGE Call: @Dclick
```

And work perfect whit BF.2C packet.

Thx a lot !
