### ISSUE TITLE
Timers vs Worldsaves

### ISSUE THREAD

**Issue by Maxoule22** [Sphereserver/Source-X#428]
During a Worldsave
-Timerf's timers will freeze and wait for the save to end
-Item timers that uses the on=@timer trigger will keep rolling during the save. 
On=@timer's timers should freeze during a worldsave just like Timerf

**Comment by Jhobean** [comment]
https://github.com/Sphereserver/Source-X/commit/0d42711b61b3c920217160b4167edd10c35fedd0 Should fix this.
