### ISSUE TITLE
Items @DClick works even with bankbox closed

### ISSUE THREAD

**Issue by pentanorl** [Sphereserver/Source-X#429]
If you link an assistant like razor to an item's serial inside your bankbox, that item can be used (DClick) even if the bankbox is closed and your position is different from the MOREP of the bankbox layer. The item cannot be moved nor you can add items to the container, but they can be dclicked.

Fast way to replicate:
- Use ClassicUO client
- Open your bankbox
- Open a bag inside the bankbox with some bandages or potions inside
- Move away. The bankbox will close but the bag will remain open.
- Interact with objects inside the bag, like drinking a potion or bandageself anywhere in the world. ^^

**Comment by pentanorl** [comment]
Don't know if could be of any help... but CANSEE always returns 1 with objects inside bankbox.

**Comment by pentanorl** [comment]
I have temporarly fixed the issue this way:
````
//put this inside your main event for players
ON=@ItemDClick 
	IF ( <ACT.CONT.UID> != 0)
		IF (!( <I.P.X> == <I.FINDLAYER(29).MOREX> ) || !( <I.P.Y> == <I.FINDLAYER(29).MOREY> ) || !( <I.P.Z> == <I.FINDLAYER(29).MOREZ> ))
			IF ( <I.FINDLAYER.29.f_find_inside_bankbox <ACT.UID>> )
				I.SYSMESSAGE You can't reach that.
				RETURN 1
			ENDIF
		ENDIF
	ENDIF
````

```
[FUNCTION f_find_inside_bankbox]
REF1=<ARGN1>
FORCONTID <REF1.BASEID> 10
	IF ( <UID> == <REF1.UID> )
		RETURN 1
	ENDIF
ENDFOR
RETURN 0
```

I know it's a bit rough, but it just need to work until the issue will be fixed server-side. ^^'

**Comment by xwerswoodx** [comment]
Are you sure you tried with player character? Because I tried it player character and I can't dclick items on bankbox.

**Comment by pentanorl** [comment]
mmm, that way you are going to check only items directly inside the layer bankbox... not items inside nested containers

**Comment by GitMadKing** [comment]
@pentanorl  here you are again more enhanced for @xwerswoodx and less complex than yours.

```
On=@ItemDClick
ref1=<act.topcont>
IF (<ref1.TYPE> == t_eq_bank_box) && !(STRMATCH('<P>', '<ref1.MOREP>'))
	SYSMESSAGE You can't reach that.
ENDIF

[FUNCTION topcont]
if (<cont.isitem>)
	return <cont.topcont>
else
	return <uid>
endif
```

**Comment by xwerswoodx** [comment]
Oh okay, I got you now;

Here is a solution without causing any crash;

```
REF1=<ACT.TOPCONT>
IF (<REF1.TYPE> == t_eq_bank_box) && !(STRMATCH('<P>', '<REF1.MOREP>'))
	SYSMESSAGE You can't reach that.
ENDIF

[FUNCTION topCont]
REF1 = <UID>
WHILE (<REF1.CONT.isCont>) && !(<REF1.CONT.isChar>)
  REF1=<REF1.CONT>
ENDIF
RETURN <REF1>
```

Just improved @GitMadKing's solution with WHILE loop.

**Comment by alexdan2** [comment]
I just tested it and i tell a little example:

- I put 300 potion in a bag inside bank
- I save serial of this item in any assistant script tools
- Go to farming mob
- Play script from assistant do a Useitem on serial of potion in bankbox
- Tadannn.. i can use from bankbox totally safe and no need have it in backpack. 

This can do for all item have Use function (potion, bandage, scrolls, ecc ecc)

**Comment by Jhobean** [comment]
Same here. It's a script fix or a core fix?

**Comment by pentanorl** [comment]
> @pentanorl here you are again more enhanced for @xwerswoodx and less complex than yours.
> 
> ```
> On=@ItemDClick
> ref1=<act.topcont>
> IF (<ref1.TYPE> == t_eq_bank_box) && !(STRMATCH('<P>', '<ref1.MOREP>'))
> 	SYSMESSAGE You can't reach that.
> ENDIF
> 
> [FUNCTION topcont]
> if (<cont.isitem>)
> 	return <cont.topcont>
> else
> 	return <uid>
> endif
> ```
> 
> hope no one dclick an item nested in 351 containers #418 -.-'

sadly there are people who find entertaining do everything imaginable to cause problems... and I don’t know if you noticed, but you can nest even containers of the same type. I haven’t checked how many levels, but I got tired trying after a few dozen of bags inside bags, so I had to put a check to prevent nesting containers with same baseid.

Anyway thanks for the Topcont tip, I haven’t scripted anything in the last 5 years and I forgot a lot of stuff. Still recovering memories and removing rust. ^^’

**Comment by GitMadKing** [comment]
just use @xwerswoodx with while and no problem

**Comment by alexdan2** [comment]
Anyway i think can use item from bankbox (away from bank) is a core issue.

**Comment by pentanorl** [comment]
far from my intentions to look pedant, but as anticipated, the fix with STRMATCH won't work. Tried right now and it prevents you to use anything in your bank even if it's properly open. And in the itemdclick trigger there's a RETURN 1 missing.

So, here there's a mix of what came out from this topic, I've tested it right now and works as supposed to:
```
ON=@ItemDClick
	REF1=<ACT.f_topcont>
	IF (<REF1.TYPE> == t_eq_bank_box) && (!( <I.P.X> == <REF1.MOREX> ) || !( <I.P.Y> == <REF1.MOREY> ) || !( <I.P.Z> == <REF1.MOREZ> ))
	  SYSMESSAGE You can't reach that.
	  RETURN 1
	ENDIF

[FUNCTION f_topcont]
REF1=<UID>
WHILE (<REF1.CONT.ISCONT>) && !(<REF1.CONT.ISCHAR>)
  REF1=<REF1.CONT>
ENDIF
RETURN <REF1>
```

**Comment by xwerswoodx** [comment]
Yeah we forgot to set RETURN 1 value :)) Also STRMATCH not working because we need to use double quotes for the words including commas.
```
ON=@ItemDClick
	REF1=<ACT.f_topcont>
	IF (<REF1.TYPE> == t_eq_bank_box) && !(STRMATCH("<P>", "<REF1.MOREP>"))
	  SYSMESSAGE You can't reach that.
	  RETURN 1
	ENDIF

[FUNCTION f_topcont]
REF1=<UID>
WHILE (<REF1.CONT.ISCONT>) && !(<REF1.CONT.ISCHAR>)
  REF1=<REF1.CONT>
ENDIF
RETURN <REF1>
```

should work fine, anyway you can check one by one but I don't suppose to use 3 more check.

**Comment by pentanorl** [comment]
I'll try with the double quotes ;)

**Comment by xwerswoodx** [comment]
```
[FUNCTION bt]
if (STRMATCH("<FINDLAYER.LAYER_BANKBOX.MOREP>", "<P>"))
  RETURN 1
ENDIF
RETURN 0
```

I tried it with that function and works fine for me.

**Comment by pentanorl** [comment]
yep, I confirm, with double quotes, works as supposed to.

**Comment by JulianUO** [comment]
Hi,
Try enabling EF_FixCanSeeInClosedConts.

**Comment by alexdan2** [comment]
@JulianUO make test whit EF_FixCanSeeInClosedConts flags, but nothing change if send a useitem keep use if item is in bank and i'm away and bank close.

**Comment by Jhobean** [comment]
Work a+ for me

**Comment by alexdan2** [comment]
I confirm too, Fix work very good :) thx

**Comment by alexdan2** [comment]
**I add some details but half fixed:**
- Targer is Bandage.
- If bandage outside container in main bank box problem fixed:
This situation OK:
![image](https://user-images.githubusercontent.com/6176986/80421922-86dcf900-88dd-11ea-89d8-ceddba058278.png)

- If move bandage inside a subcontainer:
![image](https://user-images.githubusercontent.com/6176986/80422007-b1c74d00-88dd-11ea-92f3-b6623457db11.png)
- Still bugged, CAN use item away from bank whit bank closed.

**Comment by pentanorl** [comment]
items contained by containers inside the bank are still dclickable.

**Comment by Massi17** [comment]
https://www.dropbox.com/h?preview=UO+-+Bruteforce+--++0+0+0+0+0+0+0+0+497+2020-04-27+23-20-26_Trim.mp4

**Comment by Massi17** [comment]
https://www.dropbox.com/s/r7vx6mn33wijwip/UO%20-%20Bruteforce%20--%20%200%200%200%200%200%200%200%200%20497%202020-04-27%2023-20-26_Trim.mp4?dl=0

**Comment by xwerswoodx** [comment]
https://www.mediafire.com/file/null/SphereSvrX64_nightly.rar/file

Could you test it with that version? I did some changes but I need to make sure before pull request.

**Comment by alexdan2** [comment]
I try to download but:

> Something appears to be missing…
The key you provided for file access was invalid. This is usually caused because the file is no longer stored on MediaFire. This occurs when the file is removed by the originating user or MediaFire. Still have questions, or think we've made a mistake? Please contact support for further assistance.

>

**Comment by xwerswoodx** [comment]
Yeah sorry the copy link works bad on website, here is the correct link;

https://www.mediafire.com/file/1uls29llqyri55b/SphereSvrX64_nightly.rar/file

**Comment by alexdan2** [comment]
Hey! I tested to send packet useitem for subcontaier item also, and is fixed! Good Work

**Comment by xwerswoodx** [comment]
Thank you for information, I will pull the request after I finished to work on other issues.
