### ISSUE TITLE
Sector sleep scrap @timer trigger

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#430]
This bug is very a pain on the shard and is causing MANY trouble... I was able to reproduce it on Vanilla setup (Last core + nolok script pack)

Here the method

1- Set sectorsleep to 1 on the ini

2- ADD this item on script and equip it
```
[ITEMDEF i_anneau_mage]
ID=0108a
TYPE=t_jewelry
name=Anneau de Wizardry

ON=@EQUIP
timer=5
return 1

on=@timer
serv.log 5 sec
timer=5
return 1
```

3- Equip the item and see the message "5 sec" on the console 
4- Log out
5- Continu see the message each 5 sec in the console until sector sleep sleep the item
6- After 1 minute, no more message and I think it,s normal
7- Log in to account and check the timer of your ring  .xshow timer  (it's 0)
8- Set the timer to 5 manualy  .xtimer 5
9- When the 0 occur, the timer stay at 0 trigger never happen. (try step 8 100X it,s always the same)

I think it's not normal.......

 Iknow If i unequip and equip the ring it work...  But when you have a memory with timer, you CAN'T unequip/equip

**Comment by Jhobean** [comment]
Second question, at the step 5, it's normal the timer continue if I am loged out?

**Comment by Jhobean** [comment]
It was the same bug with Worldgem before the last commit.

**Comment by GitMadKing** [comment]
> Second question, at the step 5, it's normal the timer continue if I am loged out?

of.course.
linger time.
the pg is still in world.

**Comment by cbnolok** [comment]
Good report, the code and the steps make much easier to track the bug and work locally

**Comment by Jhobean** [comment]
IMPECCABLE!!  Thx
