### ISSUE TITLE
REGEX problems?

### ISSUE THREAD

**Issue by GitMadKing** [Sphereserver/Source-X#433]
this works correctly
http://regexr.com/53bg0

(it works correctly)
```
[function fff]
serv.log @<ARGV[0]> : <eval STRREGEX(^([a-zA-Z]+[ ']?)*[a-zA-Z]$), <ARGS>)>
```
```
15:40:ERROR:(test_scripts.scp,4)Undefined symbol '' ['<a']
15:40:ERROR:(test_scripts.scp,4)Deadlock detected while parsing 'a'. Fix the error in your scripts.
15:40:ERROR:(test_scripts.scp,4)Undefined symbol '' ['zA-Z]$), aaa)']
15:40:ERROR:(test_scripts.scp,4)Undefined symbol '' ['Z]$), aaa)']
15:40:aaa : 0
```
i'm I wrong?
or is an issue?

**Comment by xwerswoodx** [comment]
Try to use arguments inside double quotes, like;

`<eval STRREGEX("^([a-zA-Z]+[ ']?)*[a-zA-Z]$)", "<ARGS>")>`

**Comment by GitMadKing** [comment]
> Try to use arguments inside double quotes, like;
> 
> `<eval STRREGEX("^([a-zA-Z]+[ ']?)*[a-zA-Z]$)", "<ARGS>")>`

nop
returns always 0
got the example from here
https://wiki.spherecommunity.net/index.php?title=Chapter_10#STRREGEX

**Comment by xwerswoodx** [comment]
What you want to match?

**Comment by GitMadKing** [comment]
a correct name
begins with letter
end with letter
contains maxim 1 of SPACE or ' trough words

like:
aaa ok
aaa' not ok
aaa aaa ok
a'a ok
aa  aa not ok (double space)
aa' aa not ok (' and space )

etcc
http://regexr.com/53bg0
here you can try any combinations 
![image](https://user-images.githubusercontent.com/16067766/80309981-8eff4080-87d8-11ea-9faa-61388280b2a0.png)

**Comment by xwerswoodx** [comment]
If I get you all correct, this is the regular expression you need;
`<eval STRREGEX("[a-zA-Z]+([[:space:]]?[a-zA-Z]+|)*", "<ARGS>")>`

**Comment by GitMadKing** [comment]
yep, works
thank 
but wht is difference with mine? :|

**Comment by xwerswoodx** [comment]
The issue is ^ and $ not working for STRREGEX. I think they did it in that way. But if you don't put .* at the beginning or the end, it same meaning with ^ $.

**Comment by GitMadKing** [comment]
is very strange, i cannot fully understand how actually works, but it works this one.. 

thank again
