### ISSUE TITLE
SpellBook MORE1 & MORE2, Data lost not correct save and update

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#437]
Hello get issue on spellbook value MORE not correct update when drag and drop scroll on it.

**How replicate:**
- Make empty spellbook i_spellbook
- Make a i_scroll_summon_elem_water scroll
- Now i show info about book (for now all OK, because is empty book:

![image](https://user-images.githubusercontent.com/6176986/80364907-ff649b00-8886-11ea-9409-206ee3405487.png)

- Now i drag my scroll on book and check inside book and see spells added also tooltip update spell count.
- I inspect item:

![image](https://user-images.githubusercontent.com/6176986/80365016-35a21a80-8887-11ea-9f16-bf3de30f3a70.png)
- But i see more value not update.
- Make a save 
- Restart server
- Spells not longer exist in book

I hope understand problem.

**Additional Info:**
- Tested on clear comunity script pack
- Tested on Build (3285) 
- Sems low level 1 to 3 circle and 4 to 7 work, is possible some kind of overflow in MORE data. when reach big value of last circle spell block

**Save Block after add i_scroll_summon_elem_water on book:**

```
[WORLDITEM i_spellbook]
SERIAL=040001fc7
ATTR=024
MORE2=00
CONT=040001ffe
P=48,91
CONTGRID=5
```

**Comment by Jhobean** [comment]
Same here.

**Comment by alexdan2** [comment]
Additional test:
- I make some test about MORE value
- If manual set by .set MORE correct store in info and save
- If added by scroll (drag and drop) fail.

I think problem in located when drop scroll on bool.

**Comment by xwerswoodx** [comment]
I confirm that issue only happening on 32th and 64th spells.

**Comment by pentanorl** [comment]
any possible workaround in the meantime? :(

**Comment by alexdan2** [comment]
I make a quick test:
- Put scroll 
- Check more value (Now see correct)
- Make a save
- Restart server
- Check spellbook (Spell is present)

Good Work man!

Tomorrow i make more accurate test, if all work good i close issue, also if someone else want test it for a major feedback is good ;)

**Comment by alexdan2** [comment]
I make some accurate test and work good
