### ISSUE TITLE
worldsave bad directory

### ISSUE THREAD

**Issue by Skul83** [Sphereserver/Source-X#438]
I get the below error when loading spheresvr.exe in d:\sphere\

`Loading c:\SPHERE\worldsave\spheredata.scp...
WARNING:'c:\SPHERE\worldsave\spheredata.scp' not found...
WARNING:Can't Load c:\SPHERE\worldsave\spheredata.scp
Loading c:\SPHERE\worldsave\spherestatics.scp...
WARNING:'c:\SPHERE\worldsave\spherestatics.scp' not found...
WARNING:Can't Load c:\SPHERE\worldsave\spherestatics.scp
Loading c:\SPHERE\worldsave\sphereworld.scp...
WARNING:'c:\SPHERE\worldsave\sphereworld.scp' not found...
ERROR:Can't Load c:\SPHERE\worldsave\sphereworld.scp
FATAL:No previous backup available ?
FATAL:Server terminated: Failed to load worldsave files (code -8)
You can now close this window`

**Comment by GitMadKing** [comment]
c'mon..
is this a core problem?
please understand the basics of sphere, and if really a problem report nedded info
in this case sphere.ini folders sections
where the files are, muls, saves, what file are present in the folder you see in the error...

**Comment by cbnolok** [comment]
Guess you wrote the wrong folder or drive letter in the ini

Il lun 27 apr 2020, 14:09 Mad King <notifications@github.com> ha scritto:

**Comment by Skul83** [comment]
sphere.ini values:

`ScpFiles=scripts/
WorldSave=save/
AcctFiles=save/
MulFiles=mul/
Log=logs/`

SphereServer-X looks for c:\sphere\worldsave with these values in sphere.ini

**Comment by GitMadKing** [comment]
sphere.ini should be in same folder of exeis that one yo paste here?Marius ---- On lun, 27 apr 2020 15:01:38 +0200  notifications@github.com  wrote ----
sphere.ini values:
ScpFiles=scripts/ WorldSave=save/ AcctFiles=save/ MulFiles=mul/ Log=logs/
SphereServer-X looks for c:\sphere\worldsave with these values in sphere.ini

**Comment by Skul83** [comment]
Yes, sphere.ini is in the same folder as spheresvr.exe, I get this error when trying to load spheresvr.exe, error code -8.  Looks like sphere is looking for c:\sphere\worldsave\ as spheresvr.exe is in d:\sphere\ and WorldSave=save\ in sphere.ini

Scripts load fine, Account is located properly, Mul files load fine and Logs are working fine.  It is only the WorldSave value that is not acting properly.

**Comment by GitMadKing** [comment]
try changing scripts folder in that sphere.ini and see if you got error.if yes, look again for WorldSave in sphere inimaybe is defined more than onceMarius ---- On lun, 27 apr 2020 15:13:19 +0200  notifications@github.com  wrote ----
Yes, sphere.ini is in the same folder as spheresvr.exe, I get this error when trying to load spheresvr.exe, error code -8.  Looks like sphere is looking for c:\sphere\worldsave\ as spheresvr.exe is in d:\sphere\ and WorldSave=save\ in sphere.ini
Scripts load fine, Account is located properly, Mul files load fine and Logs are working fine.  It is only the WorldSave value that is not acting properly.

**Comment by GitMadKing** [comment]
also, what build are you using?

**Comment by GitMadKing** [comment]
another stuff,
try accessing save folder and open a file
try execute sphere as administrator
try resetting permission on files

**Comment by Skul83** [comment]
I'm using the latest win32 build from sphereserver.net
Changing the ScpFiles to /scripts2/ gives me an error:

WARNING:'scripts2/spheretables.scp' not found...
FATAL:Error opening table definitions file (spheretables..scp)...
FATAL:Server terminated: Failed to load server settings (code -3)

There is only one WorldSave in sphere.ini it is WorldSave=save/

Running SphereSvr.exe as administrator still gives this error:

Loading c:\SPHERE\worldsave\spheredata.scp...
WARNING:'c:\SPHERE\worldsave\spheredata.scp' not found...
WARNING:Can't Load c:\SPHERE\worldsave\spheredata.scp
Loading c:\SPHERE\worldsave\spherestatics.scp...
WARNING:'c:\SPHERE\worldsave\spherestatics.scp' not found...
WARNING:Can't Load c:\SPHERE\worldsave\spherestatics.scp
Loading c:\SPHERE\worldsave\sphereworld.scp...
WARNING:'c:\SPHERE\worldsave\sphereworld.scp' not found...
ERROR:Can't Load c:\SPHERE\worldsave\sphereworld.scp
FATAL:No previous backup available ?
FATAL:Server terminated: Failed to load worldsave files (code -8)
You can now close this window.

Permissions for the folder are normal, still gives WorldSave error.

**Comment by GitMadKing** [comment]
do you have discord?
could you enter there and write me to Mad King#9572

**Comment by GitMadKing** [comment]
LOL.
redefined world save in spherebook

[sphere]
worldsave=c:\SPHERE\worldsave\
