### ISSUE TITLE
Impoosible attack someone after he had invul flag

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#439]
Seem to be like https://github.com/Sphereserver/Source-X/issues/409

The last fix did not fix it.

How reproduce:
1- Take 2 character
2- Both hit each other
3- One become invul
4- After remove the invul flag, it's impossible to attack him

It's ok with the stone flag.

There was a partil fix in this COMMIT: https://github.com/Sphereserver/Source-X/pull/435

**Comment by xwerswoodx** [comment]
Hm, I remember I checked invul flag but if I am not I can send a quick fix for that with my next pull request.

**Comment by xwerswoodx** [comment]
Hmm I checked the code and I remember correct that I checked invul flag, but now I find out another issue that is little confusing, because when you are invul and not hit anyone after that others can attack you when you invul off. But if you attack someone, he can't attack you anymore as he war/tab or dclicking. This seems like when invul person attack to another person, server directly save that person as invul for other player and it doesn't reset until server restart.

**Comment by xwerswoodx** [comment]
Hmm seems like this is not an issue at all, the reason is when someone tried to attack to someone invul, sphere add him to ignore list to avoid unnecessary continuous attack search, so it takes time to remove ignore status.

**Comment by Jhobean** [comment]
Ok so in pvm I cannot use invul flag???  It was working on 56d. Dit not try in 55i

**Comment by xwerswoodx** [comment]
Hmm, maybe I can do that ignore thing as pvp only. Or you can RETURN 1 under @GetHit event instead of giving INVUL.

**Comment by Jhobean** [comment]
There a way to force "actualise" ignore list?

**Comment by xwerswoodx** [comment]
Yeah there is;
```
27-01-2015, XuN
- Updated @CombatDelete trigger with a new argn1 value, now it's telling Sphere to remove or keep 1/0 the attacker's memories when removing him from the list.
**- Added @HitIgnore trigger firing when one character is going to avoid an ignored target in the target selection: argn1=1 keep him ignored, argn2= un-ignore target (so character can attack him again).**
- Added @Eat trigger, read wiki for more info: http://wiki.sphere.torfo.org/index.php/@Eat
```

**Comment by Jhobean** [comment]
Wooo. Ok. So I put  @CombatDelete on each player event.  On this trigger i put
 if (src.defname==mymonster)
Return 1
Endif

**Comment by xwerswoodx** [comment]
I guess
```
On=@HitIgnore
IF !(<FLAGS>&STATF_INVUL)
  ARGN2=1
ENDIF
```
can be enought under npc, but I haven't used that trigger before.

**Comment by Jhobean** [comment]
I try this evvent on both player and NPC and do not work:
```
[EVENTS e_test]
On=@HitIgnore
IF !(<FLAGS>&STATF_INVUL)
  ARGN2=1
ENDIF
```
ARGn2 suppos to be what?

> it's not clear on the change log
> - Added @HitIgnore trigger firing when one character is going to avoid an ignored target in the target selection: argn1=1 keep him ignored, argn2= un-ignore target (so character can attack him again).

**Comment by xwerswoodx** [comment]
Honestly I haven't used that trigger before, so if you ask it to Xun from discord you can get better information because he added that ignore trigger.

**Comment by alexdan2** [comment]
> Ok so in pvm I cannot use invul flag??? It was working on 56d. Dit not try in 55i
> Note:
> We have game mecanic in pvm where the boss become invul until all his servant is death

I use in some boss this (invul) method but i work on @gethit more clear i think:

Event of boss:
```
[EVENTS e_cora_the_sorceress]
ON=@GETHIT
	REF1 = <TAG0.UIDSUMMON>--> Uid of summoned creature
	IF (<REF1>) // Summon è attiva
		SAY You will not escape my power!
		RETURN 1
	ENDIF
```
When npc spawn her minion simple set minion UID on tag and boss become invul if this uid still alive.

When minion death simple clear the tag

**Comment by Jhobean** [comment]
How you delete the tag? Forloop when mignon die?

**Comment by xwerswoodx** [comment]
Honestly you don't need change your code because I already fixed that, just working on other issuees before pulling request.

**Comment by Jhobean** [comment]
Haa. Ok. Thx !!

**Comment by alexdan2** [comment]
> How you delete the tag? Forloop when mignon die?

Nop simple all minion have her event trigger on death:
```
[EVENTS e_cora_the_sorceress_summon_die]
ON=@DEATH
	REF1 = <TAG0.UIDBOSS>
	IF (<REF1>)
		REF1.TAG0.UIDSUMMON = // svuoto tag della summon su boss per consentire attacco
	ENDIF
```

**Comment by xwerswoodx** [comment]
Right now, you can use @Attack trigger to override ignore status with ARGN2 input. For example, if you put the event you gave players while the quest going on:

```
On=@Attack
IF (STRMATCH("<SRC.BASEID>", "c_blabla") && !(<SRC.FLAGS>&STATF_INVUL)
  ARGN2 = 0
ENDIF
```

Player's ignore status will be cleared. I would like to make another solution with another triggers but the issue is they are not called by sphere.

**Comment by Jhobean** [comment]
Just to be sure, the @attack must be on the player?

**Comment by xwerswoodx** [comment]
Yes, later on maybe I can try another solution which is better but right now the only trigger is @Attack.

**Comment by Jhobean** [comment]
Working! THX!
