### ISSUE TITLE
Trigger @NPCRestock still make item

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#440]
When fire @NPCRestock still add item to NPC backpack and not check if exist or not.

**How Reproduce**
- Add a spawn of a vendor like c_butcher
- Set Region tag.RestockVendors=10 for fast restock (if not want use this tag have to wait 10 mins)
- Open vendor backpack and see.

**Additional info:**
- Tested on last build (3285)
- Clear script pack
- Happen only on **Brain_vendor**
- Possible connected to issue #397 fix

Little video clip: https://www.youtube.com/watch?v=_jexZ9i18d8

**NPC Script code:**
```
[CHARDEF c_butcher]
ID=c_man
NAME=#NAMES_HUMANMALE the butcher
DESIRES=i_gold
AVERSIONS=t_trap
TSPEECH=spk_human_default
TSPEECH=spk_shopkeep
CATEGORY=Civilized
SUBSECTION=Tradesmen
DESCRIPTION=Butcher (human male)
ON=@Create
   COLOR=colors_skin
   NPC=brain_vendor
   NEED=i_gold
   STR={50 75}
   DEX={45 55}
   INT={45 55}

   ANATOMY={20.0 30.0}
   ANIMALLORE={50.0 75.0}
   COOKING={20.0 30.0}
   FENCING={50.0 75.0}
   FISHING={20.0 30.0}
   FORENSICS={20.0 30.0}
   HERDING={20.0 30.0}
   MAGICRESISTANCE={20.0 30.0}
   SWORDSMANSHIP={20.0 30.0}
   TACTICS={20.0 30.0}
   TASTEID={20.0 30.0}
   WRESTLING={20.0 30.0}

   ITEMNEWBIE=random_light
   ITEMNEWBIE=random_male_hair
   COLOR=colors_hair
   ITEMNEWBIE=random_facial_hair,1,R5
   COLOR=match_hair
   ITEM=random_shirts_human
   COLOR=colors_all
   ITEM=random_pants_human
   COLOR=colors_all
   ITEM=random_footwear_human
   COLOR=colors_neutral
   ITEM=i_apron_half
   COLOR=colors_brown
ON=@NPCRestock
   ITEM=random_coin_purse
   ITEM=i_cleaver_meat,1,R3
   ITEM=i_knife_skinning,1,R3
   ITEM=i_knife_butcher,1,R3

   SELL=VENDOR_S_BUTCHER_TEMPLATE
   BUY=VENDOR_B_BUTCHER_TEMPLATE
```

**Comment by Jhobean** [comment]
Animal tamer too

**Comment by xwerswoodx** [comment]
It's not a bug, I changed the behaviour of the @npcrestock as it should be. You can use @CreateLoot trigger instead of npcrestock to set drops to npc.  Next PR I can add a setting to sphere.ini to choose between old and new behaviour.

Note that: @CreateLoot only create item when npc is dead, so it's better to use for loots.

**Comment by Jhobean** [comment]
Who will change all script pack? :-)

**Comment by xwerswoodx** [comment]
Hm, now I am in my bed trying to sleep, tomorrow I can find a solution for it. I may change the npcrestock to stock items only first time it created so it can fix the issue.

**Comment by Jhobean** [comment]
I can change all my script its fine. But someone must change the script pack

**Comment by cbnolok** [comment]
Well, actually i'd keep the way npcrestock has always worked, doing
otherwise would cause too many headaches to people

Il mar 28 apr 2020, 04:32 Jhobean <notifications@github.com> ha scritto:

**Comment by alexdan2** [comment]
@xwerswoodx i already use different way for loot. For me not is a problem :)
I simple testing it whit script pack in in download link :)

**Comment by xwerswoodx** [comment]
Hmm, okay I will make it works like before, and try to find another issue for color issue. I agree with you, many people currently using @NPCRestock so it can cause issue for them, so I will make it works like old way with a little improvement, but I am still highly recommend you to use @CreateLoot instead of @NPCRestock because @NPCRestock create items while npc is still alive, and that causes more item saves on world save, but @CreateLoot only creates loot when the npc dead so it means save files got cleaner from more than a million unnecessary items.

**Comment by alexdan2** [comment]
@xwerswoodx yeah long time ago before @CreateLoot my friend already maked a different way for loot on @death trigger for prevent item in save, now i think @CreateLoot is more faster than script on trigger @death

**Comment by GitMadKing** [comment]
sphere should improve and be basically backwards compatible with scripts no mather whatMarius ---- On mar, 28 apr 2020 12:20:50 +0200  notifications@github.com  wrote ----
@xwerswoodx yeah long time ago before @CreateLoot my friend already maked a different way for loot on @death trigger for prevent item in save, now i think @CreateLoot is more faster than script on trigger @death

**Comment by cbnolok** [comment]
Yeah for sure @CreateLoot should be the new way to go, but it's mandatory
to keep at least basic backwards compatibility (with stuff that always
worked in a certain way)

Il mar 28 apr 2020, 12:32 Mad King <notifications@github.com> ha scritto:

**Comment by GitMadKing** [comment]
speaking of loot, before any change, we should discuss and decide how should work.

.1) the loot should be inside the backpack?
...1a) should be lootable?
...1a-bis) should be restocked if looted?
.2) the loot should be created when npc dies?
...2a) is what @createloot does? got triggered when npc dies and create loot and put it inside body?
...2b) does the equip of npc sum up with the @createloot loot?
.3) where equip of npc should go?
...3a) if got stealed it should be restocked\re-equiped by npc?
.4) does @npcrestock has to do with selling item restock?
...4a) what kind of use should have in relation with that?

**Comment by GitMadKing** [comment]
speaking of loot, before any change, we should discuss and decide how should work.

.1) the loot should be inside the backpack?
...1a) should be lootable?
...1a-bis) should be restocked if looted?
.2) the loot should be created when npc dies?
...2a) is what @createloot does? got triggered when npc dies and create loot and put it inside body?
...2b) does the equip of npc sum up with the @createloot loot?
.3) where equip of npc should go?
...3a) if got stealed it should be restocked\re-equiped by npc?
.4) does @npcrestock has to do with selling item restock?
...4a) what kind of use should have in relation with that?

changing the scripts pack, is a stuff i can do, and i'll do if needed, but first decide the behaviour, to do things once

**Comment by alexdan2** [comment]
I thinked another problem about @NPCRestock not used for item:

Some script is possible use OLD @NPCRestock system for loot in backpack for stealing skill. this is one idea i thinked

**Comment by alexdan2** [comment]
I tested your commit but some not work.
Ok npc no longer restock, but also if tell him buy or sell not give any item:
![image](https://user-images.githubusercontent.com/6176986/80796276-1107b480-8b9f-11ea-9eb5-b5d2d478f604.png)

**NPC Code:**

```
[CHARDEF c_butcher]
ID=c_man
NAME=#NAMES_HUMANMALE the butcher
DESIRES=i_gold
AVERSIONS=t_trap
TSPEECH=spk_human_default
TSPEECH=spk_shopkeep
CATEGORY=Civilized
SUBSECTION=Tradesmen
DESCRIPTION=Butcher (human male)
ON=@Create
   COLOR=colors_skin
   NPC=brain_human
   NEED=i_gold
   STR={50 75}
   DEX={45 55}
   INT={45 55}

   ANATOMY={20.0 30.0}
   ANIMALLORE={50.0 75.0}
   COOKING={20.0 30.0}
   FENCING={50.0 75.0}
   FISHING={20.0 30.0}
   FORENSICS={20.0 30.0}
   HERDING={20.0 30.0}
   MAGICRESISTANCE={20.0 30.0}
   SWORDSMANSHIP={20.0 30.0}
   TACTICS={20.0 30.0}
   TASTEID={20.0 30.0}
   WRESTLING={20.0 30.0}


ON=@NPCRestock
   SELL=VENDOR_S_BUTCHER_TEMPLATE
   BUY=VENDOR_B_BUTCHER_TEMPLATE
```

**Comment by alexdan2** [comment]
Fixed in 3289 release.

@Jhobean can test it too, if for you is all ok i can close issue

**Comment by Jhobean** [comment]
Seem good. Thx

**Comment by alexdan2** [comment]
Nice i can close it. Thx
