### ISSUE TITLE
Wrong notoflag when two guildstones are in war.

### ISSUE THREAD

**Issue by Massi17** [Sphereserver/Source-X#442]
Create two guildstones, enlist a character in each guild, declare war and you will see your opponent with the notoflag-ally (green)

**Comment by pentanorl** [comment]
Looks like something is broken with notoriety colors related to guild status.
Just create different guildstones without declaring war nor alliances and you'll see everyone ORANGE (Enemy) instead of their natural notoriety colors (Blu/Red/Gray). The moment you declare war from both sides you'll see your enemy GREEN (Ally).
Of course since you'll see everyone guilded as green or orange, kills and criminal actions don't trigger at all.
Guildmates results GREEN (Ally) as supposed to, so looks like that just War/Peace colors are inverted and peace doesn't has to be considered as alliance (when guild aligns are different).


Already tested with latest build and some previous with community pack.
This is the untouched *.ini stuff related to notoriety colors
```
// Default color settings for characters names (notoriety)
//ColorNotoGood=059			// blue
//ColorNotoGuildSame=03f	// green (ally)
//ColorNotoNeutral=03b2		// grey (can be attacked)
//ColorNotoCriminal=03b2	// grey (criminal)
//ColorNotoGuildWar=090		// orange (enemy guild)
//ColorNotoEvil=022			// red
//ColorNotoInvul=035		// yellow
//ColorNotoInvulGameMaster=0b	// purple
//ColorNotoDefault=03b2		// grey (if not any other)
```

**Comment by cbnolok** [comment]
As a note to other devs and contributors, we should evaluate if it would be
useful to port the 56d guild and town system (and the chat one?) since they
were greatly reworked but i don't know if any functionality was changed

Il mar 28 apr 2020, 13:12 Stefano <notifications@github.com> ha scritto:

**Comment by pentanorl** [comment]
I just made this simple function to help debug.
The function prints out the list of notovalues showing the respective color for each player inside the list.
And well, something strange happen.
You should set the "NotoTimeOut" (*.ini) to a low value (just a few seconds) to speed things up.

**This is one scenario:**
I have three characters everybody with positive karma to simplify the situation.
Two of them are in the same guild [AAA] and a third one is in a guild at war [BBB]:
- Player One [AAA] //(myself)
- Player Two [AAA] //(guildmate)
- Player Three [BBB] //(enemy)

The function shows that my guildmate and my enemy are both GREEN (Ally) as previously said in this topic, but the function also shows that the notoriety constantly toggle from Green to Blue BEFORE the timeout is elapsed. Don't know if it's normal to act that way. Still, the client sticks to the notoriety read at first sight, the timeout won't refresh what the client sees even if the function shows that the notoriety has changed. I have to go away and wait for the list to be cleared. 

```
[DEFNAME notocolors_mask]
notoc_1	059,Blue
notoc_2	03f,Green(GuildAlly)
notoc_3	03b2,Grey(Karma)
notoc_4	03b2,Grey(Criminal)
notoc_5	090,Orange(GuildEnemy)
notoc_6	022,Red
notoc_7	035,Yellow(Invul)
notoc_8	0b,Purple(InvulGM)
notoc_9	03b2,Grey(other)

[PLEVEL 1]
SHOWNOTORIETY

[FUNCTION SHOWNOTORIETY]
SRC.SAY @,,1 # NOTOVALUES #
FOR 0 <SRC.NOTOSAVE>
	REF1=<SRC.NOTOSAVE.<eval <dlocal._for>>>
	IF ( <REF1> )
		local.colhex=<STRARG <def.notoc_<REF1.NOTOSAVE.<eval <dlocal._for>>.COLOR>>>
		local.colword=<STREAT <def.notoc_<REF1.NOTOSAVE.<eval <dlocal._for>>.COLOR>>>
		local.refresh=<EVAL <SERV.NotoTimeOut>-<REF1.NOTOSAVE.<eval <dlocal._for>>.ELAPSED>>
		IF ( <REF1.GUILD> )
			SRC.SAY @<local.colhex>,,1 #<eval <dlocal._for>>: <REF1.NAME> [<REF1.GUILD.ABBREV>] | <local.colword> (-<local.refresh>s)
		ELSE
			SRC.SAY @<local.colhex>,,1 #<eval <dlocal._for>>: <REF1.NAME> | <local.colword> (-<local.refresh>s)
		ENDIF
	ENDIF
ENDFOR
RETURN 1
```

**Comment by pentanorl** [comment]
don't know why my comment vanished...  anyway, just made this function to help debug.

```
[DEFNAME notocolors_mask]
notoc_1	059,Blue
notoc_2	03f,Green(GuildAlly)
notoc_3	03b2,Grey(Karma)
notoc_4	03b2,Grey(Criminal)
notoc_5	090,Orange(GuildEnemy)
notoc_6	022,Red
notoc_7	035,Yellow(Invul)
notoc_8	0b,Purple(InvulGM)
notoc_9	03b2,Grey(other)

[PLEVEL 1]
SHOWNOTORIETY

[FUNCTION SHOWNOTORIETY]
SRC.SAY @,,1 # NOTOVALUES #
FOR 0 <SRC.NOTOSAVE>
	REF1=<SRC.NOTOSAVE.<eval <dlocal._for>>>
	IF ( <REF1> )
		local.colhex=<STRARG <def.notoc_<REF1.NOTOSAVE.<eval <dlocal._for>>.COLOR>>>
		local.colword=<STREAT <def.notoc_<REF1.NOTOSAVE.<eval <dlocal._for>>.COLOR>>>
		local.refresh=<EVAL <SERV.NotoTimeOut>-<REF1.NOTOSAVE.<eval <dlocal._for>>.ELAPSED>>
		IF ( <REF1.GUILD> )
			SRC.SAY @<local.colhex>,,1 #<eval <dlocal._for>>: <REF1.NAME> [<REF1.GUILD.ABBREV>] | <local.colword> (-<local.refresh>s)
		ELSE
			SRC.SAY @<local.colhex>,,1 #<eval <dlocal._for>>: <REF1.NAME> | <local.colword> (-<local.refresh>s)
		ENDIF
	ENDIF
ENDFOR
RETURN 1
```

**Comment by GitMadKing** [comment]
> If a mod could restore my previous comment I'd appreciate it... I had written a lot. XD
**NOT A MOD, but i can do it :)**

> I just made this simple function to help debug.
> The function prints out the list of notovalues showing the respective color for each player inside the list.
> And well, something strange happen.
> You should set the "NotoTimeOut" (*.ini) to a low value (just a few seconds) to speed things up.
> 
> This is one scenario:
> I have three characters everybody with positive karma to simplify the situation.
> Two of them are in the same guild [AAA] and a third one is in a guild at war [BBB]:
> 
> Player One [AAA] //(myself)
> Player Two [AAA] //(guildmate)
> Player Three [BBB] //(enemy)
> The function shows that my guildmate and my enemy are both GREEN (Ally) as previously said in this topic, but the function also shows that the notoriety constantly toggle from Green to Blue BEFORE the timeout is elapsed. Don't know if it's normal to act that way. Still, the client sticks to the notoriety read at first sight, the timeout won't refresh what the client sees even if the function shows that the notoriety has changed. I have to go away and wait for the list to be cleared.

```
[DEFNAME notocolors_mask]
notoc_1	059,Blue
notoc_2	03f,Green(GuildAlly)
notoc_3	03b2,Grey(Karma)
notoc_4	03b2,Grey(Criminal)
notoc_5	090,Orange(GuildEnemy)
notoc_6	022,Red
notoc_7	035,Yellow(Invul)
notoc_8	0b,Purple(InvulGM)
notoc_9	03b2,Grey(other)

[PLEVEL 1]
SHOWNOTORIETY

[FUNCTION SHOWNOTORIETY]
SRC.SAY @,,1 # NOTOVALUES #
FOR 0 <SRC.NOTOSAVE>
	REF1=<SRC.NOTOSAVE.<eval <dlocal._for>>>
	IF ( <REF1> )
		local.colhex=<STRARG <def.notoc_<REF1.NOTOSAVE.<eval <dlocal._for>>.COLOR>>>
		local.colword=<STREAT <def.notoc_<REF1.NOTOSAVE.<eval <dlocal._for>>.COLOR>>>
		local.refresh=<EVAL <SERV.NotoTimeOut>-<REF1.NOTOSAVE.<eval <dlocal._for>>.ELAPSED>>
		IF ( <REF1.GUILD> )
			SRC.SAY @<local.colhex>,,1 #<eval <dlocal._for>>: <REF1.NAME> [<REF1.GUILD.ABBREV>] | <local.colword> (-<local.refresh>s)
		ELSE
			SRC.SAY @<local.colhex>,,1 #<eval <dlocal._for>>: <REF1.NAME> | <local.colword> (-<local.refresh>s)
		ENDIF
	ENDIF
ENDFOR
RETURN 1
```

**Comment by Massi17** [comment]
any news?

**Comment by JulianUO** [comment]
I think I found the issue and pulled a requeest to the source.
Will try to add the DeclareAlly functions ASAP so you can play with alliances aswell.

**Comment by Massi17** [comment]
really appreciated your help Julian

**Comment by JulianUO** [comment]
Can you test if it's fixed?

**Comment by Massi17** [comment]
yes. Atm our co-guild are green (ally), if two GS are in war we see our opponent orange (enemies).
i can confirm we can't do alliance between two guildstones and alignment doesn't change our notoflag.

**Comment by JulianUO** [comment]
I'll add the alignment tweak via script so everyone can tweak the factions and play with them easily.
About the alliance is an enhancement I'm working on, but it will take some time.

**Comment by Massi17** [comment]
i agree on alignment... and for the alliance it's ok, take your time... for now we just need the system is playable. our players can wait for alliances.

**Comment by xwerswoodx** [comment]
@Massi17 please check your issue if still happening, we need to close the issue if there is no issue.

**Comment by Massi17** [comment]
it still happening
