### ISSUE TITLE
strange behaviour with instances

### ISSUE THREAD

**Issue by GitMadKing** [Sphereserver/Source-X#444]
empty world
execute in console
add i_bee_swarm in game
look at info "instances", it has 8.
try goitemid i_bee_swarm
you will go to just the one you created.
even forinstances loop will not loop trough nothing

```
[function f_tsi]
for 0 30
	local.item=<serv.deflist.itemdef.<dlocal._for>>
	serv.log <local.item> <serv.itemdef.<local.item>.defname> <serv.itemdef.<local.item>.instances>
endfor
```

**Comment by xwerswoodx** [comment]
I added a i_bee_swarm. I check it's instances equals 1, later I add another, it says 2, added another it says 3. And used .goitemid i_bee_swarm, first sent me on 3rd one I created, later 2nd and at last 1st one. Seems like everything working fine. Maybe your info script is showing instances info wrong?

**Comment by GitMadKing** [comment]
of course is not info menu.
i use clean sphere, clean xscriptpack, clean saves.
first execute function attached
then do the test you did

**Comment by GitMadKing** [comment]
of course is not info menu.
i use clean sphere, clean xscriptpack, clean saves.
first execute function attached
then do the test you did

even the log in server looks wrong.
every "same item"(dupelists) it increments their value to 8. like there were created.

**Comment by xwerswoodx** [comment]
I tried it and still everything correct for me.

**Comment by GitMadKing** [comment]
@xwerswoodx let me show more detaieled
just downloaded sphere, xscriptapack
THE VIDEO:
https://streamable.com/3j9udg
THE SPHERE:
[clean_sphere_bee.zip](https://github.com/Sphereserver/Source-X/files/4566190/clean_sphere_bee.zip)
```
22:38:5:'Mad King' Says UNICODE 'ITA' 'F_TSI' mode=0
22:38:(book_content_default.scp,10)i_eq_followSrc i_eq_followSrc 0
22:38:(book_content_default.scp,10)i_pagegm_teleport_delay i_pagegm_teleport_delay 0
22:38:(book_content_default.scp,10)i_memory_fishing_splash i_memory_fishing_splash 0
22:38:(book_content_default.scp,10)i_gem_arcane i_gem_arcane 0
22:38:(book_content_default.scp,10)2331 i_bee_swarm 1
22:38:(book_content_default.scp,10)2332 i_bee_swarm 2
22:38:(book_content_default.scp,10)2333 i_bee_swarm 3
22:38:(book_content_default.scp,10)2334 i_bee_swarm 4
22:38:(book_content_default.scp,10)2335 i_bee_swarm 5
22:38:(book_content_default.scp,10)2336 i_bee_swarm 6
22:38:(book_content_default.scp,10)2337 i_bee_swarm 7
22:38:(book_content_default.scp,10)2338 i_bee_swarm 8
22:38:(book_content_default.scp,10)2339 i_fx_bee_swarm2 0
22:38:(book_content_default.scp,10)2340 i_fx_bee_swarm2 1
22:38:(book_content_default.scp,10)2341 i_fx_bee_swarm2 2
22:38:(book_content_default.scp,10)2342 i_fx_bee_swarm2 3
22:38:(book_content_default.scp,10)2343 i_fx_bee_swarm2 4
22:38:(book_content_default.scp,10)2344 i_fx_bee_swarm2 5
22:38:(book_content_default.scp,10)2345 i_fx_bee_swarm2 6
22:38:(book_content_default.scp,10)2346 i_fx_bee_swarm2 7
22:38:(book_content_default.scp,10)3546 i_moongate_red 0
22:38:(book_content_default.scp,10)3547 i_moongate_red 1
22:38:(book_content_default.scp,10)3548 i_moongate_red 2
22:38:(book_content_default.scp,10)3549 i_moongate_red 3
22:38:(book_content_default.scp,10)3550 i_moongate_red 4
22:38:(book_content_default.scp,10)3923 i_fireball 0
22:38:(book_content_default.scp,10)3924 i_fireball 1
22:38:(book_content_default.scp,10)3925 i_fireball 2
22:38:(book_content_default.scp,10)3926 i_fireball 3
22:38:(book_content_default.scp,10)3927 i_fireball 4
22:38:(book_content_default.scp,10)3928 i_fireball 5
22:38:5:'m' commands 'F_TSI'=1
```
look also the strange behaviour in console logs.
instances increases every cycle

**Comment by xwerswoodx** [comment]
Hm, now I got what you mean, I haven't used command because you only said execute console, so I just think you gave to command to see instances so I haven't used it. Anyway this is really strange, first time it increases count but second time it just get 8 without increase.

**Comment by cbnolok** [comment]
Is that still happening?

**Comment by xwerswoodx** [comment]
@cbnolok yes I just tested it, it still happening.
