### ISSUE TITLE
Spell Mind Blast

### ISSUE THREAD

**Issue by alexrmrm** [Sphereserver/Source-X#445]
Problem with spell Mind Blast, if 2 chars have same INT, iDiff=0 and will use on spelleffect 0, and not make dmg.
**CCharSpell.cpp**

> 			case SPELL_Mind_Blast:
> 				if (pObj->IsChar())
> 				{
> 					CChar * pChar = dynamic_cast <CChar*> (pObj);
> 					ASSERT(pChar);
> 					int iDiff = (Stat_GetAdjusted(STAT_INT) - pChar->Stat_GetAdjusted(STAT_INT)) / 2;
> 
> 					if (iDiff < 0)
> 					{
> 						pChar = this;	// spell revereses !
> 						iDiff = -iDiff;
> 					}
> 					int iMax = pChar->Stat_GetMaxAdjusted(STAT_STR) / 2;
> 					pChar->OnSpellEffect(spell, this, minimum(iDiff, iMax), nullptr);
> 				}
> 				break;

**CCharSpell.cpp:**

> 	if ( iSkillLevel <= 0 )		// spell died or fizzled
> 		return false;

**Comment by xwerswoodx** [comment]
Honestly I think about that much, but I haven't sure if it's bug. Because this skill works like;

if attacker int bigger than attacked player:
  damage attacked player half of the difference

if attacker in lower than attacked player:
  damage attacker with half of the difference

So seems like if there is no difference noone can manage to blask other's mind. If we return it as fizzle it can let player think the spell doesn't working when ints are equal. It's really strange I agree, as the default way of the spell is very different on OSI. But I can't change the spell at all without asking developers about it, so I just left that note here.

**Comment by alexrmrm** [comment]
Perhaps it is not considered a bug. But if you want to do it other than OSI, there is no option to modify that diff either.

**Comment by xwerswoodx** [comment]
I like Renaissance way to get Highest Skill and lowest skill of the attacker and divide it to 2. That cause huge amount of damage but when int&dex&str is equal to 100 it causes bug again, so it's not for a global use.  So the best way to use OSI style or improve sphere custom code. Maybe the difference can get rand from diff-5 to diff+5 so damage can be more random and there only %9 chance to get "0" damage when difference equals zero.

**Comment by cbnolok** [comment]
So, through UO eras, the way how this spell works has changed? Right now, does it work in a totally custom way or does it match a specific UO era?

**Comment by xwerswoodx** [comment]
Long time happened, but I remember that the way in the sphere is totally custom (or maybe get somewhere else), I checked Renaissance and Uo.com mind blass spells but;

UO:
Mind Blast (Por Corp Wis) | Black Pearl, Mandrake Root, Nightshade, Sulfurous Ash | Makes a mind blast hit your target for max 40 to 42 points of Cold damage. Damage level depends on Magery and Intelligence. Has a small delay.
-- | -- | --

Seems like UO.com get the magery and intelligence and add 40-42 damage I guess magery + int / 50 or something like this.

Renaissance:
Mind blast checks the targets stats and determines which stat is the highest and lowest then determines the difference between the two. This number is halved and checked to make sure it is not more than 40 damage. Should the target player pass a resist check the damage would be halved.

Example 1: Str: 100: Dex:25 Int:100, Highest Stat 100, Lowest Stat 25, Difference:75
Result 1: Damage:37, Resisted Damage:18

Example 2: Str: 100: Dex:25 Int:110, Highest Stat 110, Lowest Stat 25, Difference:85
Result 2: Damage:40, Resisted Damage:20

Example 3: Str: 90: Dex:45 Int:90, Highest Stat 90, Lowest Stat 45, Difference:45
Result3: Damage:22, Resisted Damage:11

As you can see balanced stats are critical when mitigating the damage from the mind blast spell.

Formula: (Highest Stat - Lowest Stat) / 2

This formula get highest stat from str/int or dex and lowest stat then get difference between them and make a damage depends on it, if i understand correctly.

Sphere Custom:
Get Attacker's Intelligence then get difference between Attacker's Intelligence and Attacked Player's Intelligence and cause damage depends on this.

**Comment by Jhobean** [comment]
https://cdn.discordapp.com/attachments/488892196096049163/786705987531702293/unknown.png

**Comment by xwerswoodx** [comment]
Yes in sphere custom it works like this, where did you find that picture?

**Comment by Soulless-1** [comment]
under the spelldef you can make the spell work like any era or in any custom way you would like: 
local.Effect | IO | Changes the EFFECT value of the spell (For changing EFFECT_ID see Local.CreateObject1).
