### ISSUE TITLE
Skill do not go down when over Skillcap

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#447]
We have a little Issue with the skill. Our skillcap is at 1500.

- Player set their useless skill with the down arrow 
![image](https://user-images.githubusercontent.com/51728381/80721174-eac51480-8acb-11ea-885b-953ae3357f31.png)

- The skill go down correctly by 0.1 when we use other skill when we are under 1500 skill pts

- When player have more than 1500 pts, the arrow down 's functionnality do not work anymore. Player must page and GM must down manually some skill.

**Comment by alexdan2** [comment]
Normally skill have to go down only when reach skillcap .

Example: 
If have 1400 and set down a skill, this skill can't go down because not reached 1500.
Have to go down only when have a total of 1500,

**Is more than one bug:**
- _The skill go down correctly by 0.1 when we use other skill when we are under 1500 skill pts_ -> This is wrong skill not have to go down if not reached skillcap.
- Skill have to go down only if reached 1500

**Comment by xwerswoodx** [comment]
Something wrong for gain/lost skill as I noticed that RETURN 1 also doesn't block skill lost as I mentioned at #411

**Comment by Jhobean** [comment]
> * Skill have to go down only if reached 1500

Reached or Highter

**Comment by alexdan2** [comment]
> > * Skill have to go down only if reached 1500
> 
> Reached or Highter

Highteris impossible to reach if have 1500 skillcap how is possible have more ?

**Comment by Jhobean** [comment]
Exemple, we have scroll tha perso can buy and boost their skill...  100k gold.  Dclic on scroll and alchimie + 10.  You are now at 1510.  We accept the 1510 but all skill with arrow down must decrease.

**Comment by alexdan2** [comment]
Uhmm ok, i not calculated possible item give real skill whitout macro it. In your case ofc upper also

**Comment by Jhobean** [comment]
It's a confirm bug? Because I have ton of page and must lower skill manualy

**Comment by GitMadKing** [comment]
a script like this meanwhile? 
**UNTESTED**
```
ON=@SkillGain
local.totalskills = 48
if  <SKILLTOTAL> > <skillclass.skillsum>
	local.skillfound = 0
	FOR skll 0 <dlocal.totalskills>
		if <skilllock[<dlocal.skll>]> = 1
			try <dlocal.skll> -= 1
			local.skillfound = 1
		endif
	ENDFOR
	if <local.skillfound> = 0
		try <R0,<dlocal.totalskills>> -= 1
	endif
endif
```
**UNTESTED**

**Comment by Jhobean** [comment]
Bug may be this line https://github.com/Sphereserver/Source-X/blob/df63400f9fd4c9c34504ebd4b0716d705009a214/src/game/chars/CCharStat.cpp#L646

**Comment by Jhobean** [comment]
Work like it should be THX!
