### ISSUE TITLE
Skill @prestart return 1, infinite delay

### ISSUE THREAD

**Issue by criminalx** [Sphereserver/Source-X#450]
When I add a return 1 in @prestart, it not prevent do the action, instead it make the skill with infinite delay,  I show in video: 
https://puu.sh/FEVmU/975baed7df.mp4

script: 
```
ON=@PreStart
if (<src.targ> == <src>)
	src.sysmessage @,,1 You know yourself quite well enough already.
  	return 1 // this should prevent start the skill
endif
```

**Comment by alexdan2** [comment]
I use for mining and not have any problem

**Code:**
> ON=@PreStart
> 	IF (<SRC.FLAGS> & statf_onhorse|statf_hovering)
> 		SRC.SYSMESSAGE You can't dig while riding or flying.
> 		return 1
> 	ELIF (<SRC.FLAGS> & statf_polymorph)
> 		SRC.SYSMESSAGE You can't dig while polymorphed.
> 		return 1
> 	ENDIF

**Tested on anatomy and confirm issue:**
```
[SKILL 1]
DEFNAME=Skill_Anatomy
KEY=Anatomy
TITLE=Biologist
PROMPT_MSG=Whom shall I examine?
DELAY=3.0,1.0
STAT_STR=15
STAT_DEX=15
STAT_INT=70
BONUS_STR=0
BONUS_DEX=0
BONUS_INT=100
BONUS_STATS=50
ADV_RATE=2.5,50.0,200.0

ON=@PreStart
if (<src.targ> == <src>)
	src.sysmessage @,,1 You know yourself quite well enough already.
  	return 1 // this should prevent start the skill
endif
```

**Comment by Jhobean** [comment]
I had same issue on 56d. Here the fix of coruja https://github.com/Sphereserver/Source/commit/6be4f3619630d1ed1ad20d4d4c8b7a8027ffd9ae

**Comment by alexrmrm** [comment]
I tested with last build and now cancel action, its ok now.

**Comment by alexdan2** [comment]
Buld 3289 fixed, thx
