### ISSUE TITLE
musicanship/tracking, abort raise skill

### ISSUE THREAD

**Issue by criminalx** [Sphereserver/Source-X#451]
Just tried musicanship, dclick the instrument and "tab" you will abort and skill will raise, 0-100 in few mins. vide: https://puu.sh/FEWaF/a6c69d8087.mp4

**Comment by xwerswoodx** [comment]
I have no issue about it, I tried to click drum, abort the skill, it says aborted and doesn't gain anything. Maybe you have an event that makes it continue.

**Comment by Jhobean** [comment]
Normaly, pass 30 the skillgain is on success.

**Comment by alexrmrm** [comment]
Tested on last build and  that work. If with 0.0 skill not work raise to 0.1.
[](https://streamable.com/iz49u9)

same for tracking.

And that up more of 30.0

tested with scriptpack default.

**Comment by xwerswoodx** [comment]
I am trying what you said, Dclick on the drum, and tab and it says "You put down the instrument" and stop gaining skill at all. I don't know if it's a sphere or client bug, I will check it with default client later.

**Comment by drk84** [comment]
From the video, there are no "You must wait to perform another action messages." that must means that the DELAY value of your musicianship skill is near to 0, and that's probably why you are getting these rapid increases.

**Comment by criminalx** [comment]
> From the video, there are no "You must wait to perform another action." that must means that the DELAY value of your musicianship skill is near to 0, and that's probably why you are getting these rapid increases.

it is because i use war/peace, so it abort the skill, and skill is at 38..

**Comment by alexdan2** [comment]
I try to replicate this bug in Lase release (3344), but not happen. Simple get "You put down your instrument." when switch to War Mode. 

Simple call
```
ON=@Abort
	SRC.SYSMESSAGE You put down your instrument
```
And not get any gain

**Comment by cbnolok** [comment]
Is this still an issue?

**Comment by Soulless-1** [comment]
i was able to test on the latest build and it's working without issue. closing this out
![image](https://github.com/Sphereserver/Source-X/assets/17236327/5a166956-b27c-41b6-be03-3cd4a06f671f)
