### ISSUE TITLE
 Suggestion limit of packages client -> server

### ISSUE THREAD

**Issue by alexrmrm** [Sphereserver/Source-X#452]
some client tools are capable of sending many packets in ms, it would be nice to be able to control this to be able to do something with these clients

**Comment by alexdan2** [comment]
Amount of data send and recevied is different by situation i think hard manage it, also what problem.

If is only one tipe of packet can simple filter by catch it:
```
place PACKET191=f_packet_0xbf in sphere.ini
[function f_packet_0xbf] to catch packets
```
After filter it can do all action you want.

Also if client send 100 click but your script manage correct delay nothing bad happen

**Comment by Jhobean** [comment]
Added by Nolok in this commit: https://github.com/Sphereserver/Source-X/commit/d4e9facfcec163dfc935738e1cdcbb5675b3cea6
