### ISSUE TITLE
TARGETCANCEL does not work or "old clients" not responding?

### ISSUE THREAD

**Issue by GitMadKing** [Sphereserver/Source-X#453]
do someone know if this is a bug of client or sphere?

.target
.targetcancel

still have target

**Comment by xwerswoodx** [comment]
It's because the command is ".TargetClose" not ".TargetCancel".

**Comment by GitMadKing** [comment]
right, it works, "target cancelled" but the target cursor is still viewed, even if it does not do anyhthing when targeting
any possibile fix?

**Comment by xwerswoodx** [comment]
Oh, seems like old client bug, could you try to use .update or .fix after .targetclose?

**Comment by GitMadKing** [comment]
no response with nothingMarius ---- On dom, 03 mag 2020 12:23:43 +0200  notifications@github.com  wrote ----
Oh, seems like old client bug, could you try to use .update or .fix after .targetclose?

**Comment by GitMadKing** [comment]
seems related to client. 2.0 has this problem
tryied out the 3.0 and not.
i don't know if can be fixed anyway server side.
if not close this issue.

thank

**Comment by xwerswoodx** [comment]
I guess it's because of client doesn't update itself when the package sent, I am not sure if it's fixed on server-side because newer clients works fine, I guess it's because of client.

**Comment by GitMadKing** [comment]
well then
