### ISSUE TITLE
HardCoded Champ System - Mobs not placed

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#454]
Hello i started to test HardCoded Champ System, but get some issue at start:

**Issue:**
When champ start all mobs placed over idol (but not a big problem):
![image](https://user-images.githubusercontent.com/6176986/80911589-7f7f7a80-8d37-11ea-87dd-483f979c3d59.png)

If kill one of this this still undead, 0 hits but not die.
Also when make a save get errors like this:
```
11:42:ERROR:GC: 54 unplaced objects!
11:42:ERROR:GC: Deleted UID=08a0, Defname='c_orc', Name='Orco'. Invalid code=0x3202 (Object not placed in the world).
11:42:ERROR:GC: Deleted UID=0893, Defname='c_orc', Name='Orco'. Invalid code=0x3202 (Object not placed in the world).
11:42:ERROR:GC: Deleted UID=0888, Defname='c_orc', Name='Orco'. Invalid code=0x3202 (Object not placed in the world).
```
This error repeat for all mobs. 
After save all mobs vanish because deleted by GC.

Another issue i think connected to npc spawn is @Spawn, this trigger never fire (but i think is because mobs never placed)

**My Script code:**
```
[CHAMPION 01]
DEFNAME=CHAMPION_Test
NAME=TestTest
LevelMax=5 
Spawns=100 
NPCGroup[1] = c_orc, c_orc_lord
NPCGroup[2] = c_orc, c_orc_lord
NPCGroup[3] = c_orc, c_orc_lord
NPCGroup[4] = c_orc, c_orc_lord
CHAMPIONID=c_vampiro_dracula

[ITEMDEF i_champion_idol_test]
ID=01f18
TYPE=t_champion_spawn
NAME=Test Champion Idol

ON=@Create
more=CHAMPION_Test
ATTR |= ATTR_MOVE_NEVER

ON=@DClick
if (<timer> == -1)
	f_Region_Message DEBUG: Champ Start
	start 
else
	f_Region_Message DEBUG: Champ Stop
	stop
endif
return 1

ON=@AddWhiteCandle
	f_Region_Message DEBUG: POP White candle

ON=@AddRedCandle
	f_Region_Message DEBUG: POP red candle

ON=@Spawn
	SERV.LOG DEBUG NPCNAME: <argo.NAME>
```

**Comment by xwerswoodx** [comment]
Hmm seems like something wrong about Champion System, because it gives a debug for me.

**Comment by fjgo86** [comment]
Looks like the defname of the current pack is not the same I used for my tests and the changelog, this is the real one:
t_spawn_champion		300   // Champion Spawn

I'll update the revisions file, anyway I have another fix to send for champions, so you may want to wait to test it.

**Comment by alexdan2** [comment]
Ofc sure i wait new release for test it :)

**Comment by alexdan2** [comment]
**Tested on Release 3293 And Work perfect! Thx**

I have some extra ideas, i post here or make new "issue" whit report of all ideas ?

**Comment by xwerswoodx** [comment]
You can post here or make a new issue as you wish, but for me if you close that issue and create new one is better.

**Comment by alexdan2** [comment]
Oky man i follow your idea "create new one is better" is more clear for all :)
