### ISSUE TITLE
Weightreduction doesn't increase status bar

### ISSUE THREAD

**Issue by xwerswoodx** [Sphereserver/Source-X#455]
Note that bug until fixed for not forgetting it, because everytime you set 100% wr on item, it drops the weight from the status bar but when you set it back to 0% it doesn't increase status bar, so everytime you do that your weight getting lower and lower, when you unequip everything you wear, it drops down to negative it replaces with 65535. So players can't move anymore if there is an item that gives a WR to player.

![Image](https://s6.gifyu.com/images/a431f408ec50b4b2c.gif)

**Comment by Jhobean** [comment]
Other Issue about same feature: https://github.com/Sphereserver/Source-X/issues/407
