### ISSUE TITLE
Little bug in vendor sell menu

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#456]
When i set custom price in vendor buy list, sell menu not correct read PRICE but use standard item VALUE, but when i complese sell he give correct gold.

**Template Code:**
```
[TEMPLATE VENDOR_B_ALCHEMIST]
CATEGORY=Vendor Templates
SUBSECTION=Buy Templates
DESCRIPTION=Alchemist
BUY=i_potion_strength
PRICE=10
```

This is wrong:
![image](https://user-images.githubusercontent.com/6176986/80928044-2862bf80-8da2-11ea-8e18-c7874b135b87.png)

This is correct:
![image](https://user-images.githubusercontent.com/6176986/80928052-43353400-8da2-11ea-9995-04c0644bee00.png)

**Comment by xwerswoodx** [comment]
what do you mean with custom price?

**Comment by GitMadKing** [comment]
was not to use buyvalue sellvalue
?

**Comment by alexdan2** [comment]
I not know this buy and sell value can link me docs pls. Is possible this fix this issue than set Direct in buylist
--
Inviato da Libero Mail per Android Martedì, 05 Maggio 2020, 08:35PM +02:00 da Mad King  notifications@github.com :

**Comment by Jhobean** [comment]
I think the value must be in the itemdef of the item.. Never use the value on the template. it's suppose to work?

**Comment by alexdan2** [comment]
I use value in template for set different sell price.. 
For example if want npc sell red potion to 800gp but not want alchemy player can sell to high ratio value automatic calculated from 800gp i set PRICE=10 on vendor template.

NPC give correct PRICE=10 but show different in sell gump.

**Comment by alexdan2** [comment]
@GitMadKing 
I try to find SELLVALUE usefull guide but nothing on wiki, also i try to put SELLVALUE=10 on item but not work also on template.

**Comment by Jhobean** [comment]
The bug seem to be there
Where the packet is send to the client, the server use the itemdef value instead of the item value.
Don't know how to fix it.
https://github.com/Sphereserver/Source-X/blob/4b73c9c73efb1a2235297743059ff11fec6eb1ab/src/network/send.cpp#L2266

**Comment by Jhobean** [comment]
hmmm  Don't seem to have a bug. 
![image](https://user-images.githubusercontent.com/51728381/94294614-125ec280-ff2e-11ea-80fd-69d0b576b790.png)

The price is ajusted.... Did you restock your npc?

**Comment by alexdan2** [comment]
Hello,
I see you example @Jhobean but major problem is if i set a price on BUY template, he show itemdeff price. Not value of "price" present in vendor table

**Comment by Jhobean** [comment]
Price is use on player vendor.  If you want change the value of an item trade with NPC you should use value=

**Comment by Jhobean** [comment]
I don't think you can set the price of item NPC will buy the item on the template list.... NPC buy the item at the value or price set ON the item

**Comment by alexdan2** [comment]
Nice, i make few test and seems all OK,

Goodjob
