### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by canavar2212** [Sphereserver/Source-X#457]
Is it possible to separate the tooltips usage from FEATURE_AOS_UPDATE_B, that is, fightbook necro / paladin and others?

**Comment by canavar2212** [comment]
I want to use the tooltip without turning on the use of fightbook and abilitybook.

**Comment by alexdan2** [comment]
I think is client sidem when enable expansion automatic add this gump to paperdool and enable tooltip manager.
Possible solution is remove image from gump file :) fightbook and abilitybook no longer show

**Comment by fjgo86** [comment]
It is not possible for us to separate it, we send one flag when the character logs in and the client itself is the one that handle it to enable tooltips and those books.

**Comment by alexdan2** [comment]
@canavar2212 
Simple delete gump object in file and can get this result:
![image](https://user-images.githubusercontent.com/6176986/80989651-855b8580-8e35-11ea-8ba2-8a49dfbfe0b6.png)

**Comment by canavar2212** [comment]
okay, I got it.  thank you guys.
