### ISSUE TITLE
No able delete CHAR

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#459]
When I try delete CHAR in the login screen, nothing happen and i have this error on console:

`21:17:WARNING:d:Bad Char Delete Attempted 3 (acct='dixonze', char='cdcasdc', IP='127.0.0.1')`

**Comment by alexdan2** [comment]
I confirm this issue, try whit 7 days char old.

Tested on Build 3289

My ini setting:
`MinCharDeleteTime=2*24*60*60`

**Comment by GitMadKing** [comment]
i can...
could you try setting to 1?
could you try creating q new char and deleting it
also give char creation timer and actuql timer of server

may be related to an old bug where some timer were in secs and other in tenth
also "age" un game

**Comment by Jhobean** [comment]
Hmm. Maybe the conversion of 56d to x....   So for testing i'll set the ini to 1?

**Comment by alexdan2** [comment]
I try to set 1 but same error frist time, if make some other try deleted.

`Bad Char Delete Attempted 3 (acct='tt', char='fsdfsdfsdfs', IP='127.0.0.1')

**This Account block:**
```
[tt]
PRIV=00
RESDISP=8
PASSWORD=tt
LASTCHARUID=05473
CHARUID=05473
FIRSTCONNECTDATE=2020/05/12 14:04:29
FIRSTIP=127.0.0.1
LASTCONNECTDATE=2020/05/12 14:04:11
LASTIP=127.0.0.1
CHATNAME=fsdfsdfsdfs
LANG=ENU
TAG.FIRSTCHARUID=21619
TAG.TICKET_LASTLOGIN=10227708
```

**This char Block:**
```
[WORLDCHAR c_man]
SERIAL=05473
NAME=fsdfsdfsdfs
COLOR=083ea
MODMAXWEIGHT=69
MAXFOLLOWER=5
TAG.FIRST_LOGIN_A_R=1
TAG.monitor_timeexp=10227284
TAG.monitor_timehonor=10227284
TAG.TRANSFERREADY=1
EVENTS=Class_Mage
EVENTS=e_mage
ACCOUNT=tt
SKILLCLASS=Class_Mage
SPEECHCOLOR=690
EMOTECOLOR=34
P=4369,3748,-25
OSKIN=083ea
FLAGS=020000000
ACT=04fffffff
HOME=0,0
OKARMA=0
OFAME=0
OFOOD=14
FOOD=14
OSTR=25
OINT=45
ODEX=20
HITS=25
STAM=20
MANA=45

```

**Comment by GitMadKing** [comment]
```
[FUNCTION f_onchar_create]
serv.log @char <src.name> (<src.uid>) CREATE - <serv.rtime> (MinCharDeleteTime = <serv.MinCharDeleteTime>)

[FUNCTION f_onchar_delete]
serv.log @char <src.name> (<src.uid>) TRYDELETE - <serv.rtime>
```

> 15:52:char MCDT-test (01f35) CREATE - 2020/05/12 15:52:42 (**MinCharDeleteTime = 1**)
> 15:52:9:Account 'test2' created new char 'MCDT-test' [01f35]
> 15:52:9:Character startup for account 'test2', char 'MCDT-test'. IP='127.0.0.1'.
> 15:52:9:Client disconnected [Total:0]. Account: 'test2'. Char: 'MCDT-test'. IP='127.0.0.1'.
> 15:52:a:Client connected [Total:1]. IP='127.0.0.1'. (Connecting/Connected: 1/1).
> 15:52:a:Login for account 'test2'. IP='127.0.0.1'. ConnectionType: ServerList.
> 15:52:a:Client disconnected [Total:0]. Account: 'test2'. IP='127.0.0.1'.
> 15:52:b:Client connected [Total:1]. IP='127.0.0.1'. (Connecting/Connected: 1/2).
> 15:52:b:Login for account 'test2'. IP='127.0.0.1'. ConnectionType: CharList/Game.
> 15:53:WARNING:b:Bad Char Delete **Attempted 2** (acct='test2', char='MCDT-test', IP='127.0.0.1')
> 15:53:delete **attempted 2 (CLIENT PLAYING)**
> 15:53:WARNING:b:Bad Char Delete Attempted 3 (acct='test2', char='MCDT-test', IP='127.0.0.1')
> 15:53:delete **attempted 3 (time not meet)**
> 15:53:WARNING:b:Bad Char Delete Attempted 3 (acct='test2', char='MCDT-test', IP='127.0.0.1')
> .
> .
> 15:54:WARNING:b:Bad Char Delete Attempted 3 (acct='test2', char='MCDT-test', IP='127.0.0.1')
> 15:54:char MCDT-test (01f35) TRYDELETE - 2020/05/12 15:54:24
> 15:54:b:Account 'test2' deleted char 'MCDT-test' [01f35] on client login screen
###MinCharDeleteTime = 1 => TIME 102 SEC

> 15:58:char MCDT-test-two (01f2c) CREATE - 2020/05/12 15:58:05 (**MinCharDeleteTime = 2**)
> 15:58:b:Account 'test2' created new char 'MCDT-test-two' [01f2c]
> 15:58:b:Character startup for account 'test2', char 'MCDT-test-two'. IP='127.0.0.1'.
> 15:58:b:Client disconnected [Total:0]. Account: 'test2'. Char: 'MCDT-test-two'. IP='127.0.0.1'.
> 15:58:c:Client connected [Total:1]. IP='127.0.0.1'. (Connecting/Connected: 1/1).
> 15:58:WARNING:d:Bad Char Delete Attempted 2 (acct='test2', char='MCDT-test-two', IP='127.0.0.1')
> .
> 15:58:WARNING:d:Bad Char Delete Attempted 3 (acct='test2', char='MCDT-test-two', IP='127.0.0.1')
> .
> 15:59:WARNING:d:Bad Char Delete Attempted 3 (acct='test2', char='MCDT-test-two', IP='127.0.0.1')
> .
> 16:00:WARNING:d:Bad Char Delete Attempted 3 (acct='test2', char='MCDT-test-two', IP='127.0.0.1')
> .
> 16:01:WARNING:d:Bad Char Delete Attempted 3 (acct='test2', char='MCDT-test-two', IP='127.0.0.1')
> 16:01:char MCDT-test-two (01f2c) TRYDELETE - 2020/05/12 16:01:27
> 16:01:d:Account 'test2' deleted char 'MCDT-test-two' [01f2c] on client login screen.
###MinCharDeleteTime = 2 => TIME 202 SEC

CONCLUSION:
seems like bugged, and it seems to rapresente how many hundrends seconds to wait.
LOL

**Comment by Jhobean** [comment]
I'm suppose to be able to delete old char?  If I go on my account and try to delete one character, I have the same error.

`21:20:WARNING:1:Bad Char Delete Attempted 3 `

Do I have something to change?

**Comment by GitMadKing** [comment]
you have yo use "remove 1" to force

**Comment by xwerswoodx** [comment]
```
		BadPass        = 0x00, // incorrect password
		NotExist       = 0x01, // character does not exist
		InUse          = 0x02, // character is being played right now
		NotOldEnough   = 0x03, // character is not old enough to delete
		BackupQueue    = 0x04, // character is currently queued for backup
		InvalidRequest = 0x05, // couldn't carry out the request

		Success        = 0xFF  // no error
```
Seems like it's not old enough to delete, Can you check sphere.ini "MinCharDeleteTime" setting?

**Comment by GitMadKing** [comment]
look at my comment.
MinCharDeleteTime = 1 
can delete after 100 sec
MinCharDeleteTime = 2
can delete after 200 sec

**Comment by Jhobean** [comment]
Seem strange again...  How I know the age of a character...  The time on the ini don't seem to work for old character.

**Comment by GitMadKing** [comment]
i have also this question.
how "AGE" is calculated, how creation time is saved?
i cannot figure from where the timer of creation is taken, or saved

**Comment by cbnolok** [comment]
Oh the problem is that for some reason the CREATE keyword of a character wasn't saved anymore on some point on X, so at the server startup there's no info in the save file and it's set as the current SERV.TIME. I'm putting that back

**Comment by GitMadKing** [comment]
oh lol. i remembered it was saved once.
i tryed the last build.
confirm working delete in seconds
also confirm CREATE is save in spherechar

**Comment by Jhobean** [comment]
What happen for char without create field? It will fix automatically?

**Comment by cbnolok** [comment]
On the next save it will be saved with create value equal to the serv.time
at the last startup

Il dom 17 mag 2020, 01:28 Jhobean <notifications@github.com> ha scritto:

**Comment by Jhobean** [comment]
Seem ok
