### ISSUE TITLE
Death Status

### ISSUE THREAD

**Issue by xMirroRx** [Sphereserver/Source-X#460]
I think there is an error in the death animation, the screen is not gray.
![unknown](https://user-images.githubusercontent.com/10285831/81331931-fa83c080-90aa-11ea-97d6-976196610100.png)

**Comment by GitMadKing** [comment]
may be a client bug or "feature"
orion client patch have an option to not see gray.
maybe is not sphere,
try another client, watch to not be invulerable, and to be really dead

**Comment by criminalx** [comment]
it is a bug, already reported, also you can't pass through doors
https://github.com/Sphereserver/Source-X/issues/369

**Comment by GitMadKing** [comment]
i can confirm, client 3.0.6j
even if logout and login back, dead, still see in color

however, is a duplicate,
maybe one issue should be closed

**Comment by xMirroRx** [comment]
and at the same time, everything that needs to be done alive can be done even if you are dead.

**Comment by JulianUO** [comment]
I sent a commit a few days after this report, can you check if it's fixed?

**Comment by xMirroRx** [comment]
Good Job. It works fine, the problem is solved.
