### ISSUE TITLE
Throwing Animation

### ISSUE THREAD

**Issue by xMirroRx** [Sphereserver/Source-X#461]
There is a problem with shooting. Return effecti is not applied.

https://i.imgyukle.com/2020/05/05/riFSXY.gif

**Comment by Jhobean** [comment]
How it should suppose to be? Seem Well on video

**Comment by cbnolok** [comment]
Is there a return effect on OSI? And is it there for every weapon type?

**Comment by xMirroRx** [comment]
https://youtu.be/AyOjkKzH7xE?t=100

**Comment by drk84** [comment]
It's only for Gargoyle throwing weapons.

**Comment by Tolokio** [comment]
we could close this?
