### ISSUE TITLE
Combat Elemental Engine

### ISSUE THREAD

**Issue by xMirroRx** [Sphereserver/Source-X#462]
Yeah. I know this is not a sphere problem, but it is a negative situation for those who want to develop a special system.

Unless CombatFlags = 08 // combat_elemental_engine is enabled, values in the status bar cannot be changed.

ResPhysical
Resfire
ResPoison
ResCold
ResEnergy  values should be allowed to change on the display.

**Comment by xwerswoodx** [comment]
Yeah but this is the what Elemental Engine is. If you haven't enabled it, that means your server doesn't send or receive elemental damage packets at all.

**Comment by xMirroRx** [comment]
yes I understand you. I just wanted to report it because I think it might be a negative situation for those who code their system.

Also, commands  resfire, poison etc. can be changed in the background.
for example resfire 10
resfire status shown 10

If this is not effective in the closed state, I think it is okay to show it in the status bar.

or how you want. :)

**Comment by drk84** [comment]
i close this because there is a more recent one #742
