### ISSUE TITLE
Empty LOCAL broken

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#464]
In last release 3293 if set EMPTY value for local generate console error in build 3289 all is OK.

**Script for replicate error:**
```
[function f_local_test]
local.test = 10
SRC.SYSMESSAGE <local.test>
local.test = // <-- This is line of error
SRC.SYSMESSAGE <local.test>
```

**Error Message:**
`12:14:ERROR:(test.scp,23)Undefined keyword 'local.test'`

**Aditional info:**
Seems core clear local but spam message

**Comment by GitMadKing** [comment]
made a test, and also can confirm till 3289 no error, from then any build does gives the error message

**Comment by pentanorl** [comment]
yep, I can confirm too.

**Comment by alexdan2** [comment]
Tested on build: 14 2020 (19:40:03) build 3296

Bug still present

**Comment by Jhobean** [comment]
Seem to make an console error
`09:53:ERROR:(PointsRP.scp,148)Undefined keyword 'LOCAL.bonusxpitem`

**Comment by alexdan2** [comment]
Yes if is empty get this error

**Comment by alexdan2** [comment]
Thx now is fixed :)

Good Work man
