### ISSUE TITLE
Unknown game packet received last build.

### ISSUE THREAD

**Issue by canavar2212** [Sphereserver/Source-X#466]
Unknown game packet (0x49) received.
Unknown game packet (0x1) received.

Client version: 6.0.1.10
Default Script Pack:
SphereServer Version X1-Nightly [WIN64] by www.spherecommunity.net.
Compiled at May 10 2020 (11:01:36) [build 3294 / GIT hash 8863de976ef33013313d66b2fc0492d18cb76a52]

When it takes items unequip the character, it gives bad package warning and the client freezes, 
there is no such problem with other client versions.

**Comment by alexdan2** [comment]
When is happen, is happen when you do a RESYNC ? or "random" ?

**Comment by canavar2212** [comment]
I login the game with the character, then it happens when I unequip item from me.

**Comment by alexdan2** [comment]
Uhmm, i test whit last release (3293) and not happen.
You can tell some other information, like what client use, if use assistant, if use clear comunity script pack ecc,

**Comment by canavar2212** [comment]
no, default client does not patch at all. no problem, I can switch to a different client version.
