### ISSUE TITLE
LOWERREAGENTCOST Not work good (2 Issue)

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#472]
Hello i have Two issue connected on LOWERREAGENTCOST 

.set LOWERREAGENTCOST 10 and LOWERMANACOST 10 to a robe, for now all right:

![image](https://user-images.githubusercontent.com/6176986/81617929-9f253b80-93e6-11ea-8bea-b280012cb0dd.png)

After i equip and check if correct "bonus" placed on char whit item equipped by xshow LOWERMANACOST  and LOWERREAGENTCOST 

![image](https://user-images.githubusercontent.com/6176986/81618015-cbd95300-93e6-11ea-8ef8-d2e2253a739f.png)
![image](https://user-images.githubusercontent.com/6176986/81618053-deec2300-93e6-11ea-868b-5afcca4a5f1c.png)

LOWERREAGENTCOST not set on char when item equipped.

Second issue:
I manual set LOWERREAGENTCOST on a char and for now all ok.

I make two test:
.set LOWERREAGENTCOST 100
Ok i can cast whitout reags.
.set LOWERREAGENTCOST 50
Some time tell me no reags and is ok other time (50% of LOWERREAGENTCOST) try to cast but frizz (call @abort spell trigger)

**Comment by JulianUO** [comment]
Fixed the first issue, will pull it soon.
But I can't replicate the second one (Abort)

**Comment by alexdan2** [comment]
I Confirm Issue 1 fixed. 
For issue 2 i make some accurate test and make a way for reproduce it.

For now i can close issue.
Thx for fix
