### ISSUE TITLE
Region Events

### ISSUE THREAD

**Issue by canavar2212** [Sphereserver/Source-X#473]
only one of the events given to the regions.

```
[AREADEF a_townPapua]
NAME=Papua
GROUP=Papua
P=5729,3209,-1,0
RECT=5639,3095,5831,3318,0
RECT=5831,3237,5851,3267,0
FLAGS=region_flag_nobuilding
EVENTS=r_default,r_default_rock,r_default_water,r_default_tree,r_default_grass,r_papua
```
21:57:Compiled at May 12 2020 (06:15:00) [build 3294 / GIT hash 8863de976ef33013313d66b2fc0492d18cb76a52]

Default script pack

https://imgur.com/Mz5ntW6
output: Papua 'region.events' for 'Admin' is 'r_default'

**Comment by canavar2212** [comment]
I just realized that this is happening in all events. it does not show all events in a separated way in events. shows only the first event received.

output: Admin 'events' for 'Admin' is 'E_STAT'

Eventlist;
EVENTS=E_GENERAL
EVENTS=E_PLAYER
EVENTS=E_RANK
EVENTS=E_STAT

**Comment by criminalx** [comment]
Bug confirmed, I notice sometime ago using .show events only show the first event added

**Comment by alexdan2** [comment]
I make a test whit
.xshow region.events and target my char work correct for me:

![image](https://user-images.githubusercontent.com/6176986/81870731-c90d6800-9576-11ea-9256-467caa5e29b4.png)

**Comment by xwerswoodx** [comment]
I haven't any issue with events, as I just make a script with events 1 week before there was no issue at all, I will check it again but maybe you have another events command that override default function?

**Comment by canavar2212** [comment]
Script pack buradan indirilip kuruldu üzerinde herhangi bir değişiklik yapmadım. Ayrıca ben ne gibi bir değişiklik yaparsam böyle bir soruna sebep olabilir ki?

**Comment by GitMadKing** [comment]
![image](https://user-images.githubusercontent.com/16067766/82152828-3ca7c180-9864-11ea-8df4-d7a2d07fa991.png)
seems working
