### ISSUE TITLE
NEWITEM def,amount,cont doesn't trigger @Equip

### ISSUE THREAD

**Issue by xwerswoodx** [Sphereserver/Source-X#475]
I found out this is a really old core issue, and it can cause server crashes when the item gives stat under @Equip and remove it back under @Unequip trigger because of equipping item without trigger @Equip trigger.

**Comment by JulianUO** [comment]
The format is NEWITEM ItemID, Amount, ContainerUID, (bool)Trigger@Equip

**Comment by xwerswoodx** [comment]
Oh, this is my mistake, I haven't known that there is a boolean for equip.
