### ISSUE TITLE
Packhorse do not follow on portal

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#478]
I don't know if we can modify that but pack horse and pack lama was following us on portal in 55i.

Would be a good feature/fi to implement.

**Comment by GitMadKing** [comment]
Compiled at May 16 2020 (18:33:16) build 3298 / GIT hash 5eee2e7c42bebf2c98e70f7c455d7fc00331ea11

seems working
summoned gates
map tepeport (like papua)
.go commands.

**Comment by Jhobean** [comment]
WOrking when doing it correctly
