### ISSUE TITLE
mysql aexecute

### ISSUE THREAD

**Issue by alexrmrm** [Sphereserver/Source-X#481]
Trying run execute on background, but not work, not make any.

**Comment by xwerswoodx** [comment]
Threads have an known issue that explained here by @Jhobean: https://github.com/Sphereserver/Source-X/issues/484 

So do you try it by restarting server and don't resync it by changing ini file. So if still not working please let us know.

**Comment by alexrmrm** [comment]
I have tried it again and was using it incorrectly. With the example of wikipedia it works.

But, if I want to use it without getting a response, is it not possible?

`[FUNCTION f_test_execute]
DB.AEXECUTE "insert into test (test) values ('execute')"`

**Comment by xwerswoodx** [comment]
What do you mean with response? I haven't used execute command for a long time, i don't remember if it's give response or not. If yes, can you tell me what is the response is.

**Comment by alexrmrm** [comment]
I was using the function incorrectly.

https://wiki.spherecommunity.net/index.php/AEXECUTE
