### ISSUE TITLE
Trigger @Attack

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#482]
Hello, @Attack trigger have problem if i attack someone back to peace and attack again (no longer fire)

**How Riproduce:**
- add my test event e_test_attack 
- Summon a orc
- Attack and see correct response from e_test_attack event @attack fire
- Go in peace mode
- Reattack same npc and @attack no longer fire

**Test event code:**
```
[EVENTS e_test_attack]
ON=@ATTACK
	I.SYSMESSAGE Start attack to <SRC.NAME>
```

**Aditional Info:**
- Tested on last build
- Clear comunity pack script

**Comment by pentanorl** [comment]
Previous builds had this problem too.
It can be annoying cause every time an action is stopped (action=-1), the target is also lost, and it cannot be recovered cause the @Attack won't fire again unless you attack a different target first, even if you toggle war/peace.

**Comment by Jhobean** [comment]
There was modif on attack trigger on this commit recently.
https://github.com/Sphereserver/Source-X/commit/bef98bbb36c7ac21c311f96ca1486eb5a8945de1

Was working before this?

**Comment by pentanorl** [comment]
honestly I don't know... I noticed this issue only recently while debugging other stuff.

**Comment by alexdan2** [comment]
I think this problem in connected to #486 Because lose flags and no trigger attack because no real longer in warmode

**Comment by xwerswoodx** [comment]
Mmm, I need to check but it can be the reason that client doesn't send attack packet without change your target. But for the commit I can tell the commit doesn't changed anything about attack trigger. On the other hand, I need to make some test before telling anything.

**Comment by JulianUO** [comment]
Just sent a PR.
Waiting for approval.
