### ISSUE TITLE
Flag never movable add to item on save

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#483]
Each save my Water through is flagged never movable:
![image](https://user-images.githubusercontent.com/51728381/82591723-c65dd480-9b6d-11ea-8aa8-c3e517105d9b.png)

Xun THink it's maybe these line.

https://github.com/Sphereserver/Source-X/blob/892048b5e39e1df94bdca90a59a3c9d92aeff6ee/src/game/items/CItem.cpp#L842

Something like this may work?
```
    if (IsMovableType())
    {
        if ((IsType(IT_WATER) || Can(CAN_I_WATER)) && !(isattr(ATTR_MOVE_always)) )
        {
            SetAttr(ATTR_MOVE_NEVER);
        }
    }
```

**Comment by xwerswoodx** [comment]
Hmm, we need to know why it fixed as attr_move_never before make any changes because seems like someone did it for some reason.

**Comment by Jhobean** [comment]
Maybe the water barrel??  But if always movable is set, that mean the personnintentionnaly need it be always movable. Ao ita why we can add this restriction?

**Comment by xwerswoodx** [comment]
Yeah, I agree with you but maybe someone did it to make sure some bugs doesn't happening. Because if we  did some changes without thinking it can causes another issues. Maybe some exception can add for attr_move_always but I just need to check why they need to create a function to set waters move_never.

**Comment by Jhobean** [comment]
Yes I understad..I dont have the answer and don't know where find it..  Maybe I have a hint, it's not like this on 56d. So the modification must be on X changelog

**Comment by GitMadKing** [comment]
> Yeah, I agree with you but maybe someone did it to make sure some bugs doesn't happening. Because if we did some changes without thinking it can causes another issues. Maybe some exception can add for attr_move_always but I just need to check why they need to create a function to set waters move_never.

maybe because can be consumed (drinked) if movable?

**Comment by Jhobean** [comment]
I found the Commit adding this line: https://github.com/Sphereserver/Source-X/commit/c41f0a1e3467e63840a25e352bc5f2f18e6cf3e8

And the issue link to it https://github.com/Sphereserver/Source-X/issues/195

I can't find the "Logic reason" to add this nevermovable flag...
