### ISSUE TITLE
Profiler stop working when resync the ini File

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#484]
When we change any setting in the ini file and resync the serverm the profiler do not work anymore....
![image](https://user-images.githubusercontent.com/51728381/82707067-4b69ec00-9c49-11ea-828d-f33554347fcf.png)

I have all the function details but the last 10 sec is desactivate. Need to reboot to fix.

**Comment by Jhobean** [comment]
I can reproduce it when you inactive profiler in the ini
// EF_Script_Profiler			00000400

And you reactivate it.

It's not what i'm doing when when it crash but it's the same problem (All timer to 0 and all the function history)

**Comment by Jhobean** [comment]
Just updated the issue because I found how to "crash" the profiler. Juste resync a modif in the ini.

**Comment by cbnolok** [comment]
Is this still an issue?

**Comment by Jhobean** [comment]
Yes

**Comment by xwerswoodx** [comment]
The issue is not Resync, the issue is you haven't enabled profiler in sphere.ini, there is a Profile=0 property and EF flag for profiler, but seems like when server first start profiler ignore sphere.ini settings and enable it from the beginning, but when you resync sphere.ini Profile=0 value readn and set your Profiles: OFF which you can see at the top of the profiler.

**Comment by Jhobean** [comment]
Hooo  Well see!!!
THX

**Comment by Jhobean** [comment]
I tested it well and it's not work.
If you resync the server with no modif in ini it's work.

If you resync the ini with a modification, profiler do not work anymore.

**Comment by xwerswoodx** [comment]
Do you have Profile=1 because it seems working fine for me

**Comment by Jhobean** [comment]
![image](https://github.com/Sphereserver/Source-X/assets/51728381/be2fe7d3-dc7e-4381-a567-ef7506cb09a5)

Yes it's activate. At the moment you modify something in ini and resync, profiler crash.

**Comment by xwerswoodx** [comment]
You get me wrong, this is not a profiler, EF_Script_Profiler is activates the Script part of the profiler which is 

![image](https://github.com/Sphereserver/Source-X/assets/6155640/04e91015-9dcc-41fb-b61a-92ed2672b4af)

This is the script profiler

But the real profiler is;

![image](https://github.com/Sphereserver/Source-X/assets/6155640/71581102-a2ac-4d4a-8b95-69f4dcc34046)

This option.

**Comment by Jhobean** [comment]
Hooo man.. its really clear!!! We should add a N.B on ini file that they work together😂

Thx!
