### ISSUE TITLE
WarMode flags autoreset when kill a char

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#486]
Hello, i have bug in WarMode flags, he automatic reset to OFF when my target die.

**How Reproduce:**
- Set WarMode 
- See flags and have correct 020 enabled
- Add a Orc or other mobs
- Attack and kill it
- When mob die Flags back to 00. 

**Additional Info:**
- Tested on last build 3299 
- Tested on clear Comunity script Pack

EDIT: I think this bug cause also this issue: #482

**Comment by JulianUO** [comment]
Just sent a PR.
Waiting for approval.
