### ISSUE TITLE
Kills and Deaths Counts

### ISSUE THREAD

**Issue by canavar2212** [Sphereserver/Source-X#487]
hello I want to add multiple kills and deaths count system on the server. for example, I want to separate it as KILLS, KILLSNPC and KILLSPLAYER. KILLSPLAYER is running, but the reason I added KILLSNPC NOT WORKING WHAT HAPPENS?

Murder Kills;
`
case CPC_KILLS:
sVal.FormatVal( m_wMurders );
return true;
`
`case CPC_KILLS:
			m_wMurders = (word)(s.GetArgVal());
			pChar->NotoSave_Update();
			return true;
`
in r_WriteChar

`if ( m_wMurders )
		s.WriteKeyVal("KILLS", m_wMurders);
`

in CworldImport 
IMPFLAGS_CHARS
`
			else if ( s.IsKey("KILLS" ) && pChar->m_pPlayer )
			{
				pChar->m_pPlayer->m_wMurders = (word)(atoi(pArg));
			}
`

in CcharPlayer_Props.tbl

`
ADD(KILLS,			"KILLS")
`

in CcharPlayer
```
	m_wDeaths = m_wMurders = 0;
	m_wDeathsNPC = m_wMurdersNPC = 0;
	m_wDeathsPlayer = m_wMurdersPlayer = 0;
```

it works when I add the same for KILLSPLAYER but not when I add it for KILLSNPC.

**Comment by canavar2212** [comment]
No problem when I do the same for deaths.

DEATHS, DEATHSPLAYER, DEATHSNPC

the problem only occurs when adding KILLSNPC.

console output ;

`22:36:ERROR:Undefined keyword 'killsnpc'`

**Comment by xwerswoodx** [comment]
In CCharPlayer_Props.tbl you need to make sure the it's sorted in alphabetically, if not it doesn't see the command.

**Comment by canavar2212** [comment]
Evet, alfabetik sıraya göre yapınca sorun çözüldü. Teşekkür ederim.
