### ISSUE TITLE
Can't see items tooltips in bank or bag of offline players as GM

### ISSUE THREAD

**Issue by Novocaine85** [Sphereserver/Source-X#490]
Hello,

while using a GM account i can't see the tooltips of a player while is offline with allshow.

how to reproduce:

create a gm account and a player account
log player account and put some items on his bag and his bank. logout this account.
log gm account, search for the player with allshow on and open his bank with xbank or his backpack.
hover items with mouse. Tooltips are not shown.

Client 7.0.20.0

thanks

**Comment by Jhobean** [comment]
Have the same bug... It's strange and don't know why

**Comment by Jhobean** [comment]
FIX. Can be close

**Comment by alexdan2** [comment]
Yep i confirm, last release work good
