### ISSUE TITLE
.info updates own skillgump as GM

### ISSUE THREAD

**Issue by Novocaine85** [Sphereserver/Source-X#491]
While using a gm account, if I do .info on a target (player or npc) my skillgump updates with the skills of the target.

check video example (zipped) below
[spherebug.zip](https://github.com/Sphereserver/Source-X/files/4801606/spherebug.zip)

thanks

**Comment by JulianUO** [comment]
This is not a bug, it exists since 55i.
It is an easy way to check other people skills.

**Comment by Novocaine85** [comment]
I have been GM on 56b and 56d and I never notice this. However, no problem.
Thank you :)

Il Dom 21 Giu 2020, 17:23 JulianUO <notifications@github.com> ha scritto:
