### ISSUE TITLE
CMS system to sphere account transfer without MD5. New system salt+MD5

### ISSUE THREAD

**Issue by arbayhacun** [Sphereserver/Source-X#493]
Hello;
Near all new CMS portals (Joomla, Wordpress, etc..) is not using md5. New password hash system is "salt+md5" or "blowfish" or "bcrypt". Im not sure the new system name or type. 

For example MD5 Password : (its accept old cms system and all sphere)
PASSWORD=ba8000f6942f76c3f6be52afef212341

For example new hashed password : (its not accepting sphere)
PASSWORD=$2y$10$U1S8bImMU2RzeSLxstlewuRcJM.vS4HN4SlnJ1qjuktike.0pNKm2

Is it possible Sphere accept the new password? Thanks.

**Comment by GitMadKing** [comment]
as said on discord:
had already been added all tools to do this with issue #109 
```
	IF ( <DB.connected> )
		DB.QUERY "SELECT `id`,`password` FROM `jos_users` WHERE `username`='<LOCAL.Account>' AND `block`='0'"
		IF (<EVAL <DB.ROW.NUMROWS>> > 0)
			IF (<EVAL <DB.ROW.NUMROWS>> < 2)
				LOCAL.CHECKPASS = <BCRYPTVALIDATE <LOCAL.Password>, <DB.ROW.0.password>>
```
