### ISSUE TITLE
Show error on console and it's not an error

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#498]
When I use these command: https://github.com/Sphereserver/Source-X/blob/bb9341d0b7cd0f6b740625f169dc5a416cb5a4a9/Changelog-X1-Nightlies.txt#L876

AddShip
DelShip
GetShipPos
MaxShips

```
13:59:ERROR:(Bateau.scp,59)Undefined keyword 'AddShip'
13:59:ERROR:(Bateau.scp,60)Undefined keyword 'DelShip'
```
If I type .maxships 6 with my GM I have a warning message that do not exist but its work...

![image](https://user-images.githubusercontent.com/51728381/88485969-4f1b3700-cf48-11ea-9844-c29b380e3db6.png)

**Comment by Jhobean** [comment]
Message came from here: https://github.com/Sphereserver/Source-X/blob/5b707b7fb1f63af0ddb9be4e1976e64b7e11483c/src/game/clients/CClientEvent.cpp#L1034

The 4 commands should be add on a librairi or something?

**Comment by youhide** [comment]
using light command is firing error 
Can't resolve <light>

**Comment by Jhobean** [comment]
Fix in these commits:  https://github.com/Sphereserver/Source-X/commit/3a90d798bd7a32b5ef45c6337a14d7f673017d8e 9ac3dd550135578c54fe305f6d6420b0fdbb5628
