### ISSUE TITLE
Cant create areas in the new maps (ilshenar, ter mur, etc)

### ISSUE THREAD

**Issue by RodVIII** [Sphereserver/Source-X#499]
AREADEF do not work on new maps. I just tested with the latest sphere 56d and it works fine in there.

[AREADEF a_TheTradingPost]
NAME=The Trading Post
P=1107,405,-80,2
RECT=1088,384,1125,422,2
GROUP=Trading Post
FLAGS=region_flag_nobuilding|region_antimagic_gate|region_antimagic_recall_out|region_flag_insta_logout|region_flag_safe

**Comment by cbnolok** [comment]
Do you mean that it works only for map 0? Does it create an area on the wrong map (0 instead of 2) or doesn't it create it at all?

**Comment by RodVIII** [comment]
Yes. I can only make areas on map0. Maybe map1 too, but not on the rest.

**Comment by Jhobean** [comment]
Seem to work.  Look picture 
Left before fix, Right After
![image](https://user-images.githubusercontent.com/51728381/93693079-1079a700-fac9-11ea-828a-6b173c6e0d2e.png)


```
[AREADEF a_twisted_weald]
NAME=Twisted Weald
```
