### ISSUE TITLE
Weightreduction add bug to calculate the weight of a container

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#500]
When adding weightreduction to a container it work until we use some item inside it.

Exemple:
I_bag with weight reduction of 50%.

We add 1000 arrow on the bag:
If you have an arrow with weight 0.1, and you want to reduce the weight by 50%
On the core 0.1 = 1

When you place the arrow on the bag, the bag weight is 1000*1*50% so it's 500 (50.0).  At this time it work well.

WHen you use your arrow one by one with your bow, the core calculate the weight not correctly.

50 - (1*50%)
50 -  (0.5)

Since the core can not take the float, the weight of the bag increase...

Maybe what it can be do is:
If weightreduction is activate on a container, instead of modify the weight by doing a substraction of the item removed, we can recalculate the total weight.

**Comment by drk84** [comment]
Closed, because the solution is to implement decimal weight proposed in issue #733.
