### ISSUE TITLE
Invisible GMs don't see other invisible GMs

### ISSUE THREAD

**Issue by orishi** [Sphereserver/Source-X#506]
1) Invisible GMs don't see other invisible GMs - basically same plevel should always see each other, that's a bug on X

2) I would love to make it so that all plevels higher than 1 see each other while invisible. Could you add this option to sphere.ini?

**Comment by Jhobean** [comment]
Here the Pull Request: https://github.com/Sphereserver/Source-X/pull/522

**Comment by orishi** [comment]
Perfect, works as I need it. Thanks.

**Comment by orishi** [comment]
When you use CanSeeSamePLevel=4 and Player with plevel 1 logs out of game, he can still be seen by GMs. However when player with plevel 4 or higher logs out, he disappears just fine.

When setting this ini to 0, everything works like it used to.

**Comment by Jhobean** [comment]
Do you have allshow active?

**Comment by Jhobean** [comment]
Yes there other bug too...  2 plevel 0 can see each other when they are hide:smile: i'll fix this soon

**Comment by Jhobean** [comment]
I push a Fix for the bug with Plevel 0.  @orishi ABout your Plevel1 bug, I'm not able reproduce it. If you see loged out player it's because you have allshow active or because you have linger time on logout.

**Comment by orishi** [comment]
It was ClientLinger, I didn't realize I have it set up for 300 instead of 0. It's not used for GM accounts.
