### ISSUE TITLE
Timerf Function sometime make server crash

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#516]
We are experimenting some Random crash on the shard with always this debug:
```
20:39:DEBUG:(81084)          T_Main |  2 |        CTimedFunctionHandler::OnTick | +3  
20:39:DEBUG:(81084)          T_Main |  3 |                    CSFileText::Close | +14184  
20:39:DEBUG:(81084)          T_Main |  4 |                   CSFileText::_Close | +0 <-- last function call (stack unwinding began here)
20:39:CRITICAL:"Access Violation" (0x20865f514), in ExcType=CSError catched in SUB: CWorldTicker::Tick::TimerF() ("CTimedFunctionHandler")
```
The probleme seem to appear here: 
https://github.com/Sphereserver/Source-X/blob/9ec6ab211e0df542ffd0088d06788f1454dfd615/src/game/CTimedFunctionHandler.cpp#L58
After executing the timerf function, the script erase the timerf function on the VECTOR and put a new value of iterator on IT

At the end of the For loop, the core evaluate if he must continue by doing this check: `it != m_timedFunctions[tick].end()`: 
It's where the crash appear.
![image](https://user-images.githubusercontent.com/51728381/95679112-aec7cc80-0b9e-11eb-95ee-7281512288fa.png)

Core is not able to compare the iterator with the vector and cause a fatal error closing the server.

Here the theory why it's happen:

I have a function initiate a custom spell
```
[FUNCTION Dendroid]
IF (<SRC.CTAG0.cooldowndendroid>==1)
  SRC.MESSAGE Vous devez encore attendre <eval <SRC.ISTIMERF.ctag.cooldowndendroid=>> secondes avant d'utiliser cette habileté
  RETURN 1
ENDIF

SRC.targetf f_spelldruide
```
```
[FUNCTION f_spelldruide]

IF !(<ARGO.ISCHAR>)
	src.messagerouge Vous devez choisir un être vivant.
	return 1
ENDIF

IF (<ARGO.CANSEELOS>)
	EVENTS +e_castappel
	findlayer(1).unequip
	findlayer(2).unequip

		ctag.cooldowndendroid=1
		timerf 20,ctag.cooldowndendroid=
	    src.mana=<src.mana>+-25
        src.say Vas Plan Por
		ctag.targetdendroid=<ARGO.UID>
		TIMERF 3,f_dendroid

ELSE 
    SYSMESSAGE La cible est hors de porte
    RETURN 1 
endif
RETURN 1
```
The function F_dendroid just make appear a NPC and DMg the target
```
[FUNCTION f_dendroid]
ref1=<ctag.targetdendroid>

ref1.DMG_FIXED = (20+(<tag0.sumdendroid>/25)-(<ref1.tag0.resistanceenergie>/10)), <uid>
ref1.EFFECT=3,i_fx_smoke,2,25,2

	serv.newnpc=c_dendroid0
new.p=<ref1.p>
EVENTS -e_castappel
RETURN 1
```

THE PROBLEME IS HERE! On the events e_castappel. This event is usefull because if someone hit you during your incantation, you Miss your spell and the retarded effect is cancel

```
[EVENTS e_castappel] 
on=@gethit 
trysrc <uid> message Vous ratez votre incantation.
i.EFFECT=3,i_fx_smoke_small,6,30,1 
i.EVENTS -e_castappel
i.SFX=005c 
i.timerf stop,f_dendroid //Cancel l'exécution des spell
i.timerf stop,ctag.cooldowndendroid=
i.ctag.cooldowndendroid=
RETURN 0 
```

SOMETIME when player Get hit at the same time he casting the spell, the Vector is glitched and the comparaison crash.

**Comment by xwerswoodx** [comment]
I haven't get what are you trying to do here;
`i.timerf stop,ctag.cooldowndendroid=`
Maybe that line causes the issue? I haven't tried to stop clearing ctag with timerf (I have no idea why you did it totally) and it needs function to stop and ctag is variable so it can causes some issues

**Comment by xwerswoodx** [comment]
I don't know if it's issue or not, but i haven't tried to timerf on ctag so, maybe player leave game after ctag set and the tag variable removed from sphere storage directly, so maybe that causes timerf to can't find ctag variable unique id and stop it, and it can causes the server crash.

**Comment by Jhobean** [comment]
No, its not because ctag was remove on logout. On the example, ctag is create at beginning of spell cast and remove after.

**Comment by xwerswoodx** [comment]
Okay after read your explain to understand the issue better, I thought what about to move "EVENTS +e_castappel" line under "TIMERF 3,f_dendroid" so with this way, all the timerf vectors will be already setted when you get the event, so gethit doesn't cause crashes. This is also theory, but this is still issue that need to be fixed, but by this way you can do some more test so this can help us to understand the issue better.
