### ISSUE TITLE
[PORT] a622737b2be9495d264091d7632af4987bfbfcfd , Fixed: Boat/ship parts resetting TYPE after use 'turn' commands.

### ISSUE THREAD

**Issue by fjgo86** [Sphereserver/Source-X#52]
https://github.com/Sphereserver/Source/commit/a622737b2be9495d264091d7632af4987bfbfcfd

**Comment by nefthon** [comment]
I was thinking if it would be better to Copy the item on the old ship in case there are custom tags or properties.
