### ISSUE TITLE
Custom Multi

### ISSUE THREAD

**Issue by Alfa2k20** [Sphereserver/Source-X#520]
I cannot place a custom multi and house components dont appear
ERROR:Undefined symbol '' ['ei_house_component']
ERROR:Undefined symbol '' ['ei_house_door']

**Comment by Jhobean** [comment]
I think it,s 2 differents BUG
1- Multi no able to place it
What is the multi you talk about?

2- Error
This error is generate because each house you generate the core add this event.  Simply add these to line on your script:
```
[TYPEDEF ei_house_door]
//Nothing
[TYPEDEF ei_house_component]
//Nothing
```

**Comment by Alfa2k20** [comment]
small house and another variant here script:

[MULTIDEF m_stone_and_plaster_house_fence]
ID=064
DEFNAME=m_stone_and_plaster_house_fence
NAME=Stone and plaster house with iron fence
NAMELOC=1011303 //Stone and plaster house
TYPE=t_multi
VALUE=36750
REGIONFLAGS=region_flag_nobuilding|region_antimagic_teleport
TSPEECH=spk_house_cmds
CATEGORY=Multis
SUBSECTION=Houses
DESCRIPTION=Stone and Plaster House
MULTIREGION=-3,-3,7,7
COMPONENT=06a5,0,3,7 // wooden door
COMPONENT=i_sign_brass_2,2,4,5
COMPONENT=2081=-2,3,0,0
COMPONENT=2081=-2,4,0,0
COMPONENT=2081=4,2,0,0
COMPONENT=2081=4,3,0,0
COMPONENT=2081=4,4,0,0
COMPONENT=2082=4,5,0,0
COMPONENT=2083=3,5,0,0
COMPONENT=2083=0,5,0,0
COMPONENT=2081=-2,5,0,0
COMPONENT=2083=-1,5,0,0
COMPONENT=2084=1,5,0,0
COMPONENT=2086=2,5,0,0
COMPONENT=2081=-2,2,0,0

**Comment by Jhobean** [comment]
I think it's link to this bug https://github.com/Sphereserver/Source-X/issues/492

When the core create your custom multi on boot. There an assigned ID over 0x1f41(8001). So when you add it you have a signle Gold piece.

What you can do for now  is use the normal plaster house and add the component int the multi

```
[MULTIDEF 064]
DEFNAME=m_stone_and_plaster_house
```

By the way I dont know if create a Multi like you did ID=064 it's working...  Normally I think you should create it on Fiddler but i'm not sure.

**Comment by xwerswoodx** [comment]
ID inside multidef doesn't give the 064's multi, 064 is an item, that will be the main item of your multi. So 064 is just a wall. If you want to use multi as ID you need to give multi id;

```
[MULTIDEF m_stone_and_plaster_house_fence]
ID=m_stone_and_plaster_house
DEFNAME=m_stone_and_plaster_house_fence
NAME=Stone and plaster house with iron fence
NAMELOC=1011303 //Stone and plaster house
TYPE=t_multi
VALUE=36750
REGIONFLAGS=region_flag_nobuilding|region_antimagic_teleport
TSPEECH=spk_house_cmds
CATEGORY=Multis
SUBSECTION=Houses
DESCRIPTION=Stone and Plaster House
MULTIREGION=-3,-3,7,7
COMPONENT=06a5,0,3,7 // wooden door
COMPONENT=i_sign_brass_2,2,4,5
COMPONENT=2081=-2,3,0,0
COMPONENT=2081=-2,4,0,0
COMPONENT=2081=4,2,0,0
COMPONENT=2081=4,3,0,0
COMPONENT=2081=4,4,0,0
COMPONENT=2082=4,5,0,0
COMPONENT=2083=3,5,0,0
COMPONENT=2083=0,5,0,0
COMPONENT=2081=-2,5,0,0
COMPONENT=2083=-1,5,0,0
COMPONENT=2084=1,5,0,0
COMPONENT=2086=2,5,0,0
COMPONENT=2081=-2,2,0,0
```
solve your issue.

**Comment by Soulless-1** [comment]
closing this issue out since it's purely script related.
