### ISSUE TITLE
Read file line

### ISSUE THREAD

**Issue by Alfa2k20** [Sphereserver/Source-X#521]
can show lines count but no read
ps.: OF_FileCommands is active
File contains 24 line(s)
ERROR:File I/O "CSFile::GetPosition" failed on file "" (9): Bad file descriptor

**Comment by Jhobean** [comment]
Please provide your script and your file. We can't help you if we are not able to reproduce it.

**Comment by Alfa2k20** [comment]
I am testing in linux, but the  scripts works on sphere for windows

[FUNCTION F_READ_FILE]
LOCAL.FILENAME = scripts/custom/teste.txt

IF (<FILE.FILEEXIST <LOCAL.FILENAME>>)
   FILE.MODE.APPEND=0
   FILE.MODE.CREATE=0
   FILE.MODE.WRITEFLAG = 0
   FILE.MODE.CREATEFLAG = 0
   FILE.MODE.READLFLAG=1
   IF (<FILE.OPEN <LOCAL.FILENAME>>)
      LOCAL.I = <FILE.FILELINES <LOCAL.FILENAME>>
      SERV.LOG File contains <DLOCAL.I> line(s)  
      FOR R 1 <DLOCAL.I>>
         SERV.LOG <DLOCAL.R> '<FILE.READLINE <DLOCAL.R>>'
      ENDFOR
      FILE.CLOSE
   ELSE
      SERV.LOG I cannot open file <LOCAL.FILENAME>
   ENDIF
ELSE
   SERV.LOG FILE <LOCAL.FILENAME> NOT FOUND
ENDIF

**Comment by cbnolok** [comment]
What's the line causing the error?

**Comment by Nirad** [comment]
Work for me on windows and osx. i don't currently have a linux vm seems OS releted. @Alfa2k20 does the line ending(encoding) was the same ?

**Comment by cbnolok** [comment]
I tested it with a file with two lines of random text under Ubuntu and it works. Can we have the txt file you used to replicate the error?
