### ISSUE TITLE
Xcontrol command Make own body teleport FAR away

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#523]
This function: https://github.com/Sphereserver/Source-X/blob/f59514b38b1ec25c3ee3e121d3db6000cf4a3ea1/src/game/clients/CClientTarg.cpp#L146

When you control someone else, your old body go away and the only way to find it is by doing .goname yourname

**Comment by drk84** [comment]
When you use .control the npc AI will take control of your previous body, that's why it starts to walk around.

**Comment by Jhobean** [comment]
@drk84 and its normal??   Dont think so..  personnaly my body is teleported on star chamber...

**Comment by drk84** [comment]
Is it possible that when you create a character in your shard the HOME location of new player is the star chamber? If i remember well npcs that wanders too far get teleported back to their home location

**Comment by Jhobean** [comment]
Probably but it dont do that on 55i/56d it why I tought it's an issue

**Comment by Jhobean** [comment]
Ok I found something...  When your Corpse take the brain of NPC, the home point is now the Player Home point (The city you choose on character creation)... So it's normal you are too far of spawn point.. So you are ported to the HOME
