### ISSUE TITLE
coloring for hidden players

### ISSUE THREAD

**Issue by meaowR** [Sphereserver/Source-X#525]
if i change colors
```
ColorInvis=04001            // 04001 = transparent color, 0 = default
ColorInvisSpell=04001        // 04001 = transparent color, 0 = default (This one is for s_invisibility spell, this includes the invis potion.)
ColorHidden=04001          // 04001 = transparent color, 0 = default
```
in .ini it looks like coloring my body only :slight_smile:
![map](https://user-images.githubusercontent.com/61579076/97791546-7f780e80-1be4-11eb-82ab-f13aeda869da.jpg)

**Comment by Jhobean** [comment]
Made some test, bug occur on these 2:
ColorInvisSpell=04001
ColorHidden=04001

The first one is correct

**Comment by Jhobean** [comment]
Ok some more info about this bug.

- Paperdoll skin or item should never change.
- Item on the anim should get the Hue selected in the ini setting.

**Comment by Jhobean** [comment]
Fix Merge Need feedback
