### ISSUE TITLE
Wall of Stone

### ISSUE THREAD

**Issue by Leodinas** [Sphereserver/Source-X#526]
@spelleffect 
if (<argn> = 24) //does not trigger the stone wall spell

endif

**Comment by GitMadKing** [comment]
spelleffect should truggee on the player being under (IF) the wall when createdMarius ---- On lun, 02 nov 2020 03:22:27 +0100  notifications@github.com  wrote ----
@spelleffect
if ( = 24) //does not trigger the stone wall spell
endif

**Comment by Leodinas** [comment]
https://media.discordapp.net/attachments/476635430821953567/772647707986100254/unknown.png

not trigger

**Comment by GitMadKing** [comment]
i think is not triggering because the missing piece.should be a way to create item even over player, and then remove itMarius ---- On lun, 02 nov 2020 07:38:18 +0100  notifications@github.com  wrote ----
https://media.discordapp.net/attachments/476635430821953567/772647707986100254/unknown.png
not trigger

**Comment by Leodinas** [comment]
It is deleted when it is touched!
I hope it can be triggered when touched

**Comment by cbnolok** [comment]
Please explain the problem more clearly, i can't understand it. Also, the script you pasted is incomplete and it isn't useful to understand your problem.

**Comment by Jhobean** [comment]
What I understand, it's when he cast stonewall on the head of someone 1 of the wall item do not appear because the player is there.

He want the trigger spelleffect appear.

**Comment by Leodinas** [comment]
yes
Stone wall spells can also be triggered by @spelleeffect

**Comment by Leodinas** [comment]
nice 
yes! It's done. Thank you very much!
