### ISSUE TITLE
RANGE - for bows and crossbows

### ISSUE THREAD

**Issue by golfincz** [Sphereserver/Source-X#528]
RANGEH and RANGEL are poorly displayed for bows and crossbows. RangeH shows 1 and RangeL 0.

**Comment by Jhobean** [comment]
The bug occur there: https://github.com/Sphereserver/Source-X/blob/a04e0329f452802be25ef77f804ad9c6ba0f507f/src/game/components/CCPropsItemWeapon.cpp#L74

_uiRange is always 0

**Comment by Jhobean** [comment]
I added THis
https://github.com/Jhobean/Source-X/blob/5c63d4e7a4771fe58aad8222943ae8da4c9e0287/src/game/components/CCPropsItemWeapon.cpp#L97-L101

and it's work...  I don't know how. I just copied the range setting 10 line under..

Maybe @fjgo86, @cbnolok or @coruja747  may have the explanation.

**Comment by cbnolok** [comment]
As far as i am concerned, it looks right to me, why should that be a problem?

**Comment by cbnolok** [comment]
Oh well i misread, of course before reading that value, you are setting range via scripts, is that right?

**Comment by golfincz** [comment]
Yes according to the script. And especially firearms need to have a range that is different for crossbows and different for bows (It is very individual for each weapon). And the scripted own combat system then calculates the damage, among other things, according to the extent of the weapon.

**Comment by xwerswoodx** [comment]
I can agree that bug happened to me after i updated my sphere to latest one, but i haven't updated it for a while so i have no idea which version I used last. I tried the rangeh and l before updating and they had no problem after i updated latest version and it starts return high as 1 and 0 as low

**Comment by Jhobean** [comment]
Ok I confirm the bug appear here https://github.com/Sphereserver/Source-X/commit/a04e0329f452802be25ef77f804ad9c6ba0f507f?branch=a04e0329f452802be25ef77f804ad9c6ba0f507f&diff=split
