### ISSUE TITLE
ship list is wiped on server reboot

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#530]
Before reboot I have a boat and when I do .showship I have 04001cf7b 
![image](https://user-images.githubusercontent.com/51728381/98321767-e23a2300-1fb3-11eb-9f04-4c6139eb4ba2.png)

After a save and a reboot, my ship list is empty and do not exist

![image](https://user-images.githubusercontent.com/51728381/98321882-20cfdd80-1fb4-11eb-9b15-be27061d05a6.png)

EDIT: The ship list is not wipped if there a UID on it. The ship list just Wiped if there no UID on it (on server reboot). That cause if you try to read the list , it do not exist.....  List should be alway there for player even if it's empty

**Comment by xwerswoodx** [comment]
I checked it now, I created ship and used .show ships and then .show ship get values correctly, then I saved and restart sphere then i used same commands and I have no issue at all. Do you have tillerman on your ship? Because some of your ship parts seems missing. If the ship has no tillerman it directly removed on save.

**Comment by Jhobean** [comment]
Thx for testing, Yes I have tillerman, i just removed the plank :-).  I'll make some test again...
Maybe it's script side, ill test with blank script pack.

**Comment by xwerswoodx** [comment]
What is the result? If it's still continue, can you tell me the path to follow? I can try it by your way also, if there is a issue we could take care of it.

**Comment by Jhobean** [comment]
Did not have time but the ship uid is add on the list with addship command

**Comment by Jhobean** [comment]
I do something like this
```
	       serv.newitem m_gargoyle_ship_n		
		new.p= <SRC.TARGP>
		new.more1 <src>
		new.MULTICREATE
		new.tag.maxhits=1000  //Todo, prendre en compte l'amélioration du blindage
		src.addship <new.uid>
```

**Comment by xwerswoodx** [comment]
I see, but the problem is not from list, I made some tests and I see the user created multis doesn't count as ship directly so it doesn't added on list, so when you add list, at the reboot server seems like doesn't see it as multi and remove it from the list.

**Comment by Jhobean** [comment]
Ok I found the problem but not able to fix IT:
```
1- Start the server and connect with a player without ship
2- Do .show ship (you will get an error this command do not exist)
3- generate a ship
4- Do  .show ship (you will get your ship UID)
5- Shrink your boat
6- Do  .show ship (you will get 0) 
```
This cause lot of error on console when I use "ship" verification and player do not have ship

**Comment by Tolokio** [comment]
if <ship.isvalid> gives error as well?

**Comment by Soulless-1** [comment]
for me i added a ship, i saved, restarted. and its still in my list
![image](https://github.com/Sphereserver/Source-X/assets/17236327/9c055181-3462-48c5-aa1c-f2e864849c33)
![image](https://github.com/Sphereserver/Source-X/assets/17236327/2bba1dd8-6442-453c-9c7a-29a7ba091f3f)

![image](https://github.com/Sphereserver/Source-X/assets/17236327/442968f0-c5ef-4f0e-aea9-884ae6588c01)
![image](https://github.com/Sphereserver/Source-X/assets/17236327/2ccdec3d-7222-4276-ba81-a6d642d64d84)
![image](https://github.com/Sphereserver/Source-X/assets/17236327/1482f6ca-5795-4c0e-8e67-76c195736684)

**Comment by xwerswoodx** [comment]
I remember when it firstly released houses and ships had some issues of loading but it can be fixed in time, seems like working for me too, let he Jhobean check it, if still exists we can take a look.

**Comment by Jhobean** [comment]
simply do .show ship with your GM and be certain to DONT have a ship.
![image](https://github.com/Sphereserver/Source-X/assets/51728381/ac4c2ddb-78ed-4ef1-a9fa-27d032338eb4)

You'll get an invalid command but this command exist.

This "bug" cause if I use .ship in my script I have lot of warning.
```
[function test5]
if <ship>
   serv.log I have ate least one ship
else
   serv.log I dont have ship
endif
```

If I create a ship and delete it, it will work until reboot. Look like Ship list do not exist until you need it.

**Comment by xwerswoodx** [comment]
Honestly I did it couple of mins before, I created ship and used .show ship command and show my ship uid there. Use .save then restart server and used .show ship command and show my ship exactly. And fornthe script it should be <ship.isvalid> for checks

**Comment by Jhobean** [comment]
Bug is when you DONT have ship and never had one since the reboot.

```
if <ship.0.isvalid>  // or <ship.isvalid>
   serv.log I have ate least one ship
else
   serv.log I dont have ship
endif
```

![image](https://github.com/Sphereserver/Source-X/assets/51728381/7680d227-a5ca-4966-a30b-f24772b3339d)

**Comment by xwerswoodx** [comment]
> Bug is when you DONT have ship and never had one since the reboot.
> 
> ```
> if <ship.0.isvalid>  // or <ship.isvalid>
>    serv.log I have ate least one ship
> else
>    serv.log I dont have ship
> endif
> ```
> 
> ![image](https://user-images.githubusercontent.com/51728381/275216005-7680d227-a5ca-4966-a30b-f24772b3339d.png)
> 
> .ship should alwasy return a number like 0,1,2,3,4,5,6, ?

Ohh, I get you now, but probably you meant "SHIPS" command not the ship. SHIPS give the amount of the ship you have, SHIP.n give the ship uid at index.

**Comment by Jhobean** [comment]
Ho man.  Sometimes i'm so dump😂

True Ship and ships are different.
