### ISSUE TITLE
TAGAT functions for account tags

### ISSUE THREAD

**Issue by orishi** [Sphereserver/Source-X#531]
Request to add functions for account.tag similar to character/item tags.

TAGAT.index | R | Gets a TAG at the given zero-based index.
TAGAT.index.KEY | R | Gets the name of the TAG at the given zero-based index.
TAGAT.index.VAL | R | Gets the value of the TAG at the given zero-based index.
TAGLIST | W | Outputs a list of the object's TAGs.

**Comment by xwerswoodx** [comment]
Just for note, TAGLIST already exists for accounts

**Comment by alexdan2** [comment]
Tested and work good.

I used this way for test and perfect:

```
[FUNCTION f_add_account_tag]
SRC.ACCOUNT.TAG.HELLO1 = 1
SRC.ACCOUNT.TAG.HELLO2 = 1
SRC.ACCOUNT.TAG.HELP = 1

[FUNCTION f_add_account_tag_list]
SERV.LOG Account TAGCOUNT: <SRC.ACCOUNT.TAGCOUNT>
FOR 0 <EVAL <SRC.ACCOUNT.TAGCOUNT> -1>
	SERV.LOG TAG NAME: <SRC.ACCOUNT.TAGAT.<DLOCAL._FOR>.KEY> 
	SERV.LOG TAG VALUE: <SRC.ACCOUNT.TAGAT.<DLOCAL._FOR>.VAL> 
	SERV.LOG ----------------
ENDFOR
```
