### ISSUE TITLE
Skill Wrestling

### ISSUE THREAD

**Issue by xMirroRx** [Sphereserver/Source-X#533]
Wrestling skill doesn't work properly.
It is constantly in motion, but has no effect.
Animation sounds are also not available.

**Comment by Jhobean** [comment]
Please give more detail.

![image](https://user-images.githubusercontent.com/51728381/98544678-54379400-2262-11eb-9018-c7f2752c7b4e.png)

With last core and Xscript pack seem Ok on my side.

**Comment by xMirroRx** [comment]
my build number ![image](https://user-images.githubusercontent.com/10285831/98547565-6f79c200-22a9-11eb-8cb9-78080cf7c2b5.png)

 I am using the last scp pack available here.
https://forum.spherecommunity.net/sshare.php?srt=4

It just seems to be swinging a fist and the damage does not affect the opponent in any way. and animation sounds are not heard at all. only missed sounds are available.

**Comment by xMirroRx** [comment]
I'm sorry it's my fault. I turned off the main character damage so it was not doing damage and there was no hitting sounds.
Works fine, the hood can be turned off.
