### ISSUE TITLE
"Server Tick" change when server booted since long time

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#538]
The "tick" of the server seem to change when the server is boot since a certain time
I tought it was linked to the NPC_ai increase and sector sleep but this bug was fixed and don't change our bug... I need a reboot after few days again.

I continue to see some **small** "lag" when server is up for a certain time. THis lag is headhache for caster...
For exemple, when I port with my spell there is a little anim of smoke. When the server is fresh reboot smoke appear instant when I change position.  After some time, this effect appear with a delay. This delay seem to be bigger with time. 
Idea to debug this?  What variable I should track on VS to see this timer?

I was thinking of adding a Debug line on the shard and each 5 mins or something like that Print the "tick" time
I'll compile my core on release  and see the evolution of that point and try to track why there a drifting time.

**Comment by Jhobean** [comment]
@nolok I wish help, any hint what I could track and explore?

**Comment by cbnolok** [comment]
That's difficult to solve, i think that the difference is due to the time
spent during worldsaves, in which the game time freezes but not the real
world one, we need to study that more

Il lun 23 nov 2020, 01:36 Jhobean <notifications@github.com> ha scritto:

**Comment by Jhobean** [comment]
This time, tick ,timer i dont know how call it. If I would like to calculate it and print it in the console. At each save or something like this. Maybe with this we will be able to track where the delay came from...  After save or after resync.  Be able to track it the delay saturate after few time or if the delay increase indefenely.

Will be cool to have a little function to print it..  "compare" with Windows clock in ms?
