### ISSUE TITLE
Ranged weapons ammo

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source-X#541]
Which setting applies to the ammunition requirement of ranged weapons?

Tdata3 or AMMOTYPE?

is there a working sample?

what should i do to completely remove the ammunition requirement?

When tdata3 value is empty it defaults to 02d id

**Comment by Jhobean** [comment]
Tdata3=0

**Comment by drk84** [comment]
Don't use the issues section for asking question you could get an answer in the forum / discord channel.
