### ISSUE TITLE
When OF_PetSlots is active Curfollower go up On destroy NPC

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#542]
How to reproduce
1- Activate OF_PetSlots on ini
2- Add a follower, Buy a NPC or .cast58 . follower will go up
3- .kill the npc and curfollower will climb again instead of going down

**Comment by drk84** [comment]
Here works fine, any scripts increasing the followers?

**Comment by Jhobean** [comment]
Ok thx for test, i'll investigate more and eventually close this issue

**Comment by Jhobean** [comment]
Don't know why lol! Work on my PC, not on my laptop!!  But it's clearly not a bug in the core. Thx for the test you made Drk
