### ISSUE TITLE
Stacking Item automatic do not work on some potion

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#543]
When crafting potion, some of them do not stack depending of the type.

You can reproduce it by droping the potion on the ground and slide it on your character. Potion will go on your pack. Reproduce and you'll see item do not stack. When they are on backpack, you can stack them manually.

i_potion_Agility  do NOT work
i_potion_nightsight work.

Any hint?

**Comment by drk84** [comment]
It's not a bug, item like potions / scrolls stacks only when **all** of their values are equal. 
So that means your agility potions has a different more2 value (the potion strength) and thus they cannot stack.

**Comment by Jhobean** [comment]
@drk84 why I can stack them manually?

**Comment by Jhobean** [comment]
[TYPEDEF t_potion]

ON=@Dropon_Item

IF <ARGO.BASEID> == <I.BASEID>

	ARGO.AMOUNT += <I.AMOUNT>

	REMOVE

ELSE

	RETURN 0

ENDIF


Its why :-)
