### ISSUE TITLE
TIMERF STOP, Seems not work

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#554]
I make some test for use STOP on timerf but call STOP not do nothing.

I call .f_test_Start for start the timer whit f_test_say.
When i call .f_test_Stop whit STOP on f_test_say, timerf still present

This is code i use for test:
```
[FUNCTION f_test_Start]
SRC.SYSMESSAGE Start
SRC.TIMERF 100, f_test_say
IF (<SRC.ISTIMERF.f_test_say>)
	SRC.SYSMESSAGE Present
ELSE
	SRC.SYSMESSAGE NOT Present
ENDIF
RETURN 1

[FUNCTION f_test_Stop]
SRC.TIMERF STOP, f_test_say
IF (<SRC.ISTIMERF.f_test_say>)
	SRC.SYSMESSAGE Present
ELSE
	SRC.SYSMESSAGE NOT Present
ENDIF
RETURN 1

[FUNCTION f_test_say]
	SRC.SYSMESSAGE EndTIME
RETURN 1
```

**Comment by Jhobean** [comment]
Remove the space between , and fonction name

**Comment by alexdan2** [comment]
Oky whitout space work :( damn syntax

**Comment by Jhobean** [comment]
@alexdan2 i know it because this already cause lot of headhache on my side!!:grin:

**Comment by cbnolok** [comment]
Actually it's worth fixing

**Comment by Nirad** [comment]
so just trim space shold work

**Comment by Nirad** [comment]
REF. https://github.com/Sphereserver/Source-X/blob/master/src/game/CObjBase.cpp#L2575-L2608

**Comment by alexdan2** [comment]
Thx just tested, work good whit or whitout space.
Thx
