### ISSUE TITLE
Setting OBODY does not seem to do anything

### ISSUE THREAD

**Issue by slow-loki** [Sphereserver/Source-X#555]
Seems setting OBODY does not have any real functionality.  In this example, if the starting NPC(DOG) had 10 str and a function to set its body as c_zombie was set then another set for OBODY to c_dragon it will not change any stats/skill from the OBODY value.  Incidentally, the on=@CreateLoot from the c_zombie will carry over but stats and skill will be from the original base NPC (dog)
I am unsure if this is 2  issues or 1 at this stage.

Example function I was using
[FUNCTION CHANGEBODY]
body=c_zombie
OBODY=c_dragon              <---this dont change anything
update

**Comment by Jhobean** [comment]
Body and obody only change the shape of the monster. The stat is not change and it's normal.

.Body will change the appearance see by client
.obody will be how the server see the char (exemple when you die/rez you will be this body)

**Comment by slow-loki** [comment]
[DEFNAME Soulhunt_bosses]
SoulHunt_boss_1	{c_ratman 1 c_llama 1 c_medusa 1}

[CHARDEF c_soul_boss_1]
NAME=Lord Soul Noob
ID=c_man
DAM=35,50
ARMOR=30  
CAN=MT_WALK|MT_RUN
DISPID=C_zombie

ON=@Create
COLOR=007cc
STR=450
MAXHITS=950
DEX={100 150}
INT=1
PARRYING={290.0 300.0}
MAGERY=0
MAGICRESISTANCE={290.0 300.0}
TACTICS={290.0 300.0}
WRESTLING={200.0 250.0}
npc=brain_monster
FAME=10000
KARMA=-10000
TIMERF 1,CHANGEBODY

on=@CreateLoot
item=i_soul_gem

CATEGORY=
SUBSECTION=
DESCRIPTION=

[FUNCTION CHANGEBODY]
body=<def0.SoulHunt_boss_1>
OBODY=c_soul_boss_1
update

With this it keeps stats skill same as default which is perfect.  However when the monster dies the on=@CreateLoot is called from {c_ratman 1 c_llama 1 c_medusa 1}

The purpose of the above script was to have a NPC have different body each time its created without.

**Comment by Jhobean** [comment]
what about this?
ON=@CREATE
local.body=<EVAL {c_ratman 1 c_llama 1 c_medusa 1}>
body=<local.body>
obody=<local.body>

WARNING: I think defname don't work on @create trigger (SoulHunt_boss_1) https://github.com/Sphereserver/Source-X/issues/284

**Comment by criminalx** [comment]
I can confirm, using body=xx change body, obody and fire its @createloot at die

**Comment by xwerswoodx** [comment]
OBODY is not fired anywhere, OBODY is Old Body, it holds your recent body to make sure game knows it, like when you used polymorph spell your body is changed so game saved your c_man or c_woman body as old body so game knows when you die or when your spell ended which body it needs to replace. So when you die, game directly check if he has old body and if it's different, sphere think you used polymorph spell and replace your corpse to old body. So OBODY is like a TAG.BODY, it just saved your old body to make sphere knows what your body is. So it has no usage at all. When you try to replace body by code, you need to set obody to new body like;
```
BODY=c_man
OBODY=<BODY>
```
Obody keeps the char base which says sphere this char is originally comes from the char that set on obody.

At the end, if you don't want to waste your time by writing 2 line code;
```
[FUNCTION NBODY]
BODY=<ARGS>
OBODY=<ARGS>
```
Can solve all the issues for you.

**Comment by cbnolok** [comment]
That's not the purpose of OBODY. Have you tried changing the ID on @Create?
