### ISSUE TITLE
SKILLCLASS Can't SET RealTime value

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#558]
Hello,
according to to wiki information:

![image](https://user-images.githubusercontent.com/6176986/101266662-3ec66480-3751-11eb-9290-f3c2bf370a9a.png)

All value of SKILLCLASS are RW, but i can only read can't set value:

How i test it:
- show skillclass.STR 

![image](https://user-images.githubusercontent.com/6176986/101266686-89e07780-3751-11eb-8565-74bde41f8f71.png)

Now i test to SET (write) a value:
- set skillclass.STR = 100 

![image](https://user-images.githubusercontent.com/6176986/101266705-d1670380-3751-11eb-98da-71284b32cd2c.png)

I not know if is wrong on wiki or is wrong on sphere.

**Comment by drk84** [comment]
It's not a bug, you can change a definition value by using serv.skillclass.skillclassid.str so serv.skillclass.0.str = 150 for skillclass_undeclared.

The change will last until server is closed, and it will applies to all players with that skillclass.

You need to use tag.override.statcap_0/1/2

See:
https://wiki.spherecommunity.net/index.php?title=Override_TAGs#Character-based_Override_TAGs
