### ISSUE TITLE
[PORT] a79d64ef2bee889a3a63ac0a7d96f5defc0e0459. Fixed: Multi dynamic regions getting replaced by script static regions on server resync

### ISSUE THREAD

**Issue by fjgo86** [Sphereserver/Source-X#56]
To be tested more and eventually ported.
Revision: https://github.com/Sphereserver/Source/commit/a79d64ef2bee889a3a63ac0a7d96f5defc0e0459
Author: Coruja coruja@outlook.com
Date: 27/06/2016 23:57:49
Message:
Fixed: Multi dynamic regions getting replaced by script static regions on server resync

**Comment by xwerswoodx** [comment]
Honestly we have already fixed it, so I am going to close this port issue, as we don't really need it anymore.
