### ISSUE TITLE
Stoned Npc Keep Atacking

### ISSUE THREAD

**Issue by Tolokio** [Sphereserver/Source-X#569]
Stoned Npc Keep Atacking. (xD)
They attack, cancel, and repeat attack in infinite loop. And doing it so so fast.

**Comment by drk84** [comment]
yup confirmed

**Comment by drk84** [comment]
Fix sent

**Comment by alexdan2** [comment]
I Confirm is fixed.

I tested in two way:
- Add npc (red)
- Make him attack me
- Stone it

Second way,
- add npc (red)
- Try do make some damage or spell or other

Both way npc not attack,

**Comment by Tolokio** [comment]
fixed sorry for the delay
