### ISSUE TITLE
Access Violation on SRC.MUSIC

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#581]
Hello i report this debug message of Access Violation when set SRC.MUSIC in a determinate region whit ON=@ENTER

**Additional info:**

- Happen only if player enter in this region whit ship, not if walk or teleport
- Tested on Build 3366 (Win) (old build also still affected)

**Script Code:**
```
[REGIONTYPE r_seatheme]	
ON=@ENTER
	SRC.MUSIC=32 	//boattravel  <-- This is line 35
ON=@CLIPERIODIC
	SRC.MUSIC=32 	//boattravel
ON=@REGPERIODIC
	src.SFX={025,1,026,1,027,1,010,1,011,1,012,1,013,1}


[DEFNAME midis]
....
midi_sailing			32
....
```

**Error Log:**
```
13:01:CRITICAL:(sphere_music.scp,35)"Access Violation" (0x16ad2e), in ExcType=CSError catched in CScriptObj::Verb()
13:01:DEBUG:Printing STACK TRACE for debugging purposes.
13:01:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
13:01:DEBUG:(05064)          T_Main |  0 |                       CWorld::OnTick | +0  
13:01:DEBUG:(05064)          T_Main |  1 |                   CWorldTicker::Tick | +2  
13:01:DEBUG:(05064)          T_Main |  2 |               CCMultiMovable::OnTick | +3486  
13:01:DEBUG:(05064)          T_Main |  3 |                 CCMultiMovable::Move | +1  
13:01:DEBUG:(05064)          T_Main |  4 |            CCMultiMovable::MoveDelta | +18  
13:01:DEBUG:(05064)          T_Main |  5 |             CRegion::OnRegionTrigger | +15  
13:01:DEBUG:(05064)          T_Main |  6 |          CScriptObj::OnTriggerScript | +6  
13:01:DEBUG:(05064)          T_Main |  7 |          CScriptObj::OnTriggerRunVal | +6  
13:01:DEBUG:(05064)          T_Main |  8 |             CScriptObj::OnTriggerRun | +0  
13:01:DEBUG:(05064)          T_Main |  9 |                 CRegionWorld::r_Verb | +5  
13:01:DEBUG:(05064)          T_Main | 10 |                      CRegion::r_Verb | +0  
13:01:DEBUG:(05064)          T_Main | 11 |                   CScriptObj::r_Verb | +0 <-- exception catch point (below is guessed and could be incorrect!)
13:01:DEBUG:(05064)          T_Main | 12 |                       CLog::EventStr | +54  
13:01:DEBUG:(05064)          T_Main | 13 |             CSFileText::_WriteString | +140  
13:01:DEBUG:(05064)          T_Main | 14 |                   CSFileText::_Write | +1  
13:01:DEBUG:command 'SRC.MUSIC' args '32' [0000000000000000]
```

**Comment by cbnolok** [comment]
I can't confirm here, can you give more info?
* Does it happen with any region? Which ones are you using? Is it tied to some areas in the map?
* What's the code for your MUSIC function?
* How are you adding the REGIONTYPE to the region?
* Does it change anything with GM ON/OFF?
* What are the steps you did to get that error? Added a boat with a deed, entered it via the plank or just teleported inside? Does it happen with specific boats?

**Comment by alexdan2** [comment]
> * Does it happen with any region? Which ones are you using? Is it tied to some areas in the map?

Happen in any region when player enter whit aboard of ship

> * What's the code for your MUSIC function?

```
[FUNCTION music]
IF (<ISPLAYER>)
 MIDILIST <ARGS>
ENDIF
```

> * How are you adding the REGIONTYPE to the region?

I adding like event i use in more other script and not make any problem
Here code:

```
[AREADEF a_Mare_delle_Stelle] 	//mare a nord-ovest di nujelm
NAME=Sea of Stars
GROUP=SEAS
FLAGS=region_antimagic_gate|region_antimagic_recall_out	//|region_flag_announce
P=3210,1070,0,0
RECT=3030,990,3402,1263,0
RECT=3281,843,3785,968,0
RECT=2762,1203,3050,1350,0
EVENTS=r_Mare_delle_Stelle,r_seatheme
TAG0.ALLOWMARK=0
```

> * Does it change anything with GM ON/OFF?

Nop is same

> * What are the steps you did to get that error? Added a boat with a deed, entered it via the plank or just teleported inside? Does it happen with specific boats?

Happen whit all boats.
Happen whit teleport or plank is same
Add by deed

How replicate is simple:
Place a boat in border of region
Go upper to board
Navigato to enter in region.
When trigger ON=@ENTER generate the error

**Comment by cbnolok** [comment]
Anyone else could replicate this bug? I still can't get it on my end

**Comment by cbnolok** [comment]
I'm closing it since it looks a dead issue. Feel free though if it still happens on newer builds
