### ISSUE TITLE
Logial problem in IF Condiction

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#583]
Whit new build need make a lot of ISVALID check.. 
But i not know if is a bug or not:

This condiction:
```
IF (<REF1.ISVALID> && <REF1.ISPLAYER>)
    .....
    .....
ENDIF
```

In this case if REF1 is not valid i get a error on (<REF1.ISPLAYER>).. question is why get error?
If condiction use AND .. and frist fail why try to check second condiction if frist already failed ?

Solution is:
```
IF (<REF1.ISVALID>)
     IF (<REF1.ISPLAYER>)
    .....
    .....
  ENDIF
ENDIF
```
But script code come a lot of bigger and also a lot of indented IF. If have to check more REF become insane

**Comment by cbnolok** [comment]
Sadly, for now there's little we can do to mitigate this, since in 99% of the cases sphere's script parser evaluates the full string before applying the operators... Try to use QVAL when possible, because now it is handled as a special case and has a lazy evaluation, which means that it evaluates only the expression to be returned.

**Comment by cbnolok** [comment]
Actually i can try to add a lazy evaluation like i did for QVAL, that would solve the problem but that's not easy. I'll try and keep you updated here

**Comment by alexdan2** [comment]
> Actually i can try to add a lazy evaluation like i did for QVAL, that would solve the problem but that's not easy. I'll try and keep you updated here

Oky thx :)

**Comment by cbnolok** [comment]
Qval should be fixed, but there's still work to do for IF

**Comment by alexdan2** [comment]
I confirm QVAL work good:

**Before:**
Code:
```
        SERV.LOG REF1: <REF1.ACCOUNT>
        SERV.LOG <QVAL (<REF1.ACCOUNT.PLEVEL> > 1)? (+):>
```
Result:
```
15:04:(sphere_admin.scp,101)REF1: a
15:04:(sphere_admin.scp,102) 1)? (+):>
```

**Now (Build 3370):**
Result:
```
21:15:(sphere_admin.scp,101)REF1: a
21:15:(sphere_admin.scp,102)(+)
```

Waiting for IF Fix, change all code in QVAL i not like it.. becasue for me is more clear use IF if on script work different ppl, more clear and easy to read.
Thx !!!

**Comment by Jhobean** [comment]
Ok The Qval Fix create a new BUG . It's now impossible to use REF on if statement:

```
[FUNCTION test]
ref1 = 1
if (<ref1>)
    serv.log WORK
else
    serv.log Dont WORK
endif
```

**Comment by alexdan2** [comment]
> Ok The Qval Fix create a new BUG . It's now impossible to use REF on if statement:
> 
> ```
> [FUNCTION test]
> ref1 = 1
> if (<ref1>)
>     serv.log WORK
> else
>     serv.log Dont WORK
> endif
> ```

Try, if i understand good can't check direct but have to use ISVALID:
```
[FUNCTION test]
ref1 = 1
if (<ref1.ISVALID>)
    serv.log WORK
else
    serv.log Dont WORK
endif
```

**Comment by Jhobean** [comment]
Ok My test was not good. Here the fonction causing the glitch.

```
[FUNCTION f_nothing]
return 0

[FUNCTION test]
ref1 = <UID>
if (<QVAL 0 ? 0:<src.f_nothing <ref1>>> || <ref1.ISGM>)
    serv.log WORK
else
    serv.log Dont WORK
endif
```

my real fonction on script (working before QVAL fix) is this one:

```
if <QVAL 0? 0:(<src.is_owner <ref1>>) > || (<src.is_coowner <ref1>>) || (<src.is_friend <ref1>>) || (<src.is_access <ref1>>)
                     return 0
                else
                    src.sysmessage @32,,1 Door Lock
                    return 1
                endif
```

**Comment by cbnolok** [comment]
Give the last update a shot!

**Comment by alexdan2** [comment]
I make some test whit different "var" like LINK REF LOCAL ecc, whit AND operator and all work good! If frist fail no longer console error fro try to check second condiction.

THX!
