### ISSUE TITLE
findlayer err

### ISSUE THREAD

**Issue by Leodinas** [Sphereserver/Source-X#584]
on=@gethit
serv.log <name> <src.name> <SRC.FINDLAYER(layer_hand1).color> <SRC.FINDLAYER(layer_hand2).color>
SRC has no weapons
![image](https://user-images.githubusercontent.com/14990509/103479014-6d456700-4e05-11eb-927d-9907eed56fc9.png)

**Comment by cbnolok** [comment]
It is the right behavior, now Sphere is more strict with scripting and it's a new type of error.
You're trying to access the COLOR of a nonexistant item, because there is nothing in the layers 1 and 2. You have to check if there's an item, then you can check its properties

**Comment by Leodinas** [comment]
More than 10 years of writing habits have been overturned

A large number of error reporting scripts, and need a lot of modification.

Even the default script of spheresrv will report an error

Is this really necessary

**Comment by Jhobean** [comment]
> Is this really necessary

We had the same debate you have. Personnaly on my shard there TON of error too but. I fixed them and trust me my script are more optimal now. It permit me to find some bad reference on script that I was not aware (the major purpose of this modif).

I'm agree about Findid and findlayer there sometime some aberation when 1 line become 4 line. But all the refx, argo etc it's very usefull.

I think it's an adaptation for the best.  Few hour of fixing it and you'll have permanent more strong script.

**Comment by canerksk** [comment]
Won't more queries cause more processing and more overhead?

**Comment by cbnolok** [comment]
If you mean repeating more times stuff like FINDLAYER, one for checking the validity, and another to execute the operation then yes. In this case i suggest storing the result in REF1.
Also, yes, longer scripts require longer parsing, but it's a price to be paid to eliminate those obscure bugs with no console errors
