### ISSUE TITLE
@Skillstart not failing skill with negative actdiff

### ISSUE THREAD

**Issue by RodVIII** [Sphereserver/Source-X#586]
I need to use this trigger because I need local.craftitemdef. For testing purposes, I did:

On=@SkillStart
actdiff = -1

It does not fail the skill. I also tried calling the skillfail trigger.

On=@SkillStart
trigger @SkillFail

It also does not do anything. My @Skillfail under the Skill is not empty, which I believe should trigger the behavior of the skillfail (hard-coded, I did not change anything on the skillfail).

**Comment by xwerswoodx** [comment]
Under skills you need to use @Start @Fail instead of @SkillFail or @SkillStart, @SkillStart is character base triggers which can be used under global player event, an event on characters or under chardef. @Start and @Fail is skill base triggers which have to be used under Skill defs.

@Start trigger;
https://wiki.spherecommunity.net/index.php?title=@Start

All skill triggers;
https://wiki.spherecommunity.net/index.php?title=SKILL

**Comment by RodVIII** [comment]
I did not modify anything, for example...

[SKILL 0]
DEFNAME=SKILL_ALCHEMY
KEY=Alchemy
TITLE=Alchemist
FLAGS=skf_craft

DELAY=3.0 // per stroke.
ADV_RATE=10.0,200.0,450.0
VALUES=1,20,100

BONUS_STATS=10
BONUS_STR=0
BONUS_DEX=20
BONUS_INT=80

STAT_STR=5
STAT_INT=75
STAT_DEX=40

ON=@Fail
	SRC.SYSMESSAGE You toss the failed mixture from the mortar, unable to create a potion from it.

ON=@Abort
	SRC.SYSMESSAGE You fail to complete the potion.

The skill have the Fail trigger, SkillStart is character based, ok... That means the player is starting a skill, I think I should be able to call the trigger @fail under it, no?

**Comment by xwerswoodx** [comment]
calling trigger and failing skill is not same thing. trigger @fail means you force trigger @fail but your skill doesn't fail when you trigger @fail trigger. You need to code default behaviour if you want to call trigger by yourself. Like;

```
On=@Start
SKILL=-1
ACTDIFF=-1
FULLTRIGGER @fail

On=@Fail
SYSMESSAGE @,,1 Your skill failed bla bla.
```

**Comment by drk84** [comment]
For non combat skills the only way to force it to fail is by setting a super high ACTDIFF value like 10000, for combat skills you need to set it to < 0

**Comment by RodVIII** [comment]
> For non combat skills the only way to force it to fail is by setting a super high ACTDIFF value like 10000, for combat skills you need to set it to < 0

Working like a charm! Thanks! I will close the issue now!

**Comment by xwerswoodx** [comment]
> For non combat skills the only way to force it to fail is by setting a super high ACTDIFF value like 10000, for combat skills you need to set it to < 0

Nice to learn this honestly, i haven't used actdiff before, had no idea there was difference like thar
