### ISSUE TITLE
Invis Gm can block path of player

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#587]
When a GM is invis,

 The stamina check is done for player walk on it:
https://cdn.discordapp.com/attachments/488892196096049163/796422263183900712/Ultima_Online_-_Karelia_La_Naine_des_Montagnes_Cryptonite_2021-01-06_11-57-33.mp4

**Comment by xwerswoodx** [comment]
Do you have any On=@PersonalSpace? Maybe you return 1 under it. I will check it.

**Comment by cbnolok** [comment]
An idea would be to skip walkchecks effects upon walking on the other char if has GM mode on

**Comment by Jhobean** [comment]
Bug was occur on my custom Build. Do not happen on SOURCEX build Sorry
