### ISSUE TITLE
Separate RevealFlags (invisibility spell, hiding) into sphere.ini

### ISSUE THREAD

**Issue by terrikate** [Sphereserver/Source-X#588]
It would be very complicated to do something like this https://github.com/Sphereserver/Source/issues/65#issuecomment-229544601 (or create another block for hiding) to completely separate the invisibility spell from the ability to hide in the configuration of the sphere.ini (RevealFlags)?
I think there are certain things I can solve by script but at first it's confusing to say that it applies only to the part of the spell but nevertheless affects both things. For example REVEALF_SPEAK

**Comment by Jhobean** [comment]
You have a concrete exemple of what you want to do?

**Comment by terrikate** [comment]
For example, don't reveal a character when he talks while under the invisibility spell but do so when he is hidden with the hiding skill. It is the first case I have thought about because that's how sphere 55i, 56b, etc worked, but surely there are more.

I know that there is the TAG.NOREVEAL.OVERRIDE but you have to be careful because it would affect more things.

**Comment by xwerswoodx** [comment]
You can use something like this under player speak
```
On=*
IF (<FLAGS>&statf_hidden) && !(<FLAGS>&statf_invisible)
  ...REVEAL HERE
ENDIF
```

I haven't tried it anyway. But this can be solution for speak. And you can disable automatik revealf_speak from sphere.ini

**Comment by Jhobean** [comment]
What about an ini flag: 
SpeakInvisDoNotReveal ?

**Comment by alexrmrm** [comment]
yes will be great a flag for that option for not overload sphere with speech

**Comment by Soulless-1** [comment]
reveal flags in the sphere.ini resolve this issue. using REVEALF_SPEAK. closing this issue out.
