### ISSUE TITLE
Wrong notoflag when two guildstones are allied

### ISSUE THREAD

**Issue by Massi17** [Sphereserver/Source-X#590]
if i set two guildstones as allied they see each other blue.
Is it possible that they see each other green?

**Comment by alexdan2** [comment]
Adding some details information.

If Guild stone have same ALIGN.

Stone ONE ALIGN = 2
Stone TWO ALIGN = 2

Member of this guild see blue not green like ally,

**Comment by Ben1028** [comment]
Using any custom scripts for this?
What happens if you use this...

on=@notosend
argn=2
argn2=03f

If you see everyone green, then this will narrow down the search for the bug

Also tag.name.hue will override this

**Comment by alexdan2** [comment]
I tested whit clear script pack and if set same align see blue. (no @notosend trigger and no one tag.name.hue

Now i use this for temporaney fix (and work well):

```
ON=@NotoSend	
IF (<SRC.ISPLAYER>)
	REF1=<I.MEMORYFINDTYPE.MEMORY_GUILD> 
	REF2=<SRC.MEMORYFINDTYPE.MEMORY_GUILD>
	IF (<REF1.ISVALID> && <REF2.ISVALID>)
		IF (<REF1.LINK.ALIGN> == <REF2.LINK.ALIGN>) // alleati
			ARGN1 = 2
			ARGN2 = 2
		ENDIF
	ENDIF
ENDIF
```

**Comment by Ben1028** [comment]
ah, I get it, according to the code, to be green you must declare allies. just being of the same alignment is not considered allies.
Not sure what the proper way is with OSI...

**Comment by Ben1028** [comment]
ok, not sure anything need to be done here. the stone system was turned into script a while back and this can be modified easily.
Find the script .\scriptsX\stones\genericstone_functions.scp
go down and find the function f_stonesys_internal_isalliedwith, and f_stonesys_internal_isatwarwith
remove the word COMMENT from the header to use it.
now you can modify as you wish how an ally and enemy is determined
