### ISSUE TITLE
Errors under @Createloot trigger

### ISSUE THREAD

**Issue by RodVIII** [Sphereserver/Source-X#592]
Steps to reproduce: Use @Createloot instead of @NPCRestock in your monsters

Add any monster with the trigger on it, call guards. Guards will instant kill the monster and remove their body. It will give you template error because it can't create anything.

09:44:ERROR:(c_monster_classic.scp,2313)Undefined keyword 'ITEM'.
09:44:ERROR:(c_monster_classic.scp,2314)Undefined keyword 'ITEM'.
09:44:ERROR:(c_monster_classic.scp,2315)Undefined keyword 'ITEM'.
09:44:ERROR:(c_monster_classic.scp,2316)Undefined keyword 'ITEM'.
09:44:ERROR:(c_monster_classic.scp,2317)Undefined keyword 'ITEM'.
09:44:ERROR:(c_monster_classic.scp,2318)Undefined keyword 'ITEM'.
09:44:ERROR:(c_monster_classic.scp,2319)Undefined keyword 'ITEM'.
09:44:ERROR:(c_monster_classic.scp,2320)Undefined keyword 'ITEM'.
09:44:ERROR:(c_monster_classic.scp,2321)Undefined keyword 'ITEM'.
09:44:ERROR:(c_monster_classic.scp,2323)Undefined keyword 'ITEM'.

**Comment by Jhobean** [comment]
Good find! I had this error and did not know how reproduce.

**Comment by xwerswoodx** [comment]
I can agree that is fixed with latest build.

**Comment by soulless320** [comment]
btw, small note, createloot should not make a noise when it adds loot to a monster IMO, it should just quietly place the items onto the monster. you never heard gold coins dropping into a monsters corpse on OSI when they died.

**Comment by Jhobean** [comment]
@soulless320 you remember diablo? When you have the sound of a ring falling on the ground. Ping! Sound was there:smile:
