### ISSUE TITLE
Timer do not work like 55i and 56d

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#596]
On 55i and 56d, I think timer do not trig if logout or if sector sleeping.

For exemple: My player have an i_mem with a timer on it. When i_men go to 0, I have a trigger

```
[ITEMDEF i_mem_test]
defname=i_mem_test
name=Timer test
TYPE=t_EQ_SCRIPT

on=@create
attr=attr_move_never|attr_invis
timer=5

on=@timer
timer=5
serv.log Timer continu
return 1

[FUNCTION test]
serv.newitem i_mem_test
equip <new.uid>
```

On 56d, A the moment you are loged out, not more message!!

On X, if i'm logout, 5 sec (if sector not sleep) message is send. But it should stop if LOGGED OUT. If I logged out on Britain, sector almost never sleep... So message alway appeaat

It's the same about i_mem on NPC.
I have a I_mem crating a fireball near the NPC each 60 sec.

Fireball are create but this ball never decay because sector is sleeping. So I get error of sector too complex(too many item).

Timer MUST continu but @timer SHOULD not happen util next login

**Comment by Jhobean** [comment]
About ITEM like spawnpoint or dropped item, I think the trigger @timer should work sector sleep or not. This will fix this issue: https://github.com/Sphereserver/Source-X/issues/535

**Comment by Jhobean** [comment]
Rework seem to be this. https://github.com/Sphereserver/Source-X/blob/bf2512659ba5885d767805d0d746c0aaa1b15b2c/Changelog-X1-Nightlies.txt#L1165-L1176

I think we should talk about these feature

**Comment by cbnolok** [comment]
Those are two separate things. The internal rework was absolutely needed and there's obviously no turning back, vut we can try to emulate missing old behaviors in some way

**Comment by Jhobean** [comment]
Yes optimisation is big and all the feature are in general big step forward. But I think the ajustement must be in item on Ground (without cont) and item on char layer/pack

**Comment by Jhobean** [comment]
Good job THX!
