### ISSUE TITLE
Trigger @FameChange not trigger if set value

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#598]
Hello,
Trigger @FameChange sems not trigger in Certain situation, i make some test and compare whit @SkillChange

**How Replicate:**
- .set fame 1000

**Coded Used**:
```
ON=@FameChange
	SERV.LOG CALL ARGN1: <ARGN1>
	
```
In this casenot fire, also if some script do FAME += ###  not fire also
Fire only if i kill a npc and hardcoded fame gain

I compared whit @SkillChange

**Coded Used**:
```
ON=@SkillChange
	SERV.LOG CALL SkillChange
```

In this case trigger fire in all situation like .set Tailoring ####   or script set a skill value also in normal hardcoded skillgain

**Additional info:**
- Testet whit new build, and old one before .validate check (same issue)
- Tested whit clear script pack

**Comment by xwerswoodx** [comment]
Hmm okay seems like I see the reason, but this seems like need some rework.

**Comment by AtillaG1** [comment]
i think fixed, can be closed?

**Comment by xwerswoodx** [comment]
As It's already fixed, even I updated the triggers after that you can currently download it from Actions tab. We could close the issue.
