### ISSUE TITLE
NPC Brain_Guard Not Moving Inside Buildings

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-X#599]
![image](https://user-images.githubusercontent.com/17236327/104246287-b879fe00-5433-11eb-9971-9cbdcb6c6aa9.png)
 npcs with brain_guard will stand still inside buildings and not move, even though canmove returns that it is possible
![image](https://user-images.githubusercontent.com/17236327/104246409-ef501400-5433-11eb-8e6f-203b2a432a11.png)
even setting their action to wandering and trying to force it, they will remain still.

**Comment by xwerswoodx** [comment]
I confirm that issue.

**Comment by drk84** [comment]
Fix sent in the  last scriptpack

**Comment by Jhobean** [comment]
https://github.com/cbnolok/SphereX-Scriptpack/commit/0ff7bf7d7c9d072d4999a30015528ec6800ae988

**Comment by drk84** [comment]
I close this
