### ISSUE TITLE
ManaLossFail=1 Not working in Sphere.ini

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-X#602]
With this setting on if you fail, you do not lose mana. It only works if you also have ReagentLossFail=1 set as well.

**Comment by xwerswoodx** [comment]
I think I get the reason but I will wait nolok's commit to test and pull request about that.

**Comment by drk84** [comment]
fix sent

**Comment by soulless320** [comment]
appears to be fixed, thank you sir
