### ISSUE TITLE
 MonsterFear in Sphere.ini does not seem to affect monsters

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#603]
This setting in sphere does not seem to determine whether or not monsters will run from players, I attempted different settings incase maybe it was a percentage of health or chance and I had no luck

// Monsters run when scared of death
MonsterFear=1

**Comment by xwerswoodx** [comment]
Seems like it works like, monster checks the strength difference between himself and player, then if he is strengthen he got more motivation to not fear, then check health percentages between both, and if player's hp percentage is higher than himself it lower motivation but if not it increase motivation, and then it decreases INT/16 motivation from monster.

So in short, str affect fear rate directly so if strength difference is too high from player he doesn't fear at all.

**Comment by soulless320** [comment]
hmm thats interesting, thats not at all how monsters should function in UO. monsters should always attack. monsters should though, flee when they are about to die, has it always been like this ?

**Comment by xwerswoodx** [comment]
I haven't used it before but I can check 56c source for it, but seems like this is really old code because it's coding style is old tab style. So we can think that function haven't touched by Xun, nolok or Ben for a long time.

**Comment by drk84** [comment]
You can force the npc to flee by putting a negative value in ARGN2 in the @NpcActFight trigger

**Comment by drk84** [comment]
fix sent

**Comment by soulless320** [comment]
seemed like it didnt work for me when I tried. 

I think maybe the whole fear system needs to be redone
the setting in the INI should just be a % at which all monsters will flee when they are at that % of health or below

I can't remember if monsters only flee for a certain time then come back (like in wow) but that might be an option also like fearfleetime

**Comment by soulless320** [comment]
that would be fine totally. if drops down to a certain %, they will flee % of the time, sounds great to me, will solve the problem.

**Comment by Soulless-1** [comment]
fix works. should i leave this open for the idea of adding the toggles to sphere.ini?

**Comment by drk84** [comment]
I close this, better open a new one with suggestions on a proper morale formula
