### ISSUE TITLE
ReagentLossFail issues

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-X#605]
// Reagents lost if magic fails
ReagentLossFail=1

When you set this to 1, sphere will not only consume reagents on failure, but it will consume them on @abort as well. This should be considered incorrect behavior, you do not get penalized for deciding you don't want to cast that spell after you have casted it in official servers. It's a different situation because of precast on official servers, but the concept is the same, you only lose reagents for seeing the spell through to the end, and only on failure, or success.

**Comment by Ben1028** [comment]
There is no @abort for spells...  only skills. Does this happen when you abort magery?

**Comment by soulless320** [comment]
Yeah, I don't mean for the spells, this is for the magery skill in general. as a bandaid fix I did this.

```
ON=@Abort
src.sysmessage You stop casting the spell.
src.sound 05c
src.effect=2,i_fx_smoke_small,6,15,0
return 1	//do not consume resources on abort, only fail
```
