### ISSUE TITLE
Spellcast

### ISSUE THREAD

**Issue by falanlar** [Sphereserver/Source-X#606]
@Spellcast
spells not blocked, return 1 doesnt work

**Comment by Jhobean** [comment]
Provide more info for reproduce because its work for me.  What your code?

**Comment by falanlar** [comment]
`if ((<src.uid.<src.region.uid>.type>==t_multi) || (<src.uid.<src.region.uid>.type>==t_multi_custom) || (<src.region.guarded> == 1)) && ((<argn> == 24) || (<argn> == 28) || (<argn> == 39) || (<argn> == 47) || (<argn> == 50))
src.sysmessage you can't use this spell in this area
src.skill fail
return 1
endif`
spell is used anyway in area

**Comment by Jhobean** [comment]
If you do. On=spellcast
Serv.log here
Return 1

**Comment by falanlar** [comment]
ahh bro sorry i guess it was my fault
