### ISSUE TITLE
Hair and beard on corpse

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#607]
Found a issue in player corpse (t_corpse)

When player die generate a container type t_corpse whit body of player whit equipped item and suff.

After certain time corpse become bones:
![image](https://user-images.githubusercontent.com/6176986/104656627-e7a49f80-56bf-11eb-8e03-dc04ce8c5610.png)

When corpse become bones inside it player can see a unmovable copy of t_beard and t_hair (original placed on player).,
This is a copy only because original one stil on player because have attr 014. But this copy is some case can be used by other player whit 2dlick (if not have another type equipped) and also if can't move is impossible manual get item under it.

Inside Bone:
![image](https://user-images.githubusercontent.com/6176986/104656929-68fc3200-56c0-11eb-8e41-2cc4a36b57d5.png)

Compare item on bone whit item equipped on player:
![image](https://user-images.githubusercontent.com/6176986/104656973-7c0f0200-56c0-11eb-87e1-aa91c4dff7b6.png)

**How reproduce:**
- Equip some kind of hair
- .kill self
- Go away from corpse
- Ressurrect
- Open normal body corpse (see clear, all ok)
- Se timer 1 on body for make him force to become bone whitout wait
- See now what is inside container

**Additional Info:**
- Tested whit last build (have issue)
- Tested whit build before validata check (have issue)

**What i think:**
- I think this issue happen because normal body have layer for equip it, but bones not have it is a simple cotainer

**Comment by Ben1028** [comment]
I followed your exact steps and was not able to reproduce. Working fine here.

**Comment by Jhobean** [comment]
Maybe its link to the def of hair. You have same?

**Comment by Ben1028** [comment]
I tried it with i_beard_short as shown above, same steps to reproduce, but see nothing in the pile of bones

**Comment by alexdan2** [comment]
This night i investigate more deeper and send more details.

**Comment by alexdan2** [comment]
I investigate better and tested whit different client, Whit OSI client not happen, but happen whit classicUO, is a ClassicUO issue, sorry for this mistake.
