### ISSUE TITLE
Wall of stone Player vendor

### ISSUE THREAD

**Issue by falanlar** [Sphereserver/Source-X#610]
player vendor leaves her owner when stuck in the wall of stone
I cannot solve the problem even though I made "@SpellEffect" to "return 1"

**Comment by alexdan2** [comment]
I not know how is coded your script, if you use desert for some operation or not

Possible solution try to add on vendor event
```
ON=@PetDesert
RETURN 1
```

**Comment by falanlar** [comment]
> Eğer bir operasyon için çöl kullanırsanız veya kullanmazsanız, betiğiniz nasıl kodlanır bilmiyorum
> 
> Olası hızlı çözüm, satıcı olayına eklemeye çalışın
> 
> ```
> ON=@PetDesert
> RETURN 1
> ```
thanks for answer so can I prevent the vendor from attacking?

**Comment by falanlar** [comment]
> I not know how is coded your script, if you use desert for some operation or not
> 
> Possible fast solution try to add on vendor event
> 
> ```
> ON=@PetDesert
> RETURN 1
> ```

thanks for answer so can I prevent the vendor from attacking?

**Comment by alexdan2** [comment]
> > I not know how is coded your script, if you use desert for some operation or not
> > Possible fast solution try to add on vendor event
> > ```
> > ON=@PetDesert
> > RETURN 1
> > ```
> 
> thanks for answer so can I prevent the vendor from attacking?

Set him statf_invul  . if is invul also prevent too problem whit wall

**Comment by xwerswoodx** [comment]
Sphere has no player_vendor system, but as player vendors works depends on followers (pet) system, using wall of stone on him means you attacked him, so he can desert, this is default behaviour, so I suppose you to block pet desert or the another solution is adding @GetHit, @SpellEffect triggers under npc and set RETURN 1 there, so it doesn't get any attack, but if you want to get killed you can use @PetDesert trigger to block it like alex said.

https://wiki.spherecommunity.net/index.php?title=@PetDesert

**Comment by falanlar** [comment]
@PetDesert solved the problem, but the vendor still attacks. @Gethit and @SpellEffect do not prevent vendor from attacking

**Comment by alexdan2** [comment]
> @PetDesert solved the problem, but the vendor still attacks. @GetHit and @SpellEffect do not prevent vendor from attacking

Add this:
```
ON=@NpcActFight
	RETURN 1

ON=@Attack
	RETURN 1

ON=@HitTry
	RETURN 1
```

**Comment by falanlar** [comment]
I tried but it still doesn't work

**Comment by GitMadKing** [comment]
```
ON=@CombatAdd  //ON THE NPC
RETURN 1 

```

**Comment by falanlar** [comment]
> ```
> ON=@CombatAdd  //ON THE NPC
> RETURN 1 
> ```

perfect :) problem solved 👍
