### ISSUE TITLE
Feature Request: Timerf stop,FunctionName *

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-X#612]
Add a wildcard to use after the functionname so that we can cancel every timerf function

if i have 

timerf 15,say poop 1
timerf 15,say poop 14
timerf 15,say poop 200
timerf 15,say poop 2300

timerf stop,say *  would stop every single timerf on a player using the say function

**Comment by Ben1028** [comment]
Will come once server is more stable

**Comment by alexdan2** [comment]
Tested whit this code:

```
[FUNCTION f_test22]
timerf 2,SRC.say poop 1
timerf 2,SRC.say poop 14
timerf 2,SRC.say poop 200
timerf 2,SRC.say poop 2300

timerf stop,SRC.say *
```

And work perfect !

**Comment by soulless320** [comment]
Confirmed was working, thank you!
