### ISSUE TITLE
Vendor Hear Distance

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-X#615]
vendors will sell to you from an ungodly distance
no distance limit for NPCs to hear players

**Comment by Jhobean** [comment]
made some test on OSI 

Buy distance is big (if you buy from too far client crash lol)
and dialog distance is 8 tiles max

On sphere.
Buy distance is 2
Dialog distance seem infinite

**Comment by alexdan2** [comment]
I notice some strange.. I set NPCDistanceHear=8

Before this update banker open bank whit BANK word only.
Now at 90% or time have to tell <NAMENPC> Bank for open bank

**Comment by alexdan2** [comment]
Whit last build whit negative value for disable LoS is perfect!.
Thx

**Comment by soulless320** [comment]
Thank you!
