### ISSUE TITLE
Low Priority Requests.

### ISSUE THREAD

**Issue by Tolokio** [Sphereserver/Source-X#616]
Few requests I think are good for everybody.

This changes can be done by scripts so are not necessary, but for people who looks for best performance as possible, being forced to script what sphere already does better and faster is a little mess. Little changes could safe custom servers to become heavier than they should be.

///////////////////
New Triggers://
////////////////

```
on=@itemBeingCarved
| -> Corpse being 
carved
src ->playerCarving
Return 1 ->Prevent all
Return 0 ->Prevent resource gathering but effects.

```
Reason: Right now, If u want to do any change on corpse carving, it forces you to redo entire system by script and modify every typedef able to carve corpses. This way u dont need to modify all weapons typedef, and u dont have to redo entire system.
As always, sorry for my poor eng.

/////////////////////////////
```

On=@Smelting
argo-> item being smelted
src- character
Return 1->Prevent all
Return 0->Allow effects, but no resource gathering

```
Reason: Right now, If u want to do any change on smelting system, it forces you to redo entire system by script. Sphere does it better and faster. We should have access to it instead being forced to script entire system. For example, if I want to modify Ore-ingot exchange rate, I am forced to redo everything by script.

///////////////////
FUNCTIONS//
////////////////

```
[CANSEE CANSEELOSS] 
Return <FirstBlockCoordinate> instead just "return 1"

```
Reason: Same as above, if u want to know where vision gets blocked, u need to script a custom canseeloss's function when normal "canseeloss" already knows where light of sight get blocked and it just needs to be returned. This is a very heavy and common function to be done by script.

 With this fix, Scripts would works as ever with this change, Scripts use to check if there is a return, not the value itself, so nobody should realize the fix. It would just return a coord instead "1", letting us know where the vision gets blocked.
If it is not possible to modify it, I think a "CanseelossP" function should be created.

/////////////////////////////
```
[RAISECORPSE] FIX request
(moved to issue #620)
```
 
  /////////////////////////////
  
```
[Function IsLayered]
Return 1 if item is layered on a corpse
```
This function already exist in sphere (not with the same name), so sphere can check if an item is layered or not in a corpse.
![image](https://user-images.githubusercontent.com/20745578/105178758-c2cd8380-5b28-11eb-9c40-a0acf40a31fa.png)

Would be nice to let us use it so we dont need to create tags to check which items are equipped or not.

**Comment by Tolokio** [comment]
Wild @drk84  found a very easy way to solve the [Function islayered]'s issue. 

![image](https://user-images.githubusercontent.com/20745578/109954232-62ae2d80-7ce1-11eb-87f5-9a9e55924760.png)

ty drk84

**Comment by drk84** [comment]
I think this can be closed
