### ISSUE TITLE
Moddex modint modmana Make stat go "negative"

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#618]
Moddex int and mana not have check if make stat run in negative. I not know if is normal and have to make a scriptcheck before use it or is a bug.

**How reproduce:**
- .set int 100
- .set modint -101

**This is result:** 
![image](https://user-images.githubusercontent.com/6176986/105182792-c1eb2080-5b2d-11eb-84ac-8098534eb29b.png)

**Additional Info:**
- Tested on build 3384 
- Tested on clear script pack

**Comment by Ben1028** [comment]
Currently, MOD stats do not check if final value results in negative stat. personally this should be handled by scripts.

**Comment by alexdan2** [comment]
> Currently, MOD stats do not check if final value results in negative stat. personally this should be handled by scripts.

Oky i already do by script :)

**Comment by Jhobean** [comment]
This Happen in this: https://github.com/Sphereserver/Source-X/blob/bcc0a4c67ee218f62322ce088f5ac281da37a29d/src/game/chars/CCharStat.cpp#L24

It's  possible to force the stat to 0 with these line:
```
	if (Stat_GetBase(i) + iVal < 0) //Need avoid to go in negative because stat are unsigned. So -1 str will give like 65k str...
	{
		iVal = -Stat_GetBase(i);
		g_Log.EventWarn("Trying to set %s to negative value Defaulting it to 0.\n", g_Cfg.GetStatName(i));
	}
```
The problem is when stat are going up, the offset is not add. The solution is to create a offsetOverflow for each stat and add it when we modify the stat positif. I think it's easier to fix it by script.

**Comment by alexdan2** [comment]
> This Happen in this:
> 
> https://github.com/Sphereserver/Source-X/blob/bcc0a4c67ee218f62322ce088f5ac281da37a29d/src/game/chars/CCharStat.cpp#L24
> 
> It's possible to force the stat to 0 with these line:
> 
> ```
> 	if (Stat_GetBase(i) + iVal < 0) //Need avoid to go in negative because stat are unsigned. So -1 str will give like 65k str...
> 	{
> 		iVal = -Stat_GetBase(i);
> 		g_Log.EventWarn("Trying to set %s to negative value Defaulting it to 0.\n", g_Cfg.GetStatName(i));
> 	}
> ```
> 
> The problem is when stat are going up, the offset is not add. The solution is to create a offsetOverflow for each stat and add it when we modify the stat positif. I think it's easier to fix it by script.

Yep i do more easy to check it in @equiptest if negativemod > maxstat not equip.
