### ISSUE TITLE
PAtthfinding Sendpacket Crash

### ISSUE THREAD

**Issue by Tolokio** [Sphereserver/Source-X#619]
If U sent just once the Patchfiding's packet using sendpacket, client will crash. Tested with client 7.0.20

**Comment by alexdan2** [comment]
This packet?
```
Packet: 0x38
Size: 7 Bytes

Packet Build
BYTE[1] Command
BYTE[2] X
BYTE[2] Y
BYTE[2] Z
```

Is very bugged in client this packet not work good.. (Client side).
1- have to send 19 time like spam for make some client reaction
2- If Z is negative not work at all.

**Comment by Tolokio** [comment]
I would like to use it even if I need to spawn it 25 times. But it crashes with one. :/

**Comment by alexdan2** [comment]
> I would like to use it even if I need to spawn it 25 times. But it crashes with one. :/

YOu can show me code you use i make a test :)

**Comment by Tolokio** [comment]
[function  f_test]
local.x=<eval <src.p.x>-1>
sendpacket 038 W<local.x> W<src.p.y> <src.p.z>

**Comment by alexdan2** [comment]
> [function f_test]
> local.x=<eval <src.p.x>-1>
> sendpacket 038 W<local.x> W<src.p.y> <src.p.z>

You missing a W on Z.. Because packet details dell Z value also is a 2 bytes

```
[function f_test55]
local.x=<eval <src.p.x>-5>
FOR 1 20
	sendpacket 038 W<local.x> W<src.p.y> W<src.p.z>
ENDFOR
```

This for me work good, remember not use Z negative

**Comment by Tolokio** [comment]
![image](https://user-images.githubusercontent.com/20745578/105326506-1ba32780-5bce-11eb-8d6a-28ce27d5e3af.png)
Then this is wrong. ty Ill try it later :D

**Comment by alexdan2** [comment]
IS not wrong bacause image tell 1byte for Z.. 
But pathfind packet use 2 byte for Z.. is a strange packet

This is structure:
```
Packet Build
BYTE[1] Command
BYTE[2] X
BYTE[2] Y
BYTE[2] Z
```

**Comment by Jhobean** [comment]
Client are really easy to make them crash if there a syntax error on packet. Don't think its server problem because the real sendpacket for pathfinding work.

**Comment by cbnolok** [comment]
As said, it's not a sendpacket, thus server issue. The client stucks or crashes upon receiving malformed packets
