### ISSUE TITLE
[RAISECORPSE] bad retrieving order

### ISSUE THREAD

**Issue by Tolokio** [Sphereserver/Source-X#620]
[RAISECORPSE] FIX request
The order the items are getting back to character can make items to get into floor instead.

![image](https://user-images.githubusercontent.com/20745578/105181729-74ba7f00-5b2c-11eb-9f11-0a910a5d91d4.png)

There can be an issue for people who modify backpacks system or weight system. For example if any equipped wereable modifys the amount of items/weight u can carry, Items may get into the floor if thoose wereables are not equiped before the rest of the items are taken. This issue wasn't happening before cos there were a bug preventing it (#589) .Items were forced to get into backpack even if any @drop_on denys it with "return 1", so this issue does not exist before.

How to fix: Wereables should be taken first, and the rest of the items later Can be done by script using tags and modifying @resurrect to equip layered items first. (Should be nice if we could see which items are layered without using tags as sphere does in source, something like "if <ref1.islayered>" to use on corpse's items. (posted in Rastreros Requests post.)

Anyway, I think, sphere should equip layered items first by defect.
MAybe this fix should work.
![image](https://user-images.githubusercontent.com/20745578/105174001-2a340500-5b22-11eb-931a-3c8fde0ec5e8.png)

 Nobody would have any problem with anything if this fix is done. It will increase slightly cpu usage for everybody but it is worth as it prevent this anoying issues where items can get into floor randomly while resurrecting with full backpack.
 As it is Random issue cos items are moved/equipped randomly and issue can happen or not, it could be hard to realize what is going on. 
 
 How to replicate?
 -Equip any wereable that increase amount of items/weight u can carry.
 -Get items into your backpack until reach the limit.
 -Get killed
 -Resurrect
 -Random chance item get into floor.
 (if the wereable is equipped before reach item/weight's limit, issue will not appear, it is random)
 (remember the issue #589 prevent this issue if it is not fixed)

**Comment by Jhobean** [comment]
Since 589 fix, I saw some npc when they decay their item drop on ground. Seem to be random. Not able reproduce

**Comment by Tolokio** [comment]
I think it should be not related to raisecorpse's order. Try to check if it only drop certain items such as wereables, or it just drop any random item. Did u customized backpacks, container or any?
