### ISSUE TITLE
ISTIMERF and TIMERF STOP

### ISSUE THREAD

**Issue by falanlar** [Sphereserver/Source-X#623]
ISTIMERF and TIMERF STOP do not work when leaving spaces after function

```
[Function saysometing]
src.say <args>

[Function timerfcontrol]
src.timerf 5,saysometing asd
if (<src.istimerf.saysometing>)
src.say working
else
src.say not working
endif

```

**Comment by Jhobean** [comment]
It's normal. You must use the exact syntax that the timerf store

But I heard @Ben1028 working on something to improve this.

For now you can use the function
`if (<src.istimerf.saysometing asd>)`

**Comment by falanlar** [comment]
> It's normal. You must use the exact syntax that the timerf store
> 
> But I heard @Ben1028 working on something to improve this.
> 
> For now you can use the function
> `if (<src.istimerf.saysometing asd>)`

Bro thanks for helping, i solved the problem via ctag

**Comment by Jhobean** [comment]
Check the note in timerf stop section.
http://wiki.spherecommunity.net/index.php?title=Characters

You can now improve your method.

**Comment by falanlar** [comment]
Good work thanks  :)
