### ISSUE TITLE
NPC Cast

### ISSUE THREAD

**Issue by alexrmrm** [Sphereserver/Source-X#624]
problem with npcs not cast spells, i try with wand, spell and spellbook and never cast.

on:
`bool CChar::NPC_FightMagery(CChar * pChar)`

always return false on that line:
```
    if ((iSpellCount < 1) && !pWand)
        return false;
```

**Comment by Jhobean** [comment]
You must add them spell on the @create

**Comment by alexrmrm** [comment]
thx man.
