### ISSUE TITLE
Tag=0 do not erase tag anymore.

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#626]
We are not able erase tag. Always stay In save spherechars.scp

https://cdn.discordapp.com/attachments/483721253773901824/803267529556361286/unknown.png

**Comment by alexdan2** [comment]
Yep i confirm, tested on last release

How Reproduce:
- Set tag0.hello = 1
- Set tag0.hello = 0

Result of .xtaglist
![image](https://user-images.githubusercontent.com/6176986/105987445-92449700-609e-11eb-8318-3a43f3cdca31.png)

**Comment by alexdan2** [comment]
Confirm whit last build work good. thx
