### ISSUE TITLE
Follower Slot

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#627]
In new release happen a new bug in followerslots.
When buy transfer tame a NPC, he generate +1 followers but in chardef is 0

**LLama Definition:**
```
[CHARDEF 0dc]
DEFNAME=c_llama
NAME=Llama
SOUND=snd_ANIMALS_LLAMA3
ICON=i_pet_LLAMA
CAN=MT_WALK|MT_RUN
ANIM=01fff
DAM=2,5
ARMOR=4
RESOURCES=5 i_ribs_raw, 2 i_fur_light
FOODTYPE=5 t_crops, 5 t_fruit, 5 t_grain, 5 i_hay, 60 t_grass
DESIRES=c_llama, c_llama_sand, c_llama_pack, spk_human_prime
TEVENTS=e_mount
FollowerSlots=0                                 <------------- HERE 0 followerslots
DESCRIPTION=Llama
SUBSECTION=Cavalcabili
CATEGORY=Animali

ON=@Create
   NPC=brain_animal
   STR = {8 10}
   DEX={30 55}
   INT={10 30}
   PARRYING={35.0 45.0}
   MAGICRESISTANCE=10.0
   TACTICS={20.0 30.0}
   WRESTLING={20.0 30.0}
   TAMING=50.0
   FAME=10
   KARMA={-1 -99}
```

This is result after buy one: (this not correct)
![image](https://user-images.githubusercontent.com/6176986/106016912-3c80e680-60c0-11eb-94da-93a3da8c2e92.png)

This is result on xshow followerslots on a mount: (this is correct)
![image](https://user-images.githubusercontent.com/6176986/106017712-098b2280-60c1-11eb-9448-293705452a96.png)

**Additional info:**
- Tested on last release

**Comment by alexdan2** [comment]
> Yes there was a recent changes were the minimum follower is always 1.

Bad :( this is problematic...

**Comment by Jhobean** [comment]
Will be fix dont worry. Seem an easy fix....   But it was working before?? Because the lines forcing it to 1 are there since the beginning of sphere x

**Comment by alexdan2** [comment]
> Will be fix dont worry. Seem an easy fix.... But it was working before?? Because the lines forcing it to 1 are there since the beginning of sphere x

Yep, in version Pre validate work correct if set Zero count Zero follower

**Comment by Ben1028** [comment]
This might not be just a simple fix.
A default of 1 was set so that all pets have 1 by default if the value is not set.
There is not way at the moment to differ from 0 to not set which is where the problem is.

**Comment by alexdan2** [comment]
> This might not be just a simple fix.
> A default of 1 was set so that all pets have 1 by default if the value is not set.
> There is not way at the moment to differ from 0 to not set which is where the problem is.

In old version 1 month ago not have this issue.. if zero counting like 0 in followerslot.
Problem is if ppl like me use followerslot for summon control is total broken if player have tamed pet :(

**Comment by cbnolok** [comment]
An idea could be to use internally -1 as uninitialized value, and convert that to 1 in calculations

**Comment by Ben1028** [comment]
I do have an idea as to how to fix this without changing much.
I can make the function return 1 if not set and remove the forced 1 in the calculation

**Comment by alexdan2** [comment]
I Make tests whit FollowerSlots=0 And work good.

Thx for fixing it!
