### ISSUE TITLE
can_i_dcignoredist not working

### ISSUE THREAD

**Issue by xMirroRx** [Sphereserver/Source-X#628]
It is stated to be fixed in the last fix but it does not work.

**Comment by Jhobean** [comment]
Please provide an example how to test and what particular bug occur.

If i'm right the last commit was doing modification abount LOS in the can_i_dcignoredist

**Comment by xMirroRx** [comment]
Sphere Build: 3396

![image](https://user-images.githubusercontent.com/10285831/106644849-af94cc00-659c-11eb-9284-731428cdae22.png)

**Comment by xMirroRx** [comment]
can_i_dcignorelos		004000	// It works like this. Detects only 2 frames.

**Comment by Ben1028** [comment]
This should work as intended...   can_i_dcignorelos to bypass LOS, and can_i_dcignoredist to bypass distance check

**Comment by Ben1028** [comment]
Duplicate of #614

**Comment by xMirroRx** [comment]
works great. there seems to be no problem.

**Comment by Jhobean** [comment]
If it work, mirror you can close issue.
