### ISSUE TITLE
[PORT]210563f9d22c4374e4faecdf92cd78ccd7114661, Fixed: Multi regions not reloading correctly after server resync

### ISSUE THREAD

**Issue by fjgo86** [Sphereserver/Source-X#63]
To be tested more and eventually port.
Revision: https://github.com/Sphereserver/Source/commit/210563f9d22c4374e4faecdf92cd78ccd7114661
Author: Coruja coruja@outlook.com
Date: 13/08/2016 07:24:17
Message:
Fixed: Multi regions not reloading correctly after server resync
Also added a smart check to only reload it when needed (eg: AREADEF/ROOMDEF get changed on scripts)

**Comment by xwerswoodx** [comment]
I am not sure if we need that anymore, even all multi system changed in time.

**Comment by xwerswoodx** [comment]
I checked that, we don't have any issue on multis when you resync server, probably it's an old issue.

**Comment by Raylde** [comment]
Closed. Please open it again if it happens again.
