### ISSUE TITLE
while

### ISSUE THREAD

**Issue by falanlar** [Sphereserver/Source-X#634]
There is a problem with query "while"

example:
`[defname def_whiletest]
test_0 	"1"
test_1 	"2"
test_2 	"3"

[function whiletest]
while !<isempty <def.test_<dlocal._while>>>
local.test <dlocal._while>
while !<isempty <def.test_<dlocal._while>>>
src.say <dlocal.test> <dlocal._while>
endwhile
endwhile`

while normally the result should be

`1 1
1 2
1 3
2 1
2 2
2 3
3 1
3 2
3 3`
the result comes out like this
`0
0 0
0 1
0 2
0 3`

**Comment by cbnolok** [comment]
The _while local is set at a function level, not a while level, so you have to use a custom state variable

**Comment by falanlar** [comment]
Doesn't working if there is another "while" loop inside the "while" loop , it was running on the 56d version

example :
`[defname def_whiletest]
test_0 	"1"
test_1 	"2"
test_2 	"3"

[function xxx]
while !<isempty <def.test_<dLocal._While>>>
src.say <dlocal._while> <args>
endwhile

[function whiletest]
while !<isempty <def.test_<dlocal._while>>>
src.say <dlocal._while> <xxx <dlocal._while>>
endwhile``

**Comment by Ben1028** [comment]
In your first example...   the second while !<isempty <def.test<dlocal._while>>> is missing a _ so that doesn't work as intended obviously.
second, I'm pretty sure local._while starts at 0...   so the results are acurate.
