### ISSUE TITLE
istevent

### ISSUE THREAD

**Issue by alexrmrm** [Sphereserver/Source-X#635]
`[CHARDEF 07f]
DEFNAME=c_cougar
NAME=Cougar
SOUND=073
ICON=i_pet_panther
CAN=mt_walk|mt_run

DAM=4,10
ARMOR=16
HEIGHT=8
TEVENTS=e_test`

making xshow tevents list that event

but if i make xshow istevent.e_test return alwas 0

**Comment by Ben1028** [comment]
just tested here...    works fine
