### ISSUE TITLE
can_i_Dcignoredist and container

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#639]
Hello i not know if is issue or not but i explain problem.

IF i set CAN=can_i_Dcignoredist on a type t_container i can open from XXXX dist, i manage it in script.
But i can't drop item inside it, i not know if can_i_Dcignoredist also work for drag and drop.

**Comment by xMirroRx** [comment]
Also can_i_dcignoredist canseelos does not work in 0 state.

**Comment by xwerswoodx** [comment]
Because DCIgnoreDIST meaning Double Click Ignore Distance, it only ignore distance when you dclicked the item. It doesn't work on drops.

I didn't get your 0 state meaning, there is a CAN_I_DCIGNORELOS if you want to ignore canseelos instead of distance.
