### ISSUE TITLE
[PORT]c8223f203bbeb753ff0e1d3388db13e4df0b4d4a, Fixed: Internal check to prevent drop items inside walls preventing the item drop even when the wall is on another floor

### ISSUE THREAD

**Issue by fjgo86** [Sphereserver/Source-X#64]
To be tested more and eventually port.
Revision: https://github.com/Sphereserver/Source/commit/c8223f203bbeb753ff0e1d3388db13e4df0b4d4a
Author: Coruja coruja@outlook.com
Date: 21/08/2016 05:29:13
Message:
Fixed: Internal check to prevent drop items inside walls preventing the item drop even when the wall is on another floor
Fixed: Message "Too many items here!" not showing correctly when items are dropped on areas with too many items

**Comment by Jhobean** [comment]
I confirm this line is not working: `iDecayTime = 60 * TICK_PER_SEC;		// force decay (even when REGION_FLAG_NODECAY is set)`

We have some player making potion and drop them to ground at the same spot. We have like 2000 item on ground

**Comment by Jhobean** [comment]
The 2 bug don't occur on X. Exception about the wall where GM can place item on a wall so the item go up to the top level floor.

because it,s a GM, I think it's correct

```
if (pt.IsValidPoint())
    {
        if (pCharMover && pCharMover->IsPriv(PRIV_GM))
		    ptNewPlace = pt;
        else
        {
            const CPointMap ptNear = CWorldMap::FindItemTypeNearby(pt, IT_WALL, 0, true, true);
            if (!ptNear.IsValidPoint())
                ptNewPlace = pt;
        }
    }
```

**Comment by cbnolok** [comment]
So it isn't happening when gm mode is off, right?

**Comment by Jhobean** [comment]
Yes, I confirm with GM off item go back in packback if you try to drop on wall.  We could close this issue
