### ISSUE TITLE
house lock, unlock function

### ISSUE THREAD

**Issue by xMirroRx** [Sphereserver/Source-X#642]
the attr_move_never that comes with these commands is not enough.
It should be attr_static.

ItemLock
ItemUnlock

when the item expires. Items that have expired after save are deleted. serv.savestatics // only holds items that are attr_static.

**Comment by falanlar** [comment]
if you set it to attr_lockeddown the item will not be deleted and moved

**Comment by Jhobean** [comment]
Dont think attr staticis the solution.
Just remove the decay flag of set is timer to -1

**Comment by xMirroRx** [comment]
> if you set it to attr_lockeddown the item will not be deleted and moved
If you do so, attr_lockeddown will not be deleted from the items in the unlockitem -1 function. There is a solution but it's like a longer way. 
What Jhobean said is valid.
