### ISSUE TITLE
Possible bug on the |= operator inside FORCONT loop.

### ISSUE THREAD

**Issue by bororeh** [Sphereserver/Source-X#644]
In a vendor script, the vendor receives items and "locks" them (so they can be displayed in his bag but not moved around by anyone). This part goes like this:

[CHARDEF vendor]
(...)
ON=@ReceiveItem
     (...)
	ATTR |= ATTR_MOVE_NEVER                       <-- THIS PROPERLY SETS THE ATTR
	IF (<ARGO.TYPE> == t_container)
		FORCONT <ARGO> 10
			ATTR |= ATTR_MOVE_NEVER       <-- THIS DOES NOT PROPERLY SET THE ATTR! (maybe a bug?? dunno...)
		ENDFOR
	ENDIF
	
Jhobean and burpee told me that this could be a bug and so I changed the unfunctional line to:
ATTR = ATTR_MOVE_NEVER
ATTR = <ATTR>|ATTR_MOVE_NEVER

Both solutions worked fine.

Comment 1: if I try to change other parameters of the container's content, they work fine. For example:
ON=@ReceiveItem
     (...)
	ATTR |= ATTR_MOVE_NEVER
	IF (<ARGO.TYPE> == t_container)
		FORCONT <ARGO> 10
			COLOR = 0455                            <-- works fine
		ENDFOR
	ENDIF

Comment 2: this is the "reverse" part of the script, in which the player gets the items from the vendor:
ON=2                                                                       <-- this is a button on a gump
	REF1 = <UID.<TAG.CURRENT_ITEM>>
	REF1.ATTR &=~ ATTR_MOVE_NEVER              <-- works just fine
	IF (<REF1.TYPE> == t_container)
		FORCONT <REF1> 10
			ATTR &=~ ATTR_MOVE_NEVER       <-- works just fine
		ENDFOR
	ENDIF

Our conclusions: it might be a bug on the "|=" operator. Thus, I created this issue. Thanks again to Jhobean and burpee for helping my scripting.

**Comment by cbnolok** [comment]
The issue with your script is that you are giving only 1 argument to FORCONT, which expects 2 instead. Check that: https://wiki.spherecommunity.net/index.php?title=Chapter_7#FORCONT
Of course, Sphere should give a warning instead. I'll send a fix for that. In any case, thanks for the issue, it highlighted a missing warning!
