### ISSUE TITLE
@Timer not firing

### ISSUE THREAD

**Issue by xMirroRx** [Sphereserver/Source-X#648]
// This item will work when you use it on the ground. But when you take it in your bag and use it in the bag, it won't work.
[itemdef i_test]
id = i_pouch
name = Timer Test

on=@dClick
target @,,1 Target?
return 1

on=@Targon_Item
timer = 1
return 1

on=@Timer
serv.b @,,1 Give a test message..
timer = 1
return 1

//Another problem.
//This item will not be deleted when it expires.
[function f_TestFindCont]
serv.NewItem = i_testfindcont,1,<src>
new.Timer = 1

[itemdef i_testfindcont]
id = i_memory
type = t_eq_Script

on=@Timer
remove
return 1

This is an important situation.
When you cast a spell, for example s_magic_reflection will always remain on you.

**Comment by Jhobean** [comment]
Yep seem to be a problem with the recent timer change. When you look .xshow timer, you get -1?

**Comment by xMirroRx** [comment]
It shows it as 0.
I also want to add something new.

[function f_test]
serv.newitem = i_pouch
new.p = <src.p>
new.timer = 300 // He will not give this time this way. He will give a higher.

**Comment by xMirroRx** [comment]
This problem still persists.
> It shows it as 0.
> 
> //I also want to add something new.
> [function f_test]
> serv.newitem = i_pouch
> new.p = <src.p>
> new.timer = 300 // He will not give this time this way. He will give a higher.

There seems to be no problem for the above problems.

**Comment by cbnolok** [comment]
Confirmed

**Comment by xMirroRx** [comment]
Congratulations everything seems fine.
