### ISSUE TITLE
Yomotsu Mines freezing SphereX

### ISSUE THREAD

**Issue by bororeh** [Sphereserver/Source-X#651]
Latest update freezes when Yomotsu Mines are accessed. Maybe other areas trigger the same behaviour, but I haven't noticed any. Seen the same behavious on 3 computers so far.

**Comment by Jhobean** [comment]
What the coord of this mine?
Its really the server freezing?  You cant type anymore on the console or it crash?

**Comment by cbnolok** [comment]
I found something in the code that may cause it, the fix will be in the next commit

**Comment by bororeh** [comment]
This is the areadef:
[AREADEF a_yomotsu_mines]
NAME=Yomotsu Mines
GROUP=SE Dungeons
P=6,118,0,3
RECT=0,0,129,129,3
FLAGS=region_flag_nobuilding|region_flag_underground|region_antimagic_recall_in
EVENTS=r_default,r_default_rock,r_default_water,r_default_tree,r_default_grass
TAG.MUSIC=midi_TokunoDungeon

It really freezes everything. No more console access after that!
________________________________
De: Jhobean ***@***.***>
Enviado: terça-feira, 23 de março de 2021 23:41
Para: Sphereserver/Source-X ***@***.***>
Cc: André F. Rossi ***@***.***>; Author ***@***.***>
Assunto: Re: [Sphereserver/Source-X] Yomotsu Mines freezing SphereX (#651)


What the coord of this mine?
Its really the server freezing? You cant type anymore on the console or it crash?
