### ISSUE TITLE
1044265 Displaying on ore clicking. 

### ISSUE THREAD

**Issue by slow-loki** [Sphereserver/Source-X#652]
When I click on any type of ore I am prompted with "1044265" when I am not near a forge. 

It should be displaying "You are not near a Forge" 

![Ore Error](https://user-images.githubusercontent.com/73989785/112494929-5450b000-8d7b-11eb-9416-a462bc87099c.gif)

**Comment by alexdan2** [comment]
I tested cliloc ID whit simple function:

**Comment by slow-loki** [comment]
Line 35 of type_ore change to this  src.sysmessage "@,,2 <def.scp.craft_msg_smithsmeltneeds>"

**Comment by Jhobean** [comment]
Its in x script pack?

**Comment by drk84** [comment]
No problem here, what client version  and script pack are you using

**Comment by Jhobean** [comment]
![image](https://user-images.githubusercontent.com/51728381/113075459-f7019800-919a-11eb-852b-eb1df2556f7c.png)
Work A1 with last script pack and last serveur

**Comment by Jhobean** [comment]
Ok I found the Bug. it's on the script pack when you activate the OSI smelt formula
```
// Activate or deactivate the calculation of smelt chances according to OSI.
// <boolean> (1 if yes, 0 if not).
scp.OSIOreFormula=1
```

I made a Pull request to fix the message https://github.com/cbnolok/SphereX-Scriptpack/pull/80
