### ISSUE TITLE
Guild Invitewar

### ISSUE THREAD

**Issue by xMirroRx** [Sphereserver/Source-X#653]
War invites sent with Invite War are reset when the world is saved.

**Comment by xMirroRx** [comment]
TheyAlliance // Can only be read, not writed.
WeAlliance // Can only be read, not writed.

**Comment by Soulless-1** [comment]
Tested this and it appears to be working correctly
sent a guild war declaration
saved
restarted the server
went back to the guild stone and the invitation was still there

For TheyAlliance and WeAlliance thats just to check the status. if you want to alter the status use the following functions
declarewar
declarepeace
