### ISSUE TITLE
cont.consume freezes server if char does not have the item and amount

### ISSUE THREAD

**Issue by GorGoUO** [Sphereserver/Source-X#654]
That occurs with latest builds, no problem with 3403 build ie. Server freezes when use cont.consume in @timer of a memory item. Tested with last build and clean spherex script pack. That's the test and the trouble:

```
[FUNCTION f_test_dam]

serv.newitem=i_delay_dam
new.cont=<uid>
new.timer=2
	
[ITEMDEF i_delay_dam]
ID=i_memory
type=t_eq_script
	
ON=@TIMER
cont.consume 10 i_gold <--- FREEZES HERE IF I DONT HAVE 10 i_gold
cont.say ok
timer=2
return 1
```

**Comment by alexdan2** [comment]
I make some test whit this function:

```
[FUNCTION f_test_damXX]

serv.newitem=i_delay_dam
new.cont=<uid>
new.timer=2
	
[ITEMDEF i_delay_dam]
ID=i_memory
type=t_eq_script
	
ON=@TIMER
cont.say Before <CONT.RESCOUNT i_gold>
cont.consume 100 i_gold
cont.say After <CONT.RESCOUNT i_gold>
timer=2
return 1
```

And NOT get any freeze.

![image](https://user-images.githubusercontent.com/6176986/112979337-ba14b180-9158-11eb-8b5f-c7d2578617a4.png)

**Comment by alexdan2** [comment]
I confirm! This make freeze

**Comment by Jhobean** [comment]
Bug Confirm

**Comment by alexdan2** [comment]
In last release is fixed, i testet whit same function and no longer freeze

**Comment by GorGoUO** [comment]
Tested here too. Works perfectly, great job!
