### ISSUE TITLE
Decay Flag

### ISSUE THREAD

**Issue by xMirroRx** [Sphereserver/Source-X#655]
If there is a decay flag on the item, the item taken into the bag gives a warning. I think the flag should be canceled.
12:27:ERROR:Timer expired without DECAY flag 'Katana' (UID=04000b8a6)?

**Comment by cbnolok** [comment]
I don't understand the issue.
If you are overriding the @timer trigger, you should always return 1 to block the default behavior.
The default behavior is to delete an item when the timer expires, and only if there's the decay flag. If it expires but the item doesn't have the flag, then you get a warning

**Comment by xMirroRx** [comment]
ignore my first message that there is a misunderstanding.

1. ( .add i_box_wood ) target ground.
2. throw the created box into your bag.
3. display the time with the .xshow timer and you will see that the timer is not -1.
4. When the timer is 0 you will get a warning in the consol.

Another situation.

1. ( .add i_box_wood ) target ground.
2. throw the created box into your bag.
3. then take it out of the bag again and put it on the floor.
4. Check the attr_Decay flag and you will see that it does not come.
5. Reset the timer with .xtimer 1 and you will see that it is not deleted.

**Comment by alexdan2** [comment]
I confirm this issue..

.add i_dagger
Select ground
PickUP item and palace in backpack
Timer still running.. In old release when pickup item from ground timer go to -1 in backpack
and if put back on ground start normal decay timer

**Comment by Jhobean** [comment]
True.. I have some weird error on shard. Probably link to that

**Comment by alexdan2** [comment]
I make some test a work good..

**I make this test:**
- Create item on ground (normal decay time work)
- Pick up item on ground and place in backpack timer stop -1
- Drop item from backpack to ground and normal decay timer start
- Drop item from backpack to container on ground timer still -1

**Comment by GorGoUO** [comment]
I've tested this trouble and now it works like should be.

**Comment by xMirroRx** [comment]
good job.
