### ISSUE TITLE
Impossible attack monster

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#657]
Since last build ther a bug with attack. It's impossible to attack a specific NPC. The only way to fix this is by toggle War/peace button

How to reproduce:
1- Take a gm with a dagger and stay invul
2- Go on a dungeon
3- Attack one Npc
4- Change target until attack do not work (should occur on the 5 first target)

**Comment by drk84** [comment]
I add some additional information:

1. Before the attack action stops skillstart/start is still fired
2. It seems that setting timerd =0 in skillstart/start seems to prevents the blocking attack bug.
3. I am not sure about 100% about this, if timerd in @skillstart/@start is > 0 most probably the attack bug will happens.

**Comment by drk84** [comment]
This seems fixed

**Comment by alexdan2** [comment]
I try to replicate this bugs, but whit last release  Apr 24th, 2021, 2:58 pm not get any problem

**Comment by drk84** [comment]
i close cause it seems fixed
