### ISSUE TITLE
First save take 10 times the normal save time

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#658]
how reproduce:
boot a server and save. With 400k item it take 30 secondes..

The bug appear on the build 1.1.0.958 or 1.1.0.959. I cant test the 958 because the compilation failed.

![image](https://user-images.githubusercontent.com/51728381/113078540-4e0a6b80-91a1-11eb-8d03-98aa85b3e414.png)
958 is this one: https://github.com/Sphereserver/Source-X/commit/af4b65114e13c4cba4126b8065d67e7472930356

959 is this one  https://github.com/Sphereserver/Source-X/commit/8d5d59bf40c0b5bd47289757526d5952ab57819c

**Comment by alexdan2** [comment]
Yep i confirm frist save very very long

**Comment by alexdan2** [comment]
I make some test whit build: Apr 4th, 2021, 6:09 pm

But first save still long. is not a problem because other ore are more faster like 50% but i report here time:

First:
`22:06:(sphere_serv_triggers.scp,313)WorldSave Completed in 10.9080 seconds`

Other:
```
22:06:(sphere_serv_triggers.scp,313)WorldSave Completed in 2.0390 seconds
22:07:(sphere_serv_triggers.scp,313)WorldSave Completed in 1.8120 seconds
```

**Comment by cbnolok** [comment]
I tried to profile the code and honestly i can't find a reason. Giving that there's a substantial speed boost for the next worldsaves and not an overall slowdown, i'd close this issue

**Comment by Jhobean** [comment]
No problem. Its inly the first save and ALL the other ine is faster
