### ISSUE TITLE
Criminal system issue

### ISSUE THREAD

**Issue by rodBiase** [Sphereserver/Source-X#659]
When you start a fight, the attacker becomes criminal to the player who's getting attacked. Ok, working great. But if you keep fighting, the attacker turns blue in the middle of the fight. I believe the attacker should stay criminal (to the player getting attacked) as long as he is fighting. To reproduce it simply make two characters attack each other, let them "fighting" (on fist to get less damage) and you will see they will both turn blue to each other.

**Comment by soulless320** [comment]
criminal should wear off after the criminal timer in the ini. however the player should remain gray to the victim for as long as the memory item is on the victim.  there is only a short window where guards may be called on criminals.  they certainly should not go blue in the middle of a fight though.

**Comment by xwerswoodx** [comment]
Is this still an issue? Because I did tons of test in couple of days I had no issue with criminal timer.

**Comment by xwerswoodx** [comment]
As we couldn't reproduce it, and haven't heard from you for a while, I am closing this issue, please open it back if the issue still exists.
