### ISSUE TITLE
Trade Weight strange increase

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#660]
Hello when i start trade item whit other person my personal weight increase whit strange value.

**How Reproduce:**
- Take 2 chars
- Take 10 ingot on one char
- Start a trade to other person whit ingot
- See what happen to player weight start trade.

Here a mini video to explain better: https://www.youtube.com/watch?v=AkmkD-jKvwc

Tested on release before Timer Change.

**Comment by drk84** [comment]
fix sent

**Comment by alexdan2** [comment]
Problem seems fixed. Thx
