### ISSUE TITLE
dupe on pet

### ISSUE THREAD

**Issue by alexrmrm** [Sphereserver/Source-X#663]
When u make dupe on pet with owner that not increase maxfollowers of owner, but when u removed that pet discount pet of owner.

**Comment by drk84** [comment]
fix sent

**Comment by alexrmrm** [comment]
now not copy owner.
trying duping llame owner by player. player have 3 free slots make dupe on llame, and new llama havent owner.

**Comment by drk84** [comment]
If i do .xshow owner to a new duped llama i got my character uid.
If your pet slot value is equal or above the maximum follower slots the newly duped character will be not tamed and so without owner

**Comment by alexrmrm** [comment]
fixed
