### ISSUE TITLE
ship problem

### ISSUE THREAD

**Issue by xMirroRx** [Sphereserver/Source-X#664]
I need to edit this message.
I noticed that the errors in ship movements originate from tiledata.mul and there is no problem at the moment.
However, HS ships are still not assigned ownership.

**Comment by xMirroRx** [comment]
also working on can_i_dcignoredist i_ship_tillerman.

**Comment by xMirroRx** [comment]
[typedef t_Ship]
on=@Timer // not firing
serv.b Test @Timer
on=@Destroy // not firing
serv.b Test @Destroy

**Comment by cbnolok** [comment]
Is this still an issue?
