### ISSUE TITLE
Map Size for crafted maps

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#676]
There should be a way to make the maps larger, as you gain skill you can make a larger size map that is easier to read. the only map size you get now is this one 
![image](https://user-images.githubusercontent.com/17236327/117577914-dbeb4780-b0b9-11eb-9413-f2d2c3ea1ae8.png)
 
 
 example you should be able to have larger sizes, i dont see a way to make this work with the t_map typedef
 
![image](https://user-images.githubusercontent.com/17236327/117577934-fae9d980-b0b9-11eb-9d3f-e7428a145f37.png)

**Comment by drk84** [comment]
I found you can change the map size by using TDATA1 and TDATA2:

TDATA1=300	//map width
TDATA2=300

I added the information on the wiki's typedef page

**Comment by Soulless-1** [comment]
it looks like I cant set these in game though, and thats where they need to be changed based on a mapmakers quality 
![image](https://user-images.githubusercontent.com/17236327/128201447-c70a56fc-a8b2-4b07-bcc4-4a23fc942ccb.png)

**Comment by drk84** [comment]
fix sent
