### ISSUE TITLE
NPC Speech Spam

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#677]
When you try to shove passed npcs, and are unable, they just spam their speech

![image](https://user-images.githubusercontent.com/17236327/117587210-d9551600-b0ea-11eb-983b-fb5d1b6bdbdf.png)

**Comment by drk84** [comment]
I think that unless we put a delay between movement request it will not be possible to fix the spam

**Comment by Soulless-1** [comment]
I think this actually can be done in the scripts and I can close it out, the speech is the only problem.  

What might be good though in the source is if there was a trigger that was fired off when SAY is used for NPCs. @NpcSpeak to help control spam globally from npcs instead of just this one situation.

**Comment by Soulless-1** [comment]
checked this on the latest build, the issue does not occur. closing out
