### ISSUE TITLE
"Cont=" does not update the item

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#680]
Things that are moved into your bag do not update, and do not appear till you re-open the backpack

**Comment by soulless320** [comment]
looks like the issue is just when you use something like
serv.newitem i_sword_long
new.cont=<findlayer.21>

you need to do new.update after it now, whereas it was automatically updated before. is this intended?

**Comment by drk84** [comment]
The proper way is serv.newitem i_sword_long,1,<findlayer.21>

**Comment by Soulless-1** [comment]
i just wanted to make sure this wasnt an accidental change, i fixed this on my end, but wasnt certain :)  if this was intended or if this isnt a bug I can close this out

**Comment by drk84** [comment]
I remember the new.cont = <layer> was a super old trick that can still be found in the sphere wiki (https://wiki.spherecommunity.net/index.php?title=Optimization)) but until we check the old version  we can't be sure if it fires an update or not

**Comment by Soulless-1** [comment]
it did update, this happened for certain in on builds even up until recently. as my scripts with cont= all worked until recent changes.

**Comment by Jhobean** [comment]
Bug Appear on this build
https://github.com/Sphereserver/Source-X/commit/af4b65114e13c4cba4126b8065d67e7472930356

or this one 
https://github.com/Sphereserver/Source-X/commit/8d5d59bf40c0b5bd47289757526d5952ab57819c

The first build fail on appveyor so it's impossible to know witch commit add the bug

**Comment by Soulless-1** [comment]
do we think we need it to update automatically. I know it will break things for people moving to sphere-x. but its not that hard of a fix to search through items an add an update after they are moved to the bag.  i can close this if we deem it not necessary

**Comment by Jhobean** [comment]
Ok I found the bug and fixed it But @cbnolok must tell why he added these lines.

Bug occur there:
https://github.com/Sphereserver/Source-X/blob/a51e2428997534f8fa88b5a462f20705eae3b785/src/game/items/CItem.cpp#L3115-L3118

When commenting the else, there no problem.

Nolok add these 4 lines in this commit: https://github.com/Sphereserver/Source-X/commit/af4b65114e13c4cba4126b8065d67e7472930356

To reproduce, simply add this:

```
[FUNCTION test]
serv.newitem i_dagger
NEW.CONT=<findlayer.21>
```

**Comment by cbnolok** [comment]
That fixed another cont bug that's reported in the changelog

**Comment by Jhobean** [comment]
> That fixed another cont bug that's reported in the changelog

I tryed to reproduce the "old bug" here: https://discordapp.com/channels/354358315373035542/483721253773901824/867583095980032061
Do you remember what exactly was the old bug? `Fixed: Object not being removed from client view when its CONT was changed.`

**Comment by a1exp** [comment]
guys, is there a plan for this issue? @cbnolok @Jhobean would be nice if you either agree on a solution or say it won't be fixed, so that we understand if we should wait for something or not. 

Unfortunately solution which @drk84 proposed works only for new items. There are some cases when I need to move an item form one container to another and calling update is like adding `update` every tiem you change player's gold on 56b until it was fixed on 56c.. really annoying.

**Comment by Soulless-1** [comment]
Confirmed Fixed, closing out.
