### ISSUE TITLE
House Secure This

### ISSUE THREAD

**Issue by youhide** [Sphereserver/Source-X#685]
when release a secured item with "secure this" and u can't secure or lock item on this house anymore, maybe it buggy the storage limit
released a locked item is fine on my tests, just that secure container is weird...

this error shows up on save:

10:25:CRITICAL:"Access Violation" (0x7c110), in Write Object 04003898b

this shows on house redeed:

10:27:DEBUG:Printing STACK TRACE for debugging purposes.
10:27:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ |
10:27:DEBUG:(03316)          T_Main |  0 |                      CWorld::_OnTick |  
10:27:DEBUG:(03316)          T_Main |  1 |              CItemMulti::~CItemMulti |  
10:27:DEBUG:(03316)          T_Main |  2 |           CItemMulti::UnlockAllItems | <-- last function call (stack unwinding began here)
10:27:DEBUG:(03316)          T_Main |  3 |               CItemMulti::UnlockItem |  
10:27:DEBUG:(03316)          T_Main |  4 |                    CSFileText::Close |  
10:27:DEBUG:(03316)          T_Main |  5 |                   CSFileText::_Close |  
10:27:DEBUG:(03316)          T_Main |  6 |                  CObjBase::r_LoadVal |  
10:27:DEBUG:(03316)          T_Main |  7 |         CResourceRefArray::r_LoadVal |  
10:27:DEBUG:(03316)          T_Main |  8 |  CResourceBase::ResourceGetDefByName |  
10:27:DEBUG:(03316)          T_Main |  9 |        CServerConfig::ResourceGetDef |  
10:27:DEBUG:(03316)          T_Main | 10 |        CResourceBase::ResourceGetDef |  
10:27:DEBUG:(03316)          T_Main | 11 |                  CExpression::GetVal |  
10:27:DEBUG:(03316)          T_Main | 12 |              CExpression::GetValMath |  
10:27:DEBUG:(03316)          T_Main | 13 |                        CSFile::_Seek |  
10:27:DEBUG:(03316)          T_Main | 14 |                   CSFileText::_Close |  
10:27:DEBUG:(03316)          T_Main | 15 |                   CScriptObj::r_Verb |  
10:27:DEBUG:(03316)          T_Main | 16 |              CRegionWorld::r_LoadVal |  
10:27:DEBUG:(03316)          T_Main | 17 |                   CRegion::r_LoadVal |  
10:27:DEBUG:(03316)          T_Main | 18 |                 CScriptObj::r_GetRef |  
10:27:DEBUG:(03316)          T_Main | 19 |          CNetworkOutput::QueuePacket |  
10:27:DEBUG:(03316)          T_Main | 20 | CNetworkOutput::QueuePacketTransacti |  
10:27:DEBUG:(03316)          T_Main | 21 | CNetworkOutput::QueuePacketTransacti |  
10:27:DEBUG:(03316)          T_Main | 22 |              CClient::addBarkUNICODE |  
10:27:DEBUG:(03316)          T_Main | 23 | PacketMessageUNICODE::PacketMessageU |  
10:27:DEBUG:(03316)          T_Main | 24 |                     PacketSend::push |  
10:27:DEBUG:(03316)          T_Main | 25 |          CNetworkOutput::QueuePacket |  
10:27:DEBUG:(03316)          T_Main | 26 | CNetworkOutput::QueuePacketTransacti |  
10:27:DEBUG:(03316)          T_Main | 27 |                        CChar::CanSee |  
10:27:DEBUG:(03316)          T_Main | 28 |                    CChar::CanSeeItem |  
10:27:DEBUG:(03316)          T_Main | 29 |                     PacketSend::push |  
10:27:DEBUG:(03316)          T_Main | 30 |          CNetworkOutput::QueuePacket |  
10:27:DEBUG:(03316)          T_Main | 31 | CNetworkOutput::QueuePacketTransacti |  
10:27:DEBUG:(03316)          T_Main | 32 | CNetworkOutput::QueuePacketTransacti |  
10:27:DEBUG:(03316)          T_Main | 33 |        CResourceDef::GetResourceName |  
10:27:DEBUG:(03316)          T_Main | 34 |        CResourceBase::ResourceGetDef |  
10:27:DEBUG:(03316)          T_Main | 35 |        CResourceDef::GetResourceName |  
10:27:DEBUG:(03316)          T_Main | 36 |              CExpression::GetValMath |  
10:27:DEBUG:(03316)          T_Main | 37 | CNetworkOutput::QueuePacketTransacti |  
10:27:DEBUG:(03316)          T_Main | 38 |         CCacheableScriptFile::_Close |  
10:27:DEBUG:(03316)          T_Main | 39 |         CResourceLock::_ReadTextLine |  
10:27:DEBUG:(03316)          T_Main | 40 |                  CExpression::GetVal |  
10:27:DEBUG:(03316)          T_Main | 41 |              CExpression::GetValMath |  
10:27:DEBUG:(03316)          T_Main | 42 |                  CExpression::GetVal |  
10:27:DEBUG:(03316)          T_Main | 43 |              CExpression::GetValMath |  
10:27:DEBUG:(03316)          T_Main | 44 |        CResourceBase::ResourceGetDef |  
10:27:DEBUG:(03316)          T_Main | 45 |        CResourceDef::GetResourceName |  
10:27:DEBUG:(03316)          T_Main | 46 |        CResourceDef::GetResourceName |  
10:27:DEBUG:(03316)          T_Main | 47 |        CResourceQtyArray::WriteNames |  
10:27:DEBUG:(03316)          T_Main | 48 |        CResourceQty::WriteNameSingle |  
10:27:DEBUG:(03316)          T_Main | 49 |        CServerConfig::ResourceGetDef |  
10:27:DEBUG:(03316)          T_Main | 50 |         CResourceBase::ResourceGetID |  
10:27:DEBUG:(03316)          T_Main | 51 | CResourceBase::ResourceGetID_Advance |  
10:27:DEBUG:(03316)          T_Main | 52 |                  CExpression::GetVal |  
10:27:DEBUG:(03316)          T_Main | 53 |              CExpression::GetValMath |  
10:27:DEBUG:(03316)          T_Main | 54 |        CServerConfig::ResourceGetDef |  
10:27:DEBUG:(03316)          T_Main | 55 |         CResourceBase::ResourceGetID |  
10:27:DEBUG:(03316)          T_Main | 56 | CResourceBase::ResourceGetID_Advance |  
10:27:DEBUG:(03316)          T_Main | 57 |                  CExpression::GetVal |  
10:27:DEBUG:(03316)          T_Main | 58 |              CExpression::GetValMath |  
10:27:DEBUG:(03316)          T_Main | 59 |              CExpression::GetValMath |  
10:27:DEBUG:(03316)          T_Main | 60 |              CExpression::GetValMath |  
10:27:DEBUG:(03316)          T_Main | 61 |                      CScript::_Close |  
10:27:DEBUG:(03316)          T_Main | 62 |         CCacheableScriptFile::_Close |  
10:27:DEBUG:(03316)          T_Main | 63 |                   CSFileText::_Close |  
10:27:DEBUG:(03316)          T_Main | 64 |                    CSFileText::Close |  
10:27:DEBUG:(03316)          T_Main | 65 |                   CSFileText::_Close |  
10:27:DEBUG:(03316)          T_Main | 66 |                      CScript::_Close |  
10:27:DEBUG:(03316)          T_Main | 67 |         CCacheableScriptFile::_Close |  
10:27:DEBUG:(03316)          T_Main | 68 |                   CSFileText::_Close |  
10:27:DEBUG:(03316)          T_Main | 69 |             CSFileText::_WriteString |  
10:27:DEBUG:(03316)          T_Main | 70 |                   CSFileText::_Write |  
10:27:DEBUG:(03316)          T_Main | 71 |                 CScriptObj::r_GetRef |  
10:27:DEBUG:(03316)          T_Main | 72 |                   CSFileText::_Close |  
10:27:DEBUG:(03316)          T_Main | 73 |                      CScript::_Close |  
10:27:DEBUG:(03316)          T_Main | 74 |         CCacheableScriptFile::_Close |  
10:27:DEBUG:(03316)          T_Main | 75 |              CExpression::GetValMath |  
10:27:DEBUG:(03316)          T_Main | 76 |                 CCFaction::CCFaction |  
10:27:DEBUG:(03316)          T_Main | 77 |               CScriptObj::r_WriteVal |  
10:27:DEBUG:(03316)          T_Main | 78 |             CScriptObj::r_GetRefFull |  
10:27:DEBUG:(03316)          T_Main | 79 |                    CClient::r_GetRef |  
10:27:DEBUG:(03316)          T_Main | 80 |                 CScriptObj::r_GetRef |  
10:27:DEBUG:(03316)          T_Main | 81 |          CNetworkOutput::QueuePacket |  
10:27:DEBUG:(03316)          T_Main | 82 | CNetworkOutput::QueuePacketTransacti |  
10:27:DEBUG:(03316)          T_Main | 83 |           CItemContainer::ContentAdd |  
10:27:DEBUG:(03316)          T_Main | 84 |         CObjBase::UpdatePropertyFlag |  
10:27:DEBUG:(03316)          T_Main | 85 |                      CClient::CanSee |  
10:27:DEBUG:(03316)          T_Main | 86 |                        CChar::CanSee |  
10:27:DEBUG:(03316)          T_Main | 87 |            CTimedObject::_SetTimeout |  
10:27:DEBUG:(03316)          T_Main | 88 |         CCacheableScriptFile::_Close |  
10:27:DEBUG:(03316)          T_Main | 89 |         CResourceLock::_ReadTextLine |  
10:27:DEBUG:(03316)          T_Main | 90 |                  CExpression::GetVal |  
10:27:DEBUG:(03316)          T_Main | 91 |              CExpression::GetValMath |  
10:27:DEBUG:(03316)          T_Main | 92 |                  CExpression::GetVal |  
10:27:DEBUG:(03316)          T_Main | 93 |              CExpression::GetValMath |  
10:27:DEBUG:(03316)          T_Main | 94 |        CResourceDef::GetResourceName |  
10:27:DEBUG:(03316)          T_Main | 95 |        CResourceBase::ResourceGetDef |  
10:27:DEBUG:(03316)          T_Main | 96 |        CResourceDef::GetResourceName |  
10:27:DEBUG:(03316)          T_Main | 97 |               CExpression::GetSingle |  
10:27:CRITICAL:"Access Violation" (0x7a620), in ExcType=CSError catched in CItemMulti::Cleanup in destructor()

**Comment by Soulless-1** [comment]
I believe XuN fixed this recently, can you please confirm with the latest build?

**Comment by youhide** [comment]
that was on latests builds

**Comment by Soulless-1** [comment]
well the issue was opened 28 days ago, so that would not be the latest build. :)

**Comment by youhide** [comment]
are u talking about this?
https://github.com/Sphereserver/Source-X/commit/e7e31183dd835ce4520727b53dbe273fa362f27c

**Comment by youhide** [comment]
on last build, when we release secured and locked container...

13:10:DEBUG:Printing STACK TRACE for debugging purposes.
13:10:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ |
13:10:DEBUG:(09644)          T_Main |  0 |                      CWorld::_OnTick |  
13:10:DEBUG:(09644)          T_Main |  1 |              CItemMulti::~CItemMulti |  
13:10:DEBUG:(09644)          T_Main |  2 |           CItemMulti::UnlockAllItems | <-- last function call (stack unwinding began here)
13:10:DEBUG:(09644)          T_Main |  3 |               CItemMulti::UnlockItem |  
13:10:DEBUG:(09644)          T_Main |  4 |             CScriptObj::r_ExecSingle |  
13:10:DEBUG:(09644)          T_Main |  5 |                    CSFileText::Close |  
13:10:DEBUG:(09644)          T_Main |  6 |                   CSFileText::_Close |  
13:10:DEBUG:(09644)          T_Main |  7 |                   CScriptObj::r_Verb |  
13:10:DEBUG:(09644)          T_Main |  8 |             CItemVendable::r_LoadVal |  
13:10:DEBUG:(09644)          T_Main |  9 |                     CItem::r_LoadVal |  
13:10:DEBUG:(09644)          T_Main | 10 |                  CObjBase::r_LoadVal |  
13:10:DEBUG:(09644)          T_Main | 11 |         CResourceRefArray::r_LoadVal |  
13:10:DEBUG:(09644)          T_Main | 12 |  CResourceBase::ResourceGetDefByName |  
13:10:DEBUG:(09644)          T_Main | 13 |        CServerConfig::ResourceGetDef |  
13:10:DEBUG:(09644)          T_Main | 14 |        CResourceBase::ResourceGetDef |  
13:10:DEBUG:(09644)          T_Main | 15 |                  CExpression::GetVal |  
13:10:DEBUG:(09644)          T_Main | 16 |              CExpression::GetValMath |  
13:10:DEBUG:(09644)          T_Main | 17 |              CExpression::GetValMath |  
13:10:DEBUG:(09644)          T_Main | 18 |              CExpression::GetValMath |  
13:10:DEBUG:(09644)          T_Main | 19 |                 CScriptObj::r_GetRef |  
13:10:DEBUG:(09644)          T_Main | 20 |          CNetworkOutput::QueuePacket |  
13:10:DEBUG:(09644)          T_Main | 21 | CNetworkOutput::QueuePacketTransacti |  
13:10:DEBUG:(09644)          T_Main | 22 | CNetworkOutput::QueuePacketTransacti |  
13:10:DEBUG:(09644)          T_Main | 23 |              CClient::addBarkUNICODE |  
13:10:DEBUG:(09644)          T_Main | 24 | PacketMessageUNICODE::PacketMessageU |  
13:10:DEBUG:(09644)          T_Main | 25 |                     PacketSend::push |  
13:10:DEBUG:(09644)          T_Main | 26 |          CNetworkOutput::QueuePacket |  
13:10:DEBUG:(09644)          T_Main | 27 | CNetworkOutput::QueuePacketTransacti |  
13:10:DEBUG:(09644)          T_Main | 28 |                        CChar::CanSee |  
13:10:DEBUG:(09644)          T_Main | 29 |                    CChar::CanSeeItem |  
13:10:DEBUG:(09644)          T_Main | 30 |                     PacketSend::push |  
13:10:DEBUG:(09644)          T_Main | 31 |          CNetworkOutput::QueuePacket |  
13:10:DEBUG:(09644)          T_Main | 32 | CNetworkOutput::QueuePacketTransacti |  
13:10:DEBUG:(09644)          T_Main | 33 |                  CExpression::GetVal |  
13:10:DEBUG:(09644)          T_Main | 34 |              CExpression::GetValMath |  
13:10:DEBUG:(09644)          T_Main | 35 |                  CExpression::GetVal |  
13:10:DEBUG:(09644)          T_Main | 36 |              CExpression::GetValMath |  
13:10:DEBUG:(09644)          T_Main | 37 |             CScriptObj::r_GetRefFull |  
13:10:DEBUG:(09644)          T_Main | 38 |                      CChar::r_GetRef |  
13:10:DEBUG:(09644)          T_Main | 39 |                   CObjBase::r_GetRef |  
13:10:DEBUG:(09644)          T_Main | 40 |                 CScriptObj::r_GetRef |  
13:10:DEBUG:(09644)          T_Main | 41 |                 CScriptObj::r_GetRef |  
13:10:DEBUG:(09644)          T_Main | 42 |                      CChar::r_GetRef |  
13:10:DEBUG:(09644)          T_Main | 43 |                   CObjBase::r_GetRef |  
13:10:DEBUG:(09644)          T_Main | 44 |                 CScriptObj::r_GetRef |  
13:10:DEBUG:(09644)          T_Main | 45 | CResourceBase::ResourceGetID_Advance |  
13:10:DEBUG:(09644)          T_Main | 46 |                  CExpression::GetVal |  
13:10:DEBUG:(09644)          T_Main | 47 |              CExpression::GetValMath |  
13:10:DEBUG:(09644)          T_Main | 48 |               CItem::IsResourceMatch |  
13:10:DEBUG:(09644)          T_Main | 49 |       CContainer::ContentConsumeTest |  
13:10:DEBUG:(09644)          T_Main | 50 |       CContainer::ContentConsumeTest |  
13:10:DEBUG:(09644)          T_Main | 51 |               CItem::IsResourceMatch |  
13:10:DEBUG:(09644)          T_Main | 52 |        CResourceQtyArray::WriteNames |  
13:10:DEBUG:(09644)          T_Main | 53 |        CResourceQty::WriteNameSingle |  
13:10:DEBUG:(09644)          T_Main | 54 |        CServerConfig::ResourceGetDef |  
13:10:DEBUG:(09644)          T_Main | 55 |        CResourceBase::ResourceGetDef |  
13:10:DEBUG:(09644)          T_Main | 56 | CResourceBase::ResourceGetID_Advance |  
13:10:DEBUG:(09644)          T_Main | 57 |                  CExpression::GetVal |  
13:10:DEBUG:(09644)          T_Main | 58 |              CExpression::GetValMath |  
13:10:DEBUG:(09644)          T_Main | 59 |                  CExpression::GetVal |  
13:10:DEBUG:(09644)          T_Main | 60 |              CExpression::GetValMath |  
13:10:DEBUG:(09644)          T_Main | 61 |                  CExpression::GetVal |  
13:10:DEBUG:(09644)          T_Main | 62 |              CExpression::GetValMath |  
13:10:DEBUG:(09644)          T_Main | 63 |                  CExpression::GetVal |  
13:10:DEBUG:(09644)          T_Main | 64 |              CExpression::GetValMath |  
13:10:DEBUG:(09644)          T_Main | 65 |         CCacheableScriptFile::_Close |  
13:10:DEBUG:(09644)          T_Main | 66 |                    CSFileText::Close |  
13:10:DEBUG:(09644)          T_Main | 67 |                   CSFileText::_Close |  
13:10:DEBUG:(09644)          T_Main | 68 |                      CScript::_Close |  
13:10:DEBUG:(09644)          T_Main | 69 |         CCacheableScriptFile::_Close |  
13:10:DEBUG:(09644)          T_Main | 70 |   CScriptObj::r_Call (FunctionIndex) |  
13:10:DEBUG:(09644)          T_Main | 71 |                    CSFileText::Close |  
13:10:DEBUG:(09644)          T_Main | 72 |                   CSFileText::_Close |  
13:10:DEBUG:(09644)          T_Main | 73 |                      CScript::_Close |  
13:10:DEBUG:(09644)          T_Main | 74 |         CCacheableScriptFile::_Close |  
13:10:DEBUG:(09644)          T_Main | 75 |                    CSFileText::Close |  
13:10:DEBUG:(09644)          T_Main | 76 |                   CSFileText::_Close |  
13:10:DEBUG:(09644)          T_Main | 77 |                      CScript::_Close |  
13:10:DEBUG:(09644)          T_Main | 78 |         CCacheableScriptFile::_Close |  
13:10:DEBUG:(09644)          T_Main | 79 |         CResourceLock::_ReadTextLine |  
13:10:DEBUG:(09644)          T_Main | 80 |    CScriptObj::r_Call (FunctionName) |  
13:10:DEBUG:(09644)          T_Main | 81 |   CScriptObj::r_Call (FunctionIndex) |  
13:10:DEBUG:(09644)          T_Main | 82 |                    CSFileText::Close |  
13:10:DEBUG:(09644)          T_Main | 83 |                   CSFileText::_Close |  
13:10:DEBUG:(09644)          T_Main | 84 |                      CScript::_Close |  
13:10:DEBUG:(09644)          T_Main | 85 |         CCacheableScriptFile::_Close |  
13:10:DEBUG:(09644)          T_Main | 86 |                   CSFileText::_Close |  
13:10:DEBUG:(09644)          T_Main | 87 |                    CSFileText::Close |  
13:10:DEBUG:(09644)          T_Main | 88 |                   CSFileText::_Close |  
13:10:DEBUG:(09644)          T_Main | 89 |                      CScript::_Close |  
13:10:DEBUG:(09644)          T_Main | 90 |         CCacheableScriptFile::_Close |  
13:10:DEBUG:(09644)          T_Main | 91 |                   CSFileText::_Close |  
13:10:DEBUG:(09644)          T_Main | 92 |             CSFileText::_WriteString |  
13:10:DEBUG:(09644)          T_Main | 93 |                   CSFileText::_Write |  
13:10:DEBUG:(09644)          T_Main | 94 |                 CScriptObj::r_GetRef |  
13:10:DEBUG:(09644)          T_Main | 95 |                   CSFileText::_Close |  
13:10:DEBUG:(09644)          T_Main | 96 |                      CScript::_Close |  
13:10:DEBUG:(09644)          T_Main | 97 |         CCacheableScriptFile::_Close |  
13:10:DEBUG:(09644)          T_Main | 98 |              CExpression::GetValMath |  
13:10:DEBUG:(09644)          T_Main | 99 |                 CCFaction::CCFaction |  
13:10:DEBUG:(09644)          T_Main | 100 |               CScriptObj::r_WriteVal |  
13:10:DEBUG:(09644)          T_Main | 101 |             CScriptObj::r_GetRefFull |  
13:10:DEBUG:(09644)          T_Main | 102 |                    CClient::r_GetRef |  
13:10:DEBUG:(09644)          T_Main | 103 |                 CScriptObj::r_GetRef |  
13:10:DEBUG:(09644)          T_Main | 104 |                 CObjBase::r_WriteVal |  
13:10:DEBUG:(09644)          T_Main | 105 |               CScriptObj::r_WriteVal |  
13:10:DEBUG:(09644)          T_Main | 106 |             CScriptObj::r_GetRefFull |  
13:10:DEBUG:(09644)          T_Main | 107 |                      CChar::r_GetRef |  
13:10:DEBUG:(09644)          T_Main | 108 |                   CObjBase::r_GetRef |  
13:10:DEBUG:(09644)          T_Main | 109 |                 CScriptObj::r_GetRef |  
13:10:CRITICAL:"Access Violation" (0x7b250), in ExcType=CSError catched in CItemMulti::Cleanup in destructor()

**Comment by Soulless-1** [comment]
Can confirm there is still an issue with lockdowns,secures,releases.

I had a house that had several thousand lines of lockdowns even though it only had about 15-20 lockdowns in the house actually. uids of the lockdowns ranged from vendors in shops around the world, to bananas, or other random items that had nothing to do with the house.

**Comment by AtillaG1** [comment]
its been already fixed, right?
Its working for me.

**Comment by Tolokio** [comment]
fixed or not?

**Comment by AtillaG1** [comment]
fixed, close.

**Comment by youhide** [comment]
k, closed
