### ISSUE TITLE
Feature Request : local.effect under on=@spelleffect

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-X#686]
can you please add local.effect under @spelleffect to directly control the exact amount of damage dealt.  Beneficial for a proper working magical resistance system.

**Comment by drk84** [comment]
You need to set local.resist = 0 in spelleffect to disable default magic resistance check

**Comment by soulless320** [comment]
I'll do that also, but we still need local.effect to control the exact damage done under @spelleffect on the player. argn1 just doesnt seem to work well enough . r

**Comment by drk84** [comment]
Local.effect in spelleffect works fine here, check if you have multiple spelleffect in different events or your local.effect formula has something wrong.

![immagine](https://user-images.githubusercontent.com/13728442/119775336-c05aac00-bec3-11eb-9703-358cec67657e.png)
![immagine](https://user-images.githubusercontent.com/13728442/119775368-c9e41400-bec3-11eb-96a9-619affa33420.png)

**Comment by soulless320** [comment]
oops my mistake, thank you for clearing that up for me drk!
