### ISSUE TITLE
Dragon Breath with no delay

### ISSUE THREAD

**Issue by RodVIII** [Sphereserver/Source-X#689]
I found odd they were using the breath action 4-5 times in less than a second on my server. So I downloaded a clean scriptpack and the latest X version to test it. It still happens.

To reproduce: just create a greater dragon (or whatever dragon), wait for him to use the breath action on you. Sometimes he will breath 3-4 times in less than a second.

**Comment by drk84** [comment]
I can't reproduce it

**Comment by drk84** [comment]
Found the issue

**Comment by drk84** [comment]
Fix Sent.

**Comment by drk84** [comment]
I close this, it seems fixed to me.
