### ISSUE TITLE
afk command

### ISSUE THREAD

**Issue by alexrmrm** [Sphereserver/Source-X#694]
fast spam message z

`	if ( stage == SKTRIG_STROKE )
	{
		if ( m_Act_p != GetTopPoint())
			return -SKTRIG_QTY;	// we moved.
		_SetTimeout(8);
		Speak( "z", HUE_WHITE, TALKMODE_WHISPER );
		return -SKTRIG_STROKE;	// Stay in the skill till we hit.
	}`

**Comment by drk84** [comment]
Fix Sent.

**Comment by alexrmrm** [comment]
fixed.
