### ISSUE TITLE
mindblast not firing @effect

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#696]
seems like mindblast does not fire the @effect when you target players with it.  only appears to work on NPCs

**Comment by drk84** [comment]
It works on players, the problem is that @effect is not fired when the target intelligence is near to the caster intelligence and the mind blast "power" is 0

**Comment by Soulless-1** [comment]
ah i see, that makes it difficult to customize it on effect

I have customized it on success to work around this but it makes me sad that i cant use @effect

**Comment by drk84** [comment]
Fix sent

**Comment by Soulless-1** [comment]
fixed, thank you Drk!
