### ISSUE TITLE
magic trap @effect not working

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#697]
looks like I cant fire @effect under the magic trap spell either.

**Comment by drk84** [comment]
Fix sent, remember that there is no behaviour for magic trap / untrap (for now) but the spelleffect/effect triggers are properly fired now.

**Comment by Soulless-1** [comment]
looks like i still couldnt get this one to fire

**Comment by drk84** [comment]
By default the spells has SPELLFLAG_TARG_ITEM, so you need to cast it on a item

**Comment by Soulless-1** [comment]
i casted it on a pouch, and couldnt get it to fire off `[SPELL 13]
DEFNAME=s_magic_trap
NAME=Magic Trap
SOUND=snd_spell_magic_trap
RUNES=IJ
CAST_TIME=1.0
RESOURCES=i_reag_garlic,i_reag_spider_silk,i_reag_sulfur_ash
RUNE_ITEM=i_rune_magic_trap
SCROLL_ITEM=i_scroll_magic_trap
FLAGS=spellflag_dir_anim|spellflag_targ_item|spellflag_playeronly
EFFECT_ID=0
EFFECT=0
DURATION=0.0
MANAUSE=6
SKILLREQ=MAGERY 10.0
INTERRUPT=100.0,100.0

//Magic Trap can be used to trap containers. When opened, these containers will damage the person attempting to open it. For this reason, magic trapped pouches can be used to counter the Paralyze spell.
on=@effect
//if (<type>==t_container)
  //events=+t_magic_trapped_container
//endif
serv.b effect @ <name>
return 1
`

**Comment by drk84** [comment]
It works here
![immagine](https://user-images.githubusercontent.com/13728442/121488269-376b6680-c9d3-11eb-964c-25af12321226.png)

**Comment by Soulless-1** [comment]
Confirmed that this is fixed, closing out. Thank you Drk
