### ISSUE TITLE
Trying to build project using raspberry pi 4

### ISSUE THREAD

**Issue by ted182** [Sphereserver/Source-X#709]
when a tryed to compile using make comand, it returns this error:
g++: error: unrecognized command-line option ‘-m64’

I'm runnig ubuntu server 20 on raspberry pi 4.

I think it has to do with the processor architecture, any ideas?

**Comment by ted182** [comment]
I found a way to avoid errors compiling in rasp 4, just edit the file **Linux-GNU-64.cmake**
`SET (C_ARCH_OPTS	"-march=native")
SET (CXX_ARCH_OPTS	"-march=native")`

then run cmake comand.

**Comment by cbnolok** [comment]
Yup it's as you said, selecting a toolchain enforces an architecture. I'll add a new toolchain for the native arch
