### ISSUE TITLE
Region flags issue

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#713]
regions nested inside regions dont seem to have their flags recognized as the region flags that should be used. for instance inside sweet dreams inn instalog out flag should be used, allowing people to log out instantly (if not in combat)

**Comment by cbnolok** [comment]
Imho it's not a bug but more a feature request, since when you define a new region or room you are supposed to specify also the flags. They were never inherited.
An idea could be to add the regionflag regionf_inherit.

**Comment by Soulless-1** [comment]
I did find that room.flags also can pull the information I needed for what I wanted to do. So both are accessible . I think this is just  my personal problem and not something we need unless you want that feature request to stay in. 

I did notice with multis, such as a bed, or spinning wheel in a house region, that you are no long considered inside the house, that's more of an actual issue. but I think you can set the region size to 0 for those small multis and avoid this issue.

**Comment by cbnolok** [comment]
This should be solved with commit a09d665f3d384fe9584d2db3f66396faf5a9094f AREAFLAGs.

**Comment by Soulless-1** [comment]
closing
