### ISSUE TITLE
Message board dates

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#714]
attempting to add manual posts to the message board with a function using serv.time or serv.rtime results in the incorrect date being displayed. 

![image](https://user-images.githubusercontent.com/17236327/122781133-83dd5e80-d27d-11eb-87ac-18db3200c014.png)

**Comment by drk84** [comment]
Was this fixed?

**Comment by Soulless-1** [comment]
No this still seems to be an issue

**Comment by Soulless-1** [comment]
This is resolved. closing
