### ISSUE TITLE
A way to to disable sphere's internal functions for magic items

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#718]
there are scenarios where you would like to have magic clothing, but not use spheres internal code for it.  or magic weapons, yet setting  some of the more settings on these items will cause strange interactions with spheres internal code and your custom script.

example setting a weapons morex to 38 will cause you to be paralyzed when you equip it, and you cannot unequip it. 

I propose that there should be a flag in the ini to disable spheres internal code for magic items entirely, so we can script that ourselves without interference

**Comment by drk84** [comment]
38 is the paralyze spells, you can avoid to use the morex value and just use a tag. moreee simple

**Comment by Soulless-1** [comment]
this is what I do, but thought it might be better to find a way to disable. If you do things like custom poison system also you start to run out of more values :P which is my situation. It strikes me as strange, that without the magic attr that this weapon with morex 38 would paralyze you.

**Comment by drk84** [comment]
For me the bug (a part the magic attr) is that only the paralyze flags is applied while the paralyze spell item is not actually installed and thus the effect/spelleffect triggers are not fired.
 I can take a look at but take in mind that these magic item using morex are using at least 15 years old code.  I think nobody ever touched them again

**Comment by Soulless-1** [comment]
agreed, i think the paralyze spell effect should be used, not just the flag. But i also think that if magic attr is not applied, it shouldnt be used. and I wouldnt mind honestly a way to disable magic attr internally entirely, I did make my own attrs for magic armor/weapons/clothing but It would be nice to use the default attrs. 

This is just my suggestion because I know redoing all the scripts and putting my own systems into place is a completely optional path I have taken, and not the standard way people will build their shards. But I think an option to disable magic_attr completely would satisfy both types of people.

**Comment by cbnolok** [comment]
Can't you just use another attr, like attr_magic_custom?

**Comment by Soulless-1** [comment]
I do use a custom one, but morex still will do spell effects when set on a weapon, even if not attr_magic.  seems like a bug
