### ISSUE TITLE
[PORT]f1b5cffa0081d12aecf6600447ccae32cb752925, Fixed: Mass Curse spell not working correctly

### ISSUE THREAD

**Issue by fjgo86** [Sphereserver/Source-X#72]
Revision: https://github.com/Sphereserver/Source/commit/f1b5cffa0081d12aecf6600447ccae32cb752925
Author: Coruja coruja@outlook.com
Date: 21/12/2016 06:52:38
Message:
Fixed: Mass Curse spell not working correctly

**Comment by nefthon** [comment]
I think this one needs a little more understanding because, at first sight, it seems that mass curse will not do props/buff updates with COMBAT_ELEMENTAL_ENGINE set

**Comment by xwerswoodx** [comment]
Seems like this has already ported, so maybe we can close that issue.

**Comment by cbnolok** [comment]
So is everything working with mass curse?

**Comment by xwerswoodx** [comment]
I haven't tried but seems like it's already ported, for me everything seems fine but I can make some test and can edit this message for result.

**Comment by xwerswoodx** [comment]
Anyway I found out the reason is script side, when you haven't set duration under spell it causes spell effect stay still because timer is -1.
