### ISSUE TITLE
Vendor sell dialog issue

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#722]
It appears some items that show the amount in the "item" column, instead of just in the "avail." column
![image](https://user-images.githubusercontent.com/17236327/123876984-5a21d880-d90a-11eb-9789-c546226a1760.png)

**Comment by criminalx** [comment]
it happen to me too, i was thinking it was orion issue

**Comment by Soulless-1** [comment]
I had considered that possibility also, but this picture was from the vanilla client. Atleast I recall this being the case :)

**Comment by Jhobean** [comment]
@criminalx there was a similar bug with orion about picture and text. It was fix by hotride.

**Comment by drk84** [comment]
So it's a client problem?

**Comment by Soulless-1** [comment]
Confirmed, this is a client problem, closing out. Will bring it up with in the proper place at classicuo
