### ISSUE TITLE
Bags inside bags

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#723]
By default you cannot put bags inside bags, this should be a toggle, allowed by default. I did not see an option to allow this, but player chars get this message when attempting to put a i_bag inside an i_bag .  As far back as I remember there was never a restriction on putting a bag inside a bag. 

![image](https://user-images.githubusercontent.com/17236327/124004588-298f7c80-d9a6-11eb-8050-05de2a2aa7da.png)

**Comment by drk84** [comment]
I added a new flag in the ini called OF_AllowContainerInsideContainer that should solve the problem.

**Comment by Jhobean** [comment]
https://github.com/Sphereserver/Source-X/commit/12224eef08a5920c7e5248dec4b77fe76b777261

**Comment by Soulless-1** [comment]
works, but would it be possible to reverse this 
 OF_DisallowContainerInsideContainer 
 instead? 
 
 it seems backwards that we are enabling flags to disable custom behavior ? I only suggest this to give people the expected behavior out of the box instead of having a custom feature come default.

**Comment by cbnolok** [comment]
Are we sure that on older builds that was the default behavior, which at some point was changed?

**Comment by drk84** [comment]
It's from 56b
![immagine](https://user-images.githubusercontent.com/13728442/124511902-707ed700-ddd7-11eb-93c4-a23ed219291c.png)

**Comment by Soulless-1** [comment]
I mean the default behavior for UO. There was never a time that I can recall (and can't confirm on any official server, or era shard now) that you could not place a bag inside a bag. I recall on 55i having bags organized in bags on many shards. 

So when I say default I just mean the default UO Behavior, that sphere is emulating. It's just my honest opinion that we shouldn't be having custom behavior hardcoded, that conflicts with the normal expected behavior of UO. Something like this could easily be scripted for people that wanted it.

**Comment by Jhobean** [comment]
Changing the defaut value on the ini should do the trick without changing the name of flag

**Comment by Jhobean** [comment]
Someone Have a 55i server and can test?

**Comment by Soulless-1** [comment]
As far back as 55i it worked this way also, bags being blocked from being put inside bags, but just because in the past something worked wrong doesn't mean we should suffer the same fate today :)

**Comment by Jhobean** [comment]
@Soulless-1 so that mean with the actual setting its fine.  People installing sphere want to play sphere like in the past.
So in my opinion, the commit drk did is fine and give admin acces to be like "osi uo standard". I think issue can be close.

**Comment by Soulless-1** [comment]
I've only left this open just for everyone to have the opportunity to take a look at it, and make sure everyone's on the same page that it should operate this way, and not just accept it because someone from the early 2000's decided it should be that way on a whim.  Since we're attempting to make Sphere-X branch better than the rest it would be good if it didn't fall victim to the same issues that every other sphere has in the past.  

My thought is just that we should correct these issues, and add toggles for backwards behavior.  I think we should be attempting to get the default behavior as close as possible to the vanilla experience that people will be expecting, it seems totally reasonable to me. Anything that is custom or unexpected behavior in Ultima Online should have a toggle to enable it, and be left off by default, or gutted entirely and allow the users to script this themselves. Especially when it's something this simple for them to do. I think we should take caution when saying we know what a user wants or doesn't want, but offer them the expected UO default behavior and let them decide what they want. we risk nothing by making it standard, and offering optional custom features. we risk disappointment by offering it pre-customized, and offering the standard features as options.

You guys give me the word that you're not interested in sphere x working this way, and I will stop pursuing these types of changes, I'm not here to further my own agenda or make any one else's vision harder to achieve, only here to make sphere a better emulator for everyone. It's my wish one day to offer a complete package of the t2a/ren era for sphere users to download. where they could decorate the world, spawn the world, play in it with a fresh char, using the many systems and features that one would expect on a UO shard (up to various expansions), working properly and within spec. Then we can all collectively laugh in the faces of people who say Sphere isn't as good as other emulators.

**Comment by drk84** [comment]
I'll close for now because i found this

![immagine](https://user-images.githubusercontent.com/13728442/126917922-459cb349-15d7-45df-a2fa-1e39a624fb53.png)

That line is at least 500000 years old!
