### ISSUE TITLE
Pets cannot attack / damaging owners

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#724]
It appears that pets cannot damage their owners, and there appears to be no way to allow pets to damage their owners in the sphere.ini , we should have a toggle for this or it should be removed to allow scripters to script their behavior.

**Comment by Leodinas** [comment]
CCharNPCPet.cpp
find
if ( !pCharTarg || pCharTarg == pSrc || pCharTarg == this )
change
if ( !pCharTarg || pCharTarg == this )
If you want to add a switch to ini

Refer to other settings in ini and add the code

**Comment by Jhobean** [comment]
Its interesting but when it's usefull? If there a switch on ini, you really activate it? I mean, it will be hard to play.

**Comment by Leodinas** [comment]
> Its interesting but when it's usefull? If there a switch on ini, you really activate it? I mean, it will be hard to play.

This is the old version of combat mode
Use the pet to remove the attack on the owner, and let the owner remove the paralysis effect
It's OK to follow the official version, but don't ignore the charm of the old version
Many players pursue the old version

**Comment by Soulless-1** [comment]
I think the concept here should be, make it work how it should officially. then add a toggle for any other behavior changes. 
There was never an instance in official UO where you're pets could not damage you though. People used to fight their forest ostard and bandage it and themselves. 
I dont think we should be preventing simple things like this anyways, it's a couple lines of code in a script for this custom behavior of pets not damaging owners.

**Comment by Leodinas** [comment]
> I think the concept here should be, make it work how it should officially. then add a toggle for any other behavior changes.
> There was never an instance in official UO where you're pets could not damage you though. People used to fight their forest ostard and bandage it and themselves.
> I dont think we should be preventing simple things like this anyways, it's a couple lines of code in a script for this custom behavior of pets not damaging owners.

yes!

**Comment by Jhobean** [comment]
When // COMBAT_NOPETDESERT is active, PET attack you. When it,s innactive they do not attack you

**Comment by Soulless-1** [comment]
Ive got that on mine enabled. But i imo that shouldnt have to do anything with ability to attack/not attack, it should only prevent the hardcoded behavior from making them abandon you on damage.

**Comment by Jhobean** [comment]
https://github.com/Sphereserver/Source-X/blob/946301511ee387a8340210681031f22f15dd83be/src/game/chars/CCharFight.cpp#L632-L633  

![image](https://user-images.githubusercontent.com/51728381/127033193-6e3f61ed-6331-4cce-8061-80623f40f259.png)


When domaging, no domage is done

**Comment by drk84** [comment]
fix sent

**Comment by Soulless-1** [comment]
Confirmed, thank you Drk.
