### ISSUE TITLE
boats losing proper component position

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#725]
Looks like the same issue in the past where boats would lose components or the proper position on them after some time on the open ocean

https://github.com/Sphereserver/Source-X/issues/821 "anything above -4 z (such as fishing gathering nodes) will be collected by the boat and after a certain amount of things are collected it will break the components and they will fall a part."

![image](https://user-images.githubusercontent.com/17236327/124005633-5001e780-d9a7-11eb-9818-1aca2070038b.png)

**Comment by LuxionUO** [comment]
Confirmed, I have got the same problem too, even with the last build.

**Comment by Soulless-1** [comment]
I have not seen this bug in some time, closing this issue out.
