### ISSUE TITLE
Random debug error occasionally pops up

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#727]
I'm unable to run with the debugger attached, since players refuse to test on it, due to performance with it. but I occasionally get this error that seems to be random.   

04:19:CRITICAL:Assert severity=2: 'purecall' file 'unknown', line 1, in ExcType=CAssert catched in SUB: CWorldTicker::Timed Object Tick() #1 "Elapsed" ("TimedFunction")
04:19:DEBUG:Printing STACK TRACE for debugging purposes.
04:19:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ |
04:19:DEBUG:(09976)          T_Main |  0 |                      CWorld::_OnTick |  
04:19:DEBUG:(09976)          T_Main |  1 |                   CWorldTicker::Tick | <-- exception catch point (below is guessed and could be incorrect!)
04:19:DEBUG:(09976)          T_Main |  2 |                       CLog::EventStr |  
04:19:DEBUG:(09976)          T_Main |  3 |             CSFileText::_WriteString |

**Comment by cbnolok** [comment]
Are you deleting or adding a timerf inside a timerf?
