### ISSUE TITLE
@Spellselect trigger Issues

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#729]
it looks like with the spell select trigger when trying to get the flags from argn3 the following ones do not work: 
Spell selected for casting | 01
Spell is about to finish casting | 03
Spell casting finished unsuccessfully | 00

logged these on a non gm char and was not able to work with these

MagicFlags=01|04|08|0800

**Comment by drk84** [comment]
What flags you get?

**Comment by Soulless-1** [comment]
flags with green arrows I receive, red arrows I do not 
![image](https://user-images.githubusercontent.com/17236327/147720752-7d287205-f535-438f-b8ca-33fe81719afd.png)

**Comment by xwerswoodx** [comment]
Seems like it changed a bit from the old times, before spell_cancast function was called on every phrase of the casting but now we only check it when you select the spell and after successfully finish it. Probably this done for avoid to check same things all the phrases to make optimization better. If you ask me, probably we should remove @SpellSelect trigger cast after the success too. I don't really understand why spellselect should trigger after spell finished, the trigger supposed to work only once when you select the skill. Or if it designed to work on every stage, the name should be different, anyway if you ask me, I wonder why someone need to check all these argn3 values while we have @Fail (spell casting finished unsuccessfully), @Success (spell is about to finish casting), @Cast (spell is about to start casting), @Effect (spell casting finished successfully), @Select (spell selected for casting) triggers that done it directly.

**Comment by Soulless-1** [comment]
i forgot what i was trying to accomplish, this was long ago. i know i had to find a work around but it would of been more convenient if all those had worked. i can't remember, ill think on it for a bit and get back to you.

**Comment by Soulless-1** [comment]
I'm going to close this out. we should leave the trigger as is, i believe that whatever it was i found a proper solution. I know i use the trigger for my runebook to not use charges, as well as some other scripts, so no change needed here.
