### ISSUE TITLE
equip test not able to block equipping on dragging

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#730]
When you try to block equipping with the @equip trigger, it does not fire when you drag an item onto the char, only when you dclick

**Comment by drk84** [comment]
@EquipTest works here both with dragging and dclicking

**Comment by drk84** [comment]
equiptest works here both by draggin and dclicking. check if you have some conflict with other equiptest triggers

**Comment by Soulless-1** [comment]
works, was just an issue with checking layers on my end. if (<layer> <= 24) didnt seem to work, but it was a legitimate item less than layer 24. strange issue.  works though
