### ISSUE TITLE
tag.override.sound_hit doesn't work

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#731]
appears that this override tag does not work , have tried it on several weapons, and on the player themselves.

**Comment by drk84** [comment]
Both were replaced with AMMOSOUNDHIT and AMMOSOUNDMISS but they only work with ranged weapons, should these properties be allowed to be used with melee weapon or i need to create a new property like MELEESOUNDHIT and MELEESOUNDMISS?

**Comment by Soulless-1** [comment]
What about just WEAPONHITSOUND and WEAPONMISSSOUND?

**Comment by drk84** [comment]
It sounds weird but better keep ammosoundhit and ammosoundmiss for backward compatibility and for avoding to have properties with the same functionality.

**Comment by drk84** [comment]
Fix Sent

**Comment by Soulless-1** [comment]
Confirmed, thank you!
