### ISSUE TITLE
REVEALF_OSILIKEPERSONALSPACE not working

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#732]
This flag in the INI does not work, you can still reveal someone when stepping over them while hidden.

// REVEALF_OSILIKEPERSONALSPACE		020     // Do not reveal when a character enters on personal space (and do not send any message).

**Comment by Jhobean** [comment]
I tested it with a i_potion_Invisibility and it's work A1. Don't forget this behavior is for Invisible flag and not hidden flag­

**Comment by Soulless-1** [comment]
ah, i see.

// REVEALF_SPEAK works for hidden though. looks like these flags are not working entirely as intended.  perhaps we need to look at these, and maybe make some for the hidden  flag as well.

**Comment by Soulless-1** [comment]
with just statf_hidden these work:

REVEALF_LOOTINGSELF
REVEALF_LOOTINGOTHERS
REVEALF_SPEAK
REVEALF_SNOOPING           	

so this makes it very confusing, and then impossible to really use these flags without affecting hiding also.  I assume most of the other ones apply to hiding as well.

**Comment by Jhobean** [comment]
The osilikepersonnal space suppose to be like osi. How it work on osi?

**Comment by Soulless-1** [comment]
it notifies you that youve pushed through something invisible but does not reveal them. 

![image](https://user-images.githubusercontent.com/17236327/125330097-4ddb4980-e314-11eb-8575-5d78bafe2a23.png)

though truthfully invis and hiding did not work differently from one another on OSI, this is just a sphere thing where they work differently. so we should continue to have flags to modify invis, but also we should add the same ones for hidden.

**Comment by Jhobean** [comment]
See #343

**Comment by Soulless-1** [comment]
Fix confirmed, thank you Jhobean
