### ISSUE TITLE
NPC_AI_PATH if enabled starts to reveal players in loop

### ISSUE THREAD

**Issue by LuxionUO** [Sphereserver/Source-X#734]
// NPC_AI_PATH	00001	Enable advanced NPC pathfinding engine (this can significantly increase server CPU usage)

When this flag is enabled and active, the monsters' behaviour is very good but if the player is hiding near monsters he get revealed instantly. Basically you can't use hiding/stealth skill near monsters.

I have tried a lot of things in order to fix it but there is no way.

- Monsters don't use detecting hidden skill when this happens.
- Monsters don't use Reveal spell when this happens.
- Monsters action is still "Wrestling" all the time (normal).

So, through debug messages, I can't see any type of unusual situation. I think is related to Sphere?

Thanks.

**Comment by Soulless-1** [comment]
I tested this and it seems like its only when the npc actually stepped on the char, I used a fresh script pack. is it specifically when they step on a hidden player?

**Comment by Jhobean** [comment]
Its linked with NPC_AI_PATH .  Monster suppose to reveal player When walk on them??

**Comment by Soulless-1** [comment]
Typically in sphere that has been how it works, when any character walks on another, it reveals them. 

This is not the standard behavior though in UO so it should be considered incorrect.  What happens is you walk onto someone if you have full dex, and it notifies you that you stumbled onto something hidden. You then must use reveal, or detect hidden to find out what it is. Having flags for this behavior should benefit everyone.

#732  this issue explains how that's supposed to work.

Though it sounds like perhaps Luxion was saying that it's not a npc walking directly on the char, but only near them, haven't been able to confirm yet.

**Comment by Jhobean** [comment]
But if Ai  path is enable, that mean monster are intelligent and may detect you? Its more difficult in this way and its fine?

**Comment by Soulless-1** [comment]
I would leave that to just pathfinding and not other behavior, because then if someone just wants better pathfinding but not some kind of AI activity where they detect players, the path finding would be rendered unusable for them.  detecting hidden players is something scripters could do on their own if they wanted that behavior

**Comment by alexdan2** [comment]
I think also is connected whit this old "issue":
https://github.com/Sphereserver/Source-X/issues/343

**Comment by Soulless-1** [comment]
I asked Luxion about this and he said this addressed the issue, I believe we can close this one now.

**Comment by Leodinas** [comment]
//else
				//{
				//	snprintf(pszMsg, STR_TEMPLENGTH, g_Cfg.GetDefaultMsg(DEFMSG_HIDING_STUMBLE), pChar->GetName());
				//	if (!fPathFinding) // When NPC use pathfinding(NPC_AI_PATH) to calculate their destination, char should not be reveal
				//		pChar->Reveal(STATF_INVISIBLE | STATF_HIDDEN);
				//}

delete here
add detection whether it is a player
if it's player reveal

**Comment by Jhobean** [comment]
I dont think player use this pathfinding method. You tested it?

**Comment by Leodinas** [comment]
Some settings should follow the old mode and be carried out together with the official version!

If someone asks me, give me a hint! I don't think there's a problem!

I'm already using it because I'm changing it according to the model of 51A.

I think many people are trying to simulate the old version!

If you really understand the old version.
@Jhobean

**Comment by Jhobean** [comment]
So you propose to be able activate this bug on the ini? On my opinion it's a bug. I'm curious to have other opinion.

**Comment by Leodinas** [comment]
Don't boil all the problems down to bugs

Some problems are multifaceted

Instead of being fixed, these functions can be achieved by script

**Comment by Leodinas** [comment]
else if (pChar->IsStatFlag(STATF_INVISIBLE | STATF_HIDDEN) ) {
				if ((g_Cfg.m_iRevealFlags & REVEALF_OSILIKEPERSONALSPACE))
					// OSILIKEPERSONALSPACE flag block the reveal but DEFMSG_HIDING_STUMBLE_OSILIKE is send. To avoid it, simply use return 1 in @PERSONALSPACE 
					snprintf(pszMsg, STR_TEMPLENGTH, g_Cfg.GetDefaultMsg(DEFMSG_HIDING_STUMBLE_OSILIKE));
				else if ( !m_pNPC && pChar->IsStatFlag(STATF_HIDDEN) )
				{
					snprintf(pszMsg, STR_TEMPLENGTH, g_Cfg.GetDefaultMsg(DEFMSG_HIDING_STUMBLE), pChar->GetName());
					pChar->Reveal(STATF_INVISIBLE | STATF_HIDDEN);
				}
				//else
				//{
				//	snprintf(pszMsg, STR_TEMPLENGTH, g_Cfg.GetDefaultMsg(DEFMSG_HIDING_STUMBLE), pChar->GetName());
				//	if (!fPathFinding) // When NPC use pathfinding(NPC_AI_PATH) to calculate their destination, char should not be reveal
				//		pChar->Reveal(STATF_INVISIBLE | STATF_HIDDEN);
				//}
			}
What bug is this

**Comment by Jhobean** [comment]
If you comment the line like you did, player will not be revealed if you walk on it.

**Comment by Leodinas** [comment]
Players can find that I have said it! Add your own player detection

**Comment by Jhobean** [comment]
You mean when you use pathfinding with player, it was reveal other player too? Its this you. Want keep?
1- you use pathfinding 
2 - you dont use detec hidden
3 - you dont walk on the   player
4- the player is reveal?

I dont cath what you want.

**Comment by Leodinas** [comment]
You can use the 51A test

You'll get the answer

**Comment by Jhobean** [comment]
I cant help you if you cant help me. Just say or show me what you want. I dont have 51A server available

**Comment by Soulless-1** [comment]
I'm not certain what the conversation is about, but to weigh in on this with my opinion on the matter, revealing any character (npc or player) should have nothing to do with pathfinding. If an admin want's npcs to reveal players he can script this behavior. It's much easier for everyone if this behavior doesn't exist and admins can do it themselves, than it is for it to exist and admins to attempt and stop it. 

pathfinding should be completely separate from any sort of reveal behavior.

**Comment by Leodinas** [comment]
> I'm not certain what the conversation is about (mistranslations perhaps), but to weigh in on this with my opinion on the matter, revealing any character (npc or player) should have nothing to do with pathfinding. If an admin want's npcs to reveal players he can script this behavior. It's much easier for everyone if this behavior doesn't exist and admins can do it themselves, than it is for it to exist and admins to attempt and stop it.
> 
> pathfinding should be completely separate from any sort of reveal behavior. so if that's what happens now, it should be removed entirely, and/or a sphere.ini toggle should be added to keep it.

yes

**Comment by Jhobean** [comment]
Sincerely I want to help on this but I just don't understand what the difference you get on your side... Just give detail and maybe there a better 51a like behavior we can add.  51a server had NPCAI?

On my modification, I only Added this line:
`if (!fPathFinding)`
On the code the fpathFinding variable = TRUE only when NPC use the pathfinding function to determine the way they will take.

What the exact problem you get? You can take 5 mins to show me the difference by video or by clear text?  You notice différence player vs player or NPC vs PLAYER?

**Comment by LuxionUO** [comment]
The issue about NPC revealing seems solved. I'll reopen this Issue in case of new event.
