### ISSUE TITLE
@itembuy issue with return 1

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#738]
When doing return 1 on @itembuy, it still seems to do the speech that says the player bought the items, saying how much it was and thanking them for their business. return 1 should stop all actions I think. 

![image](https://user-images.githubusercontent.com/17236327/126119999-b9f9be0b-669a-44be-8404-f53071f6153b.png)

on=@itembuy
if (<act.type>==t_figurine)
  if (<eval <curfollower>+<argn1>> > <maxfollower>) 
    argo.say Your order cannot be fulfilled, please try again.
    return 1
  endif
endif

**Comment by drk84** [comment]
Fix Sent

**Comment by Soulless-1** [comment]
fix confirmed, thank you!
