### ISSUE TITLE
feature request: @destroy trigger for npcs on removal

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#740]
When an npc is removed rather than killed or dying from something, @destroy could trigger for them. this would important for people who have npc garbage cleanup systems that remove orphaned npcs in their world every so often.  or help users regulate their followers, pets, and hired npcs in their various scripts if they are removed. right now the NPC just appears to be removed and @death or @destroy do not trigger.

Someone let me know if there is already something to achieve this though. :)

**Comment by Jhobean** [comment]
On my side, I use @destroy on my script pack since a long time.Trigger occur when a npc monster get kill  or if you remove them....  I put the On=@destroy just under the chardef.

**Comment by Soulless-1** [comment]
You are right, this was a mistake on my end, I should of tested better. Thanks Jhobean.
