### ISSUE TITLE
Feature Request: ablility to modify resfire, rescold, respoison, and resenergy

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#742]
Would be good to have the opportunity to modify these keywords on a char even if it's not activated to use the elemental / resistances in the ini.

**Comment by drk84** [comment]
I agree, also i closed #462 so we can continue on this most recent one thread

**Comment by drk84** [comment]
If i remember well, the elemental properties were tied to the FEATURE_AOS_UPDATE_A instead of the more recent changes about combat elemental engine.

**Comment by cbnolok** [comment]
Since polling those dynamic properties brings a slight cpu cost, that flag was used as a switch to disable checks on them if not necessary.
We can add an additional flags to turn on the usage of that property, but not their sphere internal usage.

**Comment by drk84** [comment]
Added!

**Comment by Jhobean** [comment]
Nice feature! I use it and tested it. I was looking for this too. Thx Drk

**Comment by Soulless-1** [comment]
thank you, closing out
