### ISSUE TITLE
Advanced LOS issue

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#744]
with advanced LOS, npcs can see players through the multis walls in their houses.

**Comment by xwerswoodx** [comment]
I am checking that and seems like canseelos_new which is advanced has multi check but I am not sure if advancedlos works on npcs I need to check but how can I test it? placing any ranged npc around house is enough or need to do anything else to reproduce?

**Comment by Soulless-1** [comment]
you just need to stand on the otherside of a window in at a player house, its because you can see through windows. a flag might be a good idea but i dont think this is really an 'issue' anymore since a way exists to solve it for people who either want it and those who don't want it. 

this can actually be solved by someone going into the scripts and adding can_i_block to their window itemdefs, which is really easy. I'm going to close this out.
