### ISSUE TITLE
Npcs not hearing words that should trigger actions

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#748]
Here a player is standing right next to a banker, can confirm the banker was just on the other side of the wall from him. And saying bank did not open up his bank box, however saying banker bank did work for him. 

![image](https://user-images.githubusercontent.com/17236327/128437217-09ab5716-2206-47bb-81ce-feaf5eed760e.png)

**Comment by alexdan2** [comment]
Happen because not have LOS.

Set this:
NPCDistanceHear=-8

on sphere.ini

if value is negataive is max range (tile) whitout LoS check.
if value is positive is max range (tile) whit LoS check,

**Comment by Soulless-1** [comment]
confirmed and closing, thank you Alex.
