### ISSUE TITLE
@ShoveCharacter trigger (something similar to @personalspace)

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#752]
Currently we have @personalSpace which is good for the char being stepped on, but it would be good to have a trigger for the character doing the shoving so we can make separate custom events for each chardef or group of characters, without needing to put everything in one big chunk of code under a generic npc event for @personalsapce

could work the same, controlling if the character is able to step, and most importantly the stamina how much it will take for them to step on the other character. This makes a it little easier to work with this mechanic, and for people like myself wanting to have specific npcs that take no stamina to push through anyone else, such as guards

**Comment by Tolokio** [comment]
this is done. clse plz
