### ISSUE TITLE
Delete character issue

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#753]
When deleting a character it appears that it does not update the character list on your screen till you reload it, this should automatically happen after deleting the char, I believe this is the cause for a few players accidently deleting chars they didn't mean to, in an attempt to delete the character that appears to stay on the char list.

**Comment by alexdan2** [comment]
I "fixed" this iussue whit a simple trick, when delete a char force a disconnect.. and player have to login again and see correct list,,

**Comment by Soulless-1** [comment]
found this packet information 
https://docs.polserver.com/packets/index.php?Packet=0x86

Packet Name: Resend Characters After Delete
Last Modified: 2009-03-02 07:48:32
Modified By: Turley

Packet: 0x86
Sent By: Server
Size: 304 Bytes

Packet Build
BYTE[1] cmd
BYTE[2] blockSize
BYTE[1] # of characters
Following repeated 5 times
BYTE[30] character name
BYTE[30] character password

**Comment by Jhobean** [comment]
Party occur there:
https://github.com/Sphereserver/Source-X/blob/a09d665f3d384fe9584d2db3f66396faf5a9094f/src/game/clients/CClientMsg.cpp#L2844-L2848

The packet should update the list but apparently not...

**Comment by Jhobean** [comment]
Should be fix in #883

**Comment by Jhobean** [comment]
I Confirm it is fixed

**Comment by Tolokio** [comment]
so this can be closed? Lets do it.

**Comment by drk84** [comment]
Yup seems fixed!
