### ISSUE TITLE
Shard list feature request

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#754]
I know there used to be a shard list that was available on the website, and you could see all the online sphere servers using the feature, what do we think maybe about having this list again? With our community being so small, this could help with visibility. I do not know what is required of this, i am certain it would need some kind of polling service. I would be happy to setup a gateway for this feature on the mini hp prodesk that isn't being utilized here now.

**Comment by Jhobean** [comment]
A setting on the ini you check and your shard stat is send automatic to a specific server? Its the reverse uoportal and other service. You push the data instead of be ping?

**Comment by Soulless-1** [comment]
yeah, enable in INI to push your data to somewhere, that will list all the shards, can sort by sphere version, days up, players online, ping, etc. would be great for the community.

**Comment by cbnolok** [comment]
Afair there were security issues, i can't remember why the feature was dismissed (we have the source code tho), maybe @Ben1028 remembers

**Comment by Ben1028** [comment]
This feature was removed before my time, so I don't know the reason it was removed.

**Comment by a1exp** [comment]
@Soulless-1 this sounds to me like [UO Gateway](https://www.uogateway.com/) polling support (the server is temporarily down, but hopefully will be back). 

Are you saying it is disabled in sphere-x?

**Comment by Soulless-1** [comment]
Yeah, this is something that was just a sphere.ini toggle, and it would list it somewhere with all other sphere shards. 

This was something disabled long long ago, i cant even remember when. Sometimes people request it, I think it's a good idea.

**Comment by Soulless-1** [comment]
this can be closed, its a very low priority.
