### ISSUE TITLE
Able to walk on certain unwalkable tiles/walls

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#755]
Looks like your able to walk off of the sides of these sandstone houses, i dont recall this being an issue in prior spheres

![image](https://user-images.githubusercontent.com/17236327/130560084-4234bd5f-b924-4312-92d1-513cb8384ad9.png)

**Comment by drk84** [comment]
I have the same problem but it's that some wall items do not have the proper tiledata flags (wall, impassable etc) 
The item in question is 0x1ec

**Comment by drk84** [comment]
![immagine](https://user-images.githubusercontent.com/13728442/130767570-2bfee7c5-d9cd-464c-a978-b07de8c761ca.png)

By default it has the surface, bridge flags while the nearest sandstone low wall (0x1ee) has the right flags (wall, impassable)

**Comment by drk84** [comment]
I close this
