### ISSUE TITLE
Hallucination err

### ISSUE THREAD

**Issue by Leodinas** [Sphereserver/Source-X#757]
Hallucination magic causes the client to crash

client version 6061
server build 3364 / GIT hash 0fc15b5ba49e4a579c9973ce7da57d13220b0d3d

**Comment by drk84** [comment]
Is the hallucination flag or the hallucination sphere spell?

**Comment by Leodinas** [comment]
spell 1005

**Comment by drk84** [comment]
Ehm try use a most recent build

**Comment by Leodinas** [comment]
Compiled at Aug 21 2021 (16:15:29) [build 3468 / GIT hash d69c5220788bd3a09cadfbc7d8990507ef01b74b]
The error still exists

Client crash

**Comment by drk84** [comment]
Can't reproduce, check if your hallucination spell has the spellflag_tick

**Comment by Leodinas** [comment]
have
[SPELL 1005]
DEFNAME=s_Hallucination
NAME=Hallucination
SOUND=snd_Z_END_MYSTERY1
RUNES=WN
CAST_TIME=60
RESOURCES=i_reag_garlic,i_reag_nightshade
RUNE_ITEM=i_rune_MIND_BLAST
SCROLL_ITEM=i_scroll_MIND_BLAST
FLAGS=SPELLFLAG_TARG_CHAR|SPELLFLAG_DIR_ANIM| SPELLFLAG_HARM | SPELLFLAG_FX_TARG| spellflag_curse|spellflag_tick
EFFECT_ID=i_fx_curse
EFFECT=2,5
LAYER=layer_flag_hallucination
DURATION=2*60.0,4*60.0
MANAUSE=15
SKILLREQ=MAGERY 30.0, NECROMANCY 40.0
INTERRUPT=100.0,100.0

**Comment by drk84** [comment]
The crash happens when the spell is cast or when the spell expires? Can you reproduce it in another client?

**Comment by Leodinas** [comment]
Successful casting

It is possible to crash when NPC changes

I have three computers that crash

**Comment by drk84** [comment]
Can't reproduce, try a different client like 7.0.20

**Comment by Leodinas** [comment]
I'm not going to upgrade the client version for the time being

Because I changed some functions in the 6061 client

**Comment by drk84** [comment]
You modified the client?

**Comment by Leodinas** [comment]
yes

But it will not affect its operation

Because I use the client without modifying the memory will still crash

**Comment by drk84** [comment]
I'll try with client 6061

**Comment by drk84** [comment]
No crash, what's the error in console about the client crashing?

**Comment by Leodinas** [comment]
No hint

Client flash back

**Comment by Jhobean** [comment]
You modified client?  So its the open source classicuo?

**Comment by Leodinas** [comment]
Memory modification

Even if I don't modify it

It will also collapse

**Comment by Jhobean** [comment]
But what client you use? Classic, cross, osi, orion?

**Comment by Leodinas** [comment]
Classic 6061

**Comment by Leodinas** [comment]
https://ia800906.us.archive.org/view_archive.php?archive=/27/items/UltimaOnlineTM9thAnniversary6.0.1.10Patch72/Ultima%20Online%E2%84%A2%20-%209th%20Anniversary%20%5B6.0.1.10%20%5BPatch%2072%5D%5D.iso&file=Ultima%20Online%E2%84%A2%20-%209th%20Anniversary%206.0.1.10%20%5BPatch%2072%5D.exe
Client crash

**Comment by Leodinas** [comment]
yes 
7.0.20.0 Normal operation

The client will not crash

**Comment by Leodinas** [comment]
7.0.20.0 Will collapse, just for a long time

**Comment by Leodinas** [comment]
id = (CREID_TYPE)(Calc_GetRandVal(CREID_SUCCUBUS));
Change here, client crash fixed
