### ISSUE TITLE
parsing Problem with some caracter

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#758]
problem occur when you lack a space between the variable and the operator

```
[FUNCTION TEST]
hits=50
serv.log <hits>
hits -= 1
serv.log <hits>

hits=50
serv.log <hits>
hits-=1
serv.log <hits>
```

here the log 
```
09:13:(sphere_item_profession.scp,450)50
09:13:(sphere_item_profession.scp,452)49
09:13:(sphere_item_profession.scp,455)50
09:13:(sphere_item_profession.scp,457)1
```

**Comment by cbnolok** [comment]
It had always been like that, and to make it work like you suggested would mean to rewrite significant parts of the parser, which will probably result slower. Imho, it isn't worth it

**Comment by Jhobean** [comment]
Thx, for the answer. I thought it was a bug.
