### ISSUE TITLE
inscription err

### ISSUE THREAD

**Issue by Leodinas** [Sphereserver/Source-X#762]
inscription trigger @spellselect

on=@spellselect
if (<argn1> == 1)
serv.log trigger @spellselect
endif

**Comment by Leodinas** [comment]
argn == 1

**Comment by drk84** [comment]
it's because when you are trying to create a scribe scroll the cancast function is called in the skillmenu scripts

**Comment by Leodinas** [comment]
Isn't that a mistake

**Comment by Jhobean** [comment]
But cancast function should trigger @spellcast? It make nonsense?

**Comment by Leodinas** [comment]
inscription skills
IT_SCROLL_BLANK trigger @spellselect?

**Comment by Leodinas** [comment]
case CHC_CANCAST:
			{
				ptcKey += 7;
				//ITEMID_TYPE id = (ITEMID_TYPE)(g_Cfg.ResourceGetIndexType(RES_ITEMDEF, ptcKey));
				GETNONWHITESPACE(ptcKey);

				tchar * ppArgs[2];
				int iQty = Str_ParseCmds(const_cast<tchar *>(ptcKey), ppArgs, CountOf( ppArgs ));

				// Check that we have at least the first argument
				if ( iQty <= 0 )
					return false;

				// Lookup the spell ID to ensure it's valid
				SPELL_TYPE spell = (SPELL_TYPE)(g_Cfg.ResourceGetIndexType( RES_SPELL, ppArgs[0] ));
				bool fCheckAntiMagic = true; // AntiMagic check is enabled by default

				// Set AntiMagic check if second argument has been provided
				if ( iQty == 2 )
					fCheckAntiMagic = ( Exp_GetVal( ppArgs[1] ) >= 1 );
				CItem* pItem = dynamic_cast <CItem*> (pSrc);

				if ( pItem != nullptr ) //I don't know if it's right
					sVal.FormatVal( Spell_CanCast( spell, true, this, false, fCheckAntiMagic ) );
			}

**Comment by drk84** [comment]
I close this
