### ISSUE TITLE
IF statement is parsed incorrectly 

### ISSUE THREAD

**Issue by a1exp** [Sphereserver/Source-X#766]
The following statement is parsed incorrecly on SphereX and returns true, which leads to unexpeded behavior in scripts. 
```
  if (1 + 2 ) > 10
    serv.log 'DEBUG' false-positive
  endif
```
It works fine when you add more parentheses, but it's a huge work to migrate existing shard scripts from 56b/c/d to SphereX due to this, as there is no warning and you have to review all your code and add missing parentheses. 
```
  if ((1 + 2 ) > 10)
    serv.log 'DEBUG' bla bla
  endif
```

I'm using SphreX nightly version from Sep 14, 2021. 
discord [discussion](https://discord.com/channels/354358315373035542/476635430821953567/892716535200755763)

**Comment by Jhobean** [comment]
I tested and it's Fix in this commit: https://github.com/Sphereserver/Source-X/commit/1ec0790b415d6772c036898cbb2efac1b5a61d79

**Comment by drk84** [comment]
fix sent by nolok
