### ISSUE TITLE
Item not shown in backpack when using cont

### ISSUE THREAD

**Issue by a1exp** [Sphereserver/Source-X#768]
If you unequip an item from player hands to their backpack using something like this and while the player has their backpack open
```
src.findlayer(1).cont = <src.findlayer(21).uid>
```
then item is not shown in the backpack until the player closes and opens backpack again.

Also if you just create a new item and put it in the backpack via `cont` and not via `bounce`, the item is not visible until backpack close/open. 

Nightly version from Sep 14, 2021.

**Comment by Jhobean** [comment]
Yes its dupe of this issue.
https://github.com/Sphereserver/Source-X/issues/680

**Comment by a1exp** [comment]
ok, thanks man
waiting for a fix to be live :)
