### ISSUE TITLE
There is no space in rune prefix and name by default

### ISSUE THREAD

**Issue by a1exp** [Sphereserver/Source-X#770]
How to reproduce:
 - rename a rune (e.g. to "TEST")
 - new name will be "a recall rune forTEST" without a space 

Most likely the problem is [here](https://github.com/Sphereserver/Source-X/blob/0067aa84376759bb1c8353152acdb73e84f7731a/src/game/clients/CClientEvent.cpp#L1775). 

Workaround by scripts is to uncomment and  change `rune_to` in `messages.scp` to add a space at the end.

**Comment by Jhobean** [comment]
Interesting. Are you able to do a Pull request? If you are interested, I can show you. Contact me in discord

**Comment by Jhobean** [comment]
The bug is in the text description because it use the same line of code for KEY, rune and stone rename.

![image](https://user-images.githubusercontent.com/51728381/135758553-feddbd54-9395-49e9-94f3-9696d3da5397.png)

I'll send a fix

**Comment by a1exp** [comment]
@Jhobean 👍

**Comment by a1exp** [comment]
Fixed by https://github.com/Sphereserver/Source-X/pull/771.
