### ISSUE TITLE
Players can loot hair and beard from NPC humanoids

### ISSUE THREAD

**Issue by a1exp** [Sphereserver/Source-X#775]
There is a weird issue reported by a player:

```
some time is possible looting hair and beard from humanoid mobs
[5:24 PM]
and that items are invisible in your backpack
[5:26 PM]
and persist to exists in backpack after death, like an item newbie
[5:27 PM]
function looter(){
    while (Orion.FindTypeEx(any,any,lastcontainer).length > 0){
        var i = Orion.FindTypeEx(any,any,lastcontainer).shift();
        Orion.MoveItem(i.Serial());
        Orion.Wait(100);
    }
}
[5:28 PM]
i looted them by this script with orion
[5:28 PM]
function testShowMyItems(){
    var myItems = Orion.FindTypeEx(any, any, backpack);
    TextWindow.Open();
    TextWindow.Clear();
    for (var i = 0; i< myItems.length;i++){
        Orion.Click(myItems[i].Serial());
        Orion.CheckLag();
        TextWindow.Print("  Name=" + myItems[i].Name() + " -Serial="+myItems[i].Serial() + " \t\t\t-Graphic=" + myItems[i].Graphic() + " \t\t\t-Color="+ myItems[i].Color() );
    }
}
[5:29 PM]
and i can see that are in back pack with this function

```

I tried to reproduce it with the default script pack and it is reproduceable with this Orion script. E.g. add c_barbarian_chieftain, kill him, loot by a player with Orion.

Note the hair/beard item is not visible in backpack even to a GM, so I used `.x show findlayer(21).findtype.t_hair` to make sure the item exists. Also checked attr on such items, thery are newbie :) This may prevent a player going to a tournament which requires empty backpack.. 

On the next save sphere's GC deletes such items:

```
18:18:ERROR:GC: Deleted UID=04000a52b, Defname='i_hair_curly', Name='Curly'. Invalid code=0x2227 (Hair/Beard item not equipped / not in a corpse / not in a vendor box).
```

**Comment by xwerswoodx** [comment]
I am not sure if it's about sphere at all, because Orion edit the Client so seems like it's totally Orion-Base issue. As you said, the item is newbie so it shouldn't be obtained with anyway, but Orion script seems like doesn't check if the item is newbie or not by sending packets. So for me, it doesn't seem like Sphere-Base issue but it worth to check anyway.

**Comment by a1exp** [comment]
First of all, this does not happen on 56b with Orion, just on SphereX. 
Second, such logic should be handled by server not client, otherwise a lot of cheats would be posisble if client contolled newbiew flags :)

**Comment by Tolokio** [comment]
if item appear in the looters backpack using .xshow, it can't be orion issue only as sphere should deny to move the item. Did it work with other newbie stuff?

**Comment by Soulless-1** [comment]
i would make hair attr_move_never, there's no reason to move it anyways.  
this was a bug shortly on the classicuo client, which has been fixed some time ago, however i can confirm it never happened on the vanilla client.exe as i checked many times when the issue first arose. 

can you confirm it's still a present issue?

**Comment by Soulless-1** [comment]
closing out for now, if you can confirm on the vanilla client please comment back.
