### ISSUE TITLE
WOPFont from sphere.ini does not work in certain circumstances

### ISSUE THREAD

**Issue by a1exp** [Sphereserver/Source-X#776]
If you change `SAY_DEF_UNICODE` to 1 in sphere_messages.scp like this:

```
// Default settings for Say
// Note: these settings will not override player speech settings
SAY_DEF_COLOR		946
SAY_DEF_FONT		3
SAY_DEF_UNICODE		1
```
then `WOPFont` from sphere.ini does not have any effect. All fonts look the same (see below). I belive it is due to unicode. 
![image](https://user-images.githubusercontent.com/31130012/135894256-9ce32a77-3df2-4f70-9a05-826889e4d28e.png)

What I was trying to achieve originally - 56c behaviour. On 56c if you change `SAY_DEF_UNICODE` to 1 it does not impact player's WOP, but it only used for speech which was nice and usefull for NPC and players in some cases. 

Now on Sphere X players started to cast spells with unicode font as well and I can't find a way to change player's WOP to the old style, default gray like this:
![image](https://user-images.githubusercontent.com/31130012/135894115-828d96be-00a4-4696-9811-3ea33f28ff61.png)

Perhaps something like a new option "WOPFontUnicode" would help.. I would like to turn it off. 

Also, I will be happy with a workaround if you got one.

**Comment by Jhobean** [comment]
bug came from there... https://github.com/Sphereserver/Source-X/blob/96ad8d189dc07e5f9f9bcc3cf6e91cdd165506e7/src/game/chars/CCharSpell.cpp#L3348-L3349

A fix caused a bug

**Comment by drk84** [comment]
I didn't make that fix!

**Comment by Jhobean** [comment]
> I didn't make that fix!

Ho.. you just ported it from Coruja. An other reason to revert...
