### ISSUE TITLE
Spell @success is triggered for Teleport even if the spell was blocked 

### ISSUE THREAD

**Issue by a1exp** [Sphereserver/Source-X#779]
When you try to cast Teleport to a fence for instance you can't do it and the following sysmessage is shown. However spell @Success trigger still fires. 

![image](https://user-images.githubusercontent.com/31130012/136208735-cb007147-8cd6-4f44-8db7-18686d8feac3.png)

It breaks some logic in my scripts, e.g. I want to show an additional animation upon successfull teleporting. 

Is there a way to trigger @fail in such cases? Or are there any other workarounds?

**Comment by a1exp** [comment]
Hm.. In my case the sysmessage "You can't teleport to that spot." is printed, but the spell does not fizzle when I try to cast to a fense (statics) with a player. Will double check with with default script pack.

**Comment by Jhobean** [comment]
@a1exp yes you are right. I just forgive to mention on my screen shot I modified the code...  But the fizzle behabior is bad.. what do you think?

**Comment by a1exp** [comment]
@Jhobean 

yep, just reproduced with default script pack.

ideally, the check if the player can teleport to a given spot should be done on spell @select / @start and do not trigger @success. But I don't not if it's doable code wise. 

Triggering @fail and fizzle should be also acceptable, what is you concern? 

By the way, I checked Recall spell for a similar situation (marked a rune in anti-magic zone by GM, gave the rune to a player). When the player casts Recall, the spell fizzles and two sysmessages are displayed: 
 - `The anti-magic field blocks you`
 -  `You stop casting the spell.`

But the weird thing is that BOTH @fail and @success are triggered in such case. So the @success issues seems to be common for both Teleport and Recall spells. 

![image](https://user-images.githubusercontent.com/31130012/136674464-85084f1e-c184-4456-a551-2bd535d82fb8.png)

**Comment by xwerswoodx** [comment]
I put that as high priority take a look at it tomorrow
