### ISSUE TITLE
Delay before first swing in combat

### ISSUE THREAD

**Issue by a1exp** [Sphereserver/Source-X#782]
Comparing 56b and SphereX behaviour, there is a static delay added before firtst swing in combat. When I attack an npc or player, my player wait for 1-2 sec then start swinging. This is very noticeable with fast weapon. 

Though the delay is minor, it was noticed and reported by players, since it affect PvP. 

You can see on this video a small delay between the target is moved to another dummy and the player starts swinging. I tried to print debug with argn1 and local.animDelay from @HitTry - they are the same in all hits including very first hit. So the delay is something else before @HitTry. 

https://user-images.githubusercontent.com/31130012/136674952-d34b3a40-c2e0-45ff-b564-776c97922f0c.mp4

My combat settings:
```
CombatFlags=0
```
Option flags:
```
OptionFlags=08|0200|04000
```
and
```
CombatSpeedEra=0
```

I have pre-hit off and enabling it is not a solution, as it will have other effects. 

Is there a way to get rid of this delay?

**Comment by a1exp** [comment]
That's interesting.. Players also mentioned that seem like weapon started to swing faster, but I didn't check it yet.

**Comment by Tolokio** [comment]
![image](https://github.com/Sphereserver/Source-X/assets/20745578/22ded49a-cecd-424c-b8b5-22b23869dc26)

**Comment by xwerswoodx** [comment]
If you activate both of that flags

// COMBAT_ANIM_HIT_SMOOTH		010000 // The hit animation has the same duration as the swing delay, instead of having a fixed fast duration and being idle until the delay has expired.
// COMBAT_FIRSTHIT_INSTANT		020000 // The first hit in a fight doesn't wait for the recoil time (OSI like)

It works like 56b.

**Comment by a1exp** [comment]
Unfortunately, the animation is still not aligned with the hit when both flags are active. As you can see a hit happens some time after the animation has stopped. 

https://github.com/Sphereserver/Source-X/assets/31130012/dcd7db1e-aaf5-49c7-bf22-38c1c3a223b8

**Comment by a1exp** [comment]
might be fixed by https://github.com/Sphereserver/Source-X/issues/1011. I will re-check on the latest build.

**Comment by xwerswoodx** [comment]
It could be nice because I am trying that for a while, and seems like it shows the damage for me at the second the animation hits the character, but yes on your video there is a delay which shouldn't be, let me know when you check, if it still an issue, we can check your sphere.ini settings

**Comment by a1exp** [comment]
Yep, looks much better on the latest build. Fixed.
