### ISSUE TITLE
Feature request: implement  Chat System  on the client. Already did on 56d

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#785]
For now, on X it's impossible to use chat system.

Build in Chat is like this (image took on 56d):
![image](https://user-images.githubusercontent.com/51728381/136987904-44612948-d3dd-4272-9ae9-7fb91276806e.png)

Since the fork, Coruja made 4 big  Commit to implement this feature. He added some ini setting.
![image](https://user-images.githubusercontent.com/51728381/136988197-63c7f478-2659-4db3-ba06-8f191016b262.png)

https://github.com/Sphereserver/Source/commit/7b239b2d7530cf6b6c8f84fcbbd8b84b67a8ed95

https://github.com/Sphereserver/Source/commit/722606c54f17e3c9d8e6095fffcaa3b528c4783a

https://github.com/Sphereserver/Source/commit/f26b39b9b40fba76660c36d57baa8387d3613272

https://github.com/Sphereserver/Source/commit/26039d2ef9a121d52b561ce02cdae6d1e4624ccc

https://github.com/Sphereserver/Source/commit/2ccf98dc3c4ae7e910ea87cd3d4b5f90e499fe92

https://github.com/Sphereserver/Source/commit/ead8e666810d63a58f133de26ebe69095d12c52c

**Comment by xwerswoodx** [comment]
Probably implemented, because it seems same for me on X, I don't know how it works but probably use , key after joined the channel or something like that maybe.

**Comment by Jhobean** [comment]
Not its not implemented. On 56d you can define channel name on ini. Never achieve to make chat work with channel on X

**Comment by xwerswoodx** [comment]
Oh I see, okay I can take a look foe it later, honestly never used chat syatem befoee :))
