### ISSUE TITLE
Return 1 in @SkillStart does not abort default checks 

### ISSUE THREAD

**Issue by a1exp** [Sphereserver/Source-X#794]
I have a custom animal taming, which is temporary assigned to a player during a quest ans is  triggered by @SkillStart like this 
```
ON=@SkillStart
  if <action> == skill_taming 
    if <findid.i_m_skill_taming>
      sysmessage @sysmsg You must wait to perform another action
      action = -1
    else
      f_skill_taming_start <act.uid>
    endif
    return 1
  endif
  return 0
```
The problem is that regardless of `return 1` in the code above, seems like Sphere still performs some checks and displays messages. 

For instance I have a check for distance and print sysmessage if too war away, on SphereX I started seeing two messages with "too far away" - one from my custom check, another from sphere.

![image](https://user-images.githubusercontent.com/31130012/138922302-99199f2e-ce6d-45f5-8370-edb80820d7e6.png)

If I do `return 1` from @Start of taming skills it prevents from printing the second message, but if I do it from @SkillStart - it is not. On 56b I did not see this issue.

**Comment by drk84** [comment]
I close this
