### ISSUE TITLE
Vendor Buying Not Limited

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#802]
In the vendor buy templates there is a number that should represent how many total the vendor should buy I believe. and this is not respected when a player actually goes to sell the items. They can sell unlimited amounts until the vendor runs out of gold. quite an abusive mechanic if allowed with lots of vendgold, and often times sphere prices items without a value setting on the resources to make it. 

![image](https://user-images.githubusercontent.com/17236327/141922463-e4db4ca8-05f2-4ae8-8d69-5d7fa9774f3c.png)

**Comment by Soulless-1** [comment]
related to https://github.com/Sphereserver/Source-X/issues/814

**Comment by Soulless-1** [comment]
This seems to be related to https://github.com/Sphereserver/Source-X/issues/814

i would expect here we could put settings on how many of a particular item an npc vendor would buy from players and keep in their inventory.

**Comment by Tolokio** [comment]
@itemsell Allow u to do custom it.

I am doing a trigger for selllist and buylist, Ill see if I can add this but I see it hard.

**Comment by JulianUO** [comment]
The place you're looking at is correct, but you already have the item pointer at vendSell.
vendItem is the item at player's backpack and vendSell is the item at LAYER_BUYS from the vendor.
I'm working at a commit, but using an optional flag, because most people don't really care about this limit.

**Comment by Soulless-1** [comment]
Closing out, thanks Julian.
