### ISSUE TITLE
NPC color not updating on old clients 

### ISSUE THREAD

**Issue by a1exp** [Sphereserver/Source-X#803]
This issue is reproducible with client 2.0.3 and Sphere X. 

If you change NPC color which is on the screen - the color is not updated and calling `.update` does not help only `.removefromeview` and then `.update` helps.

To reproduce - simply do `.x color <color>` on an NPC which is on the screen. The same issue happens when NPC color is being changed by scripts. 

I also checked with client 5.0.6 and Orion - not reproducible, so looks like something changed in the way sphere sends update which impacts only older clients.

**Comment by xwerswoodx** [comment]
I see the issue, Client 2.0.3 always has update issues honestly, we could change the update system and add removefromview than update items but honestly making a change for client that released at end of the 90s not a good idea, but probably you can add a function that does removefromview and update if you wish to use 2.0.3 client.

**Comment by xwerswoodx** [comment]
There is an UPDATEX command that removefromview than updated the character.
