### ISSUE TITLE
Incorrect EVAL parsing in case of multiple subtraction

### ISSUE THREAD

**Issue by a1exp** [Sphereserver/Source-X#804]
This function gives 910 (while should give 890):

```
[FUNCTION f_test_eval]
say 1000 - 100 - 10 = <eval 1000 - 100 - 10>
```

adding brackets does not help:
```
[FUNCTION f_test_eval]
say 1000 - 100 - 10 = <eval (1000 - 100 - 10)>
```

![image](https://user-images.githubusercontent.com/31130012/143627618-2212868c-aefa-463f-84aa-bb9389d94882.png)

Meanwhile, this returns 890:
```
[FUNCTION f_test_eval]
say 1000 - 100 + 10 = <eval 1000 - 100 + 10>
```

🤷‍♂️

**Comment by drk84** [comment]
Fix sent, hope it works!

**Comment by a1exp** [comment]
@drk84 👍

**Comment by Soulless-1** [comment]
looks like this broke evals also
```
[function testtesttest]
say <eval (9-1)/4>
```
should return 2 but this is what we get

![image](https://user-images.githubusercontent.com/17236327/148356191-8d44e250-9eda-490a-8a6d-16888bfb7fc9.png)
