### ISSUE TITLE
Poison field does not apply periodic poison tick effect 

### ISSUE THREAD

**Issue by a1exp** [Sphereserver/Source-X#805]
Poison field applies poison which is gone right after initial damage (so you get the first tick and poison is removed). It does not apply periodic damage ticks like normal s_poison does. 

`MAGICF_OSIFORMULAS` is off. 

Seems like this issue was reported in [discord](https://discord.com/channels/354358315373035542/355031741569826816/461609498591756288) long time ago.

**Comment by drk84** [comment]
It's a script pack bug:
Go to Poison Field spell, add SPELLFLAG_TICK and remove SPELLFLAG_DAMAGE.
Change the value of EFFECT from 5,50 to 50,500

**Comment by a1exp** [comment]
@drk84 
ahh.. great, this helps. Thanks!
