### ISSUE TITLE
Items falling on the floor even if you are not overweight

### ISSUE THREAD

**Issue by Vulcan550** [Sphereserver/Source-X#810]
If I forge Ores it appears that the ingot is created before the ore is removed from the bag, making the ingot fall because you are overweight.

Same thing happens when you cut cloth to make bandages. Also when you buy stuff from a NPC.

Can you guys take a look at it?

**Comment by Soulless-1** [comment]
issue with ingots and bandages is that sphere does not remove these items before it adds the new thing. So when it tries to add ingots smelted from ore, you still have the weight from the ore in your bag , and the ingots will drop to the floor. Same thing with cloth and making bandages.

**Comment by drk84** [comment]
Bandage and leather strips should be fixed, i checked the bolt of cloth and they are properly removed before the folded cloth are created.

**Comment by Soulless-1** [comment]
Can confirm this is fixed.
