### ISSUE TITLE
Summoned horses | Polymorph spell

### ISSUE THREAD

**Issue by Vulcan550** [Sphereserver/Source-X#811]
The summoned horses only disappear if they are not being mounted. I think they should be removed even if you are mounted and running to save your dear life from that super evil Mongbat.

Polymorph spell is not giving any status to the player.

**Comment by Jhobean** [comment]
It's a duplication of this issue: https://github.com/Sphereserver/Source-X/issues/582

**Comment by drk84** [comment]
I close because it's a duplicate
