### ISSUE TITLE
SPEECH not respecting the code blocks

### ISSUE THREAD

**Issue by Vulcan550** [Sphereserver/Source-X#812]
Speech for pets are not respecting the code blocks.

Example:
ON=KILL
ON=STAY
ON=COME
ON=TRANSFER
say hi

If I say all stay, it will also run the hi from the ON=TRANSFER.

**Comment by drk84** [comment]
That's normal behaviour, you have to put return in all other commands.

ON=KILL
return
ON=STay
return

and so on
