### ISSUE TITLE
REQUEST: Trigger to control what items a npc vendor offers to buy/sell

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#814]
There is an itemsell and itembuy trigger, but it would be good to have control over what the vendor even shows up as an option for the player to sell to them.  

For instance here maybe the vendor has enough citrines, or maybe only wants to buy 5 more

![image](https://user-images.githubusercontent.com/17236327/147618713-39caafdc-357a-4817-93cf-7538f7f061ca.png)

having 5 show up instead of 75 would be ideal, and controlling it would be good

maybe @vendorseeitems

**Comment by Jhobean** [comment]
If you buy the 5, you. An reopen dialog and buy 5 more?

**Comment by Soulless-1** [comment]
no, not even showing up on the sell dialog if they have enough citrines you should be able to sell them more.

**Comment by Tolokio** [comment]
https://github.com/Sphereserver/Source-X/issues/802

**Comment by Soulless-1** [comment]
> #802

This request would be for modifying that when the player says "vendor buy" or "vendor sell" not for a setting in the scripts. 
Supposing you had an i_sword_long and you didnt want vendors to buy that item cause it had a tag on it. but you did want them to buy any i_sword_long. 

could be useful

**Comment by Tolokio** [comment]
What do u want to modify, the item being shown at sell/buy list?

**Comment by Soulless-1** [comment]
Yeah. this would be something like i say 
"vendor sell"

and the list is generated to show what items i could sell them
for each item (argo) it triggers, and you can return 1 to prevent it from displaying.

Something like this

**Comment by Tolokio** [comment]
hmmm It is interesting but doing a new trigger just for that is expensive. trigger wwould fire once for each item being listed. And we already have @itemsell being fired on all items.
I would do one of this options:
1- Tag.ListNot -> deny item to be listed, can be added anywhere or at @itemsell
2-Moving  @itemsell to the part where items are being listed.

**Comment by Soulless-1** [comment]
the general idea was for this trigger to just not show items that the vendor wont buy, because they have enough. i think we can close this with Julians fix for vendors not respecting items maxes in their buy list. If there is a need for this i can re-open the request.
