### ISSUE TITLE
NPCs wandering into sleeping sectors

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#816]
I just happened to be in the right spot to show this , when npcs wander into a sleeping sector, they will get stuck there, and they line up on the edge of the sector . This often time causes npcs to cluster in strange line formations all over the map.  

![image](https://user-images.githubusercontent.com/17236327/148352471-e654f426-1fb3-41c6-8fea-2841636bf297.png)

it seems like this used to not be an issue? I believe sector sleep was changed at some point in X. Perhaps the monsters can not fall asleep in a sleeping sector unless their spawn bit is in that sleeping sector as well?

**Comment by Jhobean** [comment]
Do you have last versio? Sector sleep was not working correctly for long time. It was fix recently.

**Comment by Soulless-1** [comment]
Build 3483, its been going on for quite a while just found the perfect picture to illustrate it

**Comment by Soulless-1** [comment]
NPCs still cluster up in areas along sectors, even if a player takes a moment to reach them they are not uniformly throughout the sector.  
![image](https://user-images.githubusercontent.com/17236327/156585368-a33136ae-0fc0-43b2-a253-a1ebfb177e17.png)

**Comment by Soulless-1** [comment]
This seems to be fine now. thank you.
