### ISSUE TITLE
crash with damage command 

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#818]
Server crash when using damage in the scripts and not having enough flags

under @gethit under @combatadd
.src.damage 50 dam_fire in my script crashes the shard
this doesnt crash the shard
.src.damage 50 dam_fire <uid>

using .damage 50 dam_fire in game with a gm does not cause a crash

using just this function it doesnt crash either
[function blarp]
damage 50 dam_fire

**Comment by a1exp** [comment]
Are you damage inside @GetHit does not lead to an infinite loop in your case?

**Comment by Soulless-1** [comment]
hmm will test further, i was doing it for <src>, but I do see the possibility for an infinite loop, will test under other triggers. good thought Alex

**Comment by drk84** [comment]
I can't replicate it,
I put 
ON=@GetHit
src.damage 50,dam_fire

is this correcT?

**Comment by Soulless-1** [comment]
closing, will re-open if I can replicate it properly.
