### ISSUE TITLE
Issue with COMBAT_SWING_NORANGE	anim

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#819]
The animation will play when you are at a distance, it should only play when you come back into range with the target

https://user-images.githubusercontent.com/17236327/148721485-4d085ba9-124d-4180-9791-5f6f30dd11a0.mp4

**Comment by Tolokio** [comment]
I dont understand the issue.

**Comment by Soulless-1** [comment]
see how the swing happens when you are not near the target?

**Comment by Jhobean** [comment]
I dont have this on my shard..... I should try on blank script

**Comment by Soulless-1** [comment]
that doesnt mean you are supposed to slice your sword through the air 10 ft away though. it just means your swing is stored up for the next time you come back in range, then it is supposed to happen. 

`The hit can be started at any distance and regardless of the Line of Sight, then the damage will be dealt when in range and LoS`

the animation should happen with the damage

**Comment by drk84** [comment]
Fix sent

**Comment by drk84** [comment]
I close this
