### ISSUE TITLE
Weight: Paperdoll, Dragging, and Max Carry Issues

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#822]
This is a multi faceted issue, but it all ties into one big problem that's constantly reported on many shards over many years.  (prepare yourself for a long paragrah)

Many problems that are due to several issues :  Dropping items when they unequip from your paperdoll and youre overweight,  Not being able to put things in your bag over your weight limit, Not being able to drag heavy items, and not losing stamina properly when overweight

The way UO Does it, and this is why these issues don't exist on the official servers:

Your paperdoll does not count against your weight that can go in your bag, equipped items add weight to you, but you can always equip an item regardless of your weight, should you cast a spell and it cant fit in your backpack it would just bounce back to your paperdoll and you would not drop it on the ground. you should never lose an item because it was unequipped by a game mechanic. and weight in your backpack is the only thing that should determine if you can put something into the backpack. this is the message you get for that :
![image](https://user-images.githubusercontent.com/17236327/148723649-511b4e20-77b9-47c4-b4ad-24f59d36cdd2.png)

Now the backpack's weight limit is based on your strength, and that's the amount of weight until the backpack is overloaded. when the backpack is overloaded it does not mean new items cannot go into it, that means you will lose stamina at a rate of 1 stamina for every 5 stones you are over the max carry weight. this amount you are allowed to have over the weight is about 30 stones over the backpacks max carry weight. at 100 str your backpacks max weight is 390. You can overload it up to 420 (not counting a characters equipped items) When you place an item in the backpack and it has become over loaded it's supposed to tell you that it's overloaded, once you reach 30 stones over the max carry limit then you are no longer able to fit items into the container and they bounce back to wherever they came from. overloaded message :
![image](https://user-images.githubusercontent.com/17236327/148723672-74423d00-8c07-4eda-9d9a-edb54c8536ac.png)
![image](https://user-images.githubusercontent.com/17236327/148724016-0812fbdb-44ba-452d-868e-5636a2cfc368.png)

You should be able to drag any amount of weight/items with your cursor, the weight is already added to your char as soon as you pick it up, so the same mechanics above that dictate weight/movement. If the weight is beyond what you can fit in your backpack beyond the overload limit, then you are not able to put it into your backpack. if is under 30 stones over your max backpack carry limit then you are able to fit it into your bag. Limiting what people can drag only serves as hindrance to organizing banks and chests with heavy items in it. no picture needed for this.

mentioned above a little bit, extra stamina loss when overweight is the big disadvantage to being overloaded. just being 5 stones over your max backpack carry limit will drop your stamina 1 for every step. at 15 stones over your max backpack carry limit you will lose 3 stamina every step, and this mechanic is what urges players to stay underweight.

**Comment by TheLastKingdomUO** [comment]
For many years when I was a player, I was able to move really heavy stuff inside my bank, able to put tons of loots inside a bag into the drag layer, drop it on the floor, and do it all over until I find a safe place for the bag. Still remember running overweight and the stamina going down quickly. Also, remember having heavy items in the drag layer and stamina going down. It was fun and very very very useful. On my server I cannot do that, hoping for a fix for it. It would be nice to have those settings in sphere.ini.

**Comment by Soulless-1** [comment]
perhaps we could have some more stuff for @itemequiptest ? It doesnt seem to fire if the item is going to make the player overweight. so maybe if it fired before that check and maybe a local that can be disabled when an item is putting you overweight to allow it equip anyways.

**Comment by Jhobean** [comment]
info on this issue TOO: https://github.com/Sphereserver/Source-X/issues/633 

Coruja Commit about this fix on 56d
https://github.com/Sphereserver/Source/commit/c9c0af71ba1fc54ddbab8f9bdae70739e24b0254
https://github.com/Sphereserver/Source/commit/937fd287975830c76a0cebfcd7e8e8e251b04ef4
https://github.com/Sphereserver/Source/commit/f29e8592ad154c4dd55ed4b5d8900b094793e62a
https://github.com/Sphereserver/Source/commit/191a13e7bc91a709db79d1270c467a5561038541

**Comment by Soulless-1** [comment]
drag weight, overloading bags, and stamina loss while overloaded is working good. 

I think some improvements could be made to the stamina loss while you are under maxweight, since there isnt a way to reliably control stamina loss at all weight %'s 

And items that are unequipped for any reason while you are overweight, should not drop to the ground, they should always go back to your paperdoll. After that I think we can all have a big sigh of relief

**Comment by Soulless-1** [comment]
This seemed to be working fine, i havent had any reports of issues with it lately. maybe a separate issue in that case. thank you, im closing this one out.
