### ISSUE TITLE
Eval issues, incorrect results

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#824]
some of the division is wrong 
[function test]
serv.log 10 + 10 / 2 = <eval (10+10)/2>
serv.log 10 + 10 * 2 = <eval (10+10)*2>
serv.log 10 * 10 / 2 = <eval (10*10)/2>
serv.log 10 / 10 * 2 = <eval (10/10)*2>
serv.log 8 - 4 / 2 = <eval (8 - 4)/2>         <-------------
serv.log 8 - 4 * 2 = <eval (8 - 4)*2>

![image](https://user-images.githubusercontent.com/17236327/148744747-fc8218c8-d12b-4311-bebb-275cc70fe037.png)

**Comment by drk84** [comment]
looks fixed
