### ISSUE TITLE
ONAME set on player character deletes it on startup

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#825]
Setting ONAME on a player's character will delete it on server startup

![image](https://user-images.githubusercontent.com/17236327/149126771-1ec2612f-b6a5-4f4d-b954-39a5ace7ad86.png)

**Comment by drk84** [comment]
I can't replicate it always!

**Comment by Soulless-1** [comment]
Using the Jun 8 build I have on my local test shard
1) made new char named 'onametest'
2) set 'oname' on the char to 'frank'
3) save the shard
4) close and reload the shard , the character is deleted
![image](https://user-images.githubusercontent.com/17236327/176906033-8a8cd047-c4a2-41c1-8220-39e4775bb932.png)

**Comment by drk84** [comment]
Ugly fix/workaround sent.

**Comment by Soulless-1** [comment]
Fix confirmed working. thanks.
