### ISSUE TITLE
Comparing triggers

### ISSUE THREAD

**Issue by tonyuo** [Sphereserver/Source-X#826]
I have been comparing hits and maxhits using:

(<act.hits> >= <act.maxhits>)

And seems that >= didn't run well. It only run when hits were same as maxhits.

 I don't know if it happens the same to ==,>,<,<= and !=

**Comment by drk84** [comment]
Try enable OF_StatAllowValOverMax in the sphere.ini

**Comment by drk84** [comment]
I close this
