### ISSUE TITLE
players can recall to runes in their bank when they are away from bank

### ISSUE THREAD

**Issue by a1exp** [Sphereserver/Source-X#828]
With a simple UO macro like `cast spell -> recall, wait for target, last target` you can cast recall using a rune (assuming you obtained the target before that) from your bank even when the bank is closed. 

Players on Injection or similar 3rd party programs, can obtain rune's UIDs and recall using runes from their bank, while been away from bank actually.

**Comment by Jhobean** [comment]
Nolok made a similar fix for that. Maybe we can add some behavior on it.https://github.com/Sphereserver/Source-X/issues/344

**Comment by drk84** [comment]
Does this happens only in bank or even in other containers outside the player layers? (The bank is stored inside the player)

**Comment by a1exp** [comment]
@drk84 only with a bank as far as I know.

I belive we're missing a check [here]( https://github.com/Sphereserver/Source-X/blob/174d64e65f0c8d6c6eace9fd96f5b646c697ddd0/src/game/chars/CCharSpell.cpp#L2690-L2694).

**Comment by Jhobean** [comment]
I have some teport from my player, they can use water throught(in their bank) to clean bandage....  I did not test it.

I had some player was able to use custom stone in their bank too. These stone was use with orion assistant. You just need tonstore the uid and use it

**Comment by a1exp** [comment]
Well.. if that's so, then probably we should look for a more generic solution.

**Comment by a1exp** [comment]
@Jhobean with a build from Feb 14 I can still cast using last target macro, when a bank gump is closed. Seems like it doesn't help. Does it work for you?

**Comment by a1exp** [comment]
@Jhobean now when I reviewd the fix, I see why it didn't work for me. I just closed the bank and tried to cast standing on the same location, while the fix checks that location has changed
```
 // Check if the item is in my bankbox, and i'm not in the same position from which I opened it the last time.
```
We could use `CanSeeInContainer()` function by the way instead, but it seems it has the same logic of checking the map point. So the fix is fine.  

The only thing which looks odd to me is that there is no messages displayed to the player, I would expect something like "you can't see the target" as in other similar cases. Here what I see is just "select target" and then nothing happens.

I think it's a minor issue, just being a pedantic here 😄

**Comment by Tolokio** [comment]
Fix is fine, issue can be closed?

**Comment by a1exp** [comment]
Sure, why not.
