### ISSUE TITLE
No space between skill value and name in <skillmake> text

### ISSUE THREAD

**Issue by a1exp** [Sphereserver/Source-X#832]
Cosmetic issue with displaying <skillmake> text - there is no space between skill value and skill name.

`.x show skillmake`

![image](https://user-images.githubusercontent.com/31130012/151832629-b8dd6b8c-1a62-4b11-9ec0-14642a0a6e4a.png)

while itemdef definition is with a space of course
```
[ITEMDEF 019b7]
DEFNAME = i_ore_iron
NAME = iron ore
TYPE = t_ore
SKILLMAKE = MINING 10.0
TDATA1 = i_ingot_iron
WEIGHT = 1.2
VALUE = 4
DUPELIST = 019b8,019b9,019ba
```

**Comment by drk84** [comment]
Fix Sent

**Comment by a1exp** [comment]
@drk84 verified 👍
