### ISSUE TITLE
Cannot update NPC home

### ISSUE THREAD

**Issue by a1exp** [Sphereserver/Source-X#844]
It's seems that `home` of an NPC cannot be set via `.x home <p>` (neither with a GM command nor via a script). 

Steps to reproduce:
 1. create an npc, check that initial home is `-1,-1`
 2. try to set home via `.x home 4545,1475` (or whatever) 
 3. home is not updated and still is `-1,-1`

I noticed that `home` can be initialized by simply setting `.x homedist <somehting>`. Then the home is atomatically updated to the current NPC location. But still, I haven't find a way of updating this home value later. `.x home <new p>` just does not have effect.

**Comment by drk84** [comment]
Here works properly
![immagine](https://user-images.githubusercontent.com/13728442/154247111-37f978c6-eb1f-4a16-a2c2-04df96542195.png)

The correct command is .xhome (without blank space) not .x home btw

**Comment by drk84** [comment]
![immagine](https://user-images.githubusercontent.com/13728442/154247621-25806e4d-a6b6-4cdc-bea4-532c85502bdf.png)

**Comment by a1exp** [comment]
Hm.. doesn't work for me, let me double check with the default script pack and get back to you.

**Comment by a1exp** [comment]
Sorry, the problem was on my side. @drk84 thanks for checking on that.
