### ISSUE TITLE
update README.md Building text.

### ISSUE THREAD

**Issue by ted182** [Sphereserver/Source-X#845]
I'm not sure, but it seems that cmake's way of compiling has changed a bit, where we see the text:

> cmake -DCMAKE_TOOLCHAIN_FILE=../src/cmake/toolchains/Linux-GNU-x86_64.cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Nightly" --build ./ ../src

needs to be written as follows now:

> cmake [options] -S src -B build

this way, it would look like this (inside the build folder ./Source-X/build):

> sudo cmake -DCMAKE_TOOLCHAIN_FILE=../src/cmake/toolchains/Linux-GNU-x86_64.cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Nightly" -S ../src -B ./

**Comment by Jhobean** [comment]
Appbeyor compile it with this line:
https://github.com/Sphereserver/Source-X/blob/af6c544f5a7b6ead312aab174b72d4897768c055/appveyor.yml#L128

**Comment by xwerswoodx** [comment]
Seems like already changed.
