### ISSUE TITLE
Can't combine ore at floor

### ISSUE THREAD

**Issue by tonyuo** [Sphereserver/Source-X#847]
Ore Cann't be combined at floor if it doesn't have same amount.

When you drop them on any backpck it runs well. But on the floor, you can only combine same amount of ore.

I add 2 gif that i posted at discord:

https://cdn.discordapp.com/attachments/355031741569826816/950878616584065034/ore2.gif

https://cdn.discordapp.com/attachments/355031741569826816/950876558053236776/ore.gif

**Comment by Jhobean** [comment]
Tested and comfirmed on clean xPack + last server. It's not link to Ground because same thing happen if you do it in backpack.

**Comment by drk84** [comment]
I confirm the bug, but it's not related to the amount but to the fact that some items have different DISPID when they  are below a certain amount value (It could be a client bug also, because if you drop a pile of 200 ore in the backpack that contains 1 ore you will get a stack of ore with an amount of 201)

**Comment by canerksk** [comment]
you should pay attention to this.  Items of the same type left on the same tile do not combine, but items dropped on the same item do.  item on the same tile and item on item item on item was the same thing but not anymore

**Comment by Raylde** [comment]
> you should pay attention to this. Items of the same type dropped on the same tile do not merge, but items dropped on the same item do. so dropping items on the same tile was the same as dropping items on items, but not anymore
> 
> item drop same item =stack item drop same tile ground= nostack

thats correct, right now work fine.

Closed
