### ISSUE TITLE
Conflicting teleport on resync

### ISSUE THREAD

**Issue by mtwango** [Sphereserver/Source-X#852]
When you have running sphere, changing file with map teleports (map0_teleports.scp / spheremap.scp or any other name you have it in) and resyncing scripts it gives you [Conflicting teleport](https://github.com/Sphereserver/Source-X/blob/d55c36270369ce2ffd69402668c2e5663ba598e9/src/game/CSectorTemplate.cpp#L412).

This is probably due to adding teleports again, instead of updating or removing and adding them again.

**Comment by Jhobean** [comment]
All change on MAP file need a reboot. It's the only files require this.

**Comment by drk84** [comment]
I'll close this
