### ISSUE TITLE
Memory Leak? [Linux]

### ISSUE THREAD

**Issue by youhide** [Sphereserver/Source-X#854]
the memory doesn't stop growing in the linux version, with the same build in windows it doesn't happen

![image](https://user-images.githubusercontent.com/4053124/160527560-3a030c9a-c8ed-4a74-a075-b4f6f39bd68a.png)

![unknown](https://user-images.githubusercontent.com/4053124/160527580-846f11fe-15d4-4bf0-9de4-3ed713d79b70.png)

normally it consumes 500mb only

**Comment by youhide** [comment]
![Screen Shot 2022-03-29 at 12 33 24](https://user-images.githubusercontent.com/4053124/161579555-d740b100-8fbe-43b6-8a0b-715b87e87ceb.png)

**Comment by cbnolok** [comment]
Can you try to run a debug build with gdb to check which call to free crashes? In any case, i think that's a different issue from the memory leak, i'd try to run locally a debug build with valgrind for that, i can give you some advice in case

**Comment by youhide** [comment]
i guess this was a problem with my environment, closing...
