### ISSUE TITLE
NPCs canceling other npcs from hearing player speech

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#859]
NPCs that are standing closer to you will prevent npcs further away from hearing you, for instance if you are issuing a command to a specific NPC/PET and one is closer, even if you use the correct pet/npcs name the one you are directing the speech to will not hear you because the closer one heard it and even if it's not a valid command for them to respond to, it'll just stop the other one from hearing you.

**Comment by Jhobean** [comment]
If you say his name before the command it work?

**Comment by Soulless-1** [comment]
seems to not work always. players have had the issue with player vendors, and pets mostly it seems.

**Comment by Soulless-1** [comment]
![image](https://user-images.githubusercontent.com/17236327/166112012-fd610ad3-1743-4861-9a08-2a2bac95f8b4.png)
![image](https://user-images.githubusercontent.com/17236327/166112024-2ce69196-e577-4398-831b-ac086c6b153b.png)
![image](https://user-images.githubusercontent.com/17236327/166112036-641d6a3b-b4c1-4e3c-bc43-4f6590e0264d.png)
