### ISSUE TITLE
@ITEMDROPON_CHAR

### ISSUE THREAD

**Issue by falanlar** [Sphereserver/Source-X#869]
Not working

**Comment by drk84** [comment]
They works fine, how do you use them
![immagine](https://user-images.githubusercontent.com/13728442/175811413-cb0bf749-3d61-40e8-9642-639cded02b5b.png)

**Comment by falanlar** [comment]
like this. I tried both ways, both don't work
[https://im5.ezgif.com/tmp/ezgif-5-34f7fcce53.gif]
(https://im5.ezgif.com/tmp/ezgif-5-34f7fcce53.gif)

**Comment by Jhobean** [comment]
> like this. I tried both ways, both don't work https://im5.ezgif.com/tmp/ezgif-5-34f7fcce53.gif

I cant see your image. Whete did you put the trigger on the script?

**Comment by falanlar** [comment]
sorry, link updated
https://i.gifer.com/3ONDi.gif

**Comment by drk84** [comment]
Works fine here, try use serv.log and an official client

**Comment by drk84** [comment]
I can't reproduce, works fine here

**Comment by Jhobean** [comment]
Strange if you add it not in event but direct under the itemdef? Or maybe try clean script pack

**Comment by falanlar** [comment]
@Jhobean 
i tried everything from 0 again and it still didn't work
interesting :)
