### ISSUE TITLE
Request: Exclusion to sleep/timer

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#872]
There are things that should always trigger @timer regardless if the sector is sleeping. typedefs such as t_crop. 

items on the ground should always decay because otherwise when someone comes into the mouth of a dungeon they see everything then it disappears a second later, this results in countless people paging about bugs.

mounted pets should always trigger @hunger otherwise mounted pets dont lose food levels.  Though @drk84  might of fixed this with #871  i'll have to check!

**Comment by Jhobean** [comment]
It's 100% true. Some exception should be made on some situation.

**Comment by Soulless-1** [comment]
closing this out, not required to do this in the source, people can control sector sleep and have can_o_nosleep where needed.
