### ISSUE TITLE
Height Issues

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#877]
Looks like sphere has some height issues, which cause a few problems with preventing players moving around. There are quite a few spots, but here are two examples of what the issue is :

in this example you cannot walk in these areas if your height is over 12, because the roof would be "too low" for you, however this is not a place that players are restricted from walking in UO, and in this tight area it impedes a lot of players pvping in this popular building 
![image](https://user-images.githubusercontent.com/17236327/180660494-658648a4-7172-48a5-bd39-1a7cb7bfa741.png)

and if this example if you are under 15 height you cannot walk up this hill
![image](https://user-images.githubusercontent.com/17236327/180659610-1482fe19-3301-4f1d-8f91-8318a55dba12.png)

there is no setting you can have in the current system that will not result in issues for players, and i do not see a way to turn off this system in the sphere.ini

You are short enough to fit under all buildings and too short to walk up some hills
OR
 you are too tall to fit under some rooves but tall enough to walk up all hills

**Comment by Tolokio** [comment]
the outside from britain sewers have use to need a ladder or something from many years if i remember right.

But there are certain height issues. I did a post about it.
Duper items takes height from original item, So many heights are bad.

**Comment by Tolokio** [comment]
@Soulless-1  Could u add more info abot the bbuilding issue. U said client allow to walk buy sphere denys it.
can u tell the Z of the floor and roof? and do .xshow height of both as well?

For the second, should we add a climbing trigger, or at least we should dicuss abaut whhat would be the max Z a char should b able to climb

**Comment by Soulless-1** [comment]
No, when I reference UO i mean the game ultima online traditionally does not prevent the player from going into buildings due to height. In my examples those are the types of things players should be able to do under all circumstances, otherwise it limits them access to parts of the map, or may cause them to get stuck in areas.

this isnt about item height or anything like that. 
the climb trigger would be separate from this, it's about being able to walk.

**Comment by Soulless-1** [comment]
working on a test build, will close out when PR complete, thank you Xwerswoodx

**Comment by cbnolok** [comment]
Any news on this?

**Comment by Soulless-1** [comment]
indeed fixed, need a height of 12, but i can walk in all areas. thank you!
