### ISSUE TITLE
houses | ships removing keeps them stuck in totalcount without UID

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#895]
Hi,

i just found out there is probably some issue with the houses and ships property counting multis.
If you build house / ship, houses or ships will add +1 and its UID.
this way first house/ship is house.0 and UID stored.

If you remove the house or ship, the UID will become 0, but the problem is, you still see that you have one house, with UID 0.
This diseappear only if you shutdown sphere and run again.

This way if you have sphere limit for 1 house/player and he fail to build it properly on wanted spot and needs to redeed and build again, he is blocked by limit until sphere shutdown.

**Comment by Jhobean** [comment]
Very similar to #530

**Comment by JulianUO** [comment]
I think I found the issue on the code, will test in the following week.

**Comment by Tolokio** [comment]
@julian any update?

**Comment by Julian** [comment]
Not yet.

**Comment by Tolokio** [comment]
![image](https://user-images.githubusercontent.com/20745578/197021025-fadfdcdf-56c0-4a5a-a859-8d846bb403ee.png)
shouldnt b there  nullptr instead 0?

**Comment by JulianUO** [comment]
No, this is related to how std::vector and std::map works, and it happens
when you remove an item from the list

**Comment by AtillaG1** [comment]
So we have a solution with help of GorGo.
Basically the sphere function "redeed" does the work and by using this, everything is correctly deleted, even from <houses>,<ships>.
Thats because inside this function in core, there is probably .delhouse or .delship being performed internaly, and this does the trick.

So to fix my issues, i added this before my ships redeeding function, and before my function deleting houses that decayed.
<uidofowner>.delhouse <uidofdeletedhouse>
<uidofowner>.delship <uidofdeletedship>

Only issue is, if you manualy delete house or ship, then the UID from owners list will be deleted, but the total amount will be stuck until you restart the sphere.

**Now i will let this for the Devs to decide, if this issue to be closed or not.**

**Comment by AtillaG1** [comment]
FIX PR #957 
CLOSING

**Comment by Tolokio** [comment]
there is not fix added to source-x yet. Bug stills.

**Comment by drk84** [comment]
I sent a commit
Aabout the scripts part the various messages should be moved after the remove command
![immagine](https://user-images.githubusercontent.com/13728442/206225631-5f4b3518-1357-480b-a36a-789b528b713b.png)

**Comment by AtillaG1** [comment]
seems like fixed, thanks! 😎
