### ISSUE TITLE
USEITEM NOT WORKING

### ISSUE THREAD

**Issue by falanlar** [Sphereserver/Source-X#909]
USEITEM not working unless the player enters the same screen as the item. For example, you cannot open a safe from another part of the map using useitem with a player account. Should normaly :
**USEITEM :** Double clicks the character, with SRC as the source of the event, without checking for line of sight.

**Comment by Jhobean** [comment]
Hmmm..  some restriction was added because player was able to use item far away with assistant (razor, orion, injection).
Maybe the fix implement some "bug" but I dont get how a player would have to use far away item.

**Comment by Jhobean** [comment]
I read the changelog of implementation of thia function and you are right, USEITEM was implemented to do what you say.

**Comment by falanlar** [comment]
I am using sphere version build 3529, client version 7.0.95.0 but not working, doesn't work with both player and staff characters

**Comment by Tolokio** [comment]
Even if u were allowed to open the container, player (and i think even a gm) will not be able to interact with any item inside. You will see the items inside but as soon u target them or try to grab them, they will removed from your screen by sphere's internal code.

Anyway, I think u probably are not using right "useitem" 

![image](https://user-images.githubusercontent.com/20745578/195144114-7953872f-2003-4542-ab73-a74f3a72febd.png)

As u see in the image, useitem got to ways to be used.

```[function f_far_container]
uid.<args>.useitem
```

U probably are using the second method: src.useitem <item_uid>. try to call useitem on the item instead on src and lets see if it works. But as I said, even if it works u will not be able to interact with items inside the container.










We may could be able to fix useitem, but more changes will be need to do what I think u want to do.

**Comment by falanlar** [comment]
[https://s4.gifyu.com/images/GIF-13.10.2022-01-16-41.gif](url)

**Comment by Tolokio** [comment]
no sysmessages, but at least it turns char to face the container.
Did u try the can_i_forcedc?

**Comment by falanlar** [comment]
it does not give any system message but there is no problem with potions

**Comment by Tolokio** [comment]
last question, what happens if u try with a corpse?

**Comment by falanlar** [comment]
Unfortunately i can't access containers and corpses even if I use can_i_forcedc

**Comment by falanlar** [comment]
example for corpses
https://s4.gifyu.com/images/GIF-13.10.2022-01-49-19.gif

**Comment by Tolokio** [comment]
That was really useful.

I have some theories but can't be sure. Anyway I think this is beyond my knolowdge, I dont understand how sendpackets works.

![image](https://user-images.githubusercontent.com/20745578/195463758-9e1d8ebb-5f3e-4fa1-96f8-85a44c04f7ea.png)
First theorie: Ur client is not crashing, but as pcontainer is not send to your client, it just dosnt want to open it. So it would be a client issue.

![image](https://user-images.githubusercontent.com/20745578/195464014-ef74ca77-9030-4980-bf8c-d7dc42a7d0b8.png)
second theorie: It seems there is a cansee check on last moment. As I dont know how sendpackets works, I don't know if cansee() denies the opening, but cansee() check if the items is on visual range, so could be that.


Second theorie

**Comment by falanlar** [comment]
thank you for your help. we are waiting  then :)

**Comment by Tolokio** [comment]
We wait for anyone beyond my knolowdge I am so noob with source.

anyway, even if this is fixed, u will not be able to interact with the items inside the container.

To know what I am saying do this:
1-Put a container inside your bank filled with random items.
2- Close bank
3-use "useitem" to open the container that is inside the bank.
4- try to interact with the items inside the container.

**Comment by Jhobean** [comment]
Bank is different. Because it's on yourself. Recently some check was added to block the possibility to use item on bank.

**Comment by Tolokio** [comment]
Yes, Bank is diferent. But I did that test much time ago before the recently fix. The case is, when u try to interact with the items inside a container that is inside the bank, cansee()  will check the interaction, removing from ur view any item u try to interact with. No matter if u try to grab, target or dclick the item. As soon u try it, the item will dissapear from ur view, and it is not possible to fix it by script.

In the same way, if u try to interact with items in a container that is outside ur range of view, cansee() will prevent it, removing the items from clients view. 
 Even if "useITEM" is fixed, Falanlar will not be able to do what he wants to do without another fix. And even if everything is fixed, I think client could prevent it as well making all useless.
 
 I know all this cos in the past I tried to do something similar to what he is trying. Best thing he could do is to try to move the container into layer_buy, layer_sell or layer_special. Then put the container back where it was(if he need to move it back), BUT, how knows sphere when it gets closed? He will need to use a timer that send back the container when characters changes <p>.

**Comment by AtillaG1** [comment]
I do think reaching item/box or whatever that is out of your view, either on ground, home or bank should be only possible for GMs etc...
As someone said, this was fixed because players had possibility to use/grab items that were not in their reach/view.

**Comment by Tolokio** [comment]
There are some cases/system u could want to reach things outside our point of view. Useitem is for that cases, but it dosnt work with container. It is not related to the bank fix cos bankbox is a layer that always is in your point of view.

"Useitem" allow to use anything no matter where it is, but containers needs to be sended to clients to be open. So it will not work with containers that is not on your screen.

**Comment by drk84** [comment]
what about the DCLICK command hm

**Comment by falanlar** [comment]
https://gifyu.com/image/SEbiI

**Comment by Tolokio** [comment]
> what about the DCLICK command hm

It shouldnt matter, client will not open if u dont send the container to the client first. Client would crash or ignore the order to open it, I think

**Comment by falanlar** [comment]
is there any solution yet

**Comment by drk84** [comment]
It's client related, for testing i removed the distance check and the container gump is not sent if the character distance is > 18

**Comment by Jhobean** [comment]
Same issue than #629 ?

**Comment by drk84** [comment]
Client issue imho

**Comment by drk84** [comment]
I close it
