### ISSUE TITLE
E_SHIP_PRIV & E_SHIP_HOUSE

### ISSUE THREAD

**Issue by falanlar** [Sphereserver/Source-X#912]
When I enter the house and the ship, the e_house_priv event is automatically added to the character, everything is normal until here. i have 2 question now
1-i want to replace these events with other events, is it possible ?
2-When I get on ship, the e_house_priv event is added to the character instead of e_ship_priv, is this normal ?

**Comment by JulianUO** [comment]
Hi, 
1. Yes, you can script your own event, just declare [events e_house_priv] and add your triggers.
2. No, it should be e_ship_priv for ships, check that your multi is type t_ship.

**Comment by drk84** [comment]
I close this
