### ISSUE TITLE
Upgrade for support recent OS

### ISSUE THREAD

**Issue by Raylde** [Sphereserver/Source-X#914]
Is a big problem for those who install a recent OS like Ubuntu 22 or Debian 11.
The problem is mysql, maybe upgrade with this https://github.com/Sphereserver/Source-X/pull/881 for support newest os

**Comment by mtwango** [comment]
I've tried building / running on Debian 11 (in WSL) and currently it seems pretty simple.

**Building**
I've deleted all mysql / mariadb libs.
`sudo apt install libmysql++-dev` Only mysql lib I needed, nothing from external repos.

**Running**
I've deleted all mysql / mariadb libs again.
`sudo apt install libmariadb3` Again from default repository. I've tried connecting to database on different machine (from Debian 11 in WSL to MariaDB 11.0 on localhost) and it works ok (connection, query, getting values from columns).

**Comment by cbnolok** [comment]
That pr has too much unneeded files to include, unfortunately... And i won't be sad if we officially switch to mariadb connector

**Comment by mtwango** [comment]
Maybe updating info in readme and/or build actions would be enough to make it clear how to run with current OS / tools.

**Comment by cbnolok** [comment]
Should be solved now
