### ISSUE TITLE
NPCs dont attack

### ISSUE THREAD

**Issue by Tolokio** [Sphereserver/Source-X#933]
Npcs will not attack you if u set "EventsPet" at sphere.ini to use your own event for npcs. The events will work, but for some reason I dont understand npcs will not be able to attack.
Tested with this:
![image](https://user-images.githubusercontent.com/20745578/197114992-499249b0-262b-4d32-836a-234b914eae1e.png)
If I attack, logs will appear on console, but npc will not fight back. IF there is no event set, there is no problem. :/

How to reproduce:

1-uncomment "EventsPet"  on sphere.ini tand add your own event.
2-try to force an npc to attack you.

**Comment by Tolokio** [comment]
did y try it?

**Comment by AtillaG1** [comment]
yes, with X pack.

**Comment by Tolokio** [comment]
I tried with a fresh build and it is broken for me....

**Comment by AtillaG1** [comment]
Maybe its more likely some sphere.ini settings you have enabled/disabled?

**Comment by Tolokio** [comment]
Tested with fresh empty build, with player account instead gm account. No changes at sphere.ini.

**Comment by AtillaG1** [comment]
what do you mean by no changes at sphere.ini ? No combat flags and other flags set up ?

**Comment by Tolokio** [comment]
did u really try it? go ahead and download a fresh build and try it before continue this plz

**Comment by AtillaG1** [comment]
yes im always testing with latest build. 👍

**Comment by AtillaG1** [comment]
dont need to force them to anything, they attack immediately.
https://i.gyazo.com/2c627c9324c70b8f9d81ce3527cfd962.gif
https://i.gyazo.com/28961be37f3ac07799744006afc6a8e2.gif

**Comment by Tolokio** [comment]
Then my pc is broken os something

**Comment by Tolokio** [comment]
Closed as i dont be able to reproduce it again. But I think I did everything good.
