### ISSUE TITLE
property lowermanacost doesnt work properly

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#949]
If you set the propery to whatever higher then 0, the cost of spells will be 0 and you can cast it even with 0 mana.
Not being reduced by the number you put in.

> ushort CServerConfig::Calc_SpellManaCost(CChar* pCharCaster, const CSpellDef* pSpell, CObjBase* pObj)
> {
> 	ADDTOCALLSTACK("CServerConfig::Calc_SpellManaCost");
> 
> 	ASSERT(pCharCaster);
> 	ASSERT(pSpell);
> 
> 	bool fScroll = false;
> 	if (pObj != pCharCaster)
> 	{
> 		const CItem* pItem = dynamic_cast <const CItem*> (pObj);
> 		if (pItem)
> 		{
> 			const IT_TYPE iType = pItem->GetType();
> 			if (iType == IT_WAND)
> 				return 0; //Spells from wands cost no mana.
> 			else if (iType == IT_SCROLL)
> 				fScroll = true;
> 		}
> 	}
> 
> 	const CCPropsChar* pCCPChar = pCharCaster->GetComponentProps<CCPropsChar>();
> 	const CCPropsChar* pBaseCCPChar = pCharCaster->Base_GetDef()->GetComponentProps<CCPropsChar>();
> 	const int iLowerManaCost = (int)pCharCaster->GetPropNum(pCCPChar, PROPCH_LOWERMANACOST, pBaseCCPChar);
> 	ushort iCost = (ushort)(pSpell->m_wManaUse * ((100 - iLowerManaCost) / 100));
> 	
> 	if ( fScroll )
> 		return iCost / 2; //spells cast from scrolls consume half of the mana.
> 	
> 	return iCost;
> }

**Comment by drk84** [comment]
Yup confirmed

**Comment by drk84** [comment]
fix sent
