### ISSUE TITLE
property lowerreagentcost doesnt work properly

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#950]
As you increase this property, it takes all the reagents, until the value is too high and it takes nothing.
I dont think it works correctly, since it takes everything or nothing.

> size_t CServerConfig::Calc_SpellReagentsConsume(CChar* pCharCaster, const CSpellDef* pSpell, CObjBase* pObj, bool fTest)
> {
> 	ADDTOCALLSTACK("CServerConfig::Calc_SpellReagentsConsume");
> 	
> 	ASSERT(pCharCaster);
> 	ASSERT(pSpell);
> 
> 	//Check for reagents
> 	if (g_Cfg.m_fReagentsRequired && !pCharCaster->m_pNPC && (pObj == pCharCaster))
> 	{
> 		const CResourceQtyArray* pReagents = &(pSpell->m_Reags);
> 		const CCPropsChar* pCCPChar = pCharCaster->GetComponentProps<CCPropsChar>();
> 		const CCPropsChar* pBaseCCPChar = pCharCaster->Base_GetDef()->GetComponentProps<CCPropsChar>();
> 		const int iLowerReagentCost = (int)pCharCaster->GetPropNum(pCCPChar, PROPCH_LOWERREAGENTCOST, pBaseCCPChar); //Also used for reducing Tithing points.
> 		if ( Calc_GetRandVal(100) >= iLowerReagentCost)
> 		{
> 			CContainer* pCont = static_cast<CContainer*>(pCharCaster);
> 			const size_t iMissing = pCont->ResourceConsumePart(pReagents, 1, 100, fTest);
> 			if (iMissing != SCONT_BADINDEX)
> 				return iMissing;
> 		}
> 	}
> 	return SCONT_BADINDEX;
> }

**Comment by drk84** [comment]
According to the OSI description:
It provides a percentage rate for any spell cast by the wearer **to not to consume reagents**(https://www.uoguide.com/Reagents).

**Comment by AtillaG1** [comment]
your are once again right, just tested it with 20% increase of LRC, and about 15x it took reagents, and then it didnt.
I think this is clear! thank you!
Closing!
