### ISSUE TITLE
[Feature Request] New sphere functions

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source-X#953]
Is it possible to add serv.houses (r) and serv.ships (r) functions like serv.guilds? also for serv.guilds it can be developed as serv.guild.0.name/uid (w/r) and there can be another feature like serv.house.0.name/uid (w/r).

same as serv.accounts, serv.account.<id>.name.

so we can get rid of the heavy burden of controlling the whole world with foritems or entering id under forinstances one by one.

**Comment by drk84** [comment]
There is already the player function houses and ships

**Comment by Jhobean** [comment]
Check here.
https://github.com/Sphereserver/Scripts-X/blob/5c7524f2d9a0bc6fee2f09d3e3e5f46d442db16c/core/dialogs/admin/d_admin_main.scp#L594

And few line down for ship.  Its what you need?

**Comment by canerksk** [comment]
this is for the server, not the one for the player.  When we need to perform an action on all the houses on the server, we need to check all the players first and then the houses on the players, which will increase the processing load.

**Comment by Jhobean** [comment]
Implementation is here: https://github.com/Sphereserver/Source-X/commit/7de9bb49594f0a8274469012e625e687317c1cc6
