### ISSUE TITLE
Bank does not open on different screen size

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source-X#958]
With the help of an assistant (razor/uoassist), if we adjust the screen dimensions outside the default dimensions in sphere, the bank closes immediately 1 second after it is opened.  The bank does not allow it to open.  but after resetting the window size and relogin, it opens without any problem.  When trying this, it is necessary to relogin on every window size change. 

Sending the client's window size to sphere as a package, sphere sees it without any problem, but the bank still doesn't open. Tested on different client and sphere versions, and I found that the problem was with sphere. It may be related to the last screensize package or it is related to the coodinat that the bank is trying to open on the screen.

**Comment by Tolokio** [comment]
What are u changing the size? the window's size? or the game's size that is inside the windows size? The gump's size? Dosnt happens on old spheres?

**Comment by canerksk** [comment]
Game screen size, yes, previous versions don't have this problem.

**Comment by drk84** [comment]
If you can make a list of the resolution supported by razor/uoassist i can add them to the screensize command

**Comment by canerksk** [comment]
actually this is completely set by the user, there is no fixed value. whatever the player enters. There are only maximum and minimum values. In fact, I set it as supported by sphereserver, but still the bank does not open.

**Comment by drk84** [comment]
I changed resolution with Razor, set it to 1600x900, called bank and it remained open

**Comment by drk84** [comment]
With client 7.0.97 (super recent one) seems like you can't force game resolution by razor

**Comment by canerksk** [comment]
> I changed resolution with Razor, set it to 1600x900, called bank and it remained open (client 7.0.20)

After setting the resolution, you need to re-login. Then try opening a bank.

**Comment by drk84** [comment]
I tried again with client 7.0.15.1 but can't reproduce the issue. I set this time the resolution at 1920 x 1080 and the bank stays in place. Hardcoded Gump like Bank, Paperdoll, Statusbar positions are not handled by sphere but by client, i think they are stored in the desktop.uos file in the EaGames/Ultima Online Legacy/blabla/charactername folder

**Comment by canerksk** [comment]
I don't think this issue is client related. There is no such problem when I try on 56b emulator.

**Comment by drk84** [comment]
Anyway, you wrote in the first post that you need to re-login for the bank to be opened properly.

Razor warns you to restart the client after changing the resolution, so the issue is non existant
