### ISSUE TITLE
Faction & Slayer system -> bonus damage looks like not working

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#964]
The system is implemented from what i understand, which is awesome job!
Only the bonus DMG seems like is not working properly.

In pastebin there is full code from source.
https://pastebin.com/U3Szx0LG

_added faction property to NPC, added same slayer property to weapon -> dmg is same with or without_

Maybe the iDmgBonus is incorrectly calculated?
```
iDmgBonus = pSlayer->GetSlayerDamageBonus(pWeapon->GetSlayer());
iDmg *= iDmgBonus;
```

**Comment by drk84** [comment]
In theory it works if and only if the weapon (or a spell) is causing magical damage, but i see no problems in expanding it to the types of damage

**Comment by drk84** [comment]
Fix sent.

**Comment by AtillaG1** [comment]
Working exceptionaly!! Thank you ❤
