### ISSUE TITLE
Faction & Slayer system -> core is looking only for the spellbook in hand1 not hand2

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#965]
Now we can use spellbooks in LAYER_HAND2, would be awesome to implement search for this also in this system. #955 
```
if (uType & DAMAGE_MAGIC)   // If the damage is magic
        {
            pWeapon = pSrc->LayerFind(LAYER_HAND1); // Search for an equipped spellbook
            if ((pWeapon) && (!pWeapon->IsTypeSpellbook())) // If there is nothing on the hand, or the item is not a spellbook.
            {
                pWeapon = pSrc->m_uidWeapon.ItemFind(); // then force a weapon find.
            }
        }
```

**Comment by cbnolok** [comment]
Best solution would be to add a function to look up for the spellbook and to use that on every occasion

**Comment by AtillaG1** [comment]
Could this be an solution ? 🤔

> if (uType & DAMAGE_MAGIC)   // If the damage is magic
>         {
>             pWeapon = pSrc->LayerFind(LAYER_HAND1); // Search for an equipped spellbook hand 1
> 			pWeapon2 = pSrc->LayerFind(LAYER_HAND2); // Search for an equipped spellbook hand 2
>             if (pWeapon) && (!pWeapon->IsTypeSpellbook() || (pWeapon2) && (!pWeapon2->IsTypeSpellbook()) ) // If there is nothing on the hand 1 or 2, or the item is not a spellbook.
>             {
>                 pWeapon = pSrc->m_uidWeapon.ItemFind(); // then force a weapon find.
>             }
> 			if (pWeapon2 && pWeapon2->IsTypeSpellbook())
> 			pWeapon = pWeapon2;
>         }

**Comment by drk84** [comment]
Better add a method like findlayerspellbook that replaces all the spellbook search code

**Comment by Jhobean** [comment]
A method is somthing like. Pchar->getspellbook(). ?

**Comment by drk84** [comment]
exactly

**Comment by drk84** [comment]
Fix sent.

**Comment by AtillaG1** [comment]
Working exceptionaly!! Thank you ❤
