### ISSUE TITLE
Max Damage of NPC is limited to 255

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#967]
When creating a NPC, it's not possible go over 255 of damage. I know it's for reducing memory usage but 255 seem low for some custom shard.

When I set 10,256 I got 65k dam
![image](https://user-images.githubusercontent.com/51728381/202867634-b3572956-2c51-4d27-aa26-3b6bc425d1b4.png)

```
[CHARDEF c_lanceur_roche_farydak]
DEFNAME=c_lanceur_roche_farydak
id=c_ogre
NAME=Lanceur de roches
ICON=i_pet_ogre
SOUND=snd_monster_ogre1
CAN=MT_WALK|MT_USEHANDS
DAM=10,256
ARMOR=2000
```

**Comment by drk84** [comment]
Changed.

**Comment by Jhobean** [comment]
Fast Fix and working good!  Thx VM
