### ISSUE TITLE
Max AR on ITEM not possible over 255

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#968]
How to reproduce:
On you script create an item with 255 Armor
```
[ITEMDEF 013c5]
DEFNAME=i_leather_sleeves
NAME=Brassard en cuir
TYPE=t_armor_leather
FLIP=1
ARMOR=255
```
![image](https://user-images.githubusercontent.com/51728381/202867824-d17fefd0-f6f3-425d-a3f1-32913e07b7bc.png)

You will see 255 Armor. and you can go higher with adding modAR EX: modar 10

![image](https://user-images.githubusercontent.com/51728381/202867847-e4e62453-86ad-4603-a251-a8e8e2a2ca1b.png)

Infortunatly, if you set AR 256 on script, it go to 0
![image](https://user-images.githubusercontent.com/51728381/202867886-0758795f-6a56-44b8-9b25-85b3bf378f5a.png)

But you can add modAR 10 too and get 10 of AR.

The bug is you cant create an AR over 255 by default. At least, we should have a decent option of 1000 for some custom shard.

**Comment by drk84** [comment]
It's not a bug, it's the maximum value for the data type assigned used for the old AR value

**Comment by drk84** [comment]
ah no it's a word, should be allowed up to 65k

**Comment by drk84** [comment]
Changed.

**Comment by Jhobean** [comment]
Fast Fix and working good!  Thx VM
