### ISSUE TITLE
Disbanding a party bug

### ISSUE THREAD

**Issue by merttumer** [Sphereserver/Source-X#97]
When a party gets disbanded, 

party master looks like its still in the party and when he logs out the character stays in the game and cant re enter the game with the same character. The client stays in Entering Britannia screen. Also the player cannot be disconnected by command too. These give debug error on the console and sometimes it causes sphere to crash

when player tries to login : https://github.com/Sphereserver/Source-experimental/issues/84 this happens

and another debug error that causes sphere to crash:

https://media.discordapp.net/attachments/354358315830083587/445324230171557898/unknown.png?width=921&height=480

**Comment by cbnolok** [comment]
The issue should be solved now, can you confirm?
