### ISSUE TITLE
TAG.name suffix and prefix Do not have space

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#970]
We can use override tag for the name

```
TAG.NAME.PREFIX | Sets some text to display before the character's name.
TAG.NAME.SUFFIX | Sets some text to display after the character's name.
```
I have tested it and it's weird because there no space between name..
![image](https://user-images.githubusercontent.com/51728381/205411029-77bad6c6-9c0a-4521-a8d0-48a2113ced65.png)

I can easily modify it in core but I'm wandering if I do modif on my shard only or for everyone with a PR
What was the goal of these tag at beginning?
![image](https://user-images.githubusercontent.com/51728381/205410942-228463ea-ca17-470d-a332-63448b377043.png)

![image](https://user-images.githubusercontent.com/51728381/205410978-95fb77d1-8557-460a-a8cd-aeb33031f3bb.png)
 

Maybe it was for adding special bracket like ->Ronaldo<-

**Comment by drk84** [comment]
It's not a bug, it was made on purpose:
12-11-2003, Kell
- Added support for the following TAGs on characters:
  TAG.NAME.ALT (alternate name, good for incognito effects)
  TAG.NAME.PREFIX (alternate prefix, if not set, defaults to Notoriety prefix - lady/lord)
  TAG.NAME.SUFFIX (suffix for the name)
  Note that a space isn't added for prefix or suffix on purpose, to allow text to be
  glued to the name. You can add a space by using quotes, as in: TAG.NAME.SUFFIX="text "

**Comment by Jhobean** [comment]
Hoo. Very interesting.  thx for the " ".  It was the part I was missing.
