### ISSUE TITLE
Delete a char when he his in a guild cause crash

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#971]
If you join a guild and after that delete your char, When a legit guild member go touch the guild stone (i_guildstone), You will get a critical warning. If you run shard in debug, server just crash.

![image](https://user-images.githubusercontent.com/51728381/205447588-78ba57cd-a737-46d1-8aef-315474fc5c05.png)

![image](https://user-images.githubusercontent.com/51728381/205447571-50679b95-1cec-4229-94b1-c5dd3493af27.png)

I think the fix could be done here but I dont know how.
https://github.com/Sphereserver/Source-X/blob/3dbb44713bec5d720cf3b932970584331637ec18/src/game/chars/CStoneMember.cpp#L282-L318

I think there 2 bug. One in server where he can scan an invalid UID and one in script where he dont delete invalid member.

**Comment by drk84** [comment]
fix sent
