### ISSUE TITLE
canmake with scroll

### ISSUE THREAD

**Issue by alexrmrm** [Sphereserver/Source-X#979]
for craft scroll makeitem check mana. 

But canmake return 1 if mana is less of necessary

**Comment by drk84** [comment]
I don't understand i  need an exampe

**Comment by Jhobean** [comment]
You cant craft a scroll if you have 0 mana.

When crafting a scroll, canmake function check if you have the regs learn the spell and mana...
What he said its you should be able to craft the scroll with 0 mana.  Mana requierement should be remove on canmake check.

Personnaly I dont know how this behavior should work.

When the mana is consume? When we use the scroll?

**Comment by drk84** [comment]
Oh just remove this  from the inscription spells
TESTIF=<cancast s_fireball 00>
