### ISSUE TITLE
Unequal Z betwen uoclient and sphere

### ISSUE THREAD

**Issue by Tolokio** [Sphereserver/Source-X#983]
This issue is related to #617 and #877

There is a problem with inclinated tiles. As soon players step on a inclinated tile, Sphere and UOClient will give diferent Z to players.
Player will not realize until client is refreshed, for example if player is affected by "flip", "resend", "update" or "fix". As soon refresh happens, sphere will send the real Z to uoclient.
This use to happen when people fish on a cliff, character is flipped and new z is sent. Moving the player up or down across Z axis.

This issue can cause other issues related to height of the player. There can be places where player will not be able to step on even if client allow it.  In certain cases it may cause canseelos fails.

Depending on the tile inclination and the tile where u come from, the real player's z can be higgher or lower than the one UOclient is using.

Note: Player's Z at sphere and Uoclient are already unequal before the refresh. At the refresh sphere just tell the client where the player realy is and client update the Z.

**Comment by Tolokio** [comment]
![image](https://user-images.githubusercontent.com/20745578/207864799-983ef153-83e2-4211-a556-583082246d78.png)
I think problem got to be at this functions. there are 4 functions like this.

**Comment by Jhobean** [comment]
A new method for determining the reel Z should be create and place somewhere.

Example 
servuo: https://github.com/ServUO/ServUO/blob/05cdc8780ecd81a6abca0f5f14097c8e6bc4860f/Server/Map.cs#L550
Classic UO: ?

ORION:
```
void CLandObject::UpdateZ(const int32_t &zTop, const int32_t &zRight, const int32_t &zBottom)
{
	if (m_IsStretched)
	{
		//Сохраним среднее значение Z-координаты
		m_Serial = ((m_Z + zTop + zRight + zBottom) / 4);

		//Значения для рендера
		m_Rect.left = m_Z * 4 + 1;
		m_Rect.top = zTop * 4;
		m_Rect.right = zRight * 4;
		m_Rect.bottom = zBottom * 4 + 1;

		if (abs((int32_t)m_Z - zRight) <= abs(zBottom - zTop))
			m_AverageZ = ((int32_t)m_Z + zRight) >> 1;
		else
			m_AverageZ = (zBottom + zTop) >> 1;

		//Минимальная Z-координата из всех
		m_MinZ = m_Z;

		if (zTop < m_MinZ)
			m_MinZ = zTop;

		if (zRight < m_MinZ)
			m_MinZ = zRight;

		if (zBottom < m_MinZ)
			m_MinZ = zBottom;
	}
}
```

**Comment by Tolokio** [comment]
I would like to fix this... But can't figure out how.

**Comment by Tolokio** [comment]
![image](https://user-images.githubusercontent.com/20745578/228240731-296a2da1-081a-46d9-883c-b62f02b1b4a9.png)

@drk84,  @jhobean or @any, do u know where is the best place to insert the Z fix? I`m not sure about it. So complex for me. 
Maybe where I mark in the screenshot? OR in the bocks part? If anyone points me where íll try the rest.
