### ISSUE TITLE
Sector sleep and issues with spawn (FEATURE REQUEST)

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#991]
Hi guys,

i understand the making of this feature and I like the sleeping sector feature, which is decreasing the usage of HW and making game more smooth, but in same time i would like to use it, I cannot go through it with correct functionality of spawns.

As some of you know, with sectors asleep, the spawns will just not work and thus dont spawn anything, this is a big complication for the dungeons itself, that will almost never spawn fully, unless the timer for sectors to go sleep is few hours, and even in this case, if you have spawns that spawn one mob per hour, and 5 mobs amount, this would take 5 hours of not falling to sleep.

Even tho i could get through the dungeons, there is a bigger issue and this is the random spawns for mounts, pirate AI ships and stuff like this. Since the randomly spawned object, which needs to get through timers to spawn, will most of the time be created in the sleeping sector and never spawn before someone enters. 

I tried to get around when creating the item, to GOAWAKE for the sector and spawn itself, it will wake up both, but timers still stuck.
I also tried to use the SECTOR.FLAGS=secf_nosleep and combination of all mentioned above, but its little bit weird and complicated to work out properly so the sector will go sleep again after the spawning is done. Most of the time didnt even managed to make the timers work, even tho its been woken up.

Does anyone know any way how to get through this? I kinda like the idea that NPCs/Spawns fall to sleep, but not before they actually finished its job, that way its missing the point?
Or is there any actual way how to fix this in core?

Thanks!
Gladie

**Comment by Jhobean** [comment]
Spawn point should never check if it's a sleeping sector until they have all their spawn accomplish.

**Comment by AtillaG1** [comment]
Its weird.
Im using custom loop, that after the spawn is created is supposed to spawn all <amount>, but with sleeping sectors it always spawns only 1 monster.
If i try same thing with sectors no sleeping, it will spawn everything.

**Comment by AtillaG1** [comment]
So I might have found some awkward solution. This trigger is called on the main NPCs event from sphere.ini
1. For new spawns created into the sleeping sector, the first part of the IF will do the job, idk how.
2. For the dungeons, theres the second part, which once the sector is ready to go sleep (no clients around and timer from sphere.ini is ready) there is a windows few seconds and in this time, you can quickly spawn everything that is left.

I would be definitely happy if someone has anything else or better to this.

```
ON=@CREATE
IF (<SPAWNITEM>) && (<REGION.FLAGS>&REGION_FLAG_SHIP) && (<SPAWNITEM.COUNT> < <SPAWNITEM.AMOUNT>)
	SPAWNITEM.TIMERD=1
ELIF (<SPAWNITEM>) && (<SPAWNITEM.SECTOR.CANSLEEP>) && (<SPAWNITEM.COUNT> < <SPAWNITEM.AMOUNT>)
 	SPAWNITEM.TIMERD=1
ENDIF
```

**Comment by AtillaG1** [comment]
I agree, the feature request for spawns to never fall sleep untill <count> == <amount> would be good solution.

**Comment by drk84** [comment]
The problem is that when a sector go to sleep, the sector stops ticking and thus all the items inside stops ticking, that's why the CAN_O_NOSLEEP flag does not work.
