### ISSUE TITLE
@shipmove

### ISSUE THREAD

**Issue by falanlar** [Sphereserver/Source-X#993]
Thank you for your effort, but wouldn't it be better if there was a code where we could learn the direction of the ship and intervene directly rather than the trigger? because in this way, instead of running the command all the time, it will be simpler to run only when we specify it. 
For example, there used to be "MORE2H" to find out the direction of ships (in versions 56c and 56d) then this command was removed

Not : Bu şekilde ingilizce yazmamın sebebi diğer arkadaşlara saygısızlık olmaması için

**Comment by drk84** [comment]
you can use DIRFACE for the ship direction. Anyway  i think SHip_Stop can be removed

**Comment by canerksk** [comment]
What are the alternative methods that are triggered when the ship is stopped or that the ship has stopped?

**Comment by falanlar** [comment]
The "DIRFACE" command is not useful because it only evaluates the direction the ship is facing, not the direction the ship is moving. For example, if the ship is facing north and moving backwards, DIRFACE only shows north, or there is no other way to learn intermediate directions such as NW SE etc. So the MORE2H value was more useful. By the way, @SHIP_STOP seems to be more useful because when the ship stops unintentionally, it will be easier to learn with a single trigger instead of unnecessary query load for it.

**Comment by drk84** [comment]
But there is no intermediate direction, there is only North, East, South , West
![immagine](https://user-images.githubusercontent.com/13728442/210128344-ffc8b27e-3555-4bbd-a64e-6ae7df72ce86.png)

**Comment by falanlar** [comment]
> But there is no intermediate direction, there is only North, East, South , West

In other words, there is no command to indicate which direction the ship is heading while going towards one of the "N-W-E-S-NW-NE-SW-SE" directions. In older versions, we could use "MORE2H" to find out the direction, but later this setting was deleted.

**Comment by drk84** [comment]
Can you show me a pic of a ship heading towards nw? ( a diagonal)

**Comment by falanlar** [comment]
forward left - forward right - back left - back right
i'm talking about a command to find out if the ship is going to these commands

**Comment by drk84** [comment]
Ohh i got it now!

**Comment by drk84** [comment]
Added now

**Comment by falanlar** [comment]
> Added now

that's it :) it was nice first fix of the year. thanks for helps :)
