### ISSUE TITLE
Dead Npcs or Characters sound problem (request)

### ISSUE THREAD

**Issue by falanlar** [Sphereserver/Source-X#997]
Hello again, when the character dies, he cannot see the npc, but he can hear their voices. Is there a way to prevent this? or is it possible to have a trigger that we can define for a specific field related to it? a setting that prevents dead players (example spawn) entering a certain area from being seen and heard by npc's there

**Comment by canerksk** [comment]
// Ghosts are not able to see and hear living players and creatures (0=disabled, 1=only npcs, 2=both npcs and players)
DeadCannotSeeLiving=0

Did you check the setting?

**Comment by falanlar** [comment]
yes I checked but this setting can hear voices even if it doesn't see the characters or npcs

**Comment by Soulless-1** [comment]
@falanlar  can you give us a screenshot of what your issue is and provide some information about your ini settings? what is your end goal in regards to this.

**Comment by Soulless-1** [comment]
closing out, please comment if the issue persists
